### ISSUE TITLE
Interactive shell button tooltip half visible at lower screen width

### ISSUE THREAD

**Issue by linssen** [python/pythondotorg#100]
![screen shot 2014-02-20 at 12 31 20](https://f.cloud.github.com/assets/67624/2218239/04a17b3e-9a2b-11e3-8ecf-9fd3c5e314f2.png)

**Comment by berkerpeksag** [comment]
I couldn't reproduce this with lower resolutions in both Firefox and Chrome. Could you please give more information(e.g. browser name, screen width, OS)  to reproduce this?

**Comment by linssen** [comment]
Looks like it's been fixed to me.

**Comment by berkerpeksag** [comment]
Thanks.
