### ISSUE TITLE
Established translation of the Python documentation on docs.python.org is needed.

### ISSUE THREAD

**Issue by Spamson** [python/pythondotorg#1000]
Where is documentation (https://docs.python.org/3/index.html) but in other languages? It was on adress something like https://docs.python.org/RU/3/index.html . I even tried to participate in translating with pootle.python.org . Translated part of text and the pootle also disappeared. Why? Whither? (https://wiki.python.org/moin/RussianLanguage does not contain equivalent of https://docs.python.org/3/ particularly equivalent of https://docs.python.org/3/reference/ .)

Established translation of the Python documentation on docs.python.org is needed.

Is it possible to do anything?

**Comment by JulienPalard** [comment]
In france, we're actually working on https://github.com/afpy/python_doc_fr/ and we're having some discussions about merging our work on docs.python.org/fr/:
- http://bugs.python.org/issue26546
- https://mail.python.org/pipermail/python-ideas/2016-March/038879.html

And I'm trying to make docsbuild-scripts (https://github.com/python/docsbuild-scripts/pull/6) compatible with translations.

My timeline is: Put our work on docs.python.org/fr/, then contact other translators with a clear doc on "how to do the same" so they land on it with us too.

I heard the pootle disappeared, but I'm not aware of the volume of work that disappeard with it.

**Comment by JulienPalard** [comment]
Also: http://bugs.python.org/issue13663

**Comment by berkerpeksag** [comment]
This tracker is not the correct place to discuss this. FWIW, I'm strongly against making translations available on docs.python.org.
