### ISSUE TITLE
3.6.0 release download directory listing cache not updated

### ISSUE THREAD

**Issue by cdunklau** [python/pythondotorg#1007]
A user on the Freenode #python channel reported this, and I was able to reproduce it. 

The directory listing here https://www.python.org/ftp/python/3.6.0/ was not showing 3.6.0b1 entries, although the links at the bottom of https://www.python.org/downloads/release/python-360b1/ worked fine. I tried this on my personal Linode instance in Texas as well as my work machine in Germany, both did not see the b1 entries.

I reported this in #python-dev, users haypo and matrixise reported the same thing from France and Belgium respectively. User Crys reported that they weren't able to reproduce from their machine.

User beaker then purged the CDN cache, and both of my machines were afterward able to see the b1 downloads in the directory listing. beaker mentioned that the cache probably needs to be invalidated after uploading files.

**Comment by tiran** [comment]
I was able to reproduce the issue from a machine in `psf.osuosl.org`. My local machines and my machines in Red Hat's internal network were fine.

**Comment by berkerpeksag** [comment]
The easiest way to solve this would be to add `/ftp/python/X.Y.Z/` to https://github.com/python/pythondotorg/blob/master/downloads/models.py#L209. @ned-deily, I can send a PR to implement my idea before b2.

**Comment by ned-deily** [comment]
@berkerpeksag That sounds good. I've also added a reminder about it to the text of PEP 101.
