### ISSUE TITLE
Documentation download packages not available for recent versions of 3.4

### ISSUE THREAD

**Issue by cdunklau** [python/pythondotorg#1009]
The download links here are broken: https://docs.python.org/3.4/download.html

The directory the links point to (https://www.python.org/ftp/python/doc/) show 3.4.3 and 3.5.0, but nothing newer. I suspect something changed in a workflow or some script shortly after the 3.5.0 release, since the 3.5.2 docs download page links into a different hierarchy (https://docs.python.org/3.5/archives/).

If this is not the right place to report this, please let me know where would be more helpful.

**Comment by berkerpeksag** [comment]
Thanks for the report. This is a known problem and hopefully it will be fixed soon. This falls into the authority of the release management team so it's out of scope for this tracker.

**Comment by ned-deily** [comment]
I don't think anyone has been working on this particular problem.  It looks like the 3.4 doc links are generated differently.  Invoking @birkenfeld (and @larryhastings).

**Comment by ned-deily** [comment]
Looks like the problem has been resolved now; https://docs.python.org/3.4/download.html now links to the 3.4.5 docs download page and the links on that page now provide the expected files.
