### ISSUE TITLE
microcontrollers with python

### ISSUE THREAD

**Issue by OguzAkseki** [python/pythondotorg#1010]
Hello everyone looking at my message. I am an electrical electronic engineering candidate interested with microcontrollers nowadays. As far as i know, some of languages sort of c,c++ is being used for programming a microcontroller. Python is a popular language and i am trying to explore it. Briefly ,can python be used in this area? I was looking through the net and i have come across with somethings. For example, "python doesn't come in handy in real time workings." Is this true completely? If you interest thanks in advance.

**Comment by berkerpeksag** [comment]
Thanks for the report, but the correct place to ask questions like this is [python-list](https://mail.python.org/mailman/listinfo/python-list).
