### ISSUE TITLE
wiki.python.org uses StartCom CA which is different from python.org and is not safe anymore

### ISSUE THREAD

**Issue by crackevil** [python/pythondotorg#1011]
As StartCom CA generally can't be trusted, please change the cert of wiki.python.org with the same one of python.org

**Comment by Sudo-Kid** [comment]
I agree with you that using the same CA for both sites is for the best.

I'm in no way pro StartCom, but I think the status of a CA's trusts is more a discussion for a Chrome/Firefox then Python.

**Comment by tritium21** [comment]
StartCom is no longer in Chrome or Firefox's trusted CAs for any certs issued since october.  The browsers have spoken, the wiki, if it still uses StartCom, really should move to literally anything else.

**Comment by berkerpeksag** [comment]
A new certificate has been issued on Feb 2, 2017. See #1050 for details. Thank you for the report!
