### ISSUE TITLE
docs.python.org/3.6 points to the 3.7 docs

### ISSUE THREAD

**Issue by gvanrossum** [python/pythondotorg#1014]
Do you have control over docs.python.org? Since the 'default' branch was moved to become 3.7 and 3.6 is now on a branch, some changes in the version switching menu and the redirects need to happen. (First noticed on python-dev by Wolfgang Maier.)

**Comment by ned-deily** [comment]
Working on it.

**Comment by ned-deily** [comment]
@birkenfeld takes care of some of these steps; he has been invoked.

**Comment by ned-deily** [comment]
I think @birkenfeld and I have straightened this out now.  There are still a few little oddities, like there aren't downloadable versions of the 3.6.0b1 since it's not a final release.  But the on-line live docs should be getting updated properly now for both 3.6 and 3.7.
