### ISSUE TITLE
Python on MacOsx

### ISSUE THREAD

**Issue by Kossalex** [python/pythondotorg#1017]
Whenever i try to make this thing:   '    (don't know hot to call it) whole IDLE shuts down. Im on OS X El Capitan version: 10.11.6

**Comment by ned-deily** [comment]
The right place to report bugs in Python itself, including IDLE, is on http://bugs.python.org.  However, you are certainly running into a critical bug in Tk described [here](http://bugs.python.org/issue18458).  Solutions are described here https://www.python.org/download/mac/tcltk/; basically, don't use the Apple-supplied system Python and its IDLE; if you install a python.org Python also install an up-to-date version of Tcl/Tk 8.5.x from a supplier like ActiveState.
