### ISSUE TITLE
Trying to upload a new project, shinkansen, but getting an error

### ISSUE THREAD

**Issue by reversefold** [python/pythondotorg#1018]
I searched pypi and did not find any package named shinkansen, but when I try to upload my package (see https://github.com/skyhigh-networks/shinkansen) I get the following error:

```
Submitting dist/shinkansen-1.0.0.tar.gz to https://pypi.python.org/pypi
Upload failed (403): You are not allowed to edit 'shinkansen' package information
error: Upload failed (403): You are not allowed to edit 'shinkansen' package information
```

**Comment by berkerpeksag** [comment]
1. That error means the name has already been registered by someone else.
2. The correct place to report PyPI administration issues is https://sourceforge.net/p/pypi/support-requests/ This tracker is for issues with www.python.org only.

**Comment by berkerpeksag** [comment]
You can register a name without uploading a release. There is an open issue to make this more user friendly in the new PyPI: https://github.com/pypa/warehouse/issues/1388
