### ISSUE TITLE
Switching from Bitbucket to GitHub, Installing Setuptools guide not updated

### ISSUE THREAD

**Issue by zoomx** [python/pythondotorg#1019]
The installation shell commands here
[https://pypi.python.org/pypi/setuptools/3.4.1](url)
have links to bitbucket but now the repository is on GitHub. You get a 404 error.

https://bootstrap.pypa.io/ez_setup.py is the new URL.
I believe that the guide must be updated.

**Comment by berkerpeksag** [comment]
setuptools' issue tracker is located at https://github.com/pypa/setuptools/issues.
