### ISSUE TITLE
/doc/copyright has all its html escaped for no reason

### ISSUE THREAD

**Issue by haboutnnah** [python/pythondotorg#1021]
https://python.org/doc/copyright

Also, does anyone have a clue on what the documentation on the copyright() function is? PyCharm insists it exists but I can't find documentation.

**Comment by Mariatta** [comment]
To fix the copyright page, the copyright Page entry need to be edited by one of the admins here.
I believe that the `Content Markup Style` value there needs to be changed from `Restructured Text` to `HTML`.

Seems like there is no documentation for copyright() yet. 
https://docs.python.org/3/library/constants.html
The issue tracker for that documentation is at http://bugs.python.org/
Perhaps you can file the issue there to have the documentation updated?

**Comment by Mariatta** [comment]
...Reading the docs again, perhaps this is meant to be the documentation for `copyright()` ?

> Objects that when printed, print a message like “Type license() to see the full license text”, and when called, display the corresponding text in a pager-like fashion (one screen at a time).

**Comment by ned-deily** [comment]
Thanks for the report.  The legacy "copyright" page should now be displayed correctly.  And as Mariatta notes, `copyright` is documented in the [`Built-in Constants` section of the Library Reference](https://docs.python.org/3/library/constants.html#copyright).
