### ISSUE TITLE
Transfer pythonmentors.com's content to python.org

### ISSUE THREAD

**Issue by berkerpeksag** [python/pythondotorg#1023]
See [this post](https://mail.python.org/mailman/private/core-mentorship/2016-October/003676.html) from the core-mentorship list for details.
- [x] Convert [index.html](https://bitbucket.org/jnoller/pythonmentors/src/5998fb10900d41185716f3d80ba087a15b7c34fc/site/index.html.mako?at=default&fileviewer=file-view-default) to reST
  - Please convert the HTML file to reST format and paste it to this issue
  - You can read [reStructuredText Primer](http://www.sphinx-doc.org/en/stable/rest.html) if you're not familiar with the format
- [x] Create `/dev/core-mentorship/` page on python.org
  - I'm going to do this step
- [x] Update footer on python.org to use the new link
- [x] Transfer pythonmentors.com to the PSF
  - We probably need help from the PSF's IT manager on this
  - Awaiting transfer code confirmation process to be completed
- [x] Redirect pythonmentors.com to `python.org/dev/core-mentorship`
  - We probably need help from the PSF's IT manager on this

**Comment by Mariatta** [comment]
Hi Berker,
I'd like to work on the first task, converting index.html to reST.
Thanks :)

**Comment by jnoller** [comment]
I found the domain(s) in an old godaddy account, how do I hand that all over?

**Comment by berkerpeksag** [comment]
> I found the domain(s) in an old godaddy account, how do I hand that all over?

Good question :) @MarkMangoba what's the process to transfer the domain to the PSF?

**Comment by Mariatta** [comment]
Hi @jnoller, at the bottom of the original copy, there is an 'email us' link which points to your email address.
I assume we'll be using a different one. What email address can I put there?

Thanks :)

**Comment by Mariatta** [comment]
Hi @berkerpeksag , here's the reST copy. I uploaded it as .txt file because github does not let me upload .rst file format.

At the very bottom, there is a link to 'email us'. I used jdoe@example.com 
Please update the email address as necessary 😄 

[core-mentorship.txt](https://github.com/python/pythondotorg/files/517390/core-mentorship.txt)

**Comment by kbkaiser** [comment]
If we are going to use pythonmentors, it might be a good idea to pick up the .org domain.

**Comment by jnoller** [comment]
@Mariatta Please feel free to remove my info wherever :) 

Currently waiting on godaddy to send me account unlock details, pretty sure all I have there is python-related domain names so I can provide someone the login information to transfer!

**Comment by jnoller** [comment]
![screen shot 2016-10-09 at 9 47 17 am](https://cloud.githubusercontent.com/assets/51528/19221255/68f49956-8e05-11e6-8d08-799c70768e85.png)

Yup, I can hand over the account data - I know @akuchling wanted to help maintain getpython3

**Comment by MarkMangoba** [comment]
@berkerpeksag sorry for the late reply, I was in surgery Friday.  We can get these domains transfered over via Gandi.  Are these all now in GoDaddy?  If so, i'll need the unlock details sent to mmangoba@python.org.

**Comment by matrixise** [comment]
@jnoller about your info, I suppose you talk about the .rst file ? because there is only one reference to your blog. is it right ?

**Comment by berkerpeksag** [comment]
Thanks @Mariatta. I've now created the new page at https://www.python.org/dev/core-mentorship/

**Comment by Mariatta** [comment]
Awesome! Thanks @berkerpeksag Looks good 😃

**Comment by MarkMangoba** [comment]
Hey @jnoller transferring out pythonmentors.com now, please feel free to email the auth code.  Also after its been transfered I will setup the re-direct in Gandi.net DNS zone file.

**Comment by jnoller** [comment]
I authorized the transfer via gandi this morning 

Jesse

**Comment by MarkMangoba** [comment]
@jnoller thank you sir, according to gandi.net the transfer will be finished by:  Sunday 23 October 2016.

**Comment by MarkMangoba** [comment]
I received notification from Gandi that the transfer was completed last night (Sunday PST).  I've tested the re-direct and we are good to go.

**Comment by berkerpeksag** [comment]
Great, thank you all! :)
