### ISSUE TITLE
Outdated info and broken links

### ISSUE THREAD

**Issue by philippeko** [python/pythondotorg#1024]
Please visit https://www.python.org/about/success/testgo/ and all provided links in the **Python Software Success Stories**. Regards --philippeko

**Comment by berkerpeksag** [comment]
It looks like the company has been defunct for years now. I'm not sure what can we do here. Perhaps we can just delete the page.

**Comment by malemburg** [comment]
This is a success story, one of many, and most are rather old, so it's not unsurprising that links break. I'd suggest to either not do anything or remove the links (but keep the link text).

Here's another idea:

Add the meta data from the legacy site to the success story pages (e.g. http://legacy.python.org/about/success/testgo/). This allows people to notice that the story is from 2003 and thus not cause surprises when seeing that links no longer work.

**Comment by berkerpeksag** [comment]
> Add the meta data from the legacy site to the success story pages

That's a good point! The metadata is already there, but it doesn't show up on the page. I will take a look today.

**Comment by rufwebs** [comment]
It really depends on the script that a website is using,right? The broken links can be fixed but what about the metadata that can't be changed to overwrite the script's settings. How can i implement custom metadata details on pages of a datalife engine script for example? 

[youtube movies](https://fullmoviesnow.com)

**Comment by dhruvsingh** [comment]
[Audio/Video Instructional Materials for Python](https://www.python.org/doc/av/) also has broken links.
Can they please be removed?

Some broken ones that I came across:
1. [ShowMeDo (screencasts)](http://showmedo.com/videos/python)
2. [Best Tech Videos On The Net (screencasts + videos)](http://www.bestechvideos.com/category/development/python/)

**Comment by berkerpeksag** [comment]
Done, thanks for the report. It would be better to move these information to wiki.python.org in long term.

**Comment by malemburg** [comment]
@berkerpeksag The original plan was to move more to the python.org site, but I agree with you: until we have a proper CMS in place for the content on this site, it's better to host such link collections on the wiki.

**Comment by berkerpeksag** [comment]
Yeah, I have a plan to do that on our current CMS, but unfortunately my free time is limited :(

**Comment by berkerpeksag** [comment]
I've backported old success stories into new app a while ago and I just added creation date to story detail pages in 6c5b33e07d78a8584027d4dde34e27c02a81b8f2.
