### ISSUE TITLE
Spam URLs getting fed through RSS feed

### ISSUE THREAD

**Issue by adamn** [python/pythondotorg#1028]
The PyPI RSS feed https://pypi.python.org/pypi?:action=rss is getting populated with spam links:
- https://pypi.python.org/pypi/1800.681.7208.BROTHER.PRINTER.TECH.SUPPORT.PHONE.NUMBER/681
- http://pypi.python.org/pypi/sage50_help_Customer_Tech_1844_313_4859_Support_number_Peachtree_Technical_Support_number/441

They seem to be getting removed as well but I think this probably requires some attention.

**Comment by MarkMangoba** [comment]
@adamn our Infrastructure staff is aware, you can monitor the situation here:  https://status.python.org/incidents/ry2q26575x75  thank you for the report.
