### ISSUE TITLE
Confirmation e-mail sent to incorrect email address long time ago

### ISSUE THREAD

**Issue by kysil** [python/pythondotorg#1029]
Hello,
after long time (about 6-8 month) ago, I can see this message on https://www.python.org/accounts/confirm-email/ 
Confirmation e-mail sent to kysil.me@gmail.cm.
Verify Your E-mail Address
We have sent an e-mail to you for verification. Follow the link provided to finalize the signup process. Please contact us if you do not receive it within a few minutes.

I provided incorrect my Email address for registration kysil.me@gmail.**cm** instead kysil.me @ gmail.**com**

Please send me confirmation link to this Email – kysil.me @ gmail.com

Thank You!

**Comment by MarkMangoba** [comment]
@kysil i've changed your email to reflect the correct registration.  You should have received a password reset.  Thanks, M.

**Comment by kysil** [comment]
Thank You, Mark!
Unfortunately:
502 Bad Gateway
nginx

**Comment by berkerpeksag** [comment]
That's because there are two users with the same email address: kysil and kysil2. I've deleted kysil2. It should be working now.

**Comment by kysil** [comment]
Thanks!
Done.
