### ISSUE TITLE
Python.org not working

### ISSUE THREAD

**Issue by Mariatta** [python/pythondotorg#1031]
Seeing 503 Error :(

<img width="562" alt="screen shot 2016-11-03 at 9 24 07 pm" src="https://cloud.githubusercontent.com/assets/5844587/19994512/554fc284-a20c-11e6-948d-68f5bcd48d3c.png">

**Comment by MarkMangoba** [comment]
@Mariatta internal cert expired on the load balancer.  Infra team member gutworth force salt to regenerate the cert.
