### ISSUE TITLE
Mention the optional Elasticsearch installation in the docs

### ISSUE THREAD

**Issue by Mariatta** [python/pythondotorg#1033]
Based on conversation in #883
The docs at https://pythondotorg.readthedocs.io/install.html can be updated to mention the step about installing Elasticsearch. It should be an optional step.

1) setup an Elasticsearch instance on your machine
2) update the HAYSTACK_CONNECTIONS setting in pydotorg/settings/local.py to use it

@berkerpeksag I checked install.rst and it does not yet mention Elasticsearch :)

The file to be changed is at docs/source/install.rst

**Comment by berkerpeksag** [comment]
You're right, I was confused with Warehouse documentation. Thanks for checking the installation document, @Mariatta :)
