### ISSUE TITLE
Typos (3 at least)

### ISSUE THREAD

**Issue by PallHaraldsson** [python/pythondotorg#1038]
https://www.python.org/dev/peps/pep-0529/

The extra spaces plus:

"to Python as str , they [..] bytes , they are trasncoded"

Also at https://www.python.org/dev/peps/pep-0524/ :

"iniitalization"

**Comment by Mariatta** [comment]
Thanks :) I fixed the typos in the PEPs repository, but the extra spaces is a known issue :( 
See https://github.com/python/pythondotorg/issues/825

**Comment by Rosuav** [comment]
Fixed by (now merged) #150 in PEPs. Thanks Mariatta!

**Comment by berkerpeksag** [comment]
Whitespace issue is going to be fixed by https://github.com/python/pythondotorg/pull/1013.

Thanks for the report!
