### ISSUE TITLE
expired SSL certificate

### ISSUE THREAD

**Issue by DanCornilescu** [python/pythondotorg#1039]
While trying to access https://www.python.org/downloads/mac-osx/ (following the 1st result from the Google search for "mac install python 2.7") I got this error:

> The owner of www.python.org has configured their website improperly. To protect your information from being stolen, Firefox has not connected to this website.
> 
> www.python.org uses an invalid security certificate. The certificate expired on 09/09/2016 08:00 AM. The current time is 12/07/2016 10:03 PM. Error code: SEC_ERROR_EXPIRED_CERTIFICATE

You may want to take a look.

**Comment by DanCornilescu** [comment]
Never mind, seems to be fixed now.

**Comment by MarkMangoba** [comment]
@DanCornilescu our CDN service is currently investigating intermittent TLS certificate issues:  https://status.fastly.com/incidents/3nvqmv1xdrmx you can also view the status at anytime via https://status.python.org/ - thanks!
