### ISSUE TITLE
Server side info disclosure/ Spamming inbox

### ISSUE THREAD

**Issue by sulemanmalik003** [python/pythondotorg#1041]
Good evening,

My name is suleman Malik and im security researcher. I have found a security vulnerability on https://www.python.org/accounts/password/reset/. Password reset is vulnerable to email flooding vuln. Image is attached with this report.

===Mitigation===
Use rate limit function or captcha in order to stop this kind of attack.

Here are two links that are disclosing server side information including server name version and operating system being used on python.org.

http://mail.python.org/
https://hg.python.org/

Looking forward!

Suleman Malik
InfoSec Researcher
www.sulemanmalik.com
![python](https://cloud.githubusercontent.com/assets/24320910/21397793/058d9f08-c79d-11e6-8ba5-42a095d6deb5.png)

**Comment by malemburg** [comment]
I think it's rather unlikely that someone will use this to mail bomb people, but a rate limit or captcha would be nice way to protect against automated attacks.

As always: patches are welcome (the site's source code is available in this repo).

Thanks.

**Comment by sulemanmalik003** [comment]
Thank you for your reply. Did you check the other links that are disclosing the server side information including the version and OS.

**Comment by malemburg** [comment]
On 04.01.2017 16:57, sulemanmalik003 wrote:
> Thank you for your reply. Did you check the other links that are disclosing the server side information including the version and OS.

Yes. Those are harmless.

**Comment by MarkMangoba** [comment]
@sulemanmalik003 I discussed this with the pythondotorg workgroup back when it was reported on IRC, sorry for not closing this - the issue was fixed.  As @malemburg patches are welcome, and feel free to contribute.

**Comment by sulemanmalik003** [comment]
Great Thank you..
