### ISSUE TITLE
https://python.org (without www.) causes a certificate error in firefox

### ISSUE THREAD

**Issue by somecoder42** [python/pythondotorg#1042]
When I enter python.org in my Firefox 50.1, https://python.org gets loaded with an certificate error.
Using https://www.python.org works.

> Your connection is not secure
>
> The owner of python.org has configured their website improperly. To protect your information from being stolen, Firefox has not connected to this website.
>
> This site uses HTTP Strict Transport Security (HSTS) to specify that Firefox may only connect to it securely. As a result, it is not possible to add an exception for this certificate.
>
>
> python.org uses an invalid security certificate.
>
> The certificate is not trusted because the issuer certificate is unknown.
> The server might not be sending the appropriate intermediate certificates.
> An additional root certificate may need to be imported.
>
>Error code: SEC_ERROR_UNKNOWN_ISSUER

> https://python.org/
> 
> Peer’s Certificate issuer is not recognized.
> 
> HTTP Strict Transport Security: true
> HTTP Public Key Pinning: false
> 
> Certificate chain:
> 
> -----BEGIN CERTIFICATE-----
> MIIGsTCCBZmgAwIBAgIHBqFUXC4kcDANBgkqhkiG9w0BAQsFADCBjDELMAkGA1UE
> BhMCSUwxFjAUBgNVBAoTDVN0YXJ0Q29tIEx0ZC4xKzApBgNVBAsTIlNlY3VyZSBE
> aWdpdGFsIENlcnRpZmljYXRlIFNpZ25pbmcxODA2BgNVBAMTL1N0YXJ0Q29tIENs
> YXNzIDIgUHJpbWFyeSBJbnRlcm1lZGlhdGUgU2VydmVyIENBMB4XDTE1MDIwMjA4
> MzUxMVoXDTE3MDIwMTIxMDM1OVowgbkxCzAJBgNVBAYTAlVTMQ8wDQYDVQQIEwZP
> cmVnb24xEjAQBgNVBAcTCUJlYXZlcnRvbjEjMCEGA1UEChMaUHl0aG9uIFNvZnR3
> YXJlIEZvdW5kYXRpb24xFTATBgNVBAMUDCoucHl0aG9uLm9yZzFJMEcGCSqGSIb3
> DQEJARY6ZTg5ZDY5MDFiYTNlNDcwZThjZWRjM2VhYTMyYTAwNzQtMTY5NzU2MUBj
> b250YWN0LmdhbmRpLm5ldDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
> AMZ5JGMqKwucBPv3jdeeAbEoTu4gGym4te8FIwX+CiHsvmk6seJv6iB0Eu5EStif
> ma5UHywknF2RmR1lC3ZziHUIhn7WlWyM3oTR77pIIgqH8XoQZuvXIAbLmUOdj6Uz
> MLmDnHhotXYrXCVxME5op8Pqo8Rb9FR2nZIgIhS1oZZ4JhWnRmlBM1Wa2QQoWQx5
> yXjILZGozRM5zVjzAuQKH9yDpOEyJhq2Y5yThvDc321zjxNW8BRMR++Eto/xtOGw
> Heka58I34/U3eEwKXaSGs5L8ZI3NDE7w754aPDC26hm7207LFzsFB85x7EbNVl3X
> qmaPc1QUUyQ3RhMLDjZRKcMCAwEAAaOCAucwggLjMAkGA1UdEwQCMAAwCwYDVR0P
> BAQDAgOoMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAdBgNVHQ4EFgQU
> lS5dDwR94kc4q/OIKK3v8yywBcgwHwYDVR0jBBgwFoAUEdsjRf1UzGpxb4SKA9e+
> 9wEvJoYwIwYDVR0RBBwwGoIMKi5weXRob24ub3JnggpweXRob24ub3JnMIIBVgYD
> VR0gBIIBTTCCAUkwCAYGZ4EMAQICMIIBOwYLKwYBBAGBtTcBAgMwggEqMC4GCCsG
> AQUFBwIBFiJodHRwOi8vd3d3LnN0YXJ0c3NsLmNvbS9wb2xpY3kucGRmMIH3Bggr
> BgEFBQcCAjCB6jAnFiBTdGFydENvbSBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTAD
> AgEBGoG+VGhpcyBjZXJ0aWZpY2F0ZSB3YXMgaXNzdWVkIGFjY29yZGluZyB0byB0
> aGUgQ2xhc3MgMiBWYWxpZGF0aW9uIHJlcXVpcmVtZW50cyBvZiB0aGUgU3RhcnRD
> b20gQ0EgcG9saWN5LCByZWxpYW5jZSBvbmx5IGZvciB0aGUgaW50ZW5kZWQgcHVy
> cG9zZSBpbiBjb21wbGlhbmNlIG9mIHRoZSByZWx5aW5nIHBhcnR5IG9ibGlnYXRp
> b25zLjA1BgNVHR8ELjAsMCqgKKAmhiRodHRwOi8vY3JsLnN0YXJ0c3NsLmNvbS9j
> cnQyLWNybC5jcmwwgY4GCCsGAQUFBwEBBIGBMH8wOQYIKwYBBQUHMAGGLWh0dHA6
> Ly9vY3NwLnN0YXJ0c3NsLmNvbS9zdWIvY2xhc3MyL3NlcnZlci9jYTBCBggrBgEF
> BQcwAoY2aHR0cDovL2FpYS5zdGFydHNzbC5jb20vY2VydHMvc3ViLmNsYXNzMi5z
> ZXJ2ZXIuY2EuY3J0MCMGA1UdEgQcMBqGGGh0dHA6Ly93d3cuc3RhcnRzc2wuY29t
> LzANBgkqhkiG9w0BAQsFAAOCAQEAiclQf2g+BbVBKrtCPRmSG3D2WQVBAEBwS/Dx
> 1Wn6IIs7Ql7PMRhoOb/H+VnfNX+2osT/spc9F/IHOTEmFqGvgAOLOFzXw43lcMq1
> fx+LGrGLci56gDseGGRS2L1bbqwucJX5owFgZ6X1V9eHxYpuYe5ZDZBltN1AN7ZW
> JR+40nZ+ec9Sp9U7/+z8vmryVexzTibSIYI/pMyUv+DNiAJR1EhpgxW3/1QK2bh9
> 8K2VvcNH+iRyVH/3GoSDvXgMIFvuP9XykwP+jOdyMDRJMpaz/5+4N+uXAJxOLWDd
> LtyfqaSz+JuV2mA1A6v4t8tquS0csXBe8vjvEEd5pSBVL/C37A==
> -----END CERTIFICATE-----
> -----BEGIN CERTIFICATE-----
> MIIGNDCCBBygAwIBAgIBGzANBgkqhkiG9w0BAQsFADB9MQswCQYDVQQGEwJJTDEW
> MBQGA1UEChMNU3RhcnRDb20gTHRkLjErMCkGA1UECxMiU2VjdXJlIERpZ2l0YWwg
> Q2VydGlmaWNhdGUgU2lnbmluZzEpMCcGA1UEAxMgU3RhcnRDb20gQ2VydGlmaWNh
> dGlvbiBBdXRob3JpdHkwHhcNMDcxMDI0MjA1NzA5WhcNMTcxMDI0MjA1NzA5WjCB
> jDELMAkGA1UEBhMCSUwxFjAUBgNVBAoTDVN0YXJ0Q29tIEx0ZC4xKzApBgNVBAsT
> IlNlY3VyZSBEaWdpdGFsIENlcnRpZmljYXRlIFNpZ25pbmcxODA2BgNVBAMTL1N0
> YXJ0Q29tIENsYXNzIDIgUHJpbWFyeSBJbnRlcm1lZGlhdGUgU2VydmVyIENBMIIB
> IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4k85L6GMmoWtCA4IPlfyiAEh
> G5SpbOK426oZGEY6UqH1D/RujOqWjJaHeRNAUS8i8gyLhw9l33F0NENVsTUJm9m8
> H/rrQtCXQHK3Q5Y9upadXVACHJuRjZzArNe7LxfXyz6CnXPrB0KSss1ks3RVG7RL
> hiEs93iHMuAW5Nq9TJXqpAp+tgoNLorPVavD5d1Bik7mb2VsskDPF125w2oLJxGE
> d2H2wnztwI14FBiZgZl1Y7foU9O6YekO+qIw80aiuckfbIBaQKwn7UhHM7BUxkYa
> 8zVhwQIpkFR+ZE3EMFICgtffziFuGJHXuKuMJxe18KMBL47SLoc6PbQpZ4rEAwID
> AQABo4IBrTCCAakwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYwHQYD
> VR0OBBYEFBHbI0X9VMxqcW+EigPXvvcBLyaGMB8GA1UdIwQYMBaAFE4L7xqkQFul
> F2mHMMo0aEPQQa7yMGYGCCsGAQUFBwEBBFowWDAnBggrBgEFBQcwAYYbaHR0cDov
> L29jc3Auc3RhcnRzc2wuY29tL2NhMC0GCCsGAQUFBzAChiFodHRwOi8vd3d3LnN0
> YXJ0c3NsLmNvbS9zZnNjYS5jcnQwWwYDVR0fBFQwUjAnoCWgI4YhaHR0cDovL3d3
> dy5zdGFydHNzbC5jb20vc2ZzY2EuY3JsMCegJaAjhiFodHRwOi8vY3JsLnN0YXJ0
> c3NsLmNvbS9zZnNjYS5jcmwwgYAGA1UdIAR5MHcwdQYLKwYBBAGBtTcBAgEwZjAu
> BggrBgEFBQcCARYiaHR0cDovL3d3dy5zdGFydHNzbC5jb20vcG9saWN5LnBkZjA0
> BggrBgEFBQcCARYoaHR0cDovL3d3dy5zdGFydHNzbC5jb20vaW50ZXJtZWRpYXRl
> LnBkZjANBgkqhkiG9w0BAQsFAAOCAgEAbQjxXHkqUPtUY+u8NEFcuKMDITfjvGkl
> LgrTuBW63grW+2AuDAZRo/066eNHs6QV4i5e4ujwPSR2dgggY7mOIIBmiDm2QRjF
> 5CROq6zDlIdqlsFZICkuONDNFpFjaPtZRTmuK1n6gywQgCNSIrbzjPcwR/jL/wow
> bfwC9yGme1EeZRqvWy/HzFWacs7UMmWlRk6DTmpfPOPMJo5AxyTZCiCYQQeksV7x
> UAeY0kWa+y/FV+eerOPUl6yy4jRHTk7tCySxrciZwYbd6YNLmeIQoUAdRC3CH3nT
> B2/JYxltcgyGHMiPU3TtafZgLs8fvncv+wIF1YAF/OGqg8qmzoJ3ghM4upGdTMIu
> 8vADdmuLC/+dnbzknxX6QEGlWA8zojLUxVhGNfIFoizu/V/DyvSvYuxzzIkPECK5
> gDoMoBTTMI/wnxXwulNPtfgF7/5AtDhA4GNAfB2SddxiNQAF7XkUHtMZ9ff3W6Xk
> FldOG+NlLFqsDBG/KLckyFK36gq+FqNFCbmtmtXBGB5L1fDIeYzcMKG6hFQxhHS0
> oqpdHhp2nWBfLlOnTNqIZNJzOH37OJE6Olk45LNFJtSrqIAZyCCfM6bQgoQvZuIa
> xs9SIp+63ZMk9TxEaQj/KteaOyfaPXI9778U7JElMTz3Bls62mslV2I1C/A73Zyq
> JZWQZ8NU4ds=
> -----END CERTIFICATE-----

**Comment by somecoder42** [comment]
Same happens on wiki.python.org

**Comment by abeyer** [comment]
Likely due to not having the startcom root in the trust store due to the startcom/wosign fiasco... python.org and wiki.python.org use startcom certificates, while www.python.org doesn't.

It would be nice if those could be reissued with a different CA

**Comment by MarkMangoba** [comment]
@abeyer we've reissued the cert with a different CA.
