### ISSUE TITLE
mail.python.org:25 unreachable via ipv6

### ISSUE THREAD

**Issue by logic** [python/pythondotorg#1046]
Not sure if this is the right place to report this, but I'm seeing connectivity issues as of Mon Jan  9 08:48:02 UTC 2017 to mail.python.org via SMTP when connecting via IPv6. (For completeness, although I assume whoever ends up fielding this will already know: this is bad because python.org's MX record points to mail.python.org, which has an AAAA record.)

IPv4 appears fine (which is probably why nobody has noticed) and you're listening just fine on port 443 via IPv6, so you *are* reachable, just not via SMTP.

FWIW, https://status.python.org/ is reporting that everything is a-ok. :wink:

**Comment by logic** [comment]
Port 465 doesn't work either, fwiw. :)

**Comment by berkerpeksag** [comment]
Thanks for the report, but postmaster@python.org (they might refer you to infrastructure@python.org) is a better place to report issues with mail.p.o.

This tracker is for issues with www.python.org.

**Comment by logic** [comment]
Thanks, I'll contact postmaster.

(Side note: there's some amount of irony involved in reporting an SMTP problem via the mail server with the issue. ;))
