### ISSUE TITLE
sitetree upgrade

### ISSUE THREAD

**Issue by idlesign** [python/pythondotorg#1048]
Hi,

Since you're using more than one nav type per page, please consider `sitetree` upgrade to v1.7.0, it should speed up things. From your codebase I gather that no special movements would be required, yet it's always a good idea to click-through a couple of pages.

**Comment by berkerpeksag** [comment]
Thanks for the report. Did you notice any performance issues while browsing python.org or just noticed it while reading the codebase?

**Comment by idlesign** [comment]
Noticed after `sitetree` refactoring. I'm the maintainer.

**upd:** Speed up is noticeable at my personal project - http://pythonz.net

**Comment by berkerpeksag** [comment]
That's great, thanks for the heads up! :) I'm going to upgrade it to 1.7.0.

**Comment by berkerpeksag** [comment]
I'm about to upgrade django-sitetree to 1.8.0. Note that we are using Django's default cache backend so I assume performance gain will be smaller. I've opened #1113 to use a more efficient cache backend.
