### ISSUE TITLE
need to update apps categories

### ISSUE THREAD

**Issue by djay** [python/pythondotorg#105]
Some ideas but I'm sure others have more
- update web frameworks to include pyramid, flask and bottle
- include CMS category including plone djangocms mezzanine pelican
- tools like PANDAS are also increasingly important

**Comment by akuchling** [comment]
What page are you referring to?  /about/apps has been recently updated.

**Comment by djay** [comment]
The homepage "Use python for...", which is a summary of /about/apps.
I notice it did get updated which is great. I organise a well attended python meetup in Sydney so my opinions are coming from my experience in what talks are the most attended.
I do think a CMS category is important as some feel that python doesn't offer compelling alternatives to wordpress or drupal. 
I'm also thinking mobile development is important with kivi.
Game development should be put back inc pygame and pyglet.
Would it be fair to include appengine under webdevelopment? Maybe uwsgi or gunicorn?
If you look at popularity you can see important packages to list.
zc.buildout should be under software development?
lxml should be in there. SQLAlchemy. Fabric, Celery. graphite. supervisor. sphinx. 
asyncio like tornado, gevent and twisted should be in there.
ipython notebook should be in there somewhere.
Saltstack.

**Comment by frankwiles** [comment]
Fixed long ago, just not closed.
