### ISSUE TITLE
Upgrade the shell to 3.6

### ISSUE THREAD

**Issue by yan12125** [python/pythondotorg#1051]
Currently https://console.python.org/python-dot-org-console/console_frame/ still uses 3.5. It would be great to have 3.6.

For example, when I want to show other people that their codes are broken on 3.6.

**Comment by berkerpeksag** [comment]
According to https://www.pythonanywhere.com/, it doesn't support Python 3.6 yet. Let's ping @gpjt and ask if there is any plan for adding Python 3.6 support :)

**Comment by gpjt** [comment]
There definitely is!  No hard ETA yet, but it's coming -- and we'll move the the python.org consoles over to that as soon as it's done.

**Comment by gpjt** [comment]
...and that's done :-)  This ticket can probably be closed.

**Comment by berkerpeksag** [comment]
Thanks! :)
