### ISSUE TITLE
Python 2.7.13 for Windows broken (from prompt)

### ISSUE THREAD

**Issue by frakman1** [python/pythondotorg#1052]
I used to have an older version of python 2.7 that has worked for years. I just upgraded to 2.7.13 for Windows, 32 bit and now, I can't get the interpreter to run from the command line. It just returns to the DOS prompt.

```
c:\Python27>python
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
c:\Python27>python
```

**Comment by tjguk** [comment]
On 10/02/2017 13:18, Frak wrote:
> I used to have an older version of python 2.7 that has worked for years.
> I just upgraded to 2.7.13 for Windows, 32 bit and now, I can't get the
> interpreter to run from the command line. It just returns to the DOS prompt.
>
> |c:\Python27>python Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016,
> 20:42:59) [MSC v.1500 32 bit (Intel)] on win32 Type "help", "copyright",
> "credits" or "license" for more information. c:\Python27>python |

Thanks, Frak. This isn't the right place for bugs with Python itself; 
could you raise a bug on the Python issue tracker, please:

https://bugs.python.org

This is certainly very strange, so it will help if you can details your 
platform (WinXP, Win7, 10 etc.) and any other details which you think 
might be useful

**Comment by frakman1** [comment]
Thank you. I opened a case [here](http://bugs.python.org/issue29525#)
