### ISSUE TITLE
Dev fixtures now enormous and causes error

### ISSUE THREAD

**Issue by tjguk** [python/pythondotorg#1055]
I'm just setting up a dev environment on a new machine. The step to load the dev fixtures downloads a ~40Mb gzipped file which expands to a ~375Mb JSON file! Unserialising this blows the memory of the 2Gb VM which the Vagrantfile specifies. When I upped it to 3Gb, the build then failed with a foreign key error from the account_emailaddress table.

psycopg2.IntegrityError: insert or update on table "account_emailaddress" violates foreign key constraint "account_emailaddress_user_id_222ae05cea7eaf01_fk_users_user_id"
DETAIL:  Key (user_id)=(148962) is not present in table "users_user".

The fixtures are loaded via Django's loaddata mechanism which unserialises the entire object set from the JSON data into memory before it starts to do anything.

So:
* We have a very big fixtures file which, even with enough memory, takes a long time to load
* It's possible that we could exclude some models which are not necessary for the dev environment to function, but someone would have to work out what those were.
* It's also possible we could pre-process the .json file, reserialising it without some of the data
* On top of all that, there is at least one foreign key consistency. This *might* be because the cron job which serialises the contents in the first place (via dumpdata) caught the database between writes; or it could be that there really is a mismatch.

I'm not clear what the best way forward is. There are incremental JSON unserialisers but there's no clear way to insert that into the Django loaddata command. Also, we could skip certain models and/or FK errors, but the former requires a knowledge of which models are essential, and the latter requires monkeypatching Django AFAICT.

Comments welcome

**Comment by berkerpeksag** [comment]
Yeah, my plan is to use either data migration or factory_boy to create initial data and get rid of all fixtures.

**Comment by berkerpeksag** [comment]
I've opened #1142 to create initial data via factory_boy.

**Comment by berkerpeksag** [comment]
@tjguk this should be fixed in `master` now. I've updated the [installation guide](https://pythondotorg.readthedocs.io/install.html). Could you try again?
