### ISSUE TITLE
Download URLs for a "supervisor" project versions 3.3[.1]

### ISSUE THREAD

**Issue by jem-ka** [python/pythondotorg#1058]
Trying to download anything past version 3.2 of the "supervisor" package fails when using buildroot's package system; did the package download URL scheme change? I spent a few minutes trying to find where the scheme is documented on PyPI but it's a bit obtuse to search for.

Buildroot package info for the last package version that works is:

```
SUPERVISOR_VERSION = 3.2.3
SUPERVISOR_SITE = http://pypi.python.org/packages/source/s/supervisor
SUPERVISOR_LICENSE = BSD-like, rdflib (http_client.py), PSF (medusa), ZPL-2.1
SUPERVISOR_LICENSE_FILES = COPYRIGHT.txt LICENSES.txt
SUPERVISOR_SETUP_TYPE = setuptools
```

generating an attempt to download:
`http://pypi.python.org/packages/source/s/supervisor/supervisor-3.2.3`

I'm using a somewhat dated version of buildroot itself, but it's odd to me that these work but not:
`http://pypi.python.org/packages/source/s/supervisor/supervisor-3.3.1`

**Comment by berkerpeksag** [comment]
Thanks for the report. This tracker is for issues with www.python.org. pypi.python.org's issue tracker is located at https://github.com/pypa/pypi-legacy/issues

However, you might want to report this to buildroot first. It looks like buildroot should first make a request against [`/simple/supervisor/`](https://warehouse.pypa.io/api-reference/legacy/) and fetch links from the response.
