### ISSUE TITLE
ArgParse page in library reference rewrite

### ISSUE THREAD

**Issue by sweavo** [python/pythondotorg#1059]
Although it's a reference page, it is clouded by too many examples and too little reference material. Moreover, the examples are not real-world applications of argument parsing.

I propose removing the "process some integers" example, replacing it with something more typically gnu style, e.g., `myapp.py [--quiet] [--log-level _n_] [--title=STR] {get | put} [FSPEC [, FSPEC...]]`. This shows the user how to to many of the common command-line tasks.

**Comment by Mariatta** [comment]
This issue tracker is for Python.org website.
If you have suggestions for improving Python documentation, you can create an issue at bugs.python.org. Thanks :)

**Comment by berkerpeksag** [comment]
Thanks, Steve. Please create a new issue on bugs.python.org. You may want to include your patch or pull request to the issue since it's hard to guess the scope of rewriting a document :)
