### ISSUE TITLE
Broken image in header banner on Success Stories page

### ISSUE THREAD

**Issue by linssen** [python/pythondotorg#106]

**Comment by fcurella** [comment]
img is set to `/static/img/google-trans.png` but there's no trace of that file in the repo

![screen shot 2014-02-22 at 6 49 18 pm](https://f.cloud.github.com/assets/89607/2238358/25c4b900-9bea-11e3-9db5-93ee35f44d5b.png)

**Comment by malemburg** [comment]
The success stories have not yet been ported to the new site. What you currently see are just test entries that were partially imported from the legacy site.

Note that placing company logos on these stories is a tricky business. The PSF will have to get permission to use the logos on the website, so please don't just copy e.g. some Google or YouTube logo into the site.

**Comment by hugovk** [comment]
The broken image has been removed:

<img width="1582" alt="image" src="https://github.com/user-attachments/assets/2218cda9-b886-4a67-8a3e-83ccb2305f22">

Okay to close? Please re-open if more work is needed.
