### ISSUE TITLE
cannot log into python.org

### ISSUE THREAD

**Issue by jjanderson5** [python/pythondotorg#1060]
I have an account at python.org that I create years ago, but I have been inactive with it for a number of years. I tried signing on as jjanderson5, but it was rejected multiple times. I decided to try to re-register at the registration page. I got through the page and received an email. Then responded to the email and went to the URL provided in the email to confirm, but this did not work. I did receive a follow up email that said there was an error.

Can you help me recreate the jjanderson5 login id at python.org. Can you create the account and provide me with a temporary password?

Regards,
Jim Anderson

**Comment by MarkMangoba** [comment]
@jjanderson5 can you email me at mmangoba@python.org?  That way we can get your login settled.

Thanks,
M

**Comment by MarkMangoba** [comment]
@jjanderson5 emailed me, will handle from there.
