### ISSUE TITLE
Python 3.6.0 is not working in my system, please help me to solve this problem...

### ISSUE THREAD

**Issue by ghost** [python/pythondotorg#1061]
Hello, guys, I don't what happen to my laptop, but python 3.6.0 is not working on my laptop, it is **saying api-ms-win-crt-stdio-l1-1-0.dll is missing from your computer.....**, please tell me how to solve this problem.....
![screenhunter_1509 mar 10 17 29](https://cloud.githubusercontent.com/assets/26327375/23798584/54961492-05cb-11e7-8db0-cf3eb96a5bc8.jpg)

**Comment by berkerpeksag** [comment]
Thanks for the report. This tracker is for issues with www.python.org only. Please use [python-list](https://mail.python.org/mailman/listinfo/python-list) or StackOverflow for usage and installation questions.
