### ISSUE TITLE
Update to 'Python Patterns - An Optimization Anecdote'

### ISSUE THREAD

**Issue by hardkrash** [python/pythondotorg#1064]
I came across https://www.python.org/doc/essays/list2str/ today and thought, interesting topic. What has changed in python3 that would make this article a bit different.

So I updated the example program to python3 syntax and ran it on my computer adding two newer functions written with list comprehensions and `bytes()`

Low and behold bytes was as fast as you could get, no surprise here.
But I thought it would be good to share, and maybe add an update...

How would I go about updating the article?

My modified file, dropping test f5 as string no longer has `joinlist`.
[f.py.txt](https://github.com/python/pythondotorg/files/852253/f.py.txt)
Note: Appended `.txt` to allow upload with this issue.

**Comment by laike9m** [comment]
+1, this article definitely needs to be updated.

The three options that should be compared today are:
```
''.join(chr(x) for x in a)
''.join([chr(x) for x in a])
''.join(map(chr, a))
```

**Comment by berkerpeksag** [comment]
Thanks for the report and for the updated example. All materials under /doc/essays/ are there for historical purposes so I'm not sure whether we should update that text or not.

My suggestion is 1) add a warning that basically says "the essay may be outdated" 2) add a link to a more appropriate article on wiki.python.org (I'm sure there is a page about optimizations on the Wiki) 3) (optional) publish your updated version and code examples on wiki.python.org

**Comment by berkerpeksag** [comment]
I went with option 1 and added a warning to the page. I've also add some style to warning boxes to make them more visible in https://github.com/python/pythondotorg/commit/060ae6a8061110043f84ce1e0a15cb029f15f647. 

Thanks again!
