### ISSUE TITLE
Registration Fails -> Nginx 502 error

### ISSUE THREAD

**Issue by caramucho54** [python/pythondotorg#1065]
Hi

Registration to Community seems to be broken.

Registration Fails -> Nginx 502 error

I Need to register to get help on Python :)

Please fix it fast !

Best Regards

**Comment by MarkMangoba** [comment]
@CaramuchoDotCom can you try again?

**Comment by caramucho54** [comment]
No. Same problem as I used "reset my password"

502 Bad Gateway

2017-03-22 23:12 GMT+01:00 Mark Mangoba <notifications@github.com>:

**Comment by gediz** [comment]
Hello. I see the same response when I try to reset my password. Thanks in advance.
![nginx502](https://cloud.githubusercontent.com/assets/5806838/24223574/8637aa86-0f5f-11e7-9d79-a947a5ad8ac5.png)

**Comment by MarkMangoba** [comment]
@gediz & @CaramuchoDotCom give it a try again.

**Comment by MarkMangoba** [comment]
hey @gediz @CaramuchoDotCom  let me know if your still having issues.  i'll go ahead and close this.
