### ISSUE TITLE
Links to 3.6.1 Document downloads return 404

### ISSUE THREAD

**Issue by thomco** [python/pythondotorg#1066]
As of today, the 'Python Documentation Download' page (https://docs.python.org/3/download.html) points to the 3.6.1 documents.

However, none of these archive files exist and the links all return 404

**Comment by ned-deily** [comment]
Sorry about that.  It looks like those documents are automatically built once a day and the release just missed yesterday's build cycle.  If I'm correct, they should appear in about three hours.

**Comment by thomco** [comment]
It looks like all the 3.6.1 docs are there now
Thanks!

**Comment by Mariatta** [comment]
Sounds great :) Thanks @thomco and @ned-deily.
