### ISSUE TITLE
Choosing a CI server

### ISSUE THREAD

**Issue by SamGJohn** [python/pythondotorg#1067]
[CircleCI](https://circleci.com/) has a ton of Python users and as shown [here](https://www.g2crowd.com/categories/continuous-integration) is the industry leader. I was hoping you would append the sections below to include their [continuous integration](https://circleci.com/) platform and a link to the website. Thanks.

>  Choosing a CI service
> 
> There are various CI services that provide free support for open source projects hosted on GitHub [2]. Two such examples are Travis [33] and Codeship [34]. Whatever solution is chosen will need to not time out in the time it takes to execute Python's test suite. It should optimally provide access to multiple C compilers for more thorough testing. Network access is also beneficial.
> 
> The current CI service for Python is Pypatcher [38]. A request can be made in IRC to try a patch from bugs.python.org [5]. The results can be viewed at https://ci.centos.org/job/cPython-build-patch/ .

**Comment by berkerpeksag** [comment]
Thanks for the report. This was discussed before on the core-workflow list and PEP 512 has already been implemented so I don't think we will resurrect the discussion again.

Also, this tracker is for issues with www.python.org source code.
