### ISSUE TITLE
Disabling SSL verification at application level

### ISSUE THREAD

**Issue by rnagpal** [python/pythondotorg#1068]
Is there a way to disable SSL verification at my application level. I'm using the requests module which allows be to disable it per request level(by setting verify to false) but I wanted to way to disable for all requests. I'm running my tests against my local emulator, so I don't need that check and hence want to disable it at my application(test) level.

I'm looking for something like process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0" as used in Node.js

**Comment by Mariatta** [comment]
Hello @rnagpal. This is the issue tracker for python.org website.
``requests`` library is not part of Python standard library, but rather is being maintained at https://github.com/kennethreitz/requests
Please file your concerns there :)

Thanks.

**Comment by rnagpal** [comment]
Hi @Mariatta , is there a github repo for pure Python questions? I'm using requests module but I want to know a way to disable it at my application level by using some Python environment variable.

**Comment by Mariatta** [comment]
@rnagpal General questions about Python can be asked at [python-list](https://mail.python.org/mailman/listinfo/python-list) or [python-tutor](https://mail.python.org/mailman/listinfo/tutor) mailing lists.
