### ISSUE TITLE
Text resize links don't do anything?

### ISSUE THREAD

**Issue by linssen** [python/pythondotorg#107]
![screen shot 2014-02-20 at 12 49 33](https://f.cloud.github.com/assets/67624/2218382/81c4c538-9a2d-11e3-9c9c-bffa03b84703.png)

Clicking / tapping any of those doesn't seem to do anything. It also resets the page position to the top of the page effectively opening the menu.

**Comment by frankwiles** [comment]
It was removed some time ago, so closing.
