### ISSUE TITLE
The release schedule Google calendar is not up to date

### ISSUE THREAD

**Issue by marczellm** [python/pythondotorg#1070]
Under https://www.python.org/downloads/ the visitor looking for the release schedule .is directed to a Google Calendar. This calendar is unfortunately more than two years stale. Please keep the calendar up to date or provide some other way of viewing/reaching the release schedule from here.

**Comment by berkerpeksag** [comment]
@ned-deily should we keep the calendar or can it be removed?

I'd prefer adding links of release schedule PEPs to /downloads/.

**Comment by MarkMangoba** [comment]
@berkerpeksag I agree with you but definitely up to @ned-deily!
