### ISSUE TITLE
Broken links on https://wiki.python.org/moin/PythonSpeed

### ISSUE THREAD

**Issue by GregEremeev** [python/pythondotorg#1071]
Paragraph with the title "Take advantage of diagnostic tools" contains broken link
"hotshot" (http://docs.python.org/library/hotshot.html)

Also, paragraph with the title "Consider external tools for enhancing performance" contains broken link "A beginners guide to using Python for performance computing"
 (https://scipy.org/PerformancePython). I think actual address is (http://scipy.github.io/old-wiki/pages/PerformancePython)

**Comment by berkerpeksag** [comment]
Thanks for the report! I've now fixed both of the broken links. If you'd like to fix broken links yourself you can take a look at https://wiki.python.org/moin/FrontPage#Editing_pages

Also, note that that page is a bit old and some of the tips may be outdated by now. It also doesn't mention about Python 3.
