### ISSUE TITLE
PSF landing page:  Error 503 first byte timeout.

### ISSUE THREAD

**Issue by MarkMangoba** [python/pythondotorg#1073]
@dstufft & @ewdurbin reported Error 503 first byte timeout.  https://www.python.org/psf-landing/.

**Comment by Mariatta** [comment]
I'm seeing: 504 Gateway Time-out. The server didn't respond in time.

**Comment by berkerpeksag** [comment]
Since we didn't get the same error again in the past three months and there were no commits in both python/pythondotorg and python/psf-salt repos that may cause the error, I'm going to mark this as a transient error.
