### ISSUE TITLE
Copy static resources from Legacy python.org website

### ISSUE THREAD

**Issue by Mariatta** [python/pythondotorg#1074]
Planetpython is referencing several static resources from the legacy python.org website.
For example:
https://github.com/python/planet/blob/b1f978144bb90709a0ff37fe602dcd05abf462a3/config/index.html.tmpl#L6
https://github.com/python/planet/blob/b1f978144bb90709a0ff37fe602dcd05abf462a3/config/index.html.tmpl#L8
https://github.com/python/planet/blob/b1f978144bb90709a0ff37fe602dcd05abf462a3/config/index.html.tmpl#L9

Could we copy these into the new python.org, under static directory?

This comes up while investigating these issues at planetpython (https://github.com/python/planet/pull/219) and (https://github.com/python/planet/issues/193) and trying to enable https.
cc @MarkMangoba

**Comment by berkerpeksag** [comment]
No, those files are for the old python.org design and it's better to leave them out of current python.org.

Is it impossible to serve them under planetpython.org?

**Comment by MarkMangoba** [comment]
@berkerpeksag thanks for the feedback!  Yes, i'll look into serving them under planetpython.org - that seems feasible.

**Comment by Mariatta** [comment]
Thanks for looking into this @berkerpeksag and @MarkMangoba.

**Comment by berkerpeksag** [comment]
This has been fixed in https://github.com/python/planet/commit/35a62bbc9bf7c3015534031861cae345a9fb78d2.
