### ISSUE TITLE
Downloads from pip not tracked?

### ISSUE THREAD

**Issue by stephenpaulger** [python/pythondotorg#1078]
It looks like the data for downloads of a package is incorrect.

    >>> import requests
    >>> data = requests.get("https://pypi.python.org/pypi/pip/json").json()
    >>> data["info"]["downloads"]
    {u'last_month': 0, u'last_week': 0, u'last_day': 0}

**Comment by berkerpeksag** [comment]
Thanks for the report. This issue tracker is for issues with www.python.org, not PyPI.

To answer your question, download stats are not available on PyPI anymore, but you can still see all of them by querying a Bigtable database on Google Cloud. I don't have a reliable internet connection at the moment so I'm afraid you'll need to search it on Google yourself :)
