### ISSUE TITLE
Download Page To Show 3.x First

### ISSUE THREAD

**Issue by juanal-f** [python/pythondotorg#1079]
In my opinion, it would be better if download pages had links to version 3.x on top instead of version 2.x. Otherwise, it gives the impression that version 2.x is preferable.

Location:
- https://www.python.org/downloads/mac-osx/
- https://www.python.org/downloads/windows/
- etc.

**Comment by berkerpeksag** [comment]
+1. I'll change that to list Python 3 downloads first, thanks.

**Comment by CianciuStyles** [comment]
I've just submitted a MR to solve this, it's available at https://github.com/python/pythondotorg/pull/1096.
