### ISSUE TITLE
Online Shell Isn't Loading

### ISSUE THREAD

**Issue by andrewbota** [python/pythondotorg#1081]
When I use the online shell, it loads the page but will not load the shell. It says - 
"Loading console" which is successful. Then -
"Preparing execution environment" which fails. I tried using the shell on 3 different computers, all with the same error - 
"Sorry, your console process failed to start. Please try again.
If this persists, please contact support.
Console closed."

**Comment by berkerpeksag** [comment]
Thanks for the report. I'm getting the same message. I'll just ping @gpjt in case they are not aware of the issue. Please note that things may have progress a little bit slower than usual because of PyCon US.

**Comment by gpjt** [comment]
Thanks for reporting this!  We pushed a system update this morning which should have fixed the problem -- it's currently working fine for me.

**Comment by berkerpeksag** [comment]
Thanks!
