### ISSUE TITLE
Member sign-up form doesn't display in Chrome

### ISSUE THREAD

**Issue by reubano** [python/pythondotorg#1082]
https://www.python.org/users/membership/

Chrome
![window 2017-05-23 at 21 50 05](https://cloud.githubusercontent.com/assets/157864/26387436/8607395e-4002-11e7-8398-3bf4cf0c15fb.png)

FF
![window 2017-05-23 at 21 52 46](https://cloud.githubusercontent.com/assets/157864/26387447/a81d2d78-4002-11e7-9536-a918a928b356.png)

CR #391

**Comment by reubano** [comment]
Turns out that disabling Adblock Plus allows the form to appear. I played around with the debugger and the form is being blocked because it has a class with `subscribe` in the name. Changing the class name made everything work again.

**Comment by berkerpeksag** [comment]
Thanks for the report. I'm also using Chrome and Adblock, but I can see the "Register" sidebar at https://www.python.org/accounts/login/ Do you have any custom filters set?

**Comment by jackiekazil** [comment]
@reubano can you also add what version of Chrome you are using and what resolution you are viewing it at?

**Comment by MarkMangoba** [comment]
@reubano you should be able to access:  https://www.python.org/accounts/signup/ to sign up for an account.  As @berkerpeksag mentioned, I too can see the register sidebar via adblock / chrome.

**Comment by reubano** [comment]
Chrome Version 58.0.3029.110 (64-bit). All resolutions.

Filters

×   Enabled Adblock Warning Removal List Failed, download failure
×   Enabled EasyList Failed, download failure
×   Enabled Malware Domains Failed, download failure
×   Enabled Fanboy's Social Blocking List Failed, download failure
×   Enabled EasyPrivacy Last updated at 12:16:39 AM on 5/28/2017

My guess is the "Social Blocking" filter caused the block.

**Comment by berkerpeksag** [comment]
Thank you for the details! I'm not sure what to do here :) I'm pretty sure that the PSF won't allow any advertisement on www.python.org. I usually disable AdBlock on sites I trust (e.g. Wikipedia) I think the best step is to ask the maintainer of https://github.com/ryanbr/fanboy-adblock to whitelist www.python.org.
