### ISSUE TITLE
Dead links on `python.org`

### ISSUE THREAD

**Issue by delirious-lettuce** [python/pythondotorg#1084]
* https://www.python.org/doc/newstyle/

    > Raymond Hettinger's [How-To Guide for Descriptors](http://users.rcn.com/python/download/Descriptor.htm)

    > David Mertz and Michele Simionato's [DeveloperWorks article](http://www-106.ibm.com/developerworks/linux/library/l-pymeta.html)

**Comment by Mariatta** [comment]
Thanks @delirious-lettuce 

The first link should probably be https://docs.python.org/3/howto/descriptor.html

Not sure about the second one.

I don't have access to update the content in those pages.

**Comment by delirious-lettuce** [comment]
@Mariatta ,

Thanks for the response! It's not a big deal and I just wanted to raise the issue before I forgot. I was reading about old vs new style classes and that's when I came across the dead links.

Also, I apologize for any misunderstanding about my other PR (using `textwrap.dedent`). I naively thought I was helping but I realize now that style PR's are frowned upon and I will not make that same mistake again.

Thanks for your time!

**Comment by berkerpeksag** [comment]
Thank you for the report.

I replaced the first link with http://web.archive.org/web/20170221220235/http://users.rcn.com/python/download/Descriptor.htm

I only found the Japanese version of the second link on DeveloperWorks at https://www.ibm.com/developerworks/jp/linux/library/l-pymeta/index.html So I replaced it with a mirror instead: http://gnosis.cx/publish/programming/metaclass_1.html I added a footnote to explain this.

Also, I updated warning text to add a link to the up-to-date version of the descriptor HOWTO.

**Comment by delirious-lettuce** [comment]
Thanks for the fix!

 I came across the dead links by accident and just thought it would be
helpful to report them.
