### ISSUE TITLE
[Suggestion] Improve documentation for set() API

### ISSUE THREAD

**Issue by jhpratt** [python/pythondotorg#1086]
While going through the documentation, I found that `set()` has surprisingly little documentation, not even a list of built-in methods.

I'm not sure exactly what is missing, but I know that `issubset` and `issuperset` isn't in there (that's what I was looking for, specifically).

Thanks!

**Comment by Mariatta** [comment]
Hi, this issue tracker is for python.org website.

For issues with Python documentation, please open an issue at https://bugs.python.org, and select the 'Documentation' component. 

Thanks :)

**Comment by jhpratt** [comment]
Will do. I wasn't sure if this was the right place or not.

**Comment by Mariatta** [comment]
No prob :)
