### ISSUE TITLE
Links at the bottom: Add link to the CoC in Community

### ISSUE THREAD

**Issue by vstinner** [python/pythondotorg#1087]
Hi,

Would it be possible to add a link to "Python Community Code of Conduct" https://www.python.org/psf/codeofconduct/ from the Community section at the bottom of each page at python.org.

IMHO it's important to "promote" this code of conduct!

Victor

**Comment by berkerpeksag** [comment]
Done. Added "Code of Conduct" link in "Community" section.

**Comment by vstinner** [comment]
Oh, you are fast, thank you ;-)

**Comment by willingc** [comment]
Thanks @berkerpeksag and @haypo 👍

**Comment by yarko** [comment]
Hmmm.... that is a link to the diff (changeset);   did you maybe intend to make a link to something this (?):

https://hg.python.org/coc/file/tip/CodeOfConduct.rst

**Comment by vstinner** [comment]
> Hmmm.... that is a link to the diff (changeset); did you maybe intend to make a link to something this (?): https://hg.python.org/coc/file/tip/CodeOfConduct.rst

The note at https://www.python.org/psf/codeofconduct/ already links to https://hg.python.org/coc/rev/689163936c9d It's better to use a link with a revision rather than "tip" since "tip" can changed if someone push a new change.
