### ISSUE TITLE
Ostensible Security Issue With the Console on the Open Page

### ISSUE THREAD

**Issue by theideasmith** [python/pythondotorg#1089]
I just wanted to share my concerns with the people who run python.org that perhaps the console on the main page is insecure. 

1. I am able to access information which, frankly, I shouldn't be able to see.

eg: 

`import platform; platform.node()`
`import os; os.listdir(".")`

I could even run `import np; np.arange(1e10)` which was probably too much memory for the process to handle, because the process shut down. 

2. Even more worrisome is the fact that `import subprocess; subprocess.call("your bash here"` actually works! To test this out (thinking that it wouldn't actually work) I ended up deleting the files ('README', `.pythonstartup.py`, ...) located in `/home/.anon-dfc63bde520e4d3da4a004b9` on node `conrad-liveconsole5`

3. The list goes on; the process has read access to the entire filesystem, and write access to part of it so, for example, I know the process is running in a docker container, that there is a vimrc file, etc. 

I don't know if there are any real security concerns here but I thought I'd point these issues out in case it was a real issue. 

I guess because `proc` is closed to the process you cant really start killing processes. Also `/` is closed to the process. But it is surprising in the directory in which the process starts I am actually able to delete files. 

From a devoted python user,

Akiva

**Comment by berkerpeksag** [comment]
Thank you for the report. The online REPL is maintained by PythonAnywhere and it runs in a sandbox.

This is basically a duplicate of #1035 and @gpjt has explained that why this isn't an issue in https://github.com/python/pythondotorg/issues/1035#issuecomment-268222391.

**Comment by theideasmith** [comment]
Hi @berkerpeksag thanks for your prompt response and for directing me to that other issue.
