### ISSUE TITLE
All sidebar links in events page are broken

### ISSUE THREAD

**Issue by linssen** [python/pythondotorg#109]
All link to '#'

**Comment by tomvon** [comment]
Adding some more detail. Saw the same.

http://python.org/events/python-events/past/#

![screen shot 2014-02-20 at 9 07 48 am](https://f.cloud.github.com/assets/350323/2218940/aace559c-9a38-11e3-87d5-fc7c8c6bb453.png)

**Comment by malemburg** [comment]
Flavio: This is a different request than the one you closed in #158.

Please use these links for the Python Events Calendar:
- Google Calendar: https://www.google.com/calendar/embed?src=j7gov1cmnqr9tvg14k621j7t5c@group.calendar.google.com&ctz=Europe/London
- RSS: https://www.google.com/calendar/feeds/j7gov1cmnqr9tvg14k621j7t5c@group.calendar.google.com/public/basic?orderby=starttime&sortorder=ascending&futureevents=true
- iCal: https://www.google.com/calendar/ical/j7gov1cmnqr9tvg14k621j7t5c@group.calendar.google.com/public/basic.ics
- Twitter: https://twitter.com/PythonEvents

and these links for the Python User Group Calendar:
- Google Calendar: https://www.google.com/calendar/embed?src=3haig2m9msslkpf2tn1h56nn9g@group.calendar.google.com&ctz=Europe/London
- RSS: https://www.google.com/calendar/feeds/3haig2m9msslkpf2tn1h56nn9g@group.calendar.google.com/public/basic?orderby=starttime&sortorder=ascending&futureevents=true
- iCal: https://www.google.com/calendar/ical/3haig2m9msslkpf2tn1h56nn9g@group.calendar.google.com/public/basic.ics
- Twitter: https://twitter.com/PythonEvents

Please also add a link "Add an event to this calendar" (or similar) to both calendar mentions, pointing to https://wiki.python.org/moin/PythonEventsCalendar#Submitting_an_Event

Thanks.

**Comment by malemburg** [comment]
I've added a menu entry for submitting events now, but having the "Add an event" link on the pages would be good as well.

**Comment by fcurella** [comment]
I'm going to submit a PR for the subscription links.

when that is merged, the 'events-subscriptions' box (pk# 38) will have to be modified to contain just an `a` element that points to https://wiki.python.org/moin/PythonEventsCalendar#Submitting_an_Event
