### ISSUE TITLE
Becoming owner of unmaintained package winpdb

### ISSUE THREAD

**Issue by bluebird75** [python/pythondotorg#1093]
Hi,

This is a request related to a specific PyPI package, please tell me if there is a more appropriate medium to put my request.

My request is related to the project page of Winpdb, a standalone portable WxPython debugger. It has been developed by Nir Aides, initially on google code. See ( http://www.winpdb.org and  https://pypi.python.org/pypi/winpdb ). The last release of winpdb is version 1.4.8, in 2010.

Since 2013, I have been maintaining a bug-fixed version on Github, which fixes a few annoying bugs, removes a few annoyances and provides more compatibility with latest versions of Python. A kind of a friendly fork, which I properly refernce the history of the project.

In 2014, I exchanged a few emails with Nir Aides, the author, to have my version reviewed and possibly published. Unfortunately this never happened, despite several reminders.

This could have been fine, but lately, with google code shutdown, the packaged version on PyPi no longer works: it pulls a previous buggy version of winpdb due to dead google code links (see https://github.com/bluebird75/winpdb/issues/6 ). 

My attempt to contact the author to fix this issue have been unanswered.

I therefore would like to become the de facto author on the PyPi page, in order to fix the issue above, and even release the latest bugfixed version.

Thanks in advance for your support.

Cheers,

Philippe

**Comment by bluebird75** [comment]
@nir  would you be ok with that ?

**Comment by berkerpeksag** [comment]
Thank you for the detailed report, but please report your problem to https://github.com/pypa/pypi-legacy This tracker is for issues with www.python.org.

And of course if @nir can add you as a maintainer on PyPI, you don't need to open another issue on PyPI's issue tracker.
