### ISSUE TITLE
Windows 64 downloads have an admonishment about Itanium processors

### ISSUE THREAD

**Issue by tritium21** [python/pythondotorg#1094]
On the download page on python.org, all the windows 64 bit downloads have a note stating that the download is not for Itanium processors.

![a05oqmp](https://user-images.githubusercontent.com/1781587/27813644-57c001c6-6045-11e7-9d1b-83253b66f4ac.png)

But [no one uses Itanium processors](https://en.wikipedia.org/wiki/Itanium#Market_share) (for values of no one greater than zero, but not much greater).  Is this really required?  The download link explicitly says X86-64 already, and Itanium users would know to look for that.

And as far as I can tell, Itanium is on it's way out very soon.

**Comment by berkerpeksag** [comment]
Thank you for the report. That field usually filled by release managers and/or platform experts who build installers. Let's ping @ned-deily and @zooba and see what they think about this. I can drop the Itanium part once we get feedback from them.

**Comment by tjguk** [comment]
FWIW I'm fairly sure this note was in place waaaaay back, certainly 
before Steve was involved; not sure about Ned. Anyway, let's see what 
they say, but I'm fairly sure it can safely be dropped for the reasons 
given by the OP.

We've got quite a few bits & pieces like this around the place which 
move from "useful warning" to "fairly common knowledge" to "faintly 
amusing" to "what on earth is that about?" The difficulty is in knowing 
at what stage to have a clear-out!

**Comment by berkerpeksag** [comment]
We also need to remove it from https://github.com/python/release-tools/blob/master/add-to-pydotorg.py#L57-L65 (leaving this here so I won't forget)

**Comment by ned-deily** [comment]
I'm fine with changing the wording as long as @zooba is.

**Comment by tritium21** [comment]
For the record, I don't think it causes harm, I just think to the average user it looks.... well... "what on earth is that about?"

**Comment by berkerpeksag** [comment]
I've now stripped ", not Itanium processors" from 157 release files via [this script](https://gist.github.com/berkerpeksag/ca086a09407b3d985f6bf5b83c680dc1).

**Comment by berkerpeksag** [comment]
I've also updated `add-to-pydotorg.py` script in https://github.com/python/release-tools/commit/73ca49995946eeef505c0342b2795a1dfc9c5e32.

**Comment by zonecodez** [comment]
"not itanium processors" still appears when browsing with firefox

**Comment by berkerpeksag** [comment]
The latest release files were probably uploaded by an old copy of `add-to-pydotorg.py`. There is no note about Itanium processors at https://github.com/python/release-tools/blob/31575abc23e3e2ca1ceb33aba7ae20d6448b710b/add-to-pydotorg.py#L56-L65 anymore.
