### ISSUE TITLE
python3 EOFError

### ISSUE THREAD

**Issue by leoxucn822** [python/pythondotorg#1097]
Exception Name: EOFError
Exception Message: EOF when reading a line
Exception Line number: 7
5     B = []
6     C = []
7     A = [int(x) for x in input().split()]
8     B = [int(x) for x in input().split()]
9     for index in range(N):

Hello guys:
I don't know how to solve the runtime error
Is there anyone can help me?
thanks in advance

**Comment by berkerpeksag** [comment]
Thank you for the report. This tracker is for issues with www.python.org. You can ask usage questions to [python-list](https://mail.python.org/mailman/listinfo/python-list) or [python-tutor](https://mail.python.org/mailman/listinfo/tutor) lists.
