### ISSUE TITLE
Also in the main nav, .tier-1 LIs need an ID

### ISSUE THREAD

**Issue by jhogue** [python/pythondotorg#11]
In order for the javascript to work, the ID of the LI element needs to be equal to the slug of the main nav text. For example, the "About" LI needs to be id="about", "Success Stories" needs to be id="success-stories". 

Right now the value in that spot is "None". Once that is done, the supernavs should load at the larger screen sizes (over 1024).

**Comment by jefftriplett** [comment]
The `alias` field in django-sitetree (under Additional settings) dumps out in the id name. I"m going to populate the top levels and add that to the fixture.

**Comment by jefftriplett** [comment]
On second glance, I think we started using the `alias` field with as a holder of psf-meta, about-meta, etc. Will it mess stuff up menus if I change this to just id="about" whereas I think it was using class="about-meta" before?

**Comment by jefftriplett** [comment]
Looks like our best bet is to take the `title` and filter it through Django's `slugify` filter. We just need to make sure that we don't abbreviate any of the css styles like documentation to docs though or else they won't work.
