### ISSUE TITLE
web site bug tracker unattended, apparently

### ISSUE THREAD

**Issue by vinsci** [python/pythondotorg#1103]
bugs.python.org has apparently not sent new account registration emails for fifteen months: issue on the tracker for the tracker here psf.upfronthosting.co.za/roundup/meta/issue584 'Registration confirmation emails never arrive, tested with multiple email hosts'.

That site is linked from 'Report Tracker Problem' on the bottom of the page at bugs.python.org.

**Comment by berkerpeksag** [comment]
Thank you for your report, but unfortunately this tracker is for issues with www.python.org only.

bugs.p.o infrastructure maintained by two Python core developers and issues like "I didn't get the email" usually require access to server and logs (I only have access to its source repository, for example) so it's easy to forget if they don't have free time to work on support issues. I suggest pinging that issue with your registration information (user name and email address) then I can ping them (or find someone who has coordinator privileges on the tracker to make your account active) on IRC.
