### ISSUE TITLE
Remove Page.content_type when we move PEPs to RtD

### ISSUE THREAD

**Issue by berkerpeksag** [python/pythondotorg#1105]
I noticed this while working on #1102. `Page.content_type` was added in #520. However, we could use `Page.content.markup_type` for the same purpose.

```py
>>> rss = Page.objects.get(path='dev/peps/peps.rss')
>>> rss.content_type
'application/rss+xml'
>>> rss.content.markup_type
'restructuredtext'
```

* [ ] While doing this, we should also add a comment saying `PageView.content_type` is a public attribute of [`TemplateResponseMixin.content_type`](https://docs.djangoproject.com/en/1.7/ref/class-based-views/mixins-simple/#django.views.generic.base.TemplateResponseMixin.content_type) which is a base class of [`DetailView`](https://docs.djangoproject.com/en/1.7/ref/class-based-views/flattened-index/#detailview).
* [ ] And add a note that says `templates/pages/raw.html` is used to create `/dev/peps/peps.rss`.

**Comment by hugovk** [comment]
Will be fixed by https://github.com/python/pythondotorg/pull/2552.
