### ISSUE TITLE
Travis CI Logo - PSF Sponsor

### ISSUE THREAD

**Issue by MarkMangoba** [python/pythondotorg#1116]
Hi Berker,

@bwaliszewski reported that we're having an issue with the center alignment of the Travis CI logo.  Can you take a look?  https://www.python.org/psf/

Thanks,
Mark

**Comment by berkerpeksag** [comment]
I think the problem is SVG format. I replaced it with https://travis-ci.com/images/logos/TravisCI-Full-Color.png (taken from https://travis-ci.com/logo)

Also, I think converting the list into a table or docutils field lists would make the rendering more robust on different platforms.

**Comment by MarkMangoba** [comment]
@berkerpeksag thank you sir.  I've also  updated @bwaliszewski for future reference.
