### ISSUE TITLE
Dynamic compression on Fastly edge

### ISSUE THREAD

**Issue by methane** [python/pythondotorg#1118]
Contents of docs.python.org are not compressed.

Instead of using gzip (or gzip_static) module of nginx, Fastly provides nice option.
https://docs.fastly.com/guides/basic-configuration/enabling-automatic-gzipping

How about enabling it?

**Comment by berkerpeksag** [comment]
This tracker is for issues with www.python.org only. You should report this to either infrastructure@p.o or https://github.com/python/psf-infra-meta.
