### ISSUE TITLE
Lorem Ipsum in Navigation

### ISSUE THREAD

**Issue by tomvon** [python/pythondotorg#112]
![screen shot 2014-02-20 at 9 04 00 am](https://f.cloud.github.com/assets/350323/2218895/e7c45c18-9a37-11e3-9dbe-b5cef10060d9.png)

Lorem Ipsum text when hovering over Events in the navigation.

**Comment by fcurella** [comment]
dupe of #55

**Comment by fcurella** [comment]
closed in 5fffcc988f43fdfcc113d9e762d570570070569a
