### ISSUE TITLE
Download Python for Other Platforms needs to include iOS

### ISSUE THREAD

**Issue by cclauss** [python/pythondotorg#1126]
https://www.python.org/download/other/ needs to have Pythonista for iOS http://omz-software.com/pythonista/index.html

**Comment by berkerpeksag** [comment]
Thank you for the report. I'm not sure https://www.python.org/download/other/ is the correct place to add Pythonista. All of the listed projects there are actually port of the CPython interpreter but Pythonista looks like a toolkit (it has an IDE, UI editor, 2D graphics support etc.) that comes with a Python interpreter. There is no information about internals of the project so I don't know whether it's a port of CPython or not.

**Comment by cclauss** [comment]
Check the links on that site.  Many of them go nowhere or to Python 2.4 implementations on OSes that no longer exits.

Pythonista is a port of both CPython 2.7.13 and CPython 3.5.  It is modern, well maintained, has a great user forum on an OS that is current and has massive adoption.

CPython ships with idle and with tkinter so clearly having an execution ui and an ability to build end user ui is not a reason to keep Pythonista out of the list of other CPython implementations.

**Comment by berkerpeksag** [comment]
> Check the links on that site. Many of them go nowhere or to Python 2.4 implementations on OSes that no longer exits.

Yeah, I'm well aware of that: https://github.com/python/pythondotorg/issues/96#issuecomment-317228899

**Comment by berkerpeksag** [comment]
Done: https://www.python.org/download/other/
