### ISSUE TITLE
Meta tags aren't updated with page title

### ISSUE THREAD

**Issue by ericholscher** [python/pythondotorg#1128]
Currently all links to python.org on Twitter don't include the page title:

Example: https://twitter.com/ThePSF/status/897171008649658368

This is because the meta title never gets updated: https://github.com/python/pythondotorg/blob/master/templates/base.html#L62

The page title is properly updated: https://github.com/python/pythondotorg/blob/master/templates/psf/default.html#L6 -- but the meta title is still wrong.

**Comment by berkerpeksag** [comment]
Thank you for the report. I've added all missing tags to `pages/default.html` and `psf/default.html`.

**Comment by ericholscher** [comment]
Thanks!
