### ISSUE TITLE
Update https://www.psfmember.org/

### ISSUE THREAD

**Issue by bwaliszewski** [python/pythondotorg#1129]
New copy:
[HEADLINE] Become a Supporting Member of the Python Software Foundation! 

Donate to the PSF to further the development and adoption of Python. Your donation helps support sprints, meet ups, and community events. Support Python documentation, fiscal sponsorships, contributions, and community projects. Financial donations help support the critical tools you use every day. Be public about giving to help raise awareness and spread the word that anyone can contribute to open source software. 

Your donation of $100 USD or more makes you a PSF Supporting Member for 12 months.

The PSF produces and underwrites the PyCon US Conference, the largest annual gathering for the community using and developing the open-source Python programming language. 

By joining the PSF, you show your support for our mission and help sustain a vibrant community. Membership also shows your support for Open Source and provides you the opportunity to give back to the community. We rely on memberships, donations, and corporate sponsorships to support sprints, meetups, and community events, and to help support Python documentation, fiscal sponsorships, contributions, and community projects such as:

	•	Python Core Mentorship
	•	Python Developer’s Guide
	•	Issue Tracker
	•	PyPI - the Python Package Index

We would love to have you join us.

Login/Register to become a Supporting Member.

**Comment by MarkMangoba** [comment]
Completed.  @bwaliszewski moving forward for psfmember.org please report issues here:  https://github.com/python/psfmemberdotorg/issues.
