### ISSUE TITLE
no embedded console on FF

### ISSUE THREAD

**Issue by CarlFK** [python/pythondotorg#113]
On Chrome I see the [>] button, 
but not on 
FireFox v27 on Ubuntu Saucy

**Comment by peterlandry** [comment]
Can you check again? I'm seeing it on 25 and 26 (will check 27 soon), but there have been a lot of fixes over the last day so it might have been resolved already.

**Comment by CarlFK** [comment]
Looks good - now I get

Starting encrypted connection to consoles-8.pythonanywhere.com on port 443

Python 3.3.2+ (default, Oct  9 2013, 14:50:09)

Very cool.

On Fri, Feb 21, 2014 at 11:39 AM, Peter Landry notifications@github.comwrote:

> Can you check again? I'm seeing it on 25 and 26 (will check 27 soon), but
> there have been a lot of fixes over the last day so it might have been
> resolved already.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/python/pythondotorg/issues/113#issuecomment-35753789
> .

## 

Carl K

**Comment by peterlandry** [comment]
Great! Closing this out, thanks for checking.
