### ISSUE TITLE
Donation Drive Widget

### ISSUE THREAD

**Issue by bwaliszewski** [python/pythondotorg#1133]
I would like to add a widget (2) like this on our donations page: http://www.coolfundraisingideas.net/thermometer/. I'd like to track the donation $ and membership numbers for a 30 day period during our upcoming donation drive.

Donation page: https://www.python.org/psf/donations/

I can add the copy once the thermometers are in place.

===========================

[HEADLINE] 
Donate to the PSF to further the development and adoption of Python 

Help the PSF raise money to support sprints, meet ups, and community events. Support Python documentation, fiscal sponsorships, contributions, and community projects. Financial donations help support the critical tools you use every day. Be public about giving to help raise awareness and spread the word that anyone can contribute to open source software. 

Help us reach our goal  of $5,000 ($167/day) and 3,000 (100/day) new members in 30 days! If you’ve never donated to the PSF or you’ve let your membership lapse, here is your chance to make a difference. 

Become a PSF Supporting Member for 12 months for $99, and be eligible for voting privileges. As a thank you, get this cool badge [upload image], your name listed here [http://legacy.python.org/psf/donations/], and our eternal gratitude :-).

Donating is easy - pay via credit card, PayPal, or check here [https://www.python.org/psf/donations/] Donating is easy - pay via credit card, PayPal, or check here. No amount is too small (or too large :-)). If you’re not in a position to make a financial contribution, that’s ok. You can sign up as a basic member [https://www.python.org/psf/donations/] to show your support for Python.

**Comment by levlaz** [comment]
Is this still needed? Happy to help if so.

**Comment by bwaliszewski** [comment]
Hi,

Thanks for asking. The donation drive ended on Oct. 16.
