### ISSUE TITLE
Please update Python Download Other - Solaris

### ISSUE THREAD

**Issue by unixpackages** [python/pythondotorg#1137]
Please can you update the sunfreeware link to UNIX Packages. http://www.unixpackages.com

Sunfreeware no longer provides packages for Solaris, it been replaced by our new subscription service at http://www.unixpackages.com. Its the same folks just a new name/service.

Thanks Colin & Steve.

**Comment by berkerpeksag** [comment]
Thank you for the report. I've now updated https://www.python.org/download/other/.
