### ISSUE TITLE
black on black text

### ISSUE THREAD

**Issue by CarlFK** [python/pythondotorg#114]
In Chrome, click the [>_] console button:

content="clickberry-extension-here"
"Sorry, you must have cookies enabled to use this site."

Text is black, background is very dark grey, text is pretty much unreadable.

**Comment by xen** [comment]
Also it is not working if 3rd parties cookies are disabled. 

Screenshot:
![screen shot 2014-02-20 at 5 57 13 pm](https://f.cloud.github.com/assets/31260/2219980/370e3edc-9a48-11e3-9d9f-6af6aca89a48.png)

**Comment by berkerpeksag** [comment]
Thank you for the report. Two things:

* Online console hosted by PythonAnywhere. @gpjt is there a way to customize CSS?
* We could inject some CSS code by using JavaScript, but I prefer not to add a hack for a rather rare problem

Closing this as 'wontfix". We can reopen it if there's a way to customize CSS on PythonAnywhere.

**Comment by gpjt** [comment]
Sorry for the slow reply!  I think this might date back to an older version of the site; we started proxying a bunch of stuff through `console.python.org` in order to avoid a number of cross-site cookie issues.   If there's a way to repro now, please let me know.
