### ISSUE TITLE
Lots of 404s on docs archives

### ISSUE THREAD

**Issue by n8henrie** [python/pythondotorg#1140]
Noticed while trying to download an offline copy of 3.6.2 HTML docs at <https://docs.python.org/3/archives/python-3.6.2-docs-html.zip>

```shell_session
$ curl -s https://docs.python.org/3/download.html | grep -o '"archives/.*"' | xargs -I{} bash -c 'echo; url="https://docs.python.org/3/{}"; echo "${url}"; c
url -s -I "${url}" | head -n 1'

https://docs.python.org/3/archives/python-3.6.2-docs-pdf-letter.zip
HTTP/1.1 404 Not Found

https://docs.python.org/3/archives/python-3.6.2-docs-pdf-letter.tar.bz2
HTTP/1.1 200 OK

https://docs.python.org/3/archives/python-3.6.2-docs-pdf-a4.zip
HTTP/1.1 404 Not Found

https://docs.python.org/3/archives/python-3.6.2-docs-pdf-a4.tar.bz2
HTTP/1.1 404 Not Found

https://docs.python.org/3/archives/python-3.6.2-docs-html.zip
HTTP/1.1 404 Not Found

https://docs.python.org/3/archives/python-3.6.2-docs-html.tar.bz2
HTTP/1.1 404 Not Found

https://docs.python.org/3/archives/python-3.6.2-docs-text.zip
HTTP/1.1 404 Not Found

https://docs.python.org/3/archives/python-3.6.2-docs-text.tar.bz2
HTTP/1.1 404 Not Found

https://docs.python.org/3/archives/python-3.6.2-docs.epub
HTTP/1.1 404 Not Found
```

**Comment by berkerpeksag** [comment]
Thank you for the report. Issues with docs.python.org are out of scope for this tracker. These files are uploaded by Python release managers so it should be reported to https://bugs.python.org/.

**Comment by n8henrie** [comment]
Gotcha, I was following [`Submit Website Bug`](https://github.com/python/pythondotorg/issuesz) from the footer of <https://www.python.org/about/help/>. Will submit there.

**Comment by ned-deily** [comment]
After looking into this a bit, the failing URLs are ones associated with the daily docs build job on docs, not those uploaded by the releases managers for a release.  As best I can tell, that part of the docs build has been broken for some time, probably because the docs build was updated to use newer TexLive features, newer than the 2013.20140215-1 version in Ubuntu 14.04.5 LTS on the docs server. I'm not sure what the best approach is.  I discussed this with @benjaminp last week and we thought maybe just trying to find and install a backport of a more current TexLive would be easiest.

**Comment by berkerpeksag** [comment]
@ned-deily why did you reopen it? This issue doesn't have anything to do with www.python.org. It should be discussed either in python/psf-salt or python/docsbuild-scripts.

**Comment by ned-deily** [comment]
@berkerpeksag You're right, psf-salt would be a better place to track this.  I've opened https://github.com/python/psf-salt/issues/118.

**Comment by n8henrie** [comment]
For future readers (since several similar issues have been created since this one):

Active issue is [here](https://github.com/python/psf-salt/issues/118).

As noted [here](https://bugs.python.org/msg301978), the release version is still available for download:

- Not working: https://docs.python.org/3/archives/python-3.6.2-docs-html.zip
- Working: https://docs.python.org/ftp/python/doc/3.6.2/python-3.6.2-docs-html.zip

**Comment by ned-deily** [comment]
And for further future reference, the problem was resolved by some needed updates to `Doc/conf.py`; see https://bugs.python.org/issue31423.
