### ISSUE TITLE
Changes to Supporting Member page

### ISSUE THREAD

**Issue by bwaliszewski** [python/pythondotorg#1141]
Please change the dollar amount to $99 instead of $100 here: https://www.psfmember.org/. 

Once a new member has created an account, they log back in to become a supporting member. The title of that page is showing  Python Software Foundation Associate Member". Please change that to "Supporting Member". 

Below that, change: "Please join as an Associate Member!" to "Please join as a Supporting Member!"

Under "Membership", change to "Supporting"

Thanks!

**Comment by MarkMangoba** [comment]
@bwaliszewski i've updated the pages accordingly.
