### ISSUE TITLE
Documentation by Version: wrong link for 3.3.6

### ISSUE THREAD

**Issue by volans-** [python/pythondotorg#1144]
In the `Python Documentation by Version` page ( https://www.python.org/doc/versions/ ) the link to the `3.3.6` documentation is erroneously pointing to the `3.3.5` one: `http://docs.python.org/release/3.3.5/` instead of `http://docs.python.org/release/3.3.6/`.

On a side note, the release date is also off by one day (`11 October 2014`) compared to the one in the documentation homepage ( https://docs.python.org/release/3.3.6/ ): `Oct 12, 2014`.

**Comment by berkerpeksag** [comment]
Good catch and thank you for spending time to report it! I've now fixed both issues.

**Comment by volans-** [comment]
@berkerpeksag thank you for the real-time fix!
