### ISSUE TITLE
Broken link on Python 2.3 MRO page

### ISSUE THREAD

**Issue by paulromano** [python/pythondotorg#1145]
At the end of the page on the [Python 2.3 Method Resolution Order](https://www.python.org/download/releases/2.3/mro/), there's a link to the original paper that talks about the C3 algorithm, but it is broken. It might be better to change the link to use a [DOI](https://doi.org/10.1145/236337.236343) (unfortunately paywalled).

**Comment by berkerpeksag** [comment]
Thank you for the report. We could probably use the cached version of that link but I think it's safer to use the paywalled link. I've updated the document.
