### ISSUE TITLE
Proposal Guidelines button doesn't go anywhere 

### ISSUE THREAD

**Issue by CarlFK** [python/pythondotorg#115]
http://www.python.org/psf-landing/

I click, the page shifts a bit, I see no Proposal Guidelines.

<div class="medium-widget grants-widget">
                        <h2 class="widget-title">PSF Grants Program</h2>
<p>The Python Software Foundation welcomes grant proposals for projects related to the development of Python, Python-related technology, and educational resources.</p>
<p><a class="button" href="#">Proposal Guidelines</a></p>
<p><a class="button" href="#">Grant FAQs &amp; Samples</a></p>

                    </div>

**Comment by CarlFK** [comment]
Same with More and Enter at:

PSF News
More

PSF Wiki
Enter

**Comment by malemburg** [comment]
I fixed the grants box.

**Comment by malemburg** [comment]
I also fixed the links in the psf-news box to point to the PSF blog and the PSF wiki.

**Comment by malemburg** [comment]
I guess this ticket can be closed now.

Someone else will have to do this, since I don't have the right permissions for this.
