### ISSUE TITLE
glitch in adjusting calendar 

### ISSUE THREAD

**Issue by AdarshParakh** [python/pythondotorg#1155]
`import calendar 
print(calendar.calendar(1998,2,1,10))`
![correct](https://user-images.githubusercontent.com/22986248/30819639-0082baae-a23d-11e7-97a7-4baff077b1e6.png)

Error Output: 
Input Code:
 ``import calendar 
print(calendar.calendar(1998,5,1,10))`
`
![error](https://user-images.githubusercontent.com/22986248/30819720-4f661cf6-a23d-11e7-9c70-7ca76d725cc1.png)

When spaces for each date is more than 4 the output is unecpected as in the screenshot above

**Comment by berkerpeksag** [comment]
This tracker is for issues with www.python.org only. Please report your problem to https://bugs.python.org.
