### ISSUE TITLE
Update links to the devguide to point to https://devguide.python.org/

### ISSUE THREAD

**Issue by brettcannon** [python/pythondotorg#1157]
I can find at least the "Developer's Guide" link under the "Documentation" drop-down as well as the link at https://www.python.org/dev/.

I tried to do a PR myself but I couldn't find these actual references, only:
https://github.com/python/pythondotorg/blob/a4eacfc8d814a66429a3e0cb0e6a6c6b5f844167/fixtures/boxes.json#L152

**Comment by berkerpeksag** [comment]
All of them are stored in the database. I've updated all instances you gave, thanks!

(I can give you access to Django Admin if you have a python.org account.)

**Comment by brettcannon** [comment]
@berkerpeksag I'm happy to have the access to fix anything I happen to come by, but I don't think I have a "python.org account" like you're asking about.

**Comment by berkerpeksag** [comment]
@brettcannon could you create a new one at https://www.python.org/accounts/signup/ ?

**Comment by brettcannon** [comment]
@berkerpeksag done: https://www.python.org/users/brettcannon/

**Comment by berkerpeksag** [comment]
You can now login to the admin interface at https://www.python.org/admin/

**Comment by brettcannon** [comment]
@berkerpeksag thanks!
