### ISSUE TITLE
Use parentheses for awesome code view

### ISSUE THREAD

**Issue by Mizanurrahman2010** [python/pythondotorg#1158]
Currently i am suggesting you as a developer. 
Python code are not looking good but the other is awesome, really.
For this at least i suggest to separate the code as block by defining the##  parentheses  for the function and loop declaration. That will add another edge for the python.
I suggest you to think for a few minutes about it . 

I think i will add python another edge.

Thanks

**Comment by berkerpeksag** [comment]
Thank you for the report, but could you please give us the link of the Python code you want to improve? Are you talking about the examples at https://www.python.org/ ?

**Comment by berkerpeksag** [comment]
I'm closing this for now. We can always reopen it if you could give us more information about the issue you've reported. Thank you!
