### ISSUE TITLE
broken link: irc faq

### ISSUE THREAD

**Issue by CarlFK** [python/pythondotorg#116]
http://www.python.org/community/irc/

"You should also read the FAQ for the #python channel."

click... 404

carl@twist:~/temp$ curl --head --location http://www.purl.org/wiki/python/PythonFaq
HTTP/1.1 302 Moved Temporarily
Date: Thu, 20 Feb 2014 15:03:07 GMT
Server: 1060 NetKernel v3.3 - Powered by Jetty
Location: http://twistedmatrix.com/users/jh.twistd/python/moin.cgi/PythonFaq
Content-Type: text/html; charset=iso-8859-1
X-Purl: 2.0; http://localhost:8080
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Content-Length: 299

HTTP/1.1 404 Not Found
Date: Thu, 20 Feb 2014 15:03:07 GMT
Content-Length: 167
Content-Type: text/html; charset=utf-8
Server: TwistedWeb/13.2.0

**Comment by akuchling** [comment]
Fixed; thanks!  I linked to pound-python.org instead.
