### ISSUE TITLE
web site login fails

### ISSUE THREAD

**Issue by nlc-gene** [python/pythondotorg#1160]
When I attempt to login to the website at http://bugs.python.org i get:
Invalid login

When I attempt to login though the link emailed to me upon registration https://bugs.python.org/?@action=confrego&otk=cGxI4GE8Wytyxd3k8ELzyRPDC2CVRPVB I get:
Invalid URL scheme in homepage URL

**Comment by berkerpeksag** [comment]
Thank you for your report. Note that issues with bugs.python.org needs to be reported at http://psf.upfronthosting.co.za/roundup/meta/ This tracker is issues with www.python.org only. We've recently upgraded our Roundup version so I think there might be a regression caused by that.
