### ISSUE TITLE
Link back from the event page to the google calendar event

### ISSUE THREAD

**Issue by mariocj89** [python/pythondotorg#1169]
At the moment the event as displayed on the events page of python.org cannot be exported nor the like. As all events are being actually imported from the events calendar we can add a link from that page back to it.

This will allow people to export/copy events to their calendars.

Basically, a link from [sample event in python.org](https://www.python.org/events/python-events/554/) to the [calendar  event](https://calendar.google.com/calendar/render?eid=Nm1jc2M3ODlna3Q1dXI0YXQ3bzAzY2hnZTMgajdnb3YxY21ucXI5dHZnMTRrNjIxajd0NWNAZw&ctz=Europe/London&sf=true&output=xml#eventpage_6)

Related issue #1162

**Comment by berkerpeksag** [comment]
This looks like a duplicate of #158.

**Comment by mariocj89** [comment]
It does indeed
