### ISSUE TITLE
Python Miro Community - no longer exists 

### ISSUE THREAD

**Issue by CarlFK** [python/pythondotorg#117]
http://www.python.org/doc/av
"""
Python Miro Community (video)
A collection of Python video resources, including presentations from PyCon and user groups, put together by Miro.
"""
404

That whole item should be removed. Python Miro... was replaced with pyvideo.

**Comment by akuchling** [comment]
The AV page is outdated in general: many of the podcasts have stopped producing episodes, and some no longer own their domains.  I've removed the links from /doc/ to /doc/av/, /doc/av/5minutes, and /doc/slideshows/ -- we should just remove those 3 pages.

**Comment by malemburg** [comment]
FYI: I've readded the A/V pages.

Andrew: If page content is outdated, please open a ticket to get this fixed. Simply removing content is not such a good idea, since the material may well contain other valid material.

Thanks.

**Comment by akuchling** [comment]
Here's my rationale for dropping them:

1) we are bad at keeping such content up to date.  Sure, we're having a burst of activity _right now_ to update links, but in 2 or 3 years the page will be outdated again.

2) if a person wonders "are there any Python-related podcasts?", are they more likely to come to python.org and browse through our pages, or will they type "python podcast" or "python video" into Google?  I think people will search for things, so we don't need to manually construct lists of resources; that was useful in the 1990s, but not any more.

I suggesting cutting down www.python.org to content we will actually maintain (Python releases; PSF records).

**Comment by malemburg** [comment]
On 24.02.2014 16:10, akuchling wrote:

> Here's my rationale for dropping them:
> 
> 1) we are bad at keeping such content up to date.  Sure, we're having a burst of activity _right now_ to update links, but in 2 or 3 years the page will be outdated again.
> 
> 2) if a person wonders "are there any Python-related podcasts?", are they more likely to come to python.org and browse through our pages, or will they type "python podcast" or "python video" into Google?  I think people will search for things, so we don't need to manually construct lists of resources; that was useful in the 1990s, but not any more.
> 
> I suggesting cutting down www.python.org to content we will actually maintain (Python releases; PSF records).

I think the situation with the new site will be different. It's a lot
easier getting people signed up to help and so we could have champions for
e.g. the A/V page and have them maintain it.

Please also note that by having such lists of resources, we're making it
easier for people to learn about Python. They don't have to do Google
searches and try to find the good hits out of the thousands they are
getting back.

The aim of the python.org relaunch was to address not only developers,
but also people with different backgrounds. This will require having
a different approach to how we present information. Ideally, Google
should bring back the A/V page for people looking for resources and
someone new to the language will then obviously trust our list of
resources more than the list generated by Google.

## 

Marc-Andre Lemburg

**Comment by CarlFK** [comment]
Python Miro Community - is still on
http://www.python.org/doc/av/

Looks like I can't re-open this.

**Comment by benjaminp** [comment]
I zapped it.
