### ISSUE TITLE
Add a --flush option to create_initial_data command

### ISSUE THREAD

**Issue by berkerpeksag** [python/pythondotorg#1175]
`./manage.py create_initial_data` currently prints the following message:

https://github.com/python/pythondotorg/blob/c3fc1f47405e93d97136757603ff77a9bf778bdd/cms/management/commands/create_initial_data.py#L29-L33

It would be great if we could add a `--flush` to delete existing records in the database.

**Comment by lamar-frankie** [comment]
I'd like to claim this issue. Is there a contributor guide somewhere with instructions?

**Comment by berkerpeksag** [comment]
@lamar-frankie great! Installation guide is at https://pythondotorg.readthedocs.io/install.html and a short contribution guide is at https://pythondotorg.readthedocs.io/contributing.html#code Let me know if you have any specific questions.

**Comment by fdroessler** [comment]
Sorry @lamar-frankie I had been working on a related issue and just continued before seeing your comment here....
