### ISSUE TITLE
Browse packages: no categories shown

### ISSUE THREAD

**Issue by amblina** [python/pythondotorg#1181]
Website says: 

> Please select a category from below.

But there are no categories (as far as I can see) to select from.

https://pypi.python.org/pypi?%3Aaction=browse 

![image](https://user-images.githubusercontent.com/999897/32342776-62794b2c-bff9-11e7-8751-d4e34cb14c06.png)

**Comment by berkerpeksag** [comment]
Thank you for your report. This tracker is for issues with www.python.org. The correct place to report issues with legacy PyPı is https://github.com/pypa/pypi-legacy/issues That said, I can see all categories right now. Perhaps it was a transient error.
