### ISSUE TITLE
PSF membership signup should be more visible

### ISSUE THREAD

**Issue by malemburg** [python/pythondotorg#1184]
I just received an email asking how to become a PSF member. Trying to find a page on the python.org website explaining the process, all I could find is this page:

https://www.python.org/psf/membership/

with a link in the "What membership classes are there?" section to the membership edit page. However, if you're not signed in, you don't see anything and there is no description on how or why to create an account on python.org.

It would be good to have a page clearly explaining the process and also add a menu entry pointing to this.

OTOH, perhaps we should leave things hidden... it's obvious that quite a people do figure out how to do this even without such instructions... the PSF currently has 7598 members signed up.

**Comment by AraHaan** [comment]
are members who know only python and little C Allowed to join too? age limits?

I did not know that joining the PSF has a form itself too until now.

I wonder if an bugs.python.org account counts on https://www.python.org/accounts/login/

**Comment by bwaliszewski** [comment]
Hi AraHaan,

Anyone is welcome to be a member and join the Python community :-). You'll need to create a python.org account - https://www.python.org/accounts/signup/, login, then join as a basic (free) or supporting member ($99/year).

Your bugs.python.org account is separate from a python.org account.

Betsy

**Comment by AraHaan** [comment]
@bwaliszewski would basic members be invited to the python github org? Or is that for other types of members.

**Comment by berkerpeksag** [comment]
No, they won't. The PSF membership program doesn't have anything to do with the Python core development team.

**Comment by AraHaan** [comment]
Oh

**Comment by MarkMangoba** [comment]
@AraHaan you can review:  https://devguide.python.org/coredev/
