### ISSUE TITLE
Remove banners for Jetbrains survey

### ISSUE THREAD

**Issue by pfctdayelise** [python/pythondotorg#1185]
It seems to not be closed now.

Maybe just reversing a6272bf11689173f8f115a85146340b5e9df4506 is enough :)

**Comment by berkerpeksag** [comment]
@pfctdayelise good catch, thank you for your report.

@MarkMangoba just to be sure, can we now remove the banners?

**Comment by MarkMangoba** [comment]
@berkerpeksag this is fine to do, thank you @pfctdayelise for the report!
