### ISSUE TITLE
Use Python for section shows bad/out of date examples

### ISSUE THREAD

**Issue by alex** [python/pythondotorg#119]
It's unreasonable for the "Web programming" examples to be "CGI, Zope, Django, TurboGears, XML"

**Comment by akuchling** [comment]
Assuming you meant http://www.python.org/about/apps/ , I rewrote that page but it must have gotten overwritten by the last conversion before launch.

My rewritten text is below:

# Application Domains

Python is used in many application domains.  Here's
a sampling.
- The `Python Package Index <http://pypi.python.org/pypi>`_ lists
  thousands of third party modules for Python.

## Web and Internet Development

Python offers many choices for `web development <http://wiki.python.org/moin/WebProgramming>`_:
- Frameworks such as `Django <http://www.djangoproject.com/>`_, `Pyramid <http://www.pylonsproject.org/>`__, and `TurboGears <http://www.turbogears.org/>`_.
- Micro-frameworks such as `Flask <http://flask.pocoo.org/>`__ and `Bottle <http://bottlepy.org/>`__.
- Advanced content management systems such as `Plone <http://www.plone.org/>`_ and `django CMS <https://www.django-cms.org/>`__.

Python's standard library supports many Internet protocols:
- `HTML and XML <http://docs.python.org/library/markup>`_
- `JSON <http://docs.python.org/library/json.html>`__
- `E-mail processing <http://docs.python.org/library/email>`_.
- Support for `FTP <http://docs.python.org/library/ftplib.html>`**,
  `IMAP <http://docs.python.org/2/library/imaplib.html>`**, and
  other `Internet protocols <http://docs.python.org/library/internet>`_.
- Easy-to-use `socket interface <http://docs.python.org/howto/sockets.html>`__.

And the Package Index has yet more libraries:
- `Requests <https://pypi.python.org/pypi/requests/>`__, a powerful
  HTTP client library.
- `BeautifulSoup <http://www.crummy.com/software/BeautifulSoup/>`__,
  an HTML parser that can handle all sorts of oddball HTML.
- `Feedparser <https://pypi.python.org/pypi/feedparser>`__ for parsing
  RSS/Atom feeds.
- `Paramiko <https://pypi.python.org/pypi/paramiko/>`__, implementing
  the SSH2 protocol.
- `Twisted Python <http://twistedmatrix.com/>`__, a framework for
  asynchronous network programming.

## Scientific and Numeric

Python is widely used in `scientific and numeric
<http://wiki.python.org/moin/NumericAndScientific>`__ computing:
- `SciPy <http://scipy.org/>`_ is a collection of packages for mathematics,
  science, and engineering.
- `Pandas <http://pandas.pydata.org/>`__ is a data analysis and
  modeling library.
- `IPython <http://ipython.org/>`__ is a powerful interactive shell that
  features easy editing and recording of a work session, and
  supports visualizations and parallel computing.
- The `Software Carpentry Course <http://software-carpentry.org>`__ teaches
  basic skills for scientific computing, running bootcamps and providing
  open-access teaching materials.

## Education

Python is a superb language for teaching programming, both at the introductory
level and in more advanced courses.
- Books such as `How to Think Like a Computer Scientist <http://www.openbookproject.net/thinkcs/python/english2e/>`**,
  `Python Programming: An Introduction to Computer Science <http://mcsp.wartburg.edu/zelle/python/>`**, and
  `Practical Programming <http://pragprog.com/book/gwpy2/practical-programming>`__.
- The `Education Special Interest Group </community/sigs/current/edu-sig>`__
  is a good place to discuss teaching issues.

## Desktop GUIs

The `Tk <http://wiki.python.org/moin/TkInter>`_ GUI library
is included with most binary distributions of Python.

Some toolkits that are usable on several platforms are available
separately:
- `wxWidgets <http://www.wxpython.org/>`_
- `Kivy <http://kivy.org/>`__, for writing multitouch applications.
- Qt via `pyqt <http://www.riverbankcomputing.co.uk/software/pyqt/intro>`_ or `pyside <http://www.pyside.org/>`_

Platform-specific toolkits are also available:
- `GTK+ <http://www.pygtk.org/>`_
- Microsoft Foundation Classes through the `win32 extensions <http://sourceforge.net/projects/pywin32/>`_

## Software Development

Python is often used as a support language for software developers,
for build control and management, testing, and in many other ways.
- `SCons <http://www.scons.org/>`__ for build control.
- `Buildbot <http://buildbot.sourceforge.net/>`__ and `Apache Gump <http://gump.apache.org/>`__ for automated continuous compilation and testing.
- `Roundup <http://roundup.sourceforge.net/>`_ or `Trac <http://www.edgewall.com/trac/>`__ for bug tracking and project management.
- `List of Integrated Development Environments`_.

.. _`List of Integrated Development Environments`: http://wiki.python.org/moin/IntegratedDevelopmentEnvironments

**Comment by alex** [comment]
No, I was referring to the section on the hoem page.

On Thu, Feb 20, 2014 at 7:35 AM, akuchling notifications@github.com wrote:

> Assuming you meant http://www.python.org/about/apps/ , I rewrote that
> page but it must have gotten overwritten by the last conversion before
> launch.
> 
> My rewritten text is below:
> Application Domains
> 
> Python is used in many application domains. Here's
> a sampling.
> - The Python Package Index http://pypi.python.org/pypi_ lists
>   thousands of third party modules for Python.
> 
> Web and Internet Development
> 
> Python offers many choices for web development <
> http://wiki.python.org/moin/WebProgramming>_:
> - Frameworks such as Django http://www.djangoproject.com/_, Pyramid
>   <http://www.pylonsproject.org/ <http://www.pylonsproject.org/>>__, and TurboGears
>   http://www.turbogears.org/_.
> - Micro-frameworks such as Flask http://flask.pocoo.org/__ and Bottle
>   http://bottlepy.org/__.
> - Advanced content management systems such as Plone <
>   http://www.plone.org/>_ and django CMS https://www.django-cms.org/__.
> 
> Python's standard library supports many Internet protocols:
> - HTML and XML http://docs.python.org/library/markup_
> - JSON http://docs.python.org/library/json.html__
> - E-mail processing http://docs.python.org/library/email_.
> - Support for FTP http://docs.python.org/library/ftplib.html_, IMAP
>   <http://docs.python.org/2/library/imaplib.html
>   <http://docs.python.org/2/library/imaplib.html>>_, and other Internet
>   protocols http://docs.python.org/library/internet_.
> - Easy-to-use socket interface <
>   http://docs.python.org/howto/sockets.html>__.
> 
> And the Package Index has yet more libraries:
> - Requests https://pypi.python.org/pypi/requests/__, a powerful HTTP
>   client library.
> - BeautifulSoup http://www.crummy.com/software/BeautifulSoup/__, an
>   HTML parser that can handle all sorts of oddball HTML.
> - Feedparser https://pypi.python.org/pypi/feedparser__ for parsing
>   RSS/Atom feeds.
> - Paramiko https://pypi.python.org/pypi/paramiko/__, implementing
>   the SSH2 protocol.
> - Twisted Python http://twistedmatrix.com/__, a framework for
>   asynchronous network programming.
> 
> Scientific and Numeric
> 
> Python is widely used in scientific and numeric
> http://wiki.python.org/moin/NumericAndScientific__ computing:
> - SciPy http://scipy.org/_ is a collection of packages for
>   mathematics, science, and engineering.
> - Pandas http://pandas.pydata.org/__ is a data analysis and modeling
>   library.
> - IPython http://ipython.org/__ is a powerful interactive shell that
>   features easy editing and recording of a work session, and supports
>   visualizations and parallel computing.
> - The Software Carpentry Course http://software-carpentry.org__
>   teaches basic skills for scientific computing, running bootcamps and
>   providing open-access teaching materials.
> 
> Education
> 
> Python is a superb language for teaching programming, both at the
> introductory
> level and in more advanced courses.
> - Books such as How to Think Like a Computer Scientist <
>   http://www.openbookproject.net/thinkcs/python/english2e/>*, Python
>   Programming: An Introduction to Computer Science
>   <http://mcsp.wartburg.edu/zelle/python/
>   <http://mcsp.wartburg.edu/zelle/python/>>*, and Practical Programming <
>   http://pragprog.com/book/gwpy2/practical-programming>__.
> - The Education Special Interest Group
>   </community/sigs/current/edu-sig>__ is a good place to discuss
>   teaching issues.
> 
> Desktop GUIs
> 
> The Tk http://wiki.python.org/moin/TkInter_ GUI library
> is included with most binary distributions of Python.
> 
> Some toolkits that are usable on several platforms are available
> separately:
> - wxWidgets http://www.wxpython.org/_
> - Kivy http://kivy.org/__, for writing multitouch applications.
> - Qt via pyqt http://www.riverbankcomputing.co.uk/software/pyqt/intro_
>   or pyside http://www.pyside.org/_
> 
> Platform-specific toolkits are also available:
> - GTK+ http://www.pygtk.org/_
> - Microsoft Foundation Classes through the win32 extensions <
>   http://sourceforge.net/projects/pywin32/>_
> 
> Software Development
> 
> Python is often used as a support language for software developers,
> for build control and management, testing, and in many other ways.
> - SCons http://www.scons.org/__ for build control.
> - Buildbot http://buildbot.sourceforge.net/__ and Apache Gump <
>   http://gump.apache.org/>__ for automated continuous compilation and
>   testing.
> - Roundup http://roundup.sourceforge.net/_ or Trac <
>   http://www.edgewall.com/trac/>__ for bug tracking and project
>   management.
> - List of Integrated Development Environments_.
> 
> .. _List of Integrated Development Environments:
> http://wiki.python.org/moin/IntegratedDevelopmentEnvironments
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/python/pythondotorg/issues/119#issuecomment-35633635
> .

## 

"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by xen** [comment]
I think list for http://www.python.org/about/apps/ is great, and can be copied to home page as short version.

**Comment by akuchling** [comment]
I've updated the list shown on the top page to use the same titles and links as /about/apps, but frankly I think we should just drop this box; the home page is already rather long, and it's unlikely we'll keep this content up to date.

(Note for future maintainers: to do this, I edited the Box titled "widget-use-python-for".)
