### ISSUE TITLE
Cursor flickers in slides component

### ISSUE THREAD

**Issue by 102** [python/pythondotorg#1193]
# Client
* Google Chrome, version 62.0.3202.89 (Official Build) (64-bit)
* Ubuntu 16.04

# Steps to reproduce
* visit https://www.python.org/ 
* find a button with the slide number (I was able to reproduce with buttons 2-4 only, see attached screenshot)
* hover the button's border, you'll probably see the flickering

However, I wasn't able to reproduce this behavior somewhere else (I have tried Windows 10 with Chrome and Ubuntu with Firefox), and I'm also not sure that this is actually bug of the python.org instead of chrome

![selection_030](https://user-images.githubusercontent.com/5839225/32716089-e4eaa46a-c87e-11e7-80a7-91e6a3e8f4ad.png)

**Comment by berkerpeksag** [comment]
Thank you for your report. I can reproduce it with Chrome 62.0.3202.94 in OS X but not with Safari 10.1.2 in OS X and Chrome 49.0.2623.112 in Linux.

**Comment by hugovk** [comment]
I could not reproduce on macOS with Chrome 128 or recent Safari or Firefox.

Please let us know if it's reproducible on other operating systems/browsers and we can re-open this.
