### ISSUE TITLE
Use lxml v 4.1.1

### ISSUE THREAD

**Issue by Mariatta** [python/pythondotorg#1194]
The version of `lxml` specified in base-requirements.txt is `lxml==3.4.4`.
Somehow I'm having trouble installing it on my computer (Mac OS Sierra 10.12.6), there are a bunch of errors I don't understand.
When I changed that to `lxml==4.1.1`, everything works.

I wonder if the base-requirements.txt file can be updated so it uses `lxml 4.1.1`?

Thanks.

**Comment by berkerpeksag** [comment]
Yeah, they probably don't provide 3.4.4 binaries for newer Pythons and platforms anymore. I was going to upgrade it in eb8a9a0d0ca23bd8010612b33ead6efe4a9d6e4f but I didn't had enough time to read the lxml changelog. I will do that this week.
