### ISSUE TITLE
Can't receive confirmation email

### ISSUE THREAD

**Issue by hubertokf** [python/pythondotorg#1196]
I registered at https://pypi.python.org but never received the confirmation email.

I've tried to request a password reset and no email again. Then I tried to create another account with another gmail email and everything went fine.

What am I missing?

**Comment by Mariatta** [comment]
Hi, this is not the tracker for pypi.python.org. So I'm closing your ticket.
The bugtracker for PyPI is here: https://github.com/pypa/warehouse, I would try posting your issue there.
Thanks.
