### ISSUE TITLE
Static Assets and CSS need to be rebuilt

### ISSUE THREAD

**Issue by jhogue** [python/pythondotorg#12]
This is a question as much as an assumption. The preview site does not have the new Pythonicon font loading. The CSS is still looking for the old font, IcoMoon, while it has been removed from the repo since the new font should have replaced it. There is an error in the Console about a 404 when looking for IcoMoon.svg. 

It is also possible that the CSS was not committed to the repo, if we are not building it on the server with Compass yet. 

Pythonicon is on the server: http://preview.python.org/static/fonts/
But the CSS seems like it needs to be rebuilt or I can commit the latest. Let me know.

**Comment by fcurella** [comment]
@jhogue I tried to recompile with sass but the generated css aren't any different from the ones checked in in the repo.

I've grepped the `sass` directory for `IcoMoon.svg` with no results. I've looked for `Pythonicon` and found it.

Can you check if the .scss files are correct? I might have messed those up when merging `events`.

**Comment by fcurella** [comment]
@jhogue disregard my previous comment. For some reason my git GUI didn't refresh. I'm committing the recompiled .css
