### ISSUE TITLE
Change one of the email addresses on the donation page

### ISSUE THREAD

**Issue by kbkaiser** [python/pythondotorg#1200]
python.org/psf/donations/

Near bottom:

_**If you have a question about donations, please write to the PSF at (psf@python.org).**_

People are using this email to send PayPal donations and also to direct donor organization (e.g. cybergrants) transactional email.

Please change the email to psf-donations@python.org   

which will direct it to the donations list, where it belongs.

**Comment by MarkMangoba** [comment]
@kbkaiser changed email address as requested.
