### ISSUE TITLE
Amazon Smile website does not work on Donations webpage

### ISSUE THREAD

**Issue by realslimshanky** [python/pythondotorg#1203]
The [Amazon Smile](https://smile.amazon.com/ch/04-3594598/)'s website mentioned under the section 'Other Ways to Give' on [Donations](https://www.python.org/psf/donations/) webpage does not work. Here's the page I was taken to
![image](https://user-images.githubusercontent.com/10004530/33232599-eba52e10-d22e-11e7-9547-05766feaf25a.png)

**Comment by MarkMangoba** [comment]
@realslimshanky thank you for the report!  I've corrected the issue, the link was changed from:  https://smile.amazon.com/ch/04-3594598/ to https://smile.amazon.com/ch/04-3594598
