### ISSUE TITLE
Simple typo-like error in PEP 257 convention explanation

### ISSUE THREAD

**Issue by goodwingibbins** [python/pythondotorg#1204]
I think that the line 

> XXX Mention docstrings of 2.2 properties.

Is potentially not supposed to be there on the public version? In the 'What is a DocString' section.

https://www.python.org/dev/peps/pep-0257/#id15

**Comment by Mariatta** [comment]
Thanks :) Yeah this issue has been brought up and is currently tracked in the PEPs repo: https://github.com/python/peps/issues/484

I'm closing this as a duplicate.
