### ISSUE TITLE
Job board review is broken

### ISSUE THREAD

**Issue by malemburg** [python/pythondotorg#1214]
The job review pages no longer show the usual canned response drop-down and the accept/reject buttons are gone as well.

See e.g. https://www.python.org/jobs/2877/

The pages now only allow to leave a custom written comment.

Could you please restore the previous state, since in the current version, only the overview page has accept/reject buttons left, which makes review harder than ever before.

Thanks.

**Comment by malemburg** [comment]
Screenshot:

![image](https://user-images.githubusercontent.com/6735498/34818612-9ddf4b1e-f6bb-11e7-8e9e-331c168fdf93.png)

**Comment by malemburg** [comment]
Looking at the page template:

https://github.com/python/pythondotorg/blob/master/templates/jobs/job_detail.html

it seems that only "job admins" can see those buttons. What's strange is that I am super user and still cannot. I now added myself to the job admin group, but they buttons don't show either. Perhaps some cache issue. I'll wait a few hours and then try again.

**Comment by berkerpeksag** [comment]
`user_can_edit` can be `True` if a user is a job admin. I fixed that if branch and will cherry-pick it in to the release branch.

**Comment by berkerpeksag** [comment]
Cherry-picked into release: 977ed9b2fa5882e8fa663a21931f5030d82fcaa6

Could you please try again in ~25 minutes?

**Comment by berkerpeksag** [comment]
Here's a screenshot from my development setup:

![screenshot from 2018-01-11 13 02 42](https://user-images.githubusercontent.com/26338/34819777-c64e8e66-f6cf-11e7-99f9-b9f37cefb052.png)

**Comment by berkerpeksag** [comment]
Deployed: https://www.python.org/jobs/2877/

Sorry for the noise!

**Comment by malemburg** [comment]
Thanks for the quick fix, Berker. I'll try again in an hour or so.
