### ISSUE TITLE
c++ call python api PyList_New segmentation fault 

### ISSUE THREAD

**Issue by zallmight** [python/pythondotorg#1215]
(gdb) bt
i get gdb info :
Thread 1 "server" received signal SIGSEGV, Segmentation fault.
0x00007ffff12176a1 in PyType_Ready ()
   from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
(gdb) bt
#0  0x00007ffff12176a1 in PyType_Ready ()
   from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#1  0x00007ffff12e2f98 in PyObject_Hash ()
   from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#2  0x00007ffff1216377 in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#3  0x00007ffff12ac046 in PyDict_DelItem ()
   from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#4  0x00007fffcaa23473 in ?? ()
   from /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so
#5  0x00007ffff125d263 in PyObject_Call ()
   from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#6  0x00007ffff125d6cf in PyObject_CallFunctionObjArgs ()
   from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#7  0x00007ffff1225493 in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#8  0x00007ffff1225deb in _PyObject_GC_Malloc ()
   from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#9  0x00007ffff1225e9d in _PyObject_GC_New ()
   from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#10 0x00007ffff12826dc in PyList_New ()
   from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#11 0x00007ffff6e6cd08 in detect_server (
    images=std::vector of length 15, capacity 15 = {...}, 
    ret=ret@entry=0x7fffffffdb80) at src/ServerHandle.cpp:550

and my code is :
 PyObject* image = PyList_New(resize_width);
            for(int row = 0;row< height;row++)
            {
                PyObject* image_row = PyList_New(width);
                for(int col = 0;col < width;col++)
                {
                    PyObject* image_pixel = PyList_New(3);
                    int b = (int)dimage.at<cv::Vec3b>(row, col)[0];
                    int g = (int)dimage.at<cv::Vec3b>(row, col)[1];
                    int r = (int)dimage.at<cv::Vec3b>(row, col)[2];
                    PyList_SetItem(image_pixel, 0, Py_BuildValue("i", b));
                    PyList_SetItem(image_pixel, 1, Py_BuildValue("i", g));
                    PyList_SetItem(image_pixel, 2, Py_BuildValue("i", r));
                    PyList_SetItem(image_row, col, Py_BuildValue("O", image_pixel));
                    Py_CLEAR(image_pixel);
                }
                PyList_SetItem(image, row, Py_BuildValue("O", image_row));
                if (image_row)
                    Py_DECREF(image_row);
            }

when the program run a while, i get the segmentation fault as above.

the locals var is :
image_pixel = <optimized out>
b = <optimized out>
g = <optimized out>
r = <optimized out>
col = 102
image_row = 0x7fffd206dcb0
row = 3
width = 224
height = 224
i don't know how to solve this bug. i guess my code exists bugs or system settings exists problems.
Thank you very much and forgive my poor English.

**Comment by Mariatta** [comment]
Hi, this tracker is for issues related to python.org website. I can't help with debugging your code.
Perhaps try asking in [python-list](https://mail.python.org/mailman/listinfo/python-list) or [python-tutor](https://mail.python.org/mailman/listinfo/tutor) mailing lists.
