### ISSUE TITLE
Python 3 only for Call To Action download buttons.

### ISSUE THREAD

**Issue by ewdurbin** [python/pythondotorg#1218]
#RE: https://www.python.org/downloads/

I don't think it should be done immediately... but perhaps when https://pythonclock.org read 2 years or less.

<img width="653" alt="screen shot 2018-01-23 at 9 02 40 pm" src="https://user-images.githubusercontent.com/1200832/35310777-2299437c-0081-11e8-9656-bf70a58b2779.png">

The current scenario only breeds confusion and indicates that "choosing" between Python 2 and Python 3 is even a thing anymore.

Perhaps removing the 2.7.x button, and replacing 

> Wondering which version to use? Here’s more about the difference between Python 2 and 3.

with 

> Looking for Python 2.7 releases? <a href="link to 2.7 releases">Click here</a>

**Comment by ncoghlan** [comment]
3.7.0 is scheduled for June, so it would make sense to make the simplification shortly before that: https://www.python.org/dev/peps/pep-0537/#schedule

For example, switch to 3.6 only on the quick download buttons in May (just after 3.7.0rc1 is released), so the change is ready before the 3.7.0 release.

**Comment by mpirnat** [comment]
FWIW, I've created a pull request with my hot take on resolving this.

**Comment by gvanrossum** [comment]
I'd say it's time to do this.
