### ISSUE TITLE
Security issue: http://python.org/ needs to redirect to https://www.python.org/

### ISSUE THREAD

**Issue by malemburg** [python/pythondotorg#122]
Since python.org can now be used to log into to the site, the code base needs to make sure that no python.org (without the www.) cookies are set and that all requests to the bare domain get redirected to www.python.org.

Not doing so could otherwise lead to cookie/session stealing attacks from other python.org sub-sites.

I just checked: logging in via python.org (without www.) sets cookies on the domain python.org, not www.python.org. Doing the login on www.python.org sets the cookies on the domain www.python.org.

Of course, the same redirection should happen for http://python.org/ and https://python.org/.

**Comment by westurner** [comment]
**Django**
https://docs.djangoproject.com/en/dev/ref/settings/#prepend-www

Is there an `IN_PRODUCTION` boolean for `settings`?

https://github.com/python/pythondotorg/blob/master/pydotorg/settings/base.py

**Reverse Proxy**
Not sure where this configuration is?

**Comment by techtonik** [comment]
I would ditch www. access method completely, replacing it with redirect. Who needs www. in 2014? Going with www. alone probably won't solve the problem, because evil. can still set cookie for .python.org and I suspect that this cookie will be transmitted to www.

**Comment by malemburg** [comment]
Ideally, the redirect should go straight to https://www.python.org/ and cookies should have the Secure and HttpOnly flags set (http://en.wikipedia.org/wiki/HTTP_cookie#Secure_and_HttpOnly).

**Comment by techtonik** [comment]
Ideally, there should be no need to maintain lengthy URL www. part.

On Tue, Mar 11, 2014 at 1:28 AM, malemburg notifications@github.com wrote:

> Ideally, the redirect should go straight to https://www.python.org/ and
> cookies should have the Secure and HttpOnly flags set (
> http://en.wikipedia.org/wiki/HTTP_cookie#Secure_and_HttpOnly).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/python/pythondotorg/issues/122#issuecomment-37242821
> .

## 

anatoly t.

**Comment by benjaminp** [comment]
This redirection happens now.

**Comment by malemburg** [comment]
On 14.03.2014 16:05, Benjamin Peterson wrote:

> This redirection happens now.

Great :-) Thanks, Benjamin.

## 

Marc-Andre Lemburg

**Comment by westurner** [comment]
:+1:

Wes Turner

**Comment by LitherCode** [comment]
Http://phyton.org still not redirect to the real site

**Comment by malemburg** [comment]
We have no control over that typo-domain.

**Comment by LitherCode** [comment]
Ops...sorry my fault
