### ISSUE TITLE
my account does not match my name ;-)

### ISSUE THREAD

**Issue by matrixise** [python/pythondotorg#1221]
I don't know where the bug is, but when I see my "account" on python.org, there is the right email and I suppose the right username, but not the right legal/preferred name...

the name is Stefan van der Walt, but I am not this person and it's the first time I see this name.
Did you do a migration?

Have a nice day,

**Comment by berkerpeksag** [comment]
No, we haven't touched anything and your profile doesn't seem to be updated since Aug. 28, 2015, 9:30 p.m. And the following fields were updated:

> Changed first_name and last_name. Added membership "Membership for user: matrixise".

The membership process is manual and there might be an editorial mistake. When did you logged in last time?

**Comment by matrixise** [comment]
On 02/03, Berker Peksag wrote:
>No, we haven't touched anything and your profile doesn't seem to be updated since Aug. 28, 2015, 9:30 p.m. And the following fields were updated:
>
>> Changed first_name and last_name. Added membership "Membership for user: matrixise".
>
>The membership process is manual and there might be an editorial mistake. When did you logged in last time?
really strange, I don't remember and about my info, I never updated it.

Ok, I will change the values, but it's really funny

-- 
Stéphane Wirtel - http://wirtel.be - @matrixise
