### ISSUE TITLE
Broken link to Jython Monthly

### ISSUE THREAD

**Issue by andy152** [python/pythondotorg#1222]
The page below contains a link to "Jython Monthly" that is broken.

https://www.python.org/doc/av/

The link below appears to be the active link for Jython Monthly but that page also contains broken image links.

http://www.jython.org/jythonpodcast/

**Comment by berkerpeksag** [comment]
Thanks! Jython Monthly is listed under the "Inactive Podcast Repositories" section so it's expected to have broken links :) I've just updated the link to http://www.jython.org/jythonpodcast/ Unfortunately, we can't change the links at jython.org and I don't know where to report content issues with their website.

**Comment by andy152** [comment]
Understood and thanks!
