### ISSUE TITLE
spam package

### ISSUE THREAD

**Issue by skidem** [python/pythondotorg#1225]
hello, someon can delete these package? https://pypi.python.org/pypi/clash-royale-hack-new-unlimited-gems-gold-hack-2018 becouse its spam my site :(

**Comment by berkerpeksag** [comment]
Thank you for your report, but this tracker is for issues with www.python.org. It seems like PyPI maintainers are aware of spam and working on to fix it. You can subscribe to https://github.com/pypa/pypi-legacy/issues/774 if you want to follow the process.
