### ISSUE TITLE
Change HTTP links to HTTPS where possible

### ISSUE THREAD

**Issue by l0b0** [python/pythondotorg#1226]
All the HTTP links on https://bugs.python.org/issue?@template=item are highlighted in this screenshot:

![screenshot with HTTP links highlighted](https://user-images.githubusercontent.com/168301/36617492-7c5c6a86-194c-11e8-8dce-ed6930b04dd7.png)

All of the links except "hosting by Upfront Systems" and "powered by Roundup" support and redirect to HTTPS, so they should be changed.

As an aside, some of the links also go to python.org, which redirects to www.python.org.

**Comment by Mariatta** [comment]
Thanks for the report. This is the issue tracker for python.org.
The tracker for bugs.p.o is separate, at: http://psf.upfronthosting.co.za/roundup/meta/
And while those links are `http`, they redirects to `https`.

**Comment by l0b0** [comment]
Is that the correct link to the bugs.p.o tracker? Because [they seem to think they have HTTPS support](http://psf.upfronthosting.co.za/roundup/meta/issue463), but they clearly do not (at least not on that host). First the certificate of https://psf.upfronthosting.co.za is only valid for bugs.python.org, and second changing any psf.upfronthosting.co.za URL to HTTPS results in a 404 error.

**Comment by Mariatta** [comment]
[Python bug tracker](http://psf.upfronthosting.co.za/roundup/meta/) is in https.
[The issue tracker for the bug tracker](http://psf.upfronthosting.co.za/roundup/meta/) is not in https. 😓

**Comment by l0b0** [comment]
~And registration there doesn't work. I've verified that I can receive email on the relevant account, but after about half an hour I still don't have the registration email.~ Is there a bugs.p.o meta meta bug tracker? ;)

---

Actually registration does work, it's just slow.

**Comment by Mariatta** [comment]
Sorry about that. Sadly I don't know much about the meta tracker. Perhaps @MarkMangoba?
