### ISSUE TITLE
Python Dev guide - Broken links ( Error 404 link)

### ISSUE THREAD

**Issue by dheepakg** [python/pythondotorg#1229]
In [Python Developer's Guide](https://www.python.org/dev/) , [Bug Search Browser Plugin (Firefox)](https://www.python.org/dev/searchplugin/)  link returns error 404

**Comment by lamar-frankie** [comment]
This seems like low hanging fruit. I'd like to try and fix it.

**Comment by berkerpeksag** [comment]
Thanks for the report. That plugin no longer can be found on addons.mozilla.org. I've just deleted the link at  https://www.python.org/dev/

@lamar-frankie thank you for wanting to contribute to python.org :) This is a content issue and unfortunately content issues require access to python.org's Django admin panel. #1175 and #1177 are good candidates if you'd like to start contributing to python.org.
