### ISSUE TITLE
sf redirector broken

### ISSUE THREAD

**Issue by loewis** [python/pythondotorg#123]
The old site supported http://www.python.org/sf/<bug number> (and /sf?id=<bug number>), where bug number could either be a SF bug number, or a roundup bug number. The new site now redirects this to http://legacy.python.org/sf/, i.e. dropping the number. Apparently, the redirect for id= is still supported correctly.

I suggest that either
a) the redirect is fixed, or (preferred)
b) the new site continues to support the sf redirector (probably through a django view)

For reference, I'll include the redirector code below:

```
def num():
    try:
        return int(os.environ['PATH_INFO'][1:])
    except (KeyError, ValueError, TypeError):
        try:
            import cgi
            return int(cgi.FieldStorage().getvalue("id"))
        except (ValueError, TypeError):
            return None

def bad_request(msg):
    print "Content-type: text/html"
    print ""
    print "<html><title>Invalid report</title>"
    print "<body>"+msg+"</body></html>"
    raise SystemExit

report = num()
if not report:
    bad_request("You did not provide a report number")

location = "http://bugs.python.org/issue%s" % report
print "Location: "+location+"\n"
```

**Comment by fcurella** [comment]
updated the description for prettyprinting of code

**Comment by gvanrossum** [comment]
FWIW, this is not just a legacy thing. It breaks links to bugs from the hg repo. E.g. this was reported to python-dev:

 Go to any commit link in hg.python.org/cpython, for example
http://hg.python.org/cpython/rev/d11ca14c9a61.

You have this commit message:

Issue #6815: os.path.expandvars() now supports non-ASCII Unicode
environment variables names and values. [#6815]

The [#6815] link is going to http://bugs.python.org/6815. If you
follow that link, it redirects to http://legacy.python.org/sf/ and you
get message: You did not provide a report number. The link should be
http://bugs.python.org/issue6815.

**Comment by benjaminws** [comment]
I've got a fix in for this, it may take some time for you to notice in your browser, but you can test it from the command line if you feel like verifying. See below for examples.

To be honest, I do not feel like 3 redirects is ideal. I'm certain I can send the request straight to bugs.python.org, doing away with the need for the script completely. I'm mimicking the same behavior the script is doing with the webserver already, with the exception of reporting an empty bug number. You can see how that works here: https://github.com/python/psf-chef/blob/master/cookbooks/pydotorg-redesign/templates/default/nginx.conf.erb#L292

Here are some examples so you can make sure it's working for you.
(note that I've changed the 301 to a 302, but that's not propagated yet)

<pre>
$ curl -I "http://bugs.python.org/20695"
HTTP/1.1 302 Found
Date: Thu, 20 Feb 2014 18:27:03 GMT
Server: Apache/2.2.16 (Debian)
Location: http://python.org/sf/20695
Content-Type: text/html; charset=iso-8859-1
$ curl -I "http://python.org/sf/20695"
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Thu, 20 Feb 2014 18:27:20 GMT
Content-Type: text/html
Content-Length: 178
Location: http://legacy.python.org/sf/20695
$ curl -I "http://legacy.python.org/sf/20695"
HTTP/1.1 302 Found
Date: Thu, 20 Feb 2014 18:27:35 GMT
Server: Apache/2.2.22 (Debian)
Location: http://bugs.python.org/issue20695
Vary: Accept-Encoding
Content-Type: text/html; charset=iso-8859-1
</pre>

It also works with the query string params:

<pre>
$ curl -I "http://python.org/sf?id=20695"
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Thu, 20 Feb 2014 18:31:56 GMT
Content-Type: text/html
Content-Length: 178
Location: http://legacy.python.org/sf?id=20695
curl -I "http://legacy.python.org/sf?id=20695"
HTTP/1.1 302 Found
Date: Thu, 20 Feb 2014 18:32:15 GMT
Server: Apache/2.2.22 (Debian)
Location: http://bugs.python.org/issue20695
Vary: Accept-Encoding
Content-Type: text/html; charset=iso-8859-1
</pre>

**Comment by encukou** [comment]
It looks like this is now broken again:

```
$ curl -I "http://bugs.python.org/20695"
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Tue, 04 Jun 2019 09:29:57 GMT
Content-Type: text/html
Content-Length: 178
Connection: keep-alive
Location: https://bugs.python.org/20695

$ curl -I https://bugs.python.org/20695
HTTP/1.1 404 Not Found
Server: nginx
Date: Tue, 04 Jun 2019 09:30:06 GMT
Content-Type: text/html
Connection: keep-alive

$ curl -I "http://python.org/sf/20695"
HTTP/1.1 301 Moved Permanently
Content-length: 0
Location: https://python.org/sf/20695

$ curl -I https://python.org/sf/20695
HTTP/2 301 
date: Tue, 04 Jun 2019 09:30:27 GMT
content-type: text/html
content-length: 178
server: nginx
location: https://www.python.org/sf/20695
strict-transport-security: max-age=315360000; preload
```

Do you want to re-open, or should I file a new issue?

**Comment by berkerpeksag** [comment]
SF redirector is not part of this repository. You'll need to talk to the infra team.
