### ISSUE TITLE
URGENT Can't login - password-reset and registration emails are not arriving from bugs.python.org/

### ISSUE THREAD

**Issue by vitaly-krugl** [python/pythondotorg#1231]
I've been trying both to reset the password of the account I used to use, after not being able to login after a long absence, as well as to create a new account using a different email address than the first. In both cases, I've been trying for a few days, and nothing is arriving in email in response, and I still can't login to bugs.python.org.

I checked Spam and related folders besides my inbox, and not a thing.

**Comment by MarkMangoba** [comment]
@vitaly-krugl this issue tracker is for python.org.  I can help you with your request, can you email me at mmangoba@python.org?

Best regards,
Mark
