### ISSUE TITLE
No Chinese document

### ISSUE THREAD

**Issue by wordhui** [python/pythondotorg#1232]
No Chinese document = No Chinese document = No Chinese document = No Chinese document - Three important things to say ---- Really need Chinese document

**Comment by berkerpeksag** [comment]
First, you're using the wrong place to report this. Second, we don't appreciate this kind of tone. Python is an open source project and that doesn't mean you can tell us what to work on our free time. There is a PEP that explains how to start a translation project if you want to translate the Python documentation to your own language.
