### ISSUE TITLE
Special marking of the download buttons

### ISSUE THREAD

**Issue by kb-1000** [python/pythondotorg#1233]
This is useful for automating the download, e.g. with selenium.

**Comment by pradyunsg** [comment]
Hi @kaeptmblaubaer1000!

You can just use an XPath and use that in selenium. [[1]]

I think there's no need for making changes on python.org for making automated downloads easier.

[1]: https://www.guru99.com/xpath-selenium.html

**Comment by ewdurbin** [comment]
Downloads are browsable and indexed at https://www.python.org/ftp/, so they can be navigated programmatically without any heavyweight HTML parsing.

Please reopen if this doesn't fit your requirements.
