### ISSUE TITLE
Dead link on PSF Contributor Agreement page

### ISSUE THREAD

**Issue by Harmon758** [python/pythondotorg#1236]
The Academic Free License v. 2.1 link at https://www.python.org/psf/contrib/contrib-form/ links to http://www.samurajdata.se/opensource/mirror/licenses/afl-2.1.php, which returns a 404 Not Found page.
According to http://www.samurajdata.se/opensource/mirror/: "The mirror grew stale and was well past the utility. It has therefore been removed."

**Comment by MarkMangoba** [comment]
@Harmon758 thanks for the report.  I'll touch base with @ejodlowska on the updated link for the Academic Free License v. 2.1.

**Comment by MarkMangoba** [comment]
@VanL I discussed with @ejodlowska about this and it looks like there is a couple Academic Free License v. 2.1 links out there, but not sure which we can use or link in this document.  Let me know if you have link that we can replace this 404 link.

**Comment by sth** [comment]
Wouldn't it be best to have a local copy of the license text on python.org to link to? This way you can be sure it doesn't break or change unexpectedly.

**Comment by Harmon758** [comment]
The link now points to https://spdx.org/licenses/AFL-2.1.html.
