### ISSUE TITLE
sys.__interactivehook__ 

### ISSUE THREAD

**Issue by kerwinxu** [python/pythondotorg#1237]
python3.6,anaconda3.6
slove:
file : D:\Anaconda3\Lib\site-packages\pyreadline\lineeditor\history.py
change:
    def read_history_file(self, filename=None): 
        '''Load a readline history file.'''
        if filename is None:
            filename = self.history_filename
        try:
            **rawdata = open(filename, "rb").read()
            result = chardet.detect(rawdata)
            charenc = result['encoding']**
            for line in open(filename, 'r',**encoding=charenc**):
                self.add_history(lineobj.ReadLineTextBuffer(ensure_unicode(line.rstrip())))
        except IOError:
            self.history = []
            self.history_cursor = 0

**Comment by berkerpeksag** [comment]
Thanks for the report, but the correct place to ask questions like this is [python-list](https://mail.python.org/mailman/listinfo/python-list). This tracker is for issues with www.python.org.
