### ISSUE TITLE
wiki page for eric IDE has incorrect home page (possibly malicious?)

### ISSUE THREAD

**Issue by Zakiemon** [python/pythondotorg#1238]
I didn't want to make an account at wiki.python.org just for this as it appears to be something deeper.

I was looking at this page:
https://wiki.python.org/moin/IntegratedDevelopmentEnvironments
and clicked on this link to get information on eric IDE
https://wiki.python.org/moin/eric
on this page it states:

eric's homepage is at <<<.die-offenbachs.de/detlev/eric3.html
<<< = http://www (i changed the url so its not clickable in the event it is malicious)
(also that domain seems to have been just registered?)

which is incorrect, as it is listed in linux mint and via google the eric homepage is
https://eric-ide.python-projects.org/

the eric wiki page has not been updated since 2008, was that the old site for eric? or...

**Comment by berkerpeksag** [comment]
I think the domain name die-offenbachs.de was expired and someone else registered it.

I tried to edit the link but it seems like the page is read-only (I should be an editor so I don't know why I can't edit it -- @malemburg can you take a look at this?)

Closing this for now, I'm going to change the link once I can edit pages on wiki.p.o. Thank you for the report!
