### ISSUE TITLE
Unable to read the folder

### ISSUE THREAD

**Issue by suju814** [python/pythondotorg#1239]
Hi All,
I got a strange experience while reading the folders from python code. 
If we save a folder with blank name how we can ready that folder.
Can you please suggest me on this.
Folder name is blank.

**Comment by berkerpeksag** [comment]
Thanks for the report, but the correct place to ask questions like this is [python-list](https://mail.python.org/mailman/listinfo/python-list). This tracker is for issues with www.python.org.
