### ISSUE TITLE
Packages that are not the latest version are downloaded

### ISSUE THREAD

**Issue by Leaf47** [python/pythondotorg#1240]
If you try to download python 3.6.5 with mac (Safari and Chrome of macOS High Sierra v 10.13.4) "macosx 10.6.pkg" will be downloaded.
I think that the latest version is "macosx 10.9.pkg", so please correct it.

**Comment by ned-deily** [comment]
Thanks for the suggestion.  For the moment, the 10.6 variant of the installers continue to be the default download.   Now that we provide 10.9 variants for all the releases branches in maintenance mode (3.6.x and 2.7.x, recently with 2.7.15), my intention is to make the 10.9 variant the default for all macOS downloads when 3.7.0 is released, currently planned for 2018-06-15.

**Comment by Leaf47** [comment]
Thank you for your reply.
I understood the intention.
