### ISSUE TITLE
Update PyPI URL

### ISSUE THREAD

**Issue by stevepiercy** [python/pythondotorg#1243]
There are many instances of `https://pypi.python.org/` in the code, but I'm not sure what they all do. The new URL is `https://pypi.org/`. Making updates would save a redirect.

Anyway, the one I wanted to update is that which appears in the uppermost navigation bar. I think it's this one based on its context, but I'm not positive.
https://github.com/python/pythondotorg/blob/master/cms/views.py#L6

If someone can verify, I can update that one. I don't know whether others need to be updated.

**Comment by MarkMangoba** [comment]
@stevepiercy thanks for the report!  Can you open up a PR for this?

**Comment by stevepiercy** [comment]
Done! See #1245.
