### ISSUE TITLE
New Style Classes are not yet documented?!?

### ISSUE THREAD

**Issue by cclauss** [python/pythondotorg#1247]
https://www.python.org/doc/newstyle/ says "_Unfortunately, new-style classes have not yet been integrated into Python's standard documentation. Fear not..._"  This seems to be an out-of-date statement.  Could/should it be fixed?

At this stage (Python 2.7) what are the downsides of automatically switching to [New Style Classes](https://docs.python.org/2.7/reference/datamodel.html#newstyle).  On earlier versions of Python it might have been a problem to autoswitch but in Python 2.7, are there still problems in automatically moving to New Style Class?

**Comment by berkerpeksag** [comment]
Thank you for the report. See the warning at the top of the page:

![screenshot from 2018-06-09 14 47 13](https://user-images.githubusercontent.com/26338/41191168-e9b707d6-6bf3-11e8-91ff-b509ddeff318.png)

We keep old documents as-is for historical purposes. I'd be happy to tweak the wording to make it clearer for future users. Closing this one for now, but please don't hesitate to share your suggested wording.
