### ISSUE TITLE
GitHub link under Socialize is wrong

### ISSUE THREAD

**Issue by brettcannon** [python/pythondotorg#125]
It should point to https://github.com/python/cpython which is about as official as you're going to get for a git repository

**Comment by fcurella** [comment]
labeled as 'frontend' because the URL is hardcoded in `templates/base.html`

**Comment by peterlandry** [comment]
Seems like it should point to https://github.com/python, no?

**Comment by benjaminp** [comment]
I'm not sure we should actually have a GitHub link, but while it's there, it might as well go to the best place.

**Comment by brettcannon** [comment]
@gutworth I agree it really doesn't belong there. But if it does stay then we at least we should have a link to hg.python.org and/or bugs.python.org if we are going to include developement-related locations in that menu.

**Comment by brettcannon** [comment]
I'll open another issue to argue for its removal.
