### ISSUE TITLE
Issue tracker: Can register with existing username

### ISSUE THREAD

**Issue by paulcyr** [python/pythondotorg#1250]
I completed the registration process on https://bugs.python.org/user?@template=register and received the "Complete your registration to Python tracker" email.

When I clicked the confirmation link, the site displayed the error: 

> node with key "paul" exists

I believe that a check for an existing user should happen before the registration form is accepted on the registration page.

**Comment by berkerpeksag** [comment]
Good catch and thanks for the report, but the correct place to report issues with bugs.python.org is http://psf.upfronthosting.co.za/roundup/meta/
