### ISSUE TITLE
Extra \n symbols in downloads section at the bottom

### ISSUE THREAD

**Issue by ilevkivskyi** [python/pythondotorg#1253]
It looks like #1219 broke formatting in the downloads section at the bottom. See screenshot:
<img width="497" alt="screen shot 2018-05-04 at 01 45 46" src="https://user-images.githubusercontent.com/12005495/39609131-6c4a1ba2-4f3e-11e8-9012-e81dcc775f65.png">

**Comment by ewdurbin** [comment]
Resolved! Thank You! Was bad CMS content on my part, not the PR

**Comment by ilevkivskyi** [comment]
Thanks! Also it looks like now there is no icon to the left of `Download` (unlike in all other sections). Or it was always like this?

**Comment by ilevkivskyi** [comment]
Screenshot:
<img width="896" alt="screen shot 2018-05-04 at 02 03 22" src="https://user-images.githubusercontent.com/12005495/39609241-5dead5a0-4f3f-11e8-8992-5f8de1c06cae.png">
