### ISSUE TITLE
Change "Mac OS X" and "OS X" references to "macOS"

### ISSUE THREAD

**Issue by ned-deily** [python/pythondotorg#1254]
https://en.wikipedia.org/wiki/MacOS_version_history

I think there are at least two parts to this.  The easier one is to catch and change all the references in "static" content on pydotorg.  The second, and more complicated part, would be to change references in the CMS-managed content, in particular, the entries for the numerous Python releases: that content is managed by the cPython release managers.  I'm not so concerned about all that.

In any case, none of this is high-priority.

**Comment by hugovk** [comment]
Please see PR https://github.com/python/pythondotorg/pull/1516.
