### ISSUE TITLE
Broken link in Non-English Docs (new link provided)

### ISSUE THREAD

**Issue by rodsenra** [python/pythondotorg#1256]
Hi,
I have noticed that on page https://wiki.python.org/moin/PortugueseLanguage,
the link to 
```
Translation of Python 2.4 tutorial - into Brazilian Portuguese by RodrigoSenra.
```
is broken.

Could you please point the same link to http://turing.com.br/pydoc/2.7/tutorial/index.html

There is a joint effort of volunteers to keep it up-to-date here: https://wiki.python.org.br/PythonDoc

The URL http://turing.com.br/pydoc/2.7/tutorial/index.html is the official translation effort for the Python Documentation in English into Brazilian Portuguese.
Cheers,
Rod Senra

**Comment by berkerpeksag** [comment]
Done, thank you for the report! Note that you can also edit that page yourself in the future. Quoting from https://wiki.python.org/moin/FrontPage

> If you want to edit a page and have just signed up, or you find that you can no longer edit a page that you could edit before, please write to the pydotorg-www mailing list, stating your account name and your intended edits and we'll add you to the EditorsGroup.
