### ISSUE TITLE
Python brochure page probably defaced

### ISSUE THREAD

**Issue by alexuprise** [python/pythondotorg#1265]
Greetings!

About an hour ago, I've accidentally noticed this on [brochure.getpython.info](http://brochure.getpython.info/): [lightshot link](https://prnt.sc/jmo69r).

I already left a post on the forums and emailed psf@ and webmaster@python.org, just in case. Checked the page look from three different IPs and it looks the same. Sorry if the case is a false alarm after all.

Regards!

**Comment by tjguk** [comment]
Looks that page / site is managed by Marc Andre. I've replied to the OP from webmaster@ and cc-ed MAL
