### ISSUE TITLE
Migrate website to Python 3.7

### ISSUE THREAD

**Issue by datapythonista** [python/pythondotorg#1267]
The website currently works with Python 3.4, which starts to be quite old. CPython 3.7 is already available in beta, and we can make the website work if it (if not already, since Django has been migrated recently to 1.11 and it was the previous version of Django that wasn't compatible with Python > 3.4).

---

**Blockers:**

* [ ] https://github.com/kurtmckee/feedparser/pull/131

**Comment by berkerpeksag** [comment]
Note that we are currently working on to make python.org run on Python 3.6. We can add Python 3.7 to `.travis.yml` once the feedparser PR is merged.

**Comment by scottilee** [comment]
@berkerpeksag it looks like feedparser works with Python 3.7 now: https://github.com/kurtmckee/feedparser/pull/131.

**Comment by berkerpeksag** [comment]
Unfortunately, the master branch of feedparser hasn't been released yet: https://pypi.org/project/feedparser/#history

**Comment by verhovsky** [comment]
@berkerpeksag it's been released now (October 25, 2020).

**Comment by hugovk** [comment]
The codebase was upgraded to Python 3.9 in https://github.com/python/pythondotorg/pull/2208.

@datapythonista Please can you close this issue?
