### ISSUE TITLE
Migrate website to Django 2.0

### ISSUE THREAD

**Issue by datapythonista** [python/pythondotorg#1268]
Django 2.0 was released few months ago, and the python.org website should be migrated to it. The biggest challenge is switching to the new URL dispatcher.

But the release notes should contain information on what needs to be migrated: https://docs.djangoproject.com/en/2.0/releases/2.0/

Also, running the automatic tests and performing manual testing should help identify what needs to be changed.

**Comment by berkerpeksag** [comment]
> Also, running the automatic tests and performing manual testing should help identify what needs to be changed.

+1, we also need to check our dependencies. For example, we've already switched to django-rest-framework, but we still need to keep the old API (tastypie) around (it's used by Python release manager and 3.7.0 will be released later this month) So we may need to make tastypie (or other potential dependencies) make compatible with Django 2.0 first.
