### ISSUE TITLE
Would like "AIX" added to "Python for Other platforms" page

### ISSUE THREAD

**Issue by aixtools** [python/pythondotorg#1271]
Proposed changes to this page: https://www.python.org/download/other/

Add a section "AIX", with the following text:

> Python3 (Python 3.4, Python 3.5 and Python 3.6) and Python 2 are available for free for AIX in installp format at AIXTOOLS. See http://www.aixtools.net/index.php/python for general info. Currently, there are no additional pre-requisites other than a recent version of openssl.base for Python3-3.6.5

> The download page for Python3 is at: http://www.aixtools.net/index.php/python3 and the download page for Python2 is http://www.aixtools.net/index.php/python2.

I have been hunting for the page to make a PR - but, unfortunately, cannot find it.

Thank you!

**Comment by aixtools** [comment]
After reviewing the commits from August and September 2017 - I am guessing that this change is data driven - outside of the "templates" et al that are in the github project.

**Comment by berkerpeksag** [comment]
Done, thanks for the report. You're right that we store all content in database and edit it via Django admin.

Just one question: Is "Python3-3.6.5" the name of the package (or something similar in the AIX context) or just mean that "you need a recent version of OpenSSL for Python 3.6+"?

**Comment by aixtools** [comment]
Yes, I package Python3 with the package name python3 and Python2 with package name python. This will permit both to be installed at the same time - should that be needed or desired.

FYI - the current packages - in installp terms:

aixtools.python:aixtools.python.rte:2.7.15.0::I:T:::::N:python 11-May-2018::::0::
aixtools.python3:aixtools.python3.rte:3.4.8.0::I:T:::::N:python3 13-May-2018::::0::
aixtools.python3:aixtools.python3.rte:3.5.5.0::I:T:::::N:python3 13-May-2018::::0::
aixtools.python3:aixtools.python3.rte:3.6.5.0::I:T:::::N:python3 01-Jun-2018::::0::

Thanks for the addition!

**Comment by aixtools** [comment]
Thanks again @berkerpeksag . Could you modify the text - now that Python3-3.7 is out? 

I have just finished packaging that as 32-bit, and working on 64-bit.

Maybe: 
Change: "Python3 (Python 3.4, Python 3.5 and Python 3.6) and Python 2 are available for free"

to: "Python3  and Python2 are available (no fee)"

Thx!

**Comment by berkerpeksag** [comment]
@aixtools done. Removed the "(Python 3.4, Python 3.5 and Python 3.6)" part.
