### ISSUE TITLE
Document --app-label and --flush options of create_initial_data

### ISSUE THREAD

**Issue by berkerpeksag** [python/pythondotorg#1281]
Both options have been added by @fdroessler at the sprint in London. See https://github.com/python/pythondotorg/commit/c76894e985f6f43ac7da713658c42186bdee07af (`--app-label`) and https://github.com/python/pythondotorg/commit/49ea3476a55e98ef5b688c23b67e16a4baa36899 (`--flush`) for details.

Initially, I was thinking mentioning both options at the "Manual setup" section at https://pythondotorg.readthedocs.io/install.html#manual-setup would be enough, but now I think we should create a new `commands.rst` to document all of our custom commands.

We can use documentation of the tarfile CLI from the standard library as an example: https://docs.python.org/3/library/tarfile.html#command-line-interface

**Comment by pranav0281999** [comment]
Hii.. I would like to work on this issue. @berkerpeksag  pls guide me

**Comment by berkerpeksag** [comment]
Do you have any specific questions? I already explained the initial steps and gave an example in my first comment.

What we basically need is 1) create a new file named `commands.rst` 2) add `commands.rst` to `toctree` in `index.rst` 3) use the following format to document the management command:

```rst
create_initial_data
-------------------

Explain what the command does in a couple of paragraphs.

Give some examples on how to use the command::

    $ ./manage.py create_initial_data --flush

And how to use the :option:`--app-label` option::

    $ ./manage.py create_initial_data --app-label jobs

.. And document all the options of the command:

Command-line options
~~~~~~~~~~~~~~~~~~~~

.. program:: manage.py create_initial_data

.. cmdoption:: --app-label <app_label>

   Explain the meaning of the option here.
```

and 4) add link to the `create_initial_data` documentation from https://pythondotorg.readthedocs.io/install.html

**Comment by pranav0281999** [comment]
Ok.. got it. You can assign me to this issue. I will ask if I have any questions later..

**Comment by berkerpeksag** [comment]
The assignee field is only usable for maintainers. You can submit a PR when you are ready.
