### ISSUE TITLE
Link to Python Brochure in "About" section is broken

### ISSUE THREAD

**Issue by danysdragons** [python/pythondotorg#1288]
Clicking this link (http://brochure.getpython.info/) results in the following screen:

![image](https://user-images.githubusercontent.com/40280395/41482952-4222325a-70a5-11e8-86d3-4e1afba63259.png)

**Comment by malemburg** [comment]
Thanks for the report. This must be a DNS issue.

**Comment by malemburg** [comment]
I'll check with Armin who hosts the site.

**Comment by malemburg** [comment]
Fixed now. The subdomain was accidentally removed from the DNS on Armin's server.
