### ISSUE TITLE
Some GPG key links on /download lead to 404s

### ISSUE THREAD

**Issue by mineo** [python/pythondotorg#1290]
On https://www.python.org/downloads/, section "OpenPGP Public Keys", the following are not available for download anymore:

* Anthony Baxter (key id: 6A45C816)
* Georg Brandl (key id: 36580288)
* Ned Deily (key ids: AA65421D, 6F5E1540)
* Larry Hastings (key id: F73C700D)
* Benjamin Peterson (key id: 18ADD4FF and A4135B38)

Retrieving them directly from GPG key servers via `gpg --recv-keys` still works.

**Comment by ned-deily** [comment]
Thanks for the report.  There have been recent discussions elsewhere about our old practice of hosting PGP public keys on python.org and have come to the conclusion that having them on the same website as the files to be downloaded is a bad practice as it provides no additional security and, worse, could provide an attack vector if somehow python.org security were compromised.  Thus we have updated the PGP section of the Download files and will no longer provide the combined pubkeys.txt file.  The bottom line is that public keys should be obtained from a public key server or some other mechanism that you trust.
