### ISSUE TITLE
Unable to register with bugs.python.org

### ISSUE THREAD

**Issue by james-stevens** [python/pythondotorg#1291]
I registered at bugs.python.org, received the confirm email, but am still unable to login - user id "james_r_c_stevens"

when I use the "login" option, the screen refreshed, but nothing else. There is no indication I am logged in.

If I try and register the EXACT same details again, it will let me. This suggests the registration process is broken.

**Comment by Mariatta** [comment]
Thanks for the report, and sorry you're having trouble with it.
The issue tracker for bugs.python.org is at https://github.com/python/bugs.python.org.
Could you please open your issue there?
Thanks.
