### ISSUE TITLE
Remove references to Google Groups mirror of comp.lang.python

### ISSUE THREAD

**Issue by tjguk** [python/pythondotorg#1294]
Speaking on behalf of the python-list owners

The comp.lang.python newsgroup has become dominated by spam, some of it very nasty. Those who consume the newsgroup via a newsreader are accustomed to applying filtering. The gateway into the Python mailing list also has appropriate filtering in place. However, Google Groups ("GG") is the most public mirror of the newsgroup and has no such filtering. Attempts to flag items as spam appear to have had no effect. It is supposed that Google has no interest in stewardship of their mirror.

Unfortunately this is where many users end up who have no particular knowledge of newsgroups or mailing lists and simply want a web forum-style interface.

We are considering moving the list to Mailman3 which would offer a moderated web interface. In the meantime, we'd like to remove from the python.org estate references to GG as a mirror of comp.lang.python.

The two which have been pointed out are:

* https://www.python.org/community/lists/
* https://www.python.org/search/search_news/

The first probably just needs tweaking to remove references to Google Groups

The second appears orphaned and should, I think, simply be removed.

I think I probably have the wherewithal to make these changes myself, but I'm putting this issue up to see whether anyone else on the python.org team had any particular objection or other input.

**Comment by berkerpeksag** [comment]
No objections from me.

I agree that https://www.python.org/search/search_news/ should be removed since it has broken markup and no one noticed or bothered to report it to us.

**Comment by tjguk** [comment]
Thanks @berkerpeksag. I can drop the search_news page via the CMS. But is there any process in place to detect any links which dangle as a result? Or is there some pre-check I can do to find them first?

**Comment by berkerpeksag** [comment]
Unfortunately, there is no easy way to do that. I can login to the server and run a query like `Page.objects.filter(content__contains='/search/search_news/')` (untested) via `./manage.py shell`, but I don't think that page is too important :)

We can uncheck the "Is published" option instead of dropping the page completely if we want to be super careful.

**Comment by tjguk** [comment]
Nah. I think we're fine to ditch it. I think there's probably a case for scanning the site of dangling links, but we don't have to do that here.

**Comment by tjguk** [comment]
The search_news page is now deleted. I'll take some time later to review the Community Lists page and update accordingly

**Comment by tjguk** [comment]
I've made small mods to the Community LIsts page, principally to remove a couple of references to the Google Groups mirror of comp.lang.python

**Comment by berkerpeksag** [comment]
Thanks!
