### ISSUE TITLE
bugs.python.org needs TLS version update to support 1.2

### ISSUE THREAD

**Issue by genodeftest** [python/pythondotorg#1297]
Please correct me if I'm wrong here and this report should go somewhere else.

TLS 1.0 and 1.1 are old and weak, they may be broken at some time soon. Some projects such as [Fedora](https://fedoraproject.org/wiki/Changes/StrongCryptoSettings2) plan to disable TLS versions below 1.2 by default soon. TLS 1.2 has been available for almost 10 years and TLS 1.3 is coming soon™.

Any server of the python project, including bugs.python.org, should support TLS 1.2 at least.

[SSLLabs report on bugs.python.org](https://www.ssllabs.com/ssltest/analyze.html?d=bugs.python.org)

**Comment by Mariatta** [comment]
Thanks for the report. This is not quite the right issue tracker. Do you mind filling it at https://github.com/python/bugs.python.org?
Thanks.

**Comment by genodeftest** [comment]
Reported as python/bugs.python.org#16. Thank you for hinting me to the correct repository, @Mariatta!
