### ISSUE TITLE
Audit requirements.txt

### ISSUE THREAD

**Issue by jefftriplett** [python/pythondotorg#130]
We have some out-of-date requirements (Django) and some libraries which we forked because they weren't py3 compatible yet. Some of these changes were accepted and made it back in to actual mainline releases so we should switch back. Other libraries added their own py3 support. 

Personally, I don't the website to depend on one of my forks or anyone elses: https://github.com/python/pythondotorg/blob/master/requirements.txt#L41

**Comment by dstufft** [comment]
https://requires.io/ Might be a useful tool for this.

**Comment by jefftriplett** [comment]
The Python3 world is a better place nearly a year later. I suspect all if not most of the forks / pinned shas can return back to released versions. If not, we should consider switching to a new library.

**Comment by dstufft** [comment]
Yea. Just saying that requires.io will monitor a requirements.txt and can optionally send out an email whenever there are outdated (or insecure) requirements. It also makes a badge ala Travis-CI and friends that says whether the requirements.txt is up to date, outdated, or insecure.
