### ISSUE TITLE
Mailing lists which have moved to Mailman 3 aren't listed

### ISSUE THREAD

**Issue by mattheww** [python/pythondotorg#1300]
https://www.python.org/community/lists/  has a link near the top advertising itself as a « complete listing of python.org's public mailing lists ».

But the link goes to the mail.python.org Mailman 2 listing, so lists which have moved to Mailman 3 (eg Distutils-SIG) are missing.

**Comment by berkerpeksag** [comment]
Thanks for the report! Do you have a suggestion for wording? I'm not sure how we can add a link to https://mail.python.org/mm3/mailman3/lists/ without a rewrite.

**Comment by mattheww** [comment]
I can't think of anything very elegant. Maybe something like this?
«
For a complete listing of python.org's public mailing lists, check both _lists hosted on mailman 2_ and _lists hosted on mailman 3_.
»

NB linking to https://mail.python.org/mm3/archives/ might be better than https://mail.python.org/mm3/mailman3/lists/, as the archives page has a 'find list' box (and also apparently if you're logged in https://mail.python.org/mm3/mailman3/lists/ shows only lists you're subscribed to).

**Comment by berkerpeksag** [comment]
Your suggestion sounds great, thanks! I've just updated https://www.python.org/community/lists/ with your suggested wording.
