### ISSUE TITLE
It would be great if we can clarify which Python versions are still maintained ...

### ISSUE THREAD

**Issue by Mariatta** [python/pythondotorg#1302]
... and which ones are not.

**Is your feature request related to a problem? Please describe.**
Folks not involved with Core Python development might not know which Python versions are still maintained, and which ones are no longer maintained and not preferred anymore.

We have a release schedule listed at the bottom of python.org/downloads, I guess it was meant to indicate which ones will still receive new fixes, but it was not explicit in saying that the other ones aren't being maintained anymore.

Devguide has [some more info](https://devguide.python.org/#status-of-python-branches) about it, but casual users wouldn't land on that page.

**Describe the solution you'd like**
It would be great if we can clarify which Python versions are still maintained, and which are not.
The downloads page seems like a good place. Perhaps we can add some paragraph indicating which ones are still actively maintained, and which ones are not.
We also should state that unmaintained Python versions should not be used.

**Additional context**
See twitter thread: https://twitter.com/pydanny/status/1024302657161256960

**Comment by jefftriplett** [comment]
Would it make send to update the release grid from the [downloads page](https://www.python.org/downloads/) to show whether or not a release is supported? 

Here is a screenshot: ![](https://www.evernote.com/shard/s27/sh/7c552539-f1d3-49e5-8d98-324847a8b016/ac929c11c083b5e9/res/b035d42f-ae6b-4fd0-95a6-a50e9d01ecf9/skitch.png) This could be an extra column/icon.

**Comment by jaap3** [comment]
What about doing something similar to [Django's download page](https://www.djangoproject.com/download/)?

They make a clear distinction between 

* _Latest releases_ 
    final and RC
* _Previous releases_
    Currently only the LTS version
* _Unsupported previous releases_
   With a clear indication that these releases "no longer receive security updates or bug fixes"

Furthermore they do an excellent job of communicating the timeline of supported versions.

**Comment by anlutro** [comment]
Was directed here from bugs.python.org, want to re-iterate my points because I think this is important. Every time I see people asking questions about this in IRC I have a hard time finding the official list.

There are many pretty version support pages out there but I don't think that's the most important thing. Try searching for the following in google:

- `$THING` versions support
- `$THING` versions lifecycle
- `$THING` versions roadmap
- `$THING` versions end of life

If you try these with PHP, Symfony, Django and Python, you'll go from the results being great to mediocre to absolutely terrible. Some of the Python search results even direct to a page on the devguide which only has old versions listed. If the table from the devguide was copied to somewhere on python.org and a little bit of attention is given to SEO that would help tremendously.

**Comment by berkerpeksag** [comment]
Thanks for the all comments. They all sound good to me. I'm planning to redesign downloads application (the first step is to retire v1 of downloads API) and I will incorporate all of these suggestions.

**Comment by mtbc** [comment]
It was indeed only through https://bugs.python.org/issue25296 that I finally found what I wanted at https://devguide.python.org/#status-of-python-branches

**Comment by changeling** [comment]
[UPDATE: I just realized it's right there on the top level of https://devguide.python.org/. Which is great, though it still took me awhile. I first checked PEP 478, assuming that would be the canonical source. Then I looked at https://devguide.python.org/devcycle/, assuming that chart would include projected. Then I decided to just ask google, which didn't help. Basically, I missed that top-level devguide would have it, then PEP 478, then I went into rabbit-hole. So I guess what I'd suggest is that branch PEP, at the very least, should cover lifecycle. And perhaps have life-cycle points added to the download grid.]

This seems to still be an issue. SEO seems pretty solid for PEPs, but as far as I can discover, projected EOL is  absent from those.. For an example, acting as a non-savvy end user and doing google searches, can you find EOL for 3.5? I can't. Generally, EOLed branches are fairly discoverable, but future EOL is hit or miss.

https://devguide.python.org/devcycle/ lists past EOL, but not projected.


(What _is_ 3.5 EOL? That's not even mentioned on [PEP 478 -- Python 3.5 Release Schedule](https://www.python.org/dev/peps/pep-0478/) itself. @larryhastings?)

**Comment by Mariatta** [comment]
3.5 EOL is September 13, 2020, documented in the devguide https://devguide.python.org/#status-of-python-branches

**Comment by hugovk** [comment]
> What about doing something similar to [Django's download page](https://www.djangoproject.com/download/)?

Yes, that's a good one. Other projects with short, simple, clear, dedicated pages:

# PHP

![image](https://user-images.githubusercontent.com/1324225/66715271-0257dc80-edca-11e9-83ee-083495e62f9d.png)

* https://www.php.net/supported-versions.php

---

# Node.js

![image](https://user-images.githubusercontent.com/1324225/66715282-46e37800-edca-11e9-9997-b3c02f71fe1f.png)

* https://nodejs.org/en/about/releases/

---

And @di just [made](https://twitter.com/di_codes/status/1182227000540446720) a really good chart for Python:

![image](https://user-images.githubusercontent.com/1324225/66715320-b8bbc180-edca-11e9-935b-9c715cfaa47d.png)

https://python-release-cycle.glitch.me/

I occasionally refer to the PHP and Node.js pages, they're easy to find and communicate immediately what I want to know.

How about a similar "supported versions" page for Python with this or a similar chart?

**Comment by crwilcox** [comment]
I tried adding a table to the existing downloads page and I have this in a branch on my fork: https://github.com/crwilcox/pythondotorg/tree/add-release-schedule-to-downloads

While not in the branch, I think ideally the python version column would link to the latest patch release.
 
![image](https://user-images.githubusercontent.com/638797/71303187-f3f9e400-2369-11ea-895b-cf9df203aeaa.png)

**Comment by brainwane** [comment]
Thank you @berkerpeksag !

**Comment by hugovk** [comment]
Update: a release cycle chart is now live at https://devguide.python.org/versions/

![image](https://user-images.githubusercontent.com/1324225/205892434-67024534-2520-4774-b38a-927fa5c62e6a.png)

Re: issue https://github.com/python/docs-community/issues/67 / PR https://github.com/python/devguide/pull/988
