### ISSUE TITLE
Searching for the phrase utf-8 results in errors

### ISSUE THREAD

**Issue by JamesSeiters** [python/pythondotorg#1307]
**Describe the bug**
Searching for the phrase utf-8 randomly returns an error page. The behavior is inconsistent and will sometimes return the search results. Searching for other phrases consistantly returns the search results.

**To Reproduce**
From the python.org homepage, type the characters utf-8 in the search box and click the go button or hit the enter key. After a lengthy delay, you will see a 504 Gateway Time-out page, or Error 503 first byte timeout, or Error 503 Service Unavailable.

**Expected behavior**
The search results should be displayed consistently.

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04.5 LTS 64-bit
 - Browser: Firefox Quantum
 - Version 61.0.1

**Comment by berkerpeksag** [comment]
This might be a transient error. I just tried searching "utf-8" and it gave me the results right away:

![screenshot from 2018-08-05 01 56 51](https://user-images.githubusercontent.com/26338/43681098-cbf91b40-9852-11e8-99f8-efefd2be0faa.png)

**Comment by smontanaro** [comment]
Verified just now on Android P running Chrome 68.0.3440.70.

**Comment by JamesSeiters** [comment]
I can no longer reproduce this issue, so I am going to close this. No point in leaving it lying around.
