### ISSUE TITLE
Set right expiration headers for static content

### ISSUE THREAD

**Issue by xen** [python/pythondotorg#131]
Google PageSpeed tool report some issues that slow down page load speed. Some of them harder to fix quickly some not. Static resources doesn't have proper expiration headers:

![screen shot 2014-02-20 at 7 08 43 pm](https://f.cloud.github.com/assets/31260/2220800/ae3c257e-9a51-11e3-95a7-b324fbc5db83.png)

Full speed report [here](http://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fwww.python.org%2F&tab=desktop)

**Comment by berkerpeksag** [comment]
This is mostly done. Current result looks reasonable to me:

```
https://console.python.org/python-dot-org-live-consoles-status (expiration not specified)
https://ssl.google-analytics.com/ga.js (2 hours)
```
