### ISSUE TITLE
Borders on the sides of "Python Logo" menu item in the footer

### ISSUE THREAD

**Issue by Mariatta** [python/pythondotorg#1318]
**Describe the bug**
I noticed there are two lines on the left and right pf "Python Logo" menu item.
Not sure if there was a reason for those.

**To Reproduce**
1. Go to www.python.org
2. Scroll down to the bottom.

**Expected behavior**
Perhaps there shouldn't be those extra lines, but maybe I'm missing some context.

**Screenshots**
<img width="243" alt="screen shot 2018-08-27 at 1 20 08 pm" src="https://user-images.githubusercontent.com/5844587/44683869-56540600-a9fc-11e8-90ec-4749ee74fe59.png">

**Desktop (please complete the following information):**
 - Browser Chrome 
 - Version 68.0.3440.106 (Official Build) (64-bit)

**Comment by berkerpeksag** [comment]
Can you please check staging.python.org? I think this has already been fixed by https://github.com/python/pythondotorg/commit/c1f726b8e02f28cac790b3476d5a5e52a0742d0e, but I didn't cherry-pick it into the release branch yet.

**Comment by Mariatta** [comment]
Ah, yes, the borders don't exist in staging.

**Comment by berkerpeksag** [comment]
Cherry-picked into the release branch: https://github.com/python/pythondotorg/commit/fe4532e4d7d1c7efc8133152f66827dda0139a7f.
