### ISSUE TITLE
Being able to resize the interactive shell

### ISSUE THREAD

**Issue by morphex** [python/pythondotorg#132]
Hello. :)

Would it be possible to make the shell on the frontpage resizeable?  I think rows is the most important part to be able to resize so one avoids annoying scrolling..  I remember that one of the things that got me into Python was playing around with the interactive interpreter, and a more pleasant testing shell might recruit others as well.

**Comment by berkerpeksag** [comment]
Thanks for the report. I think the height of the REPL is already big enough. It should be enough for a quick introduction (see the attached screenshot below) Also, Python comes installed on many different OSes (except Windows but it should be pretty easy to install it by using our installers at python.org)  so I'm going to close this as 'wontfix'.

![screenshot from 2017-08-01 16 27 51](https://user-images.githubusercontent.com/26338/28827484-61d01dca-76d6-11e7-8fc3-abfe4a6d4ee3.png)
