### ISSUE TITLE
Execute the last version of Python in the interactive Shell

### ISSUE THREAD

**Issue by matrixise** [python/pythondotorg#1321]
**Describe the bug**
On the main page we can execute Python in an interactive shell, but the version from PythonAnywhere is Python 3.6 and not 3.7.

**To Reproduce**
1. Go to 'https://www.python.org/shell/'
2. the version of python is 3.6.

**Expected behavior**
the version of python should be 3.7

**Comment by berkerpeksag** [comment]
Python 3.7 is pretty new, so I wouldn't expect it to be deployed on PythonAnywhere anytime soon. @gpjt can correct me if I'm wrong, though.

**Comment by gpjt** [comment]
3.7 is live on PythonAnywhere right now :-)  We'll be switching over the python.org consoles when we do our next system update, hopefully sometime over the next month.

**Comment by berkerpeksag** [comment]
That's great to hear! I'm closing this as 'fixed' then.
