### ISSUE TITLE
broken link to FAQs in "Biginner's Guide"

### ISSUE THREAD

**Issue by KKH-tw** [python/pythondotorg#1326]
The link to "FAQs" in the folllowing page is broken:

https://wiki.python.org/moin/BeginnersGuide

**Comment by mch1992** [comment]
That's the wiki.  This repo is only what is hosted at https://www.python.org/

**Comment by KKH-tw** [comment]
Thank you.

**Comment by bhawesh96** [comment]
@jhs-tw 
This issue can be closed right?
