### ISSUE TITLE
Link to "Academic Free License" is 404 in PSF Contributor Agreement

### ISSUE THREAD

**Issue by Mariatta** [python/pythondotorg#1329]
**Describe the bug**
The link to Academic Free License v 2.1 (https://www.samurajdata.se/opensource/mirror/licenses/afl-2.1.php) results in 404.

**To Reproduce**
https://www.python.org/psf/contrib/contrib-form/

Click on the link to `Academic Free License v 2.1`.

**Comment by bhawesh96** [comment]
https://spdx.org/licenses/AFL-2.1.html

Could this be used rather?

**Comment by berkerpeksag** [comment]
Looking at https://spdx.org/licenses/, it looks "official" enough to me. I've replaced the broken link with the one from spdx.org. Thanks, @bhawesh96!

**Comment by Harmon758** [comment]
This was a duplicate of/also resolved #1236.
