### ISSUE TITLE
On a fresh install, most of the nav links point to /inner/ or /#unresolved

### ISSUE THREAD

**Issue by mch1992** [python/pythondotorg#1331]
I believe this requires editing the `url` and in some cases the `urlaspattern` field  of each of the links' corresponding entries in `fixtures/sitetree_menus.json`.  For example, the link that's supposed to point to https://docs.python.org/ currently has its `url` set to `"https://docs.python.org/"` and its`urlaspattern` set to `True` which renders as /#unresolved because `url` is not a named url pattern defined in the app.

**Comment by berkerpeksag** [comment]
Good catch, that's my fault! Would you like to submit a pull request?

**Comment by mch1992** [comment]
Sure thing!

**Comment by bhawesh96** [comment]
Has this been resolved? If not, I can look into it.

**Comment by berkerpeksag** [comment]
@bhawesh96 feel free to submit a PR!

**Comment by 0xrushi** [comment]
Is it fixed ? or shall i look into it ?
