### ISSUE TITLE
Upgrade Vagrant box to run on Python 3.6

### ISSUE THREAD

**Issue by berkerpeksag** [python/pythondotorg#1333]
We probably need to use a newer Ubuntu box in https://github.com/python/pythondotorg/blob/master/provisioning/pythondotorg.yml to install Python 3.6 from the official Ubuntu repositories.

Also, https://pythondotorg.readthedocs.io/install.html#easy-setup-using-vagrant documentation needs to be updated.

**Comment by Tomasz-Kluczkowski** [comment]
Is this box better? Since it's 18.04 it comes with python 3.6 by default. 
Replace then in Vagrantfile:
```
Vagrant.configure(2) do |config|
  # TODO: https://askubuntu.com/a/854396
  config.vm.box = "bento/ubuntu-16.04"
```
with:
```
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
```

https://github.com/chef/bento/blob/master/ubuntu/ubuntu-18.04-amd64.json

**Comment by berkerpeksag** [comment]
If the official Ubuntu box for 18.04 still doesn't come with a "vagrant" user, I think that seems like the best option. Do you have time to check the official 18.04 box?

**Comment by Tomasz-Kluczkowski** [comment]
I can have a look. We have a sprint this week, may be a good subject for our work.

**Comment by Tomasz-Kluczkowski** [comment]
I have quickly downloaded / initialised default ubuntu/bionic64 (18.04) and after vagrant ssh it logs in as vagrant user. Is this what we are looking to have? Or there are more checks that need to be performed to determine if all is ok?
If that is the case we could use:
```Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
```

**Comment by Tomasz-Kluczkowski** [comment]
Looks like I spoke to early and the default bionic64 18.04 image does not allow Ansible to complete (it fails to install dependencies).
When using  bento 18.04 it proceeds to begin installing all the packages in Ansible but fails at postgres 9.5 as it is no longer the official version and cannot be obtained. I remember having identical issue with my work project and having to download a .deb file to install postgres 9.6.
We could use the bento 18.04 but then what about postgres version?

**Comment by berkerpeksag** [comment]
We can use the latest PostgreSQL version available. I don't recall anything that keeps us from upgrading our PostgreSQL version.

**Comment by Tomasz-Kluczkowski** [comment]
Ok I have done further research and managed to run the project with the following changes:
- Vagrantfile
    ```config.vm.box = "bento/ubuntu-18.04"```
- pythondotorg.yml
    ```    - name: Install PostgreSQL
      apt: name={{ item }} state=installed
      become: yes
      with_items:
        - postgresql #-9.5
        - postgresql-contrib #-9.5
        - libpq-dev
        - python-psycopg2
    ```
The project starts appropriately and is browsable.
Do you intend to upgrade to the newest postgres though as that is what was downloaded?
The tests pass.

**Comment by Tomasz-Kluczkowski** [comment]
Looks like I missed your comment above. If newest postgres is fine I shall clean this up and create a PR on Tuesday when we have our sprint in London.
I will also look at some other issues, slowly learning more about your project.

**Comment by berkerpeksag** [comment]
That's great, thanks!
