### ISSUE TITLE
Python3.7 buildin wheel for pyaudio

### ISSUE THREAD

**Issue by Rokit12** [python/pythondotorg#1345]
I have been trying to install pyaudio with different command platforms, here is the response:
C:\Users\Robinson>pip install pyaudio
Collecting pyaudio
  Using cached https://files.pythonhosted.org/packages/ab/42/b4f04721c5c5bfc196ce156b3c768998ef8c0ae3654ed29ea5020c749a6b/PyAudio-0.2.11.tar.gz
Building wheels for collected packages: pyaudio
  Running setup.py bdist_wheel for pyaudio ... error
  Complete output from command c:\users\robinson\appdata\local\programs\python\python37\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Robinson\\AppData\\Local\\Temp\\pip-install-vlodh5wr\\pyaudio\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\Robinson\AppData\Local\Temp\pip-wheel-dadlafei --python-tag cp37:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  copying src\pyaudio.py -> build\lib.win-amd64-3.7
  running build_ext
  building '_portaudio' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

  ----------------------------------------
  Failed building wheel for pyaudio
  Running setup.py clean for pyaudio
Failed to build pyaudio
Installing collected packages: pyaudio
  Running setup.py install for pyaudio ... error
    Complete output from command c:\users\robinson\appdata\local\programs\python\python37\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Robinson\\AppData\\Local\\Temp\\pip-install-vlodh5wr\\pyaudio\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Robinson\AppData\Local\Temp\pip-record-zszfczwx\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    copying src\pyaudio.py -> build\lib.win-amd64-3.7
    running build_ext
    building '_portaudio' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

    ----------------------------------------
Command "c:\users\robinson\appdata\local\programs\python\python37\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Robinson\\AppData\\Local\\Temp\\pip-install-vlodh5wr\\pyaudio\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Robinson\AppData\Local\Temp\pip-record-zszfczwx\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Robinson\AppData\Local\Temp\pip-install-vlodh5wr\pyaudio\
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by berkerpeksag** [comment]
This tracker is for issues with www.python.org. Please report this to PyAudio developers: http://people.csail.mit.edu/hubert/pyaudio/

**Comment by Zeglaty** [comment]
if you got a solution pls help

**Comment by Rokit12** [comment]
not yet, use python 3.6 that is the only solution

**Comment by RedditMaster** [comment]
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": 
It's helps to read the code, its saying you need to install Microsoft Visual C++. once you so you should be good to go.

**Comment by HOAXsk8** [comment]
I had the same problem with PyCrypt. Installing Microsoft Visual C++14.0 and every other version made no difference whatsoever. I am now looking for a solution for PyAudio but I'm not going round in the same circles as PyCrypt so I am using sounddevice instead, it seems a bit unstable though.

**Comment by sandeepnegi1996** [comment]
I have also tried installing but it is showing it is giving that .whl is not supported for this platform

**Comment by sandeepnegi1996** [comment]
It is working with python 3.6 version I don't know why they not giving the support for the 3.7 verison but yes it is working with python 3.6
