### ISSUE TITLE
Link to "message posted by Vladimir Marangozov" is 404

### ISSUE THREAD

**Issue by toonarmycaptain** [python/pythondotorg#1346]
On the [Metaclasses in Python 1.5](https://www.python.org/doc/essays/metaclasses/
) page, the link "message posted by Vladimir Marangozov" links to https://www.python.org/doc/essays/metaclasses/meta-vladimir.txt when I think it should link to https://legacy.python.org/doc/essays/metaclasses/meta-vladimir.txt - or at least that's the document I believe is intended. 

**To Reproduce**
1. Go to [Metaclasses in Python 1.5](https://www.python.org/doc/essays/metaclasses/)
2. Click on [message posted by Vladimir Marangozov](https://www.python.org/doc/essays/metaclasses/meta-vladimir.txt)
4. See error 404

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Version 69.0.3497.100 (Official Build) (64-bit)

I'm happy to submit a PR with an updated link, but can't seem to find the sourcefile to edit.

**Comment by berkerpeksag** [comment]
Thanks for the report. I've fixed that link, but there are still a few links that lead to 404 at the examples section. I will fix them later today.

Currently, the only way to update the data is to use Django admin interface.

**Comment by toonarmycaptain** [comment]
Excellent. Well if I can be of assistance, let me know. :)
