### ISSUE TITLE
Donation ways

### ISSUE THREAD

**Issue by jemeraldo** [python/pythondotorg#1347]
**Is your feature request related to a problem? Please describe.**
I'm excited with Python and it's community and just made a donation with paypal. But I spent about 10 minutes for it, typing card number, passing captcha, etc. Besides, I paid for converting RUB->USD.

**Describe the solution you'd like**
Make sending donation via Bitcoin.

**Comment by berkerpeksag** [comment]
First of all, thank you for donating to the PSF! :) This tracker is for issues with www.python.org. I think emailing to psf-donations@python.org would increase the chance of reaching to the right person about your proposal. We can reopen this issue if the PSF decides to accept donations via Bitcoin and needed to implement something on python.org to do so.
