### ISSUE TITLE
Give a dirrect download url of Visual C++ 14.0

### ISSUE THREAD

**Issue by eromoe** [python/pythondotorg#1348]
**Describe the bug**

Here,  https://wiki.python.org/moin/WindowsCompilers#Microsoft_Visual_C.2B-.2B-_14.0_standalone:_Build_Tools_for_Visual_Studio_2017_.28x86.2C_x64.2C_ARM.2C_ARM64.29
doesn't directly link to the download url.  

1. Because the page doesn't show build tool at first, it make me think microsoft pull off it and have to install vs 2017.
2. The translation of `Build tool`.  `Visual Studio 2017 生成工具` in Chinese doesn't looks like proper ,because  `build/compile` usually is translate as `编译` .  

So, give a dirrect link would be better I think

**Comment by berkerpeksag** [comment]
Thanks for the report. This tracker is for issues with www.python.org. Content of wiki.python.org is maintained by the Python community, so you can fix it yourself. See https://wiki.python.org/moin/FrontPage#Editing_pages for more details on how to edit a page on wiki.p.o.
