### ISSUE TITLE
Download Python 3.7.1 Documentation (broken links - 404 Not Found)

### ISSUE THREAD

**Issue by KoertNL** [python/pythondotorg#1350]
**Broken links** - 404 Not Found - on the website https://docs.python.org/3/download.html
- PDF (US-Letter paper size)
- PDF (A4 paper size)
- EPUB

**Comment by demonking** [comment]
This is also for the version 3.6.7  ;)

**Comment by ned-deily** [comment]
At the moment, it looks like all of the doc builds (3.8, 3.7, 3.6, and 2.7) are broken once they get past the html and text builds.  @JulienPalard, can you take a look at this, please?  (Also, please request to be added to the GitHub pythondotorg team.  Thanks!)

**Comment by JulienPalard** [comment]
It could be due to:

    Warning, treated as error:
    the python_docs_theme extension does not declare if it is safe for parallel reading, assuming it isn't - please ask the extension author to check and make it explicit

I just bumped python_docs_theme version, it should pass now, let's watch.

**Comment by demonking** [comment]
An Update from the Mailinglist : 

~~~

hmmmm... looks like somebody planned a change and then didn't complete
it, the presence of "archives" in the URLs seems to be new to 3.6/3.7.
The doc directory the download points to only is populated with some of
the doc files (the zip and tar.bz2 versions of html and text).
Meanwhile, the full set of doc files are still available in the "old"
path style:

https://www.python.org/ftp/python/doc/3.6.7
https://www.python.org/ftp/python/doc/3.7.1

we'll see if we can figure out what was intended here, thanks for the note.

~~~

**Comment by ned-deily** [comment]
@demonking, What MailingList?  That speculation is incorrect; there is no change involved.  And the full sets found at https://www.python.org/ftp/python/doc/ are something different; those are the [Python Documentation by Version docs](https://www.python.org/doc/versions/) that correspond to each exact release, e.g. as of repo tag v3.7.1 or v3.6.7.  Those docs sets are immutable.  The docs sets that are under discussion in this issue are the ones that are built daily from the head of each release branch and master, in other words, the most up-to-date docs.

**Comment by JulienPalard** [comment]
Looks related to https://github.com/sphinx-doc/sphinx/issues/5561

**Comment by JulienPalard** [comment]
With an up-to-date version of xindy the builds are passing on my laptop.
I've uploaded the pdf of 3.7.1 manually to docs.python.org as a temporary fix, just so people can download them while we're searching for a clean fix.

**Comment by matrixise** [comment]
@ned-deily and @JulienPalard I would like to close the [bpo issue](https://bugs.python.org/issue35055) because it's a duplicata of this one.

**Comment by JulienPalard** [comment]
Update on the issue: https://github.com/sphinx-doc/sphinx/pull/5574

(And for the moment, the PDF are still available online, as the docsbuild-scripts do no longer remove them on build failures).

**Comment by berkerpeksag** [comment]
I initially pinged Ned here because I didn't have the time to file an issue on bugs.p.o, but actually this tracker doesn't have anything to do with docs.p.o. Please move the discussion elsewhere. I'm trying to keep the issues in this tracker related to www.python.org. Issues with *.python.org websites should be discussed at their issue trackers.
