### ISSUE TITLE
Table of Content should not move along with the Main Content

### ISSUE THREAD

**Issue by office-github** [python/pythondotorg#1353]
This looks annoying as reader while learning the python from the official page.

As a geeks whose first visit is the Official Page. This looks very brutal to see the "Table of Content" scrolling up with the main content of the page which actually should be static.

Refer the official page of Angular.
 
References: 
https://angular.io/docs

**Comment by berkerpeksag** [comment]
Thank you for the report! This tracker is for issues with www.python.org. We don't maintain docs.python.org and its theme. There is an open issue about the same problem in the python-docs-theme issue tracker: https://github.com/python/python-docs-theme/issues/20
