### ISSUE TITLE
non-adaptive breadcrumbs / too much horizontal space 

### ISSUE THREAD

**Issue by misterfourtytwo** [python/pythondotorg#1354]
**Describe the bug**
It's not exatcly a bug, but a minor frontend problem.
Long breadcrumbs aren't wrapped into few lines and introduce the horizontal scrolling which introduce some inconvinience on small and/or touchscreen displays.
It appears to be some kind of duplicate of #731, which is closed.

**To Reproduce**
1. Go to https://www.python.org/dev/peps/pep-3333/ or any other page with long path(e.g. many of the PEP's)
2. In every display/opened window which are more narrow than the breadcrumbs text.

**Expected behavior**
For them to be carried to the next line instead of horizontally expanding otherwise perfectly scaled page.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/17276509/48196139-a4717800-e362-11e8-9a32-8ecac3c60ee4.png)

![screenshot](https://user-images.githubusercontent.com/17276509/48196396-8b1cfb80-e363-11e8-8fac-6df6a18c07e0.png)

**Devices:**
I've spotted the same behavior in chromium and firefox on my debian laptop and chrome on my smartphone(redmi 3s).

**Additional context**
If "white-space:nowrap" rule is removed from a css-class .breadcrumbs, everything is just perfect.
![screenshot](https://user-images.githubusercontent.com/17276509/48196529-d6cfa500-e363-11e8-9854-5ae28b678399.png)

**Comment by berkerpeksag** [comment]
Thanks for the report. I think this has been fixed in master, but not deployed to production yet. Could you please check https://staging.python.org/dev/peps/pep-0333/?

**Comment by misterfourtytwo** [comment]
issue appears to be fixed on pc, but void blue space to the left is still there on android.
![photo_2018-11-18_21-43-35](https://user-images.githubusercontent.com/17276509/48676689-496a2d00-eb7b-11e8-9425-a9bd4447ff30.jpg)

**Comment by hugovk** [comment]
The PEPs are now in their own repo and hosted on their own website so this should be resolved:

* https://peps.python.org/pep-0676/
* https://github.com/python/peps/
