### ISSUE TITLE
i got a but about 0.29 * 100000000

### ISSUE THREAD

**Issue by haofeann** [python/pythondotorg#1356]
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 12:04:33) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 0.29 * 100000000
28999999.999999996

**Comment by berkerpeksag** [comment]
Please see https://docs.python.org/3/tutorial/floatingpoint.html (and note that this isn't the right place to report such an issue. This tracker is for issues with www.python.org, the official Python website, not about Python itself.)
