### ISSUE TITLE
Link to Bugs does not work (Proxy Error)

### ISSUE THREAD

**Issue by schontz** [python/pythondotorg#1357]
**Describe the bug**
https://www.python.org/doc/ has a broken link to Bug Tracker (https://bugs.python.org/)

**To Reproduce**
1. Go to 'Doc'
2. Click on 'Bug Tracker'
3. See Proxy Error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Mariatta** [comment]
Thank you for the report. The url https://bugs.python.org is correct, but I know that occasionally it goes down ☹️  

But since the url is the correct one, there is nothing to be fixed from this side.
