### ISSUE TITLE
Python online editor like JDoodle

### ISSUE THREAD

**Issue by eric645** [python/pythondotorg#1359]
[`Python online editor like JDoodle`] is the feature I want.
Hints:
Hint 1:
In python.org/online_editor_shell:
```html
<script type='text/x-python'>
# Your code here...
</script>
```
End of hints

**Comment by Mariatta** [comment]
Thanks for the suggestion. JDoodle looks interesting, but it does not yet have Python 3.7 environment, only 3.6.5, 3.6.3, 3.5.1.
Meanwhile Python Anywhere (what we're using now) supports Python 3.7.  Perhaps we should keep Python Anywhere for now. Thanks!
