### ISSUE TITLE
Make use of social network names consistent in Socialize menu

### ISSUE THREAD

**Issue by brettcannon** [python/pythondotorg#136]
The Twitter link says @ThePSF, but the Google+ link does not say +Python and the IRC links doesn't say something like [#python at irc.freenode.net]. Either we should either change @ThePSF to [Twitter] part of be consistent and change [Google+] to [+Python] and [IRC on irc.freenode.net] to [#python on irc.freenode.net].

**Comment by frankwiles** [comment]
Good catch, fixed.  Thanks!
