### ISSUE TITLE
hg.python.org uses an invalid certificate

### ISSUE THREAD

**Issue by darkfoxprime** [python/pythondotorg#1367]
**Describe the bug**
The release notes for python 2.7.13 and older are stored on `hg.python.org`.  That website forces the use of `https` and enables HTTP Strict Transport Security.  However, its certificate is for `pypa.org` and therefore compliant browsers will refuse to load the page.

**To Reproduce**
1. Go to 'https://www.python.org/downloads/
2. Click on the release notes for python `2.7.13`

**Screenshots**
<img width="1050" alt="image" src="https://user-images.githubusercontent.com/11813076/50130506-d368ec80-0232-11e9-9229-d3fa0caea000.png">

**Desktop (please complete the following information):**
 - OS: macOS High Sierra version 10.13.6
 - Browser Firefox
 - Version 60.3.0esr (64-bit)

**Comment by Mariatta** [comment]
Thank you for the report!

So I think the urls should be changed to GitHub, eg https://github.com/python/cpython/blob/2.7/Misc/NEWS.d/2.7.13rc1.rst for the release notes of 2.7.13

**Comment by benjaminp** [comment]
Cert is fixed now.
