### ISSUE TITLE
In latest news part lastest entry title is shown wrong

### ISSUE THREAD

**Issue by usta** [python/pythondotorg#1368]
**Describe the bug**
In latest news part lastest (2018-12-17) entry title is shown wrong.
Just now it looks like " p.p1 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px 'Helvetica Neue'; ... "
instead of that blog entry's title.

**To Reproduce**
1. Go to https://www.python.org/
2. Click on 'Nowhere'
3. Scroll down to 'Latest News part'

**Expected behavior**
Title must look like : " Evangelizing Python in Africa: Chukwudi Nwachukwu, Q2 CSA Recipient  "

**Screenshots**
![screenshot_2018-12-18 welcome to python org](https://user-images.githubusercontent.com/112882/50146346-305cb500-02bc-11e9-8e90-4dc4fc264a01.png)

**Desktop (please complete the following information):**
 - OS:  All of them
 - Browser All of them

**Comment by berkerpeksag** [comment]
This should be resolved by https://github.com/python/pythondotorg/commit/f27baa2987a43d24b9c70d5a3d0fd010fa6d856d. I've just deployed it to production.

Thank you for your report!
