### ISSUE TITLE
Python Core Mentorship link broken

### ISSUE THREAD

**Issue by parthsharma2** [python/pythondotorg#1369]
**Describe the bug**
The link to the Python Core Mentorship mailing list is broken. Clicking on the link results in a "Page not found error."

**To Reproduce**
1. Go to 'https://www.python.org/dev/core-mentorship/'
2. Click on 'The mailing list' under 'Resources'
3. See error

**Expected behavior**
The link should direct to the following page https://mail.python.org/mailman3/lists/core-mentorship.python.org/

**Screenshots**
![Screenshot GIF](https://i.imgur.com/mSdw5Sr.gif)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Browser: Chrome
 - Version: 71.0.3578.80

**Smartphone (please complete the following information):**
 - Device: iPhone 5S
 - OS: iOS 12.0
 - Browser: Safari

**Additional context**
Removing the trailing '/' in the link should fix the problem. I would like to work on this issue if possible.

**Comment by Mariatta** [comment]
This has been fixed. You can now click on the link and not get 404. Thanks
