### ISSUE TITLE
search finds 404

### ISSUE THREAD

**Issue by CarlFK** [python/pythondotorg#137]
search for pyvideo
see one result:
"""
2014-01-31 PSF Board Meeting Minutes
The Python Software Foundation Minutes of a Regular Meeting of the Board of Directors January 31, 2014 A regular meeting of the Python Software Foundation ("PSF") Board of Directors was held over Group Conference Call via phone and Internet Relay Chat beginning at 18:00 CET/ 12:00 EST, on ...
""""
click the link:
http://www.python.org/psf/records/board/minutes/2014-01-31

see 404

**Comment by frankwiles** [comment]
Not sure why it was 404ing in the first place, but is fixed now.
