### ISSUE TITLE
Menu bar is not displayed with Firefox on Windows

### ISSUE THREAD

**Issue by atsuoishimoto** [python/pythondotorg#1371]
**Describe the bug**

Menu of the top page(https://www.python.org) is not displayed with FireFox(64.0) on Windows.
Firefox on macOS looks good.

with Firefox:

![firefox](https://user-images.githubusercontent.com/1088786/50537231-8b39ba80-0ba0-11e9-9512-d68075bef71e.png)

with Chrome:

![with chrome](https://user-images.githubusercontent.com/1088786/50537238-98ef4000-0ba0-11e9-955e-75c6ad224b81.png)

**To Reproduce**
1. Go to 'https://www.python.org' with recent Firefox on Windows.

**Desktop (please complete the following information):**
 - Windows 10
 - Firefox 64.0

**Comment by berkerpeksag** [comment]
Yes, python.org renders fine with Firefox 66.0.2 (64-bit) on macOS. I don't have a Windows to test it at the moment.

**Comment by zooba** [comment]
I can repro this - @berkerpeksag what can I get or try for you to help out? (I'm 100% not a web dev)

**Comment by zooba** [comment]
If I disable the `left: -260px` property it looks like this:

![image](https://user-images.githubusercontent.com/1693688/55916038-08ad9780-5ba0-11e9-9c08-71b3cb3ba759.png)

**Comment by berkerpeksag** [comment]
Your screenshot is already helping me to understand what's wrong :) I think there's something wrong with our operating system/browser/device screen size detecting code because that navigation is for smaller screens.

Could you also check the value of `<html class="">` attribute? For me, it's set to:

```html
<html class="js no-touch geolocation fontface generatedcontent svg formvalidation placeholder boxsizing retina flexslide" lang="en" dir="ltr" style="">
```

Also, I know you're not a lawyer, but is it OK to use my MSDN subscription for Python core devs to set up a Windows environment for python.org development?

**Comment by zooba** [comment]
Mine is:

```
js touch geolocation fontface generatedcontent svg formvalidation placeholder boxsizing retina flexslide
```

If I change `touch` to `no-touch` then it renders fine. Edge already has `no-touch` there, and changing it to `touch` breaks it in the same way.

And yeah, go right ahead using the MSDN subscription for that. It'd only get problematic if you were using it for commercial purposes.

**Comment by berkerpeksag** [comment]
Thanks! Our feature detection code is broken. I will fix it tomorrow.

**Comment by berkerpeksag** [comment]
Can you type `Modernizr.touch;` to the devtools' console? If it returns `true` then Modernizr is outdated.

**Comment by zooba** [comment]
Indeed:
![image](https://user-images.githubusercontent.com/1693688/55968393-c1231c00-5c30-11e9-8b1e-1e6ddec35d0d.png)

**Comment by berkerpeksag** [comment]
Thanks! This should normally return `false`:

```js
'ontouchstart' in window || window.navigator.msPointerEnabled || 'ontouchstart' in document.documentElement
```

**Comment by zooba** [comment]
Both `ontouchstart` conditions are true (though the values are null, but I think that's expected?)

It's odd that Edge doesn't have this on my machine, which definitely has a touch screen. Maybe there's an "opt-in to latest Edge APIs" header/meta tag missing?

**Comment by berkerpeksag** [comment]
This looks like a great mess and apparently Modernizr is planning to remove this feature checking feature in the future. I will have to do more research on this.

**Comment by berkerpeksag** [comment]
I guess this is the most reliable way to detect touch devices.

```js
"matchMedia" in window && window.matchMedia("(any-pointer: coarse)").matches
```

Unfortunately, it won't work with older browsers. I'll check python.org browser statistics.

**Comment by zooba** [comment]
It returns `true` for both Firefox and Edge for me. Is that expected?

Presumably the idea is to use a different layout with no hover effects on a touch-only device, yes? Maybe there's a different idea here about handling touch-clicks different from mouse-clicks/hovers?

**Comment by berkerpeksag** [comment]
> Presumably the idea is to use a different layout with no hover effects on a touch-only device, yes?

Correct and the problem is most of the layout code is relying on `.touch` and `.no-touch` classes. I will try to rewrite at least main navigation code to rely on media queries.

**Comment by rozeappletree** [comment]
Shouldn't this issue be closed as the "menu" itself is removed from website??

**Comment by zooba** [comment]
This seems to be fine on my machine now.
