### ISSUE TITLE
python 2.7 downloads page recommends 2.7.13 release while 2.7.15 is available

### ISSUE THREAD

**Issue by tirkarthi** [python/pythondotorg#1373]
**Describe the bug**

python 2.7 [downloads](https://www.python.org/download/releases/2.7/) page points to python 2.7.13 as recommended bug fix release but python 2.7.15 is available

**Expected behavior**

It should recommend [2.7.15](https://www.python.org/downloads/release/python-2715/) and the last bug fix release in 2019 once it's released.

**Screenshots**

![screen shot 2019-01-06 at 10 43 32 am](https://user-images.githubusercontent.com/3972343/50732379-fe928c00-119f-11e9-9437-d62b20ed34bc.png)

**Comment by berkerpeksag** [comment]
Done. Updated the content to point to 2.7.16. Thank you for your report!
