### ISSUE TITLE
Bad Link (Error 522) to Anaconda Python on Alternative Python Implementations Page

### ISSUE THREAD

**Issue by cameronsr** [python/pythondotorg#1374]
Description:
At Alternative Python Implementations (https://www.python.org/download/alternatives/), clicking the link to Anaconda Python (https://store.continuum.io/cshop/anaconda) resolves to an Error 522 (Connection Timed Out) reported from Cloudflare.

Resolution:
Recommend updating the Anaconda Python link at Alternative Python Implementations (https://www.python.org/download/alternatives/) to point to the Download Anaconda Distribution landing page (https://www.anaconda.com/download/).

**Comment by berkerpeksag** [comment]
Done. Thank you for your report!
