### ISSUE TITLE
Interactive (IPython) console help shout start with help on help

### ISSUE THREAD

**Issue by holdenweb** [python/pythondotorg#138]
This is probably an upstream for IPython, but in the context of the python.org home page, where anyone can trigger an interactive console, entering "?" as your first command (as the help command suggests) you are then faced with a page of information with a ":" prompt at the bottom. WE all know the conventions, and happily hit space bar or q, but a complete beginner might have to stab about a bit.

**Comment by fcurella** [comment]
labeled this as 'frontend' instead of 'backend' because there's no changes to the python code involved

**Comment by holdenweb** [comment]
In which case this is best dealt with by the IPython team, where I will address it further. Closing this issue - thanks.
