### ISSUE TITLE
possible grammar problem on PEP8 page

### ISSUE THREAD

**Issue by carmella-smith** [python/pythondotorg#1387]
In the section here:
https://www.python.org/dev/peps/pep-0008/#descriptive-naming-styles
it says:
_single_leading_underscore: weak "internal use" indicator. E.g. from M import * does not import objects whose name starts with an underscore.
I would change it to:
_single_leading_underscore: weak "internal use" indicator. E.g. from M import * does not import objects whose names start with an underscore.

**Comment by Mariatta** [comment]
Thank you. I think this issue is better raised at the PEPs repo at https://github.com/python/peps
Would you mind opening the issue there? Thanks.

**Comment by gvanrossum** [comment]
Please close now.

**Comment by carmella-smith** [comment]
Looks good; thanks for fixing.
