### ISSUE TITLE
Broken link on PEP 3104 page

### ISSUE THREAD

**Issue by jraman** [python/pythondotorg#1388]
**Describe the bug**
The following reference link on the [PEP 3104](https://www.python.org/dev/peps/pep-3104/) page is broken:
 http://www.python.org/search/hypermail/python-1994q1/0301.html

**To Reproduce**
1. Go to https://www.python.org/dev/peps/pep-3104/
2. Click on the link in the first reference.  The link is: http://www.python.org/search/hypermail/python-1994q1/0301.html
3. The following error is seen: Error 404: File not Found

**Expected behavior**
Expected to go to a page such as [this one](ftp://ftp.ntua.gr/mirror/python/search/hypermail/python-1994q1/0301.html) and not see the 404 error.

**Desktop (please complete the following information):**
 - OS: Mac OS 10.13.6
 - Browser: Chrome
 - Version: 71.0.3578.98

**Comment by Mariatta** [comment]
Thank you. This issue is better raised at the PEPs repo at https://github.com/python/peps
Would you mind opening the issue there? Thanks.

**Comment by jraman** [comment]
Done.  https://github.com/python/peps/issues/897

**Comment by Mariatta** [comment]
Thanks.
