### ISSUE TITLE
PEP 3119 Typo

### ISSUE THREAD

**Issue by johnsonb2** [python/pythondotorg#1393]
[Link](https://www.python.org/dev/peps/pep-3119/#overloading-isinstance-and-issubclass)
"During the development of this PEP and of its companion, PEP 3141, we repeatedly faced the choice between standardizing more, fine-grained ABCs or fewer, **course-grained** ones."
Change to:
**coarse-grained**

**Comment by Mariatta** [comment]
Thanks for the report. Would you mind opening the issue in the PEPs repo, where the text comes from?
https://github.com/python/peps 
It can be fixed there.

Thanks.

**Comment by Mariatta** [comment]
I saw you opened python/peps#912. Closing this. Thanks.

**Comment by DanteFerro3** [comment]
I like Turtles.
