### ISSUE TITLE
PEP source link regression

### ISSUE THREAD

**Issue by uranusjr** [python/pythondotorg#1394]
**Describe the bug**

See #1195. The links are now pointing back to .txt again.

Example: https://www.python.org/dev/peps/pep-8016/#id24

**To Reproduce**
1. Go to https://www.python.org/dev/peps/pep-8016/#id24
2. Click on the source link
3. GitHub responses with 404

**Expected behavior**
The link should point to the correct source.

**Comment by Mariatta** [comment]
I confirmed this is broken for all .rst-based PEPs. @berkerpeksag will you be able to look into this?
Thanks.

**Comment by berkerpeksag** [comment]
Thank you for the report!

This might be the result of https://github.com/python/pythondotorg/commit/e9cfa6bded1af0a97f4200354bb79921760556a7. I will check it out later this month (moving to a new country next week, so I won't be able to take a look at this for a while)

**Comment by mozillazg** [comment]
I opened a PR for fix this issue: https://github.com/python/peps/pull/982
