### ISSUE TITLE
'504 Gateway Time-out' when trying to create a new Python Wiki account

### ISSUE THREAD

**Issue by be-we** [python/pythondotorg#1399]
I wanted to create a new profile for myself on [Python Wiki](https://wiki.python.org/moin/PythonWebsite?action=newaccount), but it was always acknowledged with error **504 Gateway Time-out**.

**Comment by mwichmann** [comment]
I know it doesn't help, but it's a "known problem"; the vm that runs that system is underpowered and apparently is under frequent attack, limiting its ability to respond.  Don't know the status of possible improvements. Meanwhile the unofficial suggestion is just to keep trying periodically.

**Comment by berkerpeksag** [comment]
@mwichmann is right. I'm closing this for now, but please reach out to us in case you still get 504. Also pinging @malemburg since he's the one who usually restarts wiki.p.o VM.

**Comment by malemburg** [comment]
Indeed, there's nothing much we can do at this point, except perhaps get a more powerful VM with better I/O.
