### ISSUE TITLE
Update IBM i on the "Python for other platforms" page

### ISSUE THREAD

**Issue by csabella** [python/pythondotorg#1401]
This would be an update for #1072.   According to the link in this section, 5733OPS is deprecated in favor of RPM/yum and the current versions are up to date releases.

@ThePrez and @jkyeung, would you like to provide new wording?  Maybe don't mention a specific Python release, but mention the RPM/yum page?

Thanks!

**Comment by jkyeung** [comment]
I don't have time to come up with exact wording at the moment, but I wanted to at least express full agreement that we should update the IBM i entry to reflect that the RPM-based installation is the preferred and standard way to get Python on the platform.

**Comment by berkerpeksag** [comment]
Let me know when you have a suggested wording and I can update content of the page. Thank you!

**Comment by ThePrez** [comment]
Here's my suggested wording (please note the removal of "System i" also). Thanks!! (@jkyeung, how does this look?) 

**Python for IBM i (formerly AS/400, iSeries)**
Both Python 2 and Python 3 are available from IBM in RPM form. They can be installed with the 'yum' package manager or with the IBM i Access Client Solutions product. To get started with RPM-based open source packages for IBM i, visit http://ibm.biz/ibmi-rpms

These RPM packages require a version of IBM i in active (not extended) support. Alternatively, http://www.iseriespython.com hosts an IBM i port of Python 2.7, ported by Per Gummedal, which can also be run on older versions of the operating system.

**Comment by jkyeung** [comment]
Looks good to me!

**Comment by berkerpeksag** [comment]
Done: https://www.python.org/download/other/

Thank you, @ThePrez.
