### ISSUE TITLE
Install.rst has an incorrect step

### ISSUE THREAD

**Issue by eamanu** [python/pythondotorg#1402]
**Describe the bug**
On https://github.com/python/pythondotorg/blob/master/docs/source/install.rst
one of the step is activate the virtual environment (sound how the venv is created)
but venv don't exist.

**To Reproduce**
1. Go to `https://github.com/python/pythondotorg/blob/master/docs/source/install.rst`
2. Read and run:
```
# Go to the pythondotorg/ directory and activate the virtual environment.
$ cd ~/pythondotorg
$ . venv/bin/activate
```
3. See venv does not exist:
![image](https://user-images.githubusercontent.com/7605307/55282665-a9da5980-5327-11e9-8bd8-0b9f96f247cb.png)

**Comment by berkerpeksag** [comment]
Thank you for the report! This is weird. I can see `venv` in my setup:

```sh
vagrant@vagrant:~/pythondotorg$ ls | grep venv
venv
```

Do you have some logs from the provisioning step?

**Comment by berkerpeksag** [comment]
Just to make sure, I've started a fresh clone (without `venv` directory etc.) and it worked for me. It would be helpful if we know what versions of Vagrant and Ansible are installed on your machine and see logs of `vagrant up` (or `vagrant provision`) command.

**Comment by berkerpeksag** [comment]
By the way, I've made some tweaks to installation instructions (https://github.com/python/pythondotorg/commit/e12cdbf9cfa6caead9f4f2535dd9a09f0d30442a) and fixed a bug (https://github.com/python/pythondotorg/commit/34119ad27e29f785918bcbfb9422c510502d2125) that may annoy or confuse new contributors.

**Comment by eamanu** [comment]
Hello, 

Sorry for the delay of my response.

My versions are:

```
Vagrant 2.2.4
ansible 2.7.9
```
I am new on the use of vagrant, the ```vagrant provision``` run automatically?

Despite this,  when I run ```vagrant provision``` I have this error:

```
TASK [Install dependencies for the Django app inside virtual environment] ****** 
fatal: [default]: FAILED! => {"changed": false, "msg": "No setuptools found in remote host, please install it first."}
```

**Comment by eamanu** [comment]
The solution was set the vars `ansible_python_interpreter: "/usr/bin/python3"` I wil make the PR adding this vars.

I suppose that ansible check if setuptools exist for default python interpreter, and in this case (for me) python2 is default, and python2-setuptools was not installed. By the way, I think that this is an ansible bug, because the check (setuptool installed) must be with the "virtualenv_command" interpreter used

**Comment by berkerpeksag** [comment]
> I am new on the use of vagrant, the `vagrant provision` run automatically?

IIRC, it should run `vagrant provision` automatically or warn if you ran `vagrant up` the first time.

Can you paste the output of `vagrant box list`? Ubuntu 18.04 comes with Python 3.6, so I don't understand how did you end up with Python 2 as system Python.

**Comment by eamanu** [comment]
Hello, 

The output of ```vagrant box list``` is:

> bento/ubuntu-18.04 (virtualbox, 201812.27.0)

For default I have ```python2.7```:

```
vagrant@vagrant:~$ python
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

**Comment by eamanu** [comment]
I run `vagrant destroy`

And then:

eamanu@debianPC:~/dev/pythondotorg$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'bento/ubuntu-18.04'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'bento/ubuntu-18.04' version '201812.27.0' is up to date...
==> default: Setting the name of the VM: pythondotorg_default_1554596247734_12439
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 8000 (guest) => 8001 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default: 
    default: Guest Additions Version: 5.2.22
    default: VirtualBox Version: 6.0
==> default: Mounting shared folders...
    default: /home/vagrant/pythondotorg => /home/eamanu/dev/pythondotorg
==> default: Running provisioner: ansible...
    default: Running ansible-playbook...

PLAY [Create a pythondotorg VM via Vagrant] ************************************

TASK [Gathering Facts] *********************************************************
ok: [default]

TASK [Run apt-get update] ******************************************************
changed: [default]

TASK [Install base packages] ***************************************************
[DEPRECATION WARNING]: Invoking "apt" only once while using a loop via 
squash_actions is deprecated. Instead of using a loop to supply multiple items 
and specifying `name: "{{ item }}"`, please use `name: ['build-essential', 
'libpq-dev', 'lib32z1-dev', 'git', 'python3-dev', 'python3-setuptools', 
'python3-pip', 'python3-venv', 'ruby']` and remove the loop. This feature will 
be removed in version 2.11. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
changed: [default] => (item=[u'build-essential', u'libpq-dev', u'lib32z1-dev', u'git', u'python3-dev', u'python3-setuptools', u'python3-pip', u'python3-venv', u'ruby'])                                                                                                                            

TASK [Install base Ruby packages] **********************************************
changed: [default]

TASK [Install PostgreSQL] ******************************************************
[DEPRECATION WARNING]: Invoking "apt" only once while using a loop via 
squash_actions is deprecated. Instead of using a loop to supply multiple items 
and specifying `name: "{{ item }}"`, please use `name: ['postgresql', 
'postgresql-contrib', 'libpq-dev', 'python-psycopg2']` and remove the loop. 
This feature will be removed in version 2.11. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg.
changed: [default] => (item=[u'postgresql', u'postgresql-contrib', u'libpq-dev', u'python-psycopg2'])
[DEPRECATION WARNING]: State 'installed' is deprecated. Using state 'present' 
instead.. This feature will be removed in version 2.9. Deprecation warnings can
 be disabled by setting deprecation_warnings=False in ansible.cfg.

TASK [Ensure the PostgreSQL service is running] ********************************
ok: [default]

TASK [Ensure database is created] **********************************************
changed: [default]

TASK [Ensure user has access to the database] **********************************
changed: [default]

TASK [Ensure python/pythondotorg is cloned] ************************************
ok: [default]

TASK [Install dependencies for the Django app inside virtual environment] ******
ok: [default]

TASK [Install packages required by Gemfile] ************************************
changed: [default]

TASK [Apply database migrations] ***********************************************
changed: [default]

TASK [Create a superuser for Django admin] *************************************
changed: [default]

RUNNING HANDLER [Restart PostgreSQL] *******************************************
changed: [default]

PLAY RECAP *********************************************************************
default                    : ok=14   changed=10   unreachable=0    failed=0   

eamanu@debianPC:~/dev/pythondotorg$ vagrant ssh
Welcome to Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-29-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Sun Apr  7 00:28:19 UTC 2019

  System load:  0.07              Processes:           99
  Usage of /:   3.2% of 61.80GB   Users logged in:     0
  Memory usage: 9%                IP address for eth0: 10.0.2.15
  Swap usage:   0%


124 packages can be updated.
63 updates are security updates.


Last login: Sun Apr  7 00:25:48 2019 from 10.0.2.2
vagrant@vagrant:~$ python
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by berkerpeksag** [comment]
Can you check whether you have `python3` installed when you are inside Vagrant? Also, what's the output of `python -V` inside the virtual environment?

**Comment by eamanu** [comment]
> Can you check whether you have |python3| installed when you are inside
> Vagrant? Also, what's the output of |python -V| inside the virtual
> environment?
>
Sure,

```
vagrant@vagrant:~$ python -V
Python 2.7.15rc1
```

And yes, I have installed python3:

```
vagrant@vagrant:~$ python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

:/

**Comment by berkerpeksag** [comment]
Thanks! Can you activate the virtual environment inside Vagrant and share output of the following commands?

```sh
$ vagrant ssh
$ cd pythondotorg
$ . venv/bin/activate/
$ python -V
$ which python
$ python3 -V
$ which python3
```

**Comment by eamanu** [comment]
Yes!
vagrant@vagrant:~$ cd pythondotorg/
vagrant@vagrant:~/pythondotorg$ . venv/bin/activate
(venv) vagrant@vagrant:~/pythondotorg$ python -V
Python 3.6.7
(venv) vagrant@vagrant:~/pythondotorg$ which python
/home/vagrant/pythondotorg/venv/bin/python
(venv) vagrant@vagrant:~/pythondotorg$ python3 -V
Python 3.6.7
(venv) vagrant@vagrant:~/pythondotorg$ which python3
/home/vagrant/pythondotorg/venv/bin/python3


But if I don't activate the environment I have:

vagrant@vagrant:~$ python -V
Python 2.7.15rc1
vagrant@vagrant:~$ which python
/usr/bin/python


Can vagrant take the host python interpreter for default?

**Comment by berkerpeksag** [comment]
I think it's possible, but since we always activate virtual environment that might be unnecessary. Removing virtual environment creation and use the Vagrant box as a container might be good, I don't know.

So your setup looks correct  to me (sorry, I was confused system Python with virtual environment Python and said you shouldn't have Python 2 installed earlier) Do you still need PR #1405?

**Comment by eamanu** [comment]
If I run ```vagrant provision````without ansible_python_interpreter variable I have the error even I have the `venv` created:

eamanu@debianPC:~/dev/pythondotorg$ vagrant provision
==> default: Running provisioner: ansible...
    default: Running ansible-playbook...

PLAY [Create a pythondotorg VM via Vagrant] ************************************

TASK [Gathering Facts] *********************************************************
ok: [default]

TASK [Run apt-get update] ******************************************************
changed: [default]

TASK [Install base packages] ***************************************************
[DEPRECATION WARNING]: Invoking "apt" only once while using a loop via 
squash_actions is deprecated. Instead of using a loop to supply multiple items 
and specifying `name: "{{ item }}"`, please use `name: ['build-essential', 
'libpq-dev', 'lib32z1-dev', 'git', 'python3-dev', 'python3-setuptools', 
'python3-pip', 'python3-venv', 'ruby']` and remove the loop. This feature will 
be removed in version 2.11. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
ok: [default] => (item=[u'build-essential', u'libpq-dev', u'lib32z1-dev', u'git', u'python3-dev', u'python3-setuptools', u'python3-pip', u'python3-venv', u'ruby'])

TASK [Install base Ruby packages] **********************************************
ok: [default]

TASK [Install PostgreSQL] ******************************************************
[DEPRECATION WARNING]: Invoking "apt" only once while using a loop via 
squash_actions is deprecated. Instead of using a loop to supply multiple items 
and specifying `name: "{{ item }}"`, please use `name: ['postgresql', 
'postgresql-contrib', 'libpq-dev', 'python-psycopg2']` and remove the loop. 
This feature will be removed in version 2.11. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg.
ok: [default] => (item=[u'postgresql', u'postgresql-contrib', u'libpq-dev', u'python-psycopg2'])

TASK [Ensure the PostgreSQL service is running] ********************************
ok: [default]

TASK [Ensure database is created] **********************************************
ok: [default]

TASK [Ensure user has access to the database] **********************************
ok: [default]

TASK [Ensure python/pythondotorg is cloned] ************************************
ok: [default]

TASK [Install dependencies for the Django app inside virtual environment] ******
fatal: [default]: FAILED! => {"changed": false, "msg": "No setuptools found in remote host, please install it first."}
        to retry, use: --limit @/home/eamanu/dev/pythondotorg/provisioning/pythondotorg.retry

PLAY RECAP *********************************************************************
default                    : ok=9    changed=1    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

If I add the ```ansible_python_interpreter``` the provision run successfully. 

> So your setup looks correct to me (sorry, I was confused system Python with virtual environment Python and said you shouldn't have Python 2 installed earlier) Do you still need PR #1405?

If the error is not reproducible, IMO the PR must be closed until somebody has the same error. 
I will clean my ```pythondotorg/```and  I will clone and try again.

**Comment by berkerpeksag** [comment]
```
fatal: [default]: FAILED! => {"changed": false, "msg": "No setuptools found in remote host, please install it first."}
```

How did you install Ansible? If I'm reading https://github.com/ansible/ansible/issues/47361 and https://github.com/ansible/ansible/pull/47743 (better exception message) correctly, setuptools needs to be installed in the  same Python you've installed Ansible on your computer (not in Vagrant box or virtual environment in Vagrant box)

You have two more options:

1. Downgrade your Ansible to 2.6.x
2. Upgrade your Ansible to 2.8.0a1 (which it contains a much better exception message to this problem: https://github.com/ansible/ansible/commit/73141d503517aac97f3570d60bea6ffdf955e519)

**Comment by eamanu** [comment]
I installed ansible using the documentation:

https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html?extIdCarryOver=true&sc_cid=701f2000001OH6uAAG#latest-releases-via-apt-debian

But, this was installed using a ```python version: 2.7``` (probably because my host use it)

Then, I install ansible using pip3:

```
eamanu@debianPC:~/dev/pythondotorg$ ansible --version
ansible 2.7.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/eamanu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.5/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.5.3 (default, Sep 27 2018, 17:25:39) [GCC 6.3.0 20170516]
```
But I have the same problem:

```
TASK [Install dependencies for the Django app inside virtual environment] ******
fatal: [default]: FAILED! => {"changed": false, "msg": "No setuptools found in remote host, please install it first."}
        to retry, use: --limit @/home/eamanu/dev/pythondotorg/provisioning/pythondotorg.retry

PLAY RECAP *********************************************************************
default                    : ok=9    changed=1    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

I will try to upgrade to ansible v2.8.0a1

**Comment by berkerpeksag** [comment]
Thanks! This confirms why you needed https://github.com/python/pythondotorg/pull/1405 to set up dev environment. It worked with the `pip3` one because pip installs setuptools by default. Please uninstall both Ansibles first, install Ansible and setuptools (`python-setuptools`) from your package manager.

Sorry for the trouble! This is really Ansible's fault. Tools like that should be way more stable.

I'm closing this for now. Feel free to comment if you found anything new.

**Comment by eamanu** [comment]
Thanks!
