### ISSUE TITLE
Title of the Latest News is wrong

### ISSUE THREAD

**Issue by eMUQI** [python/pythondotorg#1403]
**Describe the bug**
![image](https://user-images.githubusercontent.com/32332228/55475639-0d75c700-5647-11e9-9087-0d348d5dd96e.png)
**To Reproduce**
1. Go to 'https://www.python.org/'
2. Scroll down to 'Latest News'
3. See error
![image](https://user-images.githubusercontent.com/32332228/55475712-40b85600-5647-11e9-8d4d-50e663cb2b1a.png)

**Expected behavior**
A correct title

**Desktop (please complete the following information):**
 - OS: [manjaro]
 - Browser [chromium]
 - Version [73.0.3683.86]

**Comment by berkerpeksag** [comment]
Good catch and thank you for the report! I've fixed this and I will deploy it to production once I verified my fix at staging.python.org.
