### ISSUE TITLE
I'd like to update the IRC page

### ISSUE THREAD

**Issue by nedbat** [python/pythondotorg#1406]
**Describe the bug**
The current text has "For short questions, you can get immediate help by visiting the #python channel."

**Expected behavior**
I would rather it said, "The #python channel is for all discussion about the Python language, ecosystem, and community.  You can get immediate help with programming questions."

**Comment by berkerpeksag** [comment]
Done: https://www.python.org/community/irc/

Thank you for your report and suggested wording!
