### ISSUE TITLE
Remove link to Google+

### ISSUE THREAD

**Issue by logonoff** [python/pythondotorg#1407]
**Describe the bug**
As Google+ doesn't exist anymore, the link to it under 'Socialize' should be removed.

**To Reproduce**
1. Go to 'Socialize'
2. Click on 'Google+'
3. See error

**Expected behavior**
The link shouldn't exist as the social media platform doesn't exist anymore.

**Screenshots**
![A cursor hovering over a link to Python's Google+ Page](https://i.imgur.com/KuskxYH.png)

**Comment by berkerpeksag** [comment]
Thank you for the report!
