### ISSUE TITLE
Python windows download page missing css

### ISSUE THREAD

**Issue by Alboin** [python/pythondotorg#1423]
**Describe the bug**
There seems to be some missing css for the windows download page. There is also a message about javascript at the top of the page (see attached screenshot). Tried in Chrome, Firefox, Edge and on my phone, all giving the same result.

**To Reproduce**
1. Go to https://www.python.org/downloads/windows/

**Expected behavior**
Expected it to look something like this:
https://www.python.org/downloads/

**Screenshots**
![image](https://user-images.githubusercontent.com/8807821/56116172-77ef0700-5f65-11e9-96e0-5b535a907498.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 73.0.3683.103 64-bit

**Smartphone (please complete the following information):**
 - Device: Nexus 5x

**Comment by berkerpeksag** [comment]
Thank you! I've just invalidated Fastly cache. This is basically the same issue as #1420.

https://www.python.org/downloads/source/ and https://www.python.org/downloads/mac-osx/ fixed as well.
