### ISSUE TITLE
Wrong text alongside drop down menu on PSF landing page

### ISSUE THREAD

**Issue by geoffbacon** [python/pythondotorg#1429]
**Describe the bug**
On the PSF landing page, when I hover over the "About" menu, alongside the drop down menu options of "Executive Summary", "Mission Statement", etc. I see the same text that is shown when I hover over the "About" menu on the main python.org page. The text is a generic statement about Python, not about the PSF, and thus seems out of place to me.

**To Reproduce**
1. Go to https://www.python.org/psf-landing/
2. Hover your mouse over "About"
3. Look at the text box that appears to the right of the drop down menu.
4. Notice that the text isn't really about the PSF.

**Expected behavior**
I would have expected either no text box here (like the other options on the PSF menu), or a general statement describing the PSF.

**Screenshots**
<img width="1398" alt="Screen Shot 2019-04-22 at 9 44 39 PM" src="https://user-images.githubusercontent.com/11916848/56555352-859a2300-6549-11e9-8c5e-4eb6485b6a41.png">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome
 - Version: 73

**Comment by berkerpeksag** [comment]
Thank you for the report! I think we can remove the supernav from About navigation. What do you think @ewdurbin and @ejodlowska?

**Comment by eamanu** [comment]
Hi @berkerpeksag Do you say about remove the supernav on whole About navs? or just on PSF page?
