### ISSUE TITLE
Edu sig link broken on Computer Programming for Everybody essay

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [python/pythondotorg#1430]
**Describe the bug**
Edu sig link broken on Computer Programming for Everybody essay

**To Reproduce**
click on edu-sig on "however; this is generally discussed in the EDU-SIG mailing list." [here](https://www.python.org/doc/essays/cp4e/)

**Comment by berkerpeksag** [comment]
Good catch, fixed! Thank you for the report.

**Comment by Abdur-rahmaanJ** [comment]
btw @berkerpeksag how to pr a fix for this example?

**Comment by berkerpeksag** [comment]
The content in question is stored in the CMS, not in the code, so you can't fix it by submitting a PR.

**Comment by Abdur-rahmaanJ** [comment]
@berkerpeksag actually Mr. Guido told me to open the issue, was wondering if we could PR. Thanks for info!
