### ISSUE TITLE
[very minor] incorrect casing in release doc

### ISSUE THREAD

**Issue by mdamien** [python/pythondotorg#1431]
**Describe the bug**
In the [latest release page](https://www.python.org/downloads/release/python-373/), there's a typo: "batteries-included versions **oF** Tcl/Tk 8.6"

**Expected behavior**
It should be "batteries-included versions **of** Tcl/Tk 8.6"

**Comment by berkerpeksag** [comment]
Good catch, fixed! Thank you for the report.
