### ISSUE TITLE
vagrant up fails due to dependency

### ISSUE THREAD

**Issue by scottilee** [python/pythondotorg#1437]
**Describe the bug**
Running `vagrant up` produces an ImportError about pkg_resources.

**To Reproduce**
1. Clone repository
2. Execute `vagrant up`
3. See error

**Expected behavior**
There should be no errors.

**Screenshots**
No screenshot but here is the error output:
```
TASK [Install dependencies for the Django app inside virtual environment] ******
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named pkg_resources
fatal: [default]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (setuptools) on vagrant's Python /usr/bin/python. Please read module documentation and install in the appropriate location"}

PLAY RECAP *********************************************************************
default                    : ok=10   changed=2    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again
```

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 10.13 High Sierra

**Additional context**
Adding `python-setuptools` to the "Create a {{ project.name }} VM via Vagrant" task of `provisioning/pythondotorg.yml` fixes the issue

**Comment by eamanu** [comment]
I believe that this issue is related to https://github.com/python/pythondotorg/issues/1402

Please see this message: https://github.com/python/pythondotorg/issues/1402#issuecomment-482464564

**Comment by scottilee** [comment]
@eamanu So I have to install `python-setuptools` locally before running `vagrant up`? If that's correct it should be added to the docs right?

**Comment by berkerpeksag** [comment]
Thank you for the report! How did you install Ansible? If you have working pip on your system, you should also have setuptools.

**Comment by eamanu** [comment]
If you see on line 22 ```python3-setuptools``` is installed. 

Like say in https://github.com/python/pythondotorg/issues/1402#issuecomment-482464564 , this seems to be a ansible's fault because 
(apparently) that take your host machine pip version.

**Comment by eamanu** [comment]
I was makig this PR, maybe that line help you @scottilee https://github.com/python/pythondotorg/pull/1405/files

**Comment by scottilee** [comment]
@berkerpeksag Ansible was installed using pipenv: `pipenv install ansible`

Here's some additional information (from within `pipenv shell`):
```
$ python -V
Python 3.7.2

$ vagrant version
Installed Version: 2.2.3

$ ansible --version
ansible 2.8.0
```

**Comment by berkerpeksag** [comment]
I don't use pipenv, so I can't help with debugging your problem :( Is there a command similar to `pip freeze` to check whether a module is already installed?

**Comment by eamanu** [comment]
@scottilee and your ```pip  --version```?

**Comment by scottilee** [comment]
@eamanu $ pip --version
pip 19.1.1 (python 3.7)

**Comment by eamanu** [comment]
mmm that is weird. Could you tell me what python version is linked to "python" on /usr/bin/ path?

I am not ansible expert, but  I suppose that ansible search the "python" on /usr/bin/. Making a quickly search on ansible code I found this:

https://github.com/ansible/ansible/blob/c8c326d88e10d6d0f9ea46824bdcd5305f5412da/lib/ansible/executor/interpreter_discovery.py#L115

**Comment by eamanu** [comment]
If you have a python2.7 linked to /usr/bin/python the pythondotorg ansible script will fail (IMO)
