### ISSUE TITLE
Remove Vagrant installation option

### ISSUE THREAD

**Issue by scottilee** [python/pythondotorg#1441]
**Is your feature request related to a problem? Please describe.**
The [docs](https://pythondotorg.readthedocs.io/install.html) specify installation of Vagrant 2.0+ although the `Vagrantfile` lists 1.7.0 as the minimum version

**Describe the solution you'd like**
The line `Vagrant.require_version ">= 1.7.0"` in the `Vagrantfile` should be changed to a more recent version like 2.2.4.

**Describe alternatives you've considered**
Although the `Vagrantfile` works as-is, for security and bug fixes this change should be considered.

**Comment by berkerpeksag** [comment]
I prefer removing the Vagrant setup once we merge #1440. Docker seems to be way more popular than our current choice of tooling and it would be better if we maintain one solution for setting up the development environment.

**Comment by berkerpeksag** [comment]
I've just retitled the issue.

**Comment by scottilee** [comment]
I'll include this with #1440.
