### ISSUE TITLE
links to showmedo are not working

### ISSUE THREAD

**Issue by beefsalad** [python/pythondotorg#1442]
**Describe the bug**
The website is showing links to www.showmedo.com, which appears to no longer be active (www has no A/AAAA records associated, non-www site returns unavailable)

**To Reproduce**
1. Go to https://www.python.org/doc/av/5minutes'
2. Click on any URL referencing showmedo

**Expected behavior**
Land on the showmedo page for the videos

Not a device dependent issue.
$ wget www.showmedo.com
--2019-05-27 15:56:42--  http://www.showmedo.com/
Resolving www.showmedo.com... failed: Name or service not known.
wget: unable to resolve host address “www.showmedo.com”

$ wget showmedo.com
--2019-05-27 15:59:41--  http://showmedo.com/
Resolving showmedo.com... 178.62.12.119
Connecting to showmedo.com|178.62.12.119|:80... connected.
HTTP request sent, awaiting response... 503 Service Unavailable
2019-05-27 15:59:41 ERROR 503: Service Unavailable.

Checking the internet archive, it would appear that showmedo may be unavailable on a regular (and extended) basis.  Last checking from archive.org was May 15th and the website was up, however previous checks (2 in February, 2 in March) show that the site was unavailable.  I held off submitting this issue for 24 hours to see if the website would come back, but it has not.

**Comment by ned-deily** [comment]
Perhaps we should just delete this page?

**Comment by berkerpeksag** [comment]
I've just unpublished it. Thanks for the report!
