### ISSUE TITLE
Board nomination statements aren’t rerendered on editing

### ISSUE THREAD

**Issue by jezdez** [python/pythondotorg#1444]
**Describe the bug**
I tried editing the board nomination statement and it seems to store the changes to the markdown but it doesn’t render the changes on the nomination detail page.

**To Reproduce**
1. Create a board nomination
2. Edit nomination statement with change in Markdown code
3. See change not reflected in rendered version of statement

**Expected behavior**
Rerendering the Markdown on save.

**Screenshots**
Nomination 32

**Desktop (please complete the following information):**
 - OS: iOS 12 on iPad Pro
 - Browser: Safari
 - Version: latest

**Comment by brainwane** [comment]
What I just found is that, if I log out after making my edit (or view the page in a non-logged-in browser), the rendered page reflects the updates. (I was updating different pages but the same behavior was happening to me.)

**Comment by jezdez** [comment]
Gotcha, sounds like a simple cache invalidation bug (simple haha)?

**Comment by jezdez** [comment]
Ah I see, this is probably Fastly in front of the site caching the page, since it serves a `Vary` header with `Cookie`.

I've opened https://github.com/python/pythondotorg/pull/1497 which uses the `purge_url` utility to purge the CDN page for the nomination detail page, the nomination list and the nominee detail page (since all contain the rendered snippet).
