### ISSUE TITLE
Python Downloads page renders broken

### ISSUE THREAD

**Issue by dcrosta** [python/pythondotorg#1448]
**Describe the bug**
Visiting the downloads page on python.org in Firefox, Chrome, and Safari results in a broken render.

The network inspector in the screenshot below probably shows what's going wrong -- looks like a stylesheet is 404ing.

**To Reproduce**
1. Go to https://www.python.org/downloads/

**Expected behavior**
The page should render with a look & feel similar to the rest of python.org

**Screenshots**

<img width="1552" alt="Screen Shot 2019-06-02 at 9 18 35 PM" src="https://user-images.githubusercontent.com/35122/58770266-0e11d780-857c-11e9-89d1-31276f7cc507.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.14.5
 - Browser Firefox 66.0.5, Chrome 74.0.3729.169, Safari 12.1.1

**Comment by berkerpeksag** [comment]
Thanks, I've purged cache. It should be OK now. See #1426 for more details.

**Comment by dogweather** [comment]
Broken for me, I requested the page 5 minutes ago.

**Comment by dogweather** [comment]
FYI, I'm an SRE and do web transaction monitoring. Can I help out with a monitor that'll show if it's fixed or not?
