### ISSUE TITLE
Control Flow widget typo

### ISSUE THREAD

**Issue by annaraven** [python/pythondotorg#145]
All the Flow You’d Expect
Python knows the usual control flow statements that other languages speak — if, for, while and range — with some of it own twists, of course. 

s/it own twists/its own twists/

**Comment by annaraven** [comment]
It's in fixtures / codesamples.json

**Comment by peterlandry** [comment]
Mind sending a PR?

**Comment by annaraven** [comment]
@peterlandry  Sorry I'm a dunce at github and unfamiliar with your abbreviation. Please explain what a PR is and how to do it and I'll be glad to. (Is that a "pull request" or a patch or ?)

**Comment by peterlandry** [comment]
Indeed, it's a Pull Request. Sorry about the acronym. Here's the github docs: https://help.github.com/articles/be-social#more-things-you-can-do -- it's basically just asking the owners of python/pythondotorg to merge changes in from your fork of the repository.

**Comment by annaraven** [comment]
Great. I did a fork and fixed it but have no idea how to request to merge changes back in. I'll go look at your link. Thanks.

**Comment by peterlandry** [comment]
Let me know if you have trouble, I'll try to help.

**Comment by annaraven** [comment]
I think I did it. Can you check if it worked? Thanks for your help!

**Comment by peterlandry** [comment]
Looks right to me. Thanks!

**Comment by benjaminp** [comment]
Pull request #146
