### ISSUE TITLE
Broken link for core-mentorship initial proposal

### ISSUE THREAD

**Issue by HaleTom** [python/pythondotorg#1450]
**Describe the bug**
The link with text `original proposal` at the end of the first paragraph is broken.

Link is: http://jessenoller.com/2011/03/25/just-proposed-python-core-mentorship-program/

**To Reproduce**
View first paragraph at:
https://www.python.org/dev/core-mentorship/

**Expected behavior**
The best replacement link I've seen is:
http://jessenoller.com/blog/2011/03/25/just-proposed-python-core-mentorship-program

**Comment by brainwane** [comment]
Noller has decided to take all his blog posts offline, so I suggest https://mail.python.org/pipermail/python-dev/2011-March/110077.html as a replacement link.

**Comment by brainwane** [comment]
Fixed; thanks.
