### ISSUE TITLE
Math bug with sub

### ISSUE THREAD

**Issue by virsystem** [python/pythondotorg#1451]
C:\Users\vir>python -V
Python 3.6.3

C:\Users\vir>python -c "a=1000;b=1.005;print(a*b)"
1004.9999999999999

C:\Users\vir>python -c "a=1000;b=1.005;print(a**b)"
1035.142166679343

C:\Users\vir>python -c "a=1000;b=1.005;print(b*a)"
1004.9999999999999

C:\Users\vir>python -c "a=1000;b=0.005;print(b*a)"
5.0

C:\Users\vir>python -c "a=1000;b=2.005;print(b*a)"
2005.0

C:\Users\vir>python -c "a=1000;b=1.005;print(b*a)"
1004.9999999999999

Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:01:18) [MSC v.1900 32 bit (Intel)] on win32
a=1000;b=1.005
a*b
1004.9999999999999

only by multiplying 1000 by 1.005 does not the correct calculation

**Comment by berkerpeksag** [comment]
https://docs.python.org/3/tutorial/floatingpoint.html

**Comment by eamanu** [comment]
Hi @virsystem, thanks for the report. Like say @berkerpeksag  this is not a bug and it's explain on the link.
When you think that you found a bug (after read the documentation to be sure it is a bug)  on cpython
you have to open an issue on bugs.python.org.

This repository (pythondotorg) is for the webpage.
