### ISSUE TITLE
Graph essay contains bad code

### ISSUE THREAD

**Issue by gvanrossum** [python/pythondotorg#1452]
I just received a bug report from a CS professor in Poland claiming that my code to find the shortest path in a graph runs in exponential time rather than "as fast as it gets". (He failed his students for copying it. :-( )

The code is in https://www.python.org/doc/essays/graphs/

I don't know where the source of this essay is. Is there some repo to which I can submit a PR with a correction? (I cloned pythondotorg, but I don't see it there.) If not, I see two options:

1. You can email me the source (or attach it to this issue), I can edit it, and send it back.
2. You can email me all the essays and I will host them on my own site (https://gvanrossum.github.io/) and I will make the correction there. You can then implement redirects, because presumably there are deep links to some of the essays that we don't want to fail.

**Comment by berkerpeksag** [comment]
All content stored inside the database. We are using the `Page` model to edit them via Django admin. Here's the HTML source of https://www.python.org/doc/essays/graphs/:

[graphs.txt](https://github.com/python/pythondotorg/files/3271243/graphs.txt) (renamed it to `.txt` so GitHub won't complain)

I can send you all the essays or grant you Django admin permissions (I couldn't find you on python.org; you may need to create an account at https://www.python.org/accounts/signup/) to edit them.

**Comment by gvanrossum** [comment]
OK, I now have an account, gvanrossum. Thanks!

**Comment by berkerpeksag** [comment]
Thanks! You can now find and edit all essays in /doc/essays/ at https://www.python.org/admin/pages/page/?q=doc%2Fessays Most of them haven't been converted to reST, so editing them might be painful :)

**Comment by gvanrossum** [comment]
Thanks! I updated the essay. Maybe I'll review some of the others for bad links and such.
