### ISSUE TITLE
max() gives ValueError when checking empty input

### ISSUE THREAD

**Issue by skatlapa** [python/pythondotorg#1456]
max() should return "None" or empty data structure when checking for empty sequences/values.

**The bug**

max() should return "None" when checking for empty sequences/values.

**To Reproduce**

empty_list = []
max(empty_list)

ValueError: max() arg is an empty sequence

**Expected behavior**

max(empty_list)

#output: None or [] or empty data structure

**Comment by SmartManoj** [comment]
Check the [docs ](https://docs.python.org/3/library/functions.html#max) first.
`max([],default=None)`
It should not be the right repo for it. Ask on stackoverflow for further questions.

**Comment by Mariatta** [comment]
This is the issue tracker for the python.org website, not for bugs of CPython itself. Closing.
Thanks.

**Comment by skatlapa** [comment]
@mariatta Thanks! This was more of a feature request, will file there.

**Comment by SmartManoj** [comment]
@skatlapa Use the default keyword
`max([],default=None)` ; No need to file a feature request
