### ISSUE TITLE
python and & or error?

### ISSUE THREAD

**Issue by lsircc** [python/pythondotorg#1471]
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 03:13:28) 
English:
Is 'and' and 'or' wrong?
The original code is as follows:
However, when 'and' is used, when the number of s1/s2/s3 is 8, the while ends;
When using 'or', the while needs 3 numbers to be 8 to jump out of the loop.

中文：
'and' 和'or' 是否错误？
原代码如下：
但用'and'时，s1/s2/s3一个数为8时while结束；
用'or'时，while需要3个数都为8才跳出循环。

import random
a1,a2,a3=0,0,0
ii=0
while (a1!=8 or a2!=8 or a3!=8):
    a1 = random.randint(0,10)
    a2 = random.randint(0,10)
    a3 = random.randint(0,10)
    print(ii,'  ',a1,a2,a3)
    print(a1==8 and a2==8 and a3==8)
    ii+=1

**Comment by eamanu** [comment]
Hello, 
thanks for the report. But this issue tracker is for the python.org site. You  could have a solution for your on stackoverflow or reddit, etc. :-)
