### ISSUE TITLE
Blog importer uses timestamp of import, not the published date of items

### ISSUE THREAD

**Issue by akuchling** [python/pythondotorg#148]
I added a bunch of back-dated entries to blog.python.org.  When the blog import job ran, they were all given pub_dates of Feb. 20, around 9PM:

http://www.python.org/admin/blogs/blogentry/

Which means that http://www.python.org/blogs/ doesn't show the items in publication order.  For example, Python 3.3.3 is listed before Python 3.3.4.

**Comment by justinabrahms** [comment]
Looks to me like the blog importer uses the `updated_parsed` from feedparser? Info on that property: https://pythonhosted.org/feedparser/reference-feed-updated_parsed.html

https://github.com/python/pythondotorg/blob/master/blogs/management/commands/update_blogs.py#L30

https://github.com/python/pythondotorg/blob/master/blogs/parser.py#L17
