### ISSUE TITLE
can not confirm email

### ISSUE THREAD

**Issue by kaldown** [python/pythondotorg#1487]
**Describe the bug**
was wrong in user registration email on https://www.python.org/accounts/signup/

**To Reproduce**
1. make a mistake in a email field
2. don't confirm (in case of 1.)
3. won't be able to re-register with recent nickname (already took)

**Expected behavior**
don't reserve username on a failure email provided,
or rollback upon timeout with no confirmation in a given amount of time

**Additional context**
**kAldown** - nickname being reserved under wrong email: **kaldownb@gmai.com** (without l)

same as for #1029 

Sorry for bothering.

**Comment by berkerpeksag** [comment]
Sorry for the last response! I've just updated your email address to kaldownb@gmail.com.
