### ISSUE TITLE
Latest News links are broken

### ISSUE THREAD

**Issue by ghost** [python/pythondotorg#149]
"Python 3.3.0 released" and all the others on the frontpage link to "http://www.python.org/#example".

![newsbroken](https://f.cloud.github.com/assets/5307545/2229256/237577f8-9aea-11e3-8994-45e5e8eed592.png)

Running Firefox 24.3.0esrpre (Tor Browser Bundle).

**Comment by ghost** [comment]
">>> More" link is also broken, it links http://www.python.org/#fixme.

![newsbroken2](https://f.cloud.github.com/assets/5307545/2229269/80a8e036-9aea-11e3-9982-2b3bf902cf5b.png)

**Comment by peterlandry** [comment]
This should be fixed now. Can you confirm that it is fixed for you?

**Comment by ghost** [comment]
The original problem is,  thank you! However, the news pages themselves are broken (and it seems they were earlier too). They show broken <a> tags.

![newspagebroken](https://f.cloud.github.com/assets/5307545/2235209/2861c554-9b45-11e3-995f-a0a1d0334c9a.png)

**Comment by benjaminp** [comment]
The links go somewhere now.
