### ISSUE TITLE
Wrong function name in the graphs essay

### ISSUE THREAD

**Issue by motyzk** [python/pythondotorg#1493]
**Wrong function name in the graphs essay**
It says "find_graph()" instead of "find_path()"

**To Reproduce**
1. Go to 'https://www.python.org/doc/essays/graphs/'
2. Click 'ctrl+f'/'cmd+f', then "find_graph()"
4. See typo.

![image](https://user-images.githubusercontent.com/13931734/62580744-a3e51e00-b8af-11e9-8e86-3a210687e62c.png)

**Comment by brainwane** [comment]
Fixed; thanks!
