### ISSUE TITLE
Dead link and typo in "Python Humor"

### ISSUE THREAD

**Issue by greyli** [python/pythondotorg#1494]
Page link: https://www.python.org/doc/humor

### Dead Link
location: Second paragraph
link text: Python quotations
link target: http://www.amk.ca/quotations/python-quotes/

### Typo
location: First line at https://www.python.org/doc/humor/#cute-wabbit
text: "pet show" --> "pet shop".

**Comment by lokcito** [comment]
Is there any correct link or is better remove the link?

**Comment by greyli** [comment]
@lokcito The new link is http://quotations.amk.ca/python-quotes/.

**Comment by ned-deily** [comment]
Thanks for the report and the replacement link.  Now fixed.
