### ISSUE TITLE
Error raised in last code snippet in graphs essay when no paths from start to end

### ISSUE THREAD

**Issue by motyzk** [python/pythondotorg#1495]
**Bug Description**
In the second implementation of find_shortest_path() in the graphs essay, an error is raised when paths from origin to destination don't exist.

**To Reproduce**
1. Go to 'https://www.python.org/doc/essays/graphs/'
2. To run the code and witness the bug, use the graph on the top of the page from step 1:

    ```graph = {'A': ['B', 'C'],
    graph = {'A': ['B', 'C'],
             'B': ['C', 'D'],
             'C': ['D'],
             'D': ['C'],
             'E': ['F'],
             'F': ['C']}
    ```
3. And the last code snippet on the page from step 1:

    ```from collections import deque
    from collections import deque
    def find_shortest_path(graph, start, end):
        dist = {start: [start]}
        q = deque(start)
        while len(q):
            at = q.popleft()
            for next in graph[at]:
                if next not in dist:
                    dist[next] = [dist[at], next]
                    q.append(next)
        return dist[end]
    ```
4. Now run this line:
`find_shortest_path(graph, 'A', 'E')`
5. Error raised

**Expected behavior**
Some return value that means there's no path.

**Actual behavior**
Error raised: `KeyError: 'E'`

**Suggested fix**
Replace the last line in the function to `return dist.get(end)` so that it'd look like:
```def find_shortest_path(graph, start, end):
def find_shortest_path(graph, start, end):
    dist = {start: [start]}
    q = deque(start)
    while len(q):
        at = q.popleft()
        for next in graph[at]:
            if next not in dist:
                dist[next] = [dist[at], next]
                q.append(next)
    return dist.get(end)

**Comment by berkerpeksag** [comment]
Updated, thanks! Note that these documents are published here for mostly archival purposes. You can email Guido if you have questions or found more issues in them.
