### ISSUE TITLE
Test a banner pointing to "Python 2 EOL" info page

### ISSUE THREAD

**Issue by brainwane** [python/pythondotorg#1498]
Many Python users do not know about the upcoming Python 2 End of Life and haven't started making migration plans. I'm [contracted with the PSF to reduce that problem](https://www.harihareswara.net/sumana/2019/08/05/0).

I'm writing a clear, minimal page (reusing material from [the wiki](https://wiki.python.org/moin/Python2orPython3) and related resources) and will have a draft ready in the next few days for PSF staff and the Steering Council to review. Once it's up, I'd like to post it as a page (within the CMS) on www.python.org, and point to it with a menu item within "News" and "Documentation". I can take a little bikeshedding on the exact menu placement but I'm pretty sure this needs to be accessible above the fold on the front page.

For better visibility, I would like to test a red sitewide banner pointing to the EOL page, similar to the yellow "this is a test site" banner across the top of https://test.pypi.org/ . I suggest we create it and deploy it as a test for a few hours; I would work on the wording with the designer. I would then check site analytics and do some qualitative and quantitative analysis on feedback to decide how to move forward.

Questions:

* Whose approval should I be seeking regarding the URL of and menu items pointing to the EOL page?
* Whose approval do I need for a banner?
* What site analytics are available? I looked on https://pythondotorg.readthedocs.io and couldn't tell.

**Comment by brainwane** [comment]
cc @berkerpeksag @ewdurbin

**Comment by berkerpeksag** [comment]
Thanks to https://github.com/python/pythondotorg/pull/1413, we now have an easy way to add such banner. I don't think it possible to restyle each banner, though.

> What site analytics are available?

I don't think we have a tool more sophisticated than Google Analytics :) Do you want to know how many people saw the banner and clicked to the link?

**Comment by ewdurbin** [comment]
@brainwane is this still something we should consider given that most of what was planned is completed?

**Comment by brainwane** [comment]
@ewdurbin I'm fine with closing this as not-done. I regret that I didn't make this happen last year. Thanks for the reality check.
