### ISSUE TITLE
python.org unreachable via TCP/IP v6 on Windows10

### ISSUE THREAD

**Issue by martinfalk** [python/pythondotorg#1501]
When trying to access either python.org or running pip, the connection is closed unexpectedly. 

Opera v63.0.3368.35, 64bit on Windows 10 reports:
```
This site can’t be reached
www.python.org unexpectedly closed the connection.

Try:
Checking the connection
Checking the proxy and the firewall
Running Windows Network Diagnostics
ERR_CONNECTION_CLOSED
```

Similarly, when running python's pip, e.g. `pip install flickr_api`, the connection is also reset:
```
$ pip install flickr_api
Collecting flickr_api
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted
.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/flickr-api/
...
```
This was confirmed with several other machines running Windows 10.

When I temporarily disable the TCP/IP v6 protocol for the network interface card, python.org is reachable and pip is working.

**Comment by martinfalk** [comment]
also reported in https://github.com/python/psf-infra-meta/issues/40

**Comment by brainwane** [comment]
Closing per the psf-infra-meta issue.
