### ISSUE TITLE
Download button links to release page instead of intiating download.

### ISSUE THREAD

**Issue by DrRunka** [python/pythondotorg#1502]
**Describe the bug**
The big yellow download button on python.org/downloads is acting a link to python.org/downloads/release/python-374/  (or whatever the current version is), instead of initiating a download of the latest installer.

**To Reproduce**

0. On Firefox, Windows, and a Touch-enabled device
1. Go to 'python.org/downloads'
2. Click on the big yellow button that says "Download Python x.x.x"  (3.7.4 currently)
3. Get linked to the release page for the current version instead of initiating a download.

**Expected behavior**
Expected behaviour of the big yellow button is to initiate a download of the listed version's installer (as it does in chrome or on a non-touch device). 

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox
 - Versions: (likely all) Tested: Quantum 68.0.2 and Developer Edition 69.0b16

**Additional context**
Tested on the same devices using chrome, no issue.
Tested on non-touch devices using firefox, no issue.

**Comment by ghost** [comment]
Yes it's because the site is designed to do so. So that the user can find and download the type of installer he/she wants to download ...
Thanks

**Comment by hugovk** [comment]
Thanks for the report. The button currently reads "Download Python 3.12.6".

On macOS (Chrome) it links to https://www.python.org/ftp/python/3.12.6/python-3.12.6-macos11.pkg and downloads that installer. 

On Android (Chrome) it links to https://www.python.org/downloads/release/python-3126/ so you can read more about the release.

This looks good now.
