### ISSUE TITLE
Typo at the 3.8.0b4 download page

### ISSUE THREAD

**Issue by hroncok** [python/pythondotorg#1503]
**Describe the bug**
There is a typo at https://www.python.org/downloads/release/python-380b4/

> The next pre-release of Python 3.8 and the first release candidate will be **3.8.0c1**, currently scheduled for 2019-09-30.

It should be 3.8.0**r**c1.

**Screenshots**

![screenshot](https://imgur.com/mcHLDGj.png)

**Desktop (please complete the following information):**
 - OS: any
 - Browser: any
 - Version: any

**Smartphone (please complete the following information):**
 - Device: any
 - OS: any
 - Browser: any
 - Version: any

**Additional context**

I was looking where to submit a PR, but this appears to be in a database.

**Comment by brainwane** [comment]
@ambv

**Comment by ned-deily** [comment]
Thanks for the report!  Now fixed.
