### ISSUE TITLE
Landing page is Heroku's default page

### ISSUE THREAD

**Issue by lunalucadou** [python/pythondotorg#1504]
**Describe the bug**

The landing page (https://www.python.org) displays a Heroku "No such app" page, but other pages (e.g. https://www.python.org/downloads/) load fine.

**To Reproduce**
1. Go to 'https://www.python.org'
2. See error

**Expected behavior**

I expect to see the usual landing page.

**Screenshots**

![image](https://user-images.githubusercontent.com/22415965/64129559-c83afa00-cd8a-11e9-911e-5e812ac58455.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64 build 1903
 - Browser: Chrome for Windows, Firefox for Windows, Microsoft Edge
 - Version: Chrome 76, Firefox 68, Edge 44

**Smartphone (please complete the following information):**
 - Device: Pixel 2
 - OS: Android 9.0
 - Browser: Chrome for Android
 - Version: 76

**Additional context**

It was working at 04:33:44 according to [Wayback Machine](http://web.archive.org/web/20190902043344/python.org).

**Comment by brainwane** [comment]
I'm guessing this was due to the incident that is [being tracked here](https://status.python.org/incidents/w8lq7ggjj7d9).

**Comment by lunalucadou** [comment]
The routing issue has been resolved, closing issue.
