### ISSUE TITLE
Path(file_path).exists does not work on windows 10

### ISSUE THREAD

**Issue by santhoshnumberone** [python/pythondotorg#1519]
**Bug**
`Path(file_path).exists` return `True` even if the file doesn't exist

**To Reproduce**
1. install python on Windows 10
2. Open python in 'cmd'
3. Import the library pathlib
> from pathlib import Path
4. Give any random file check if it exists
> bool(Path("C:\\User1").exists)
> True

**Expected behavior**
> bool(Path("C:\\User1").exists)
> False

Works fine if `os` used instead of `pathlib` 
> import os
> os.path.exists("C:\\User1")
> False

**Screenshots**
![image](https://user-images.githubusercontent.com/43645867/67280594-1fd42700-f4eb-11e9-8e60-2f272328cff7.png)

**Desktop (please complete the following information):**
 - OS: Wndows 10
 - Browser any
 - Version Microsoft Windows [Version 10.0.18362.356]

Bug reported [Issue35692 ](https://bugs.python.org/issue35692)

**Comment by tirkarthi** [comment]
Please use https://bugs.python.org for reporting bugs. This repo is for python.org website related issues.
