### ISSUE TITLE
3.8.0 download listed for windows as 64bit executable download but turns out to be 32bit

### ISSUE THREAD

**Issue by markcpreston** [python/pythondotorg#1522]
**Describe the bug**
64bit executable download behaving as 32 bit

**To Reproduce**
1. Go to download area for 3.8.0 in edge
2. Click on x64 executable fiel download for 3.8
3. Utilise intasller
4. See shows as 32bit

**Expected behavior**
needs ro download 64 bit
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Microsoft Edge
 - Version: 44.18362.387.0 and HTML 18.18362

**Comment by luciansmith** [comment]
I have the same problem (I think), many months later, with Python 3.8.3

EDIT:  This turned out to be a problem with trying to run Python from the "Developer's Command Prompt for VS 2019".  This somehow confuses pip, and it tries to install the wrong version.  The download links are fine.

**Comment by zooba** [comment]
Firstly, this is not the right issue tracker for your problem. If you think Visual Studio is to blame, you'll be best to use https://developercommunity.visualstudio.com/ - if you think it's a Python installer issue, report on https://bugs.python.org/

Either way, include the output of `python -m site` so whoever is helping diagnose can see which Python is running and what paths it's picked up.
