### ISSUE TITLE
Update "Other Download" info regarding AIX

### ISSUE THREAD

**Issue by aixtools** [python/pythondotorg#1523]
**Describe the bug**
Information is stale. By including any version number, it goes stale with any new release.

**To Correct**
I tried forking the site, then I recalled the content is not actually something that can be done via a PR. What follows is what I request as the updated text.

> AIX binary packages for Python3 and Python2 are provided by AIXTOOLS for no-charge. The packages are supplied in installp format (not RPM format). There are no pre-requisites other than a recent version of openssl.base.
> 
> See the AIXTOOLS wiki for additional details. The download page for Python 3 is at http://www.aixtools.net/index.php/python3 and the download page for Python 2 is at http://www.aixtools.net/index.php/python2.
> 
> For issues concerning the installation of AIXTOOLS packaging of Python please post your issue at http://forums.rootvg.net/aixtools.

**Comment by aixtools** [comment]
Please (and I corrected a spelling error!)

**Comment by aixtools** [comment]
ping!

**Comment by ned-deily** [comment]
@aixtools, Sorry about the delay!  The Python for AIX section has now been updated as you requested.
