### ISSUE TITLE
Deadline for 2020 PyCon proposals doesn't match definition of "AoE" 

### ISSUE THREAD

**Issue by nealmcb** [python/pythondotorg#1528]
**Describe the bug**
Deadline for PyCon 2020 proposals doesn't match definition of "AoE", and ends 12 hours too soon.

**To Reproduce**
1. Go to `https://us.pycon.org/2020/speaking/`
2. Note _Talk, Charlas, Poster, and Education Summit proposals — deadline is 20 December 2019 AoE._
3. Click on "AoE" link, to https://en.wikipedia.org/wiki/Anywhere_on_Earth
4. Note *The day's end AoE occurs at noon Coordinated Universal Time (UTC) of the following day*, which would be midnight in the last timezone on earth, at Howland and Baker islands, being halfway around the world from the prime meridian that is the base reference longitude for UTC.
1. Note reference to timeanddate.com explanation at _You can view what time that is locally to you here._ to [11:59:59 am Friday, December 20, 2019 in UTC-12](https://www.timeanddate.com/worldclock/fixedtime.html?msg=PyCon+2020+CFP+Deadline+for+Talks%2C+Posters%2C+Charlas%2C+and+Education+Summit&iso=20191220T115959&p1=3399) rather than **11:59:59 pm** at Baker Island.
1. Note that the time in your local timezone via that timeanddate link shows a time during the day on the 20th, while it should be some time on the 21st according to the AoE definition.
1. Note that the countdown clock itself appears to be right.

**Expected behavior**
The clock and reference should match the definition of AoE by being adjusted to **11:59:59 pm** in the same location.

**Desktop (please complete the following information):**
 - OS: [Ubuntu 18.04]
 - Browser [Chrome]
 - Version [beta, up-to-date]

**Additional context**
It wasn't actually clear where to report this bug, but I didn't see more specific instructions, and I'm assuming that content at us.pycon.org is managed by the same team.

**Comment by ewdurbin** [comment]
@nealmcb Thanks for your report. I've updated the link on the speaking page to point to the correct event time.
