### ISSUE TITLE
generate_pep_pages command duplicates images

### ISSUE THREAD

**Issue by ewdurbin** [python/pythondotorg#1529]
**Describe the bug**

With the updates to store media in S3, every time a pep containing an image is updated, a new version of all images is created in the S3 bucket.

This was reported by @ambv, who noted the behavior on the resulting page for PEP 602.

**Additional context**

The code in `peps.converters.add_pep_image` should likely be updated to only create new images if the checksum of the image in question has changed: 

https://github.com/python/pythondotorg/blob/41f8e9d019bfb8c4cad670877dc4f5475607cf03/peps/converters.py#L214-L229

This likely isn't 100% straightforward as it may not be clear which version of the image is "current". The metadata stored in the DB for images don't include their update time.

Alternatively, for images with the same name we could delete/recreate the Image object on each update to avoid Django helpfully creating a new object with a random suffix.

**Comment by hugovk** [comment]
This issue can be closed, the PEPs and their images now live in [their own repo](https://github.com/python/peps), and the code in https://github.com/python/pythondotorg/tree/main/peps is no longer run.

(It could be removed.)
