### ISSUE TITLE
problem with chaining **

### ISSUE THREAD

**Issue by sxkladi** [python/pythondotorg#1531]
**Describe the bug**
using the ** operator a few times in a row causes memory overflow

**To Reproduce**
1. type py or python
2. at the >>> type -> a = 2**3**4**5

**Expected behavior**
a fast answer this is not a really big integer -> 1 152 921 504 606 846 976

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [ Python 3.8.0 ( 64 bit )]

**Additional context**
python freezes after a few minutes. after a while I get out of memory

**Comment by berkerpeksag** [comment]
Please use a support forum to ask Python usage questions. This tracker is for issues with www.python.org.
