### ISSUE TITLE
Stale release-detail info for Python 2.7.14

### ISSUE THREAD

**Issue by mfonism** [python/pythondotorg#1532]
**Describe the bug**
[The release detail page for Python 2.7.14](https://www.python.org/downloads/release/python-2714/) says that Python 2.7.14 is the latest bug fix release in the Python 2.7.x series, but this information is stale, as three bug fix releases have been made after that (with [Python 2.7.17](https://www.python.org/downloads/release/python-2717/) being the most recent)

**To Reproduce**
1. Go to https://www.python.org/downloads/release/python-2714/
2. Scroll down to the second block of text after the article header, where the release content is specified.
4. See the misleading info on the latest bug fix release in the Python 2.7.x series.

**Additional context**
I thought it was something I could work on, as I'd like to make my first contribution to pythondotorg, so I went exploring, and tracked it down to lines 26-28 of  `templates/downloads/release-detail.html` and couldn't work on it, as it involves updating data in the database for that particular release object.

**Comment by ned-deily** [comment]
Thanks for the report.  The text for 2.7.14 has been changed to match those of other recent 2.7.x releases, i.e. 

> is a bugfix release in the Python 2.7 series

.
