### ISSUE TITLE
Old "latest release" on Python 3.6.x release pages

### ISSUE THREAD

**Issue by cor-bee** [python/pythondotorg#1533]
**Describe the bug**
On all pages `https://www.python.org/downloads/release/python-36x/` in Notes section, there is info that Python 3.7 is the latest version of Python 3, which is incorrect.

**To Reproduce**
1. Go to https://www.python.org/downloads/release/python-360/ or newer until 3.6.9
2. Scroll down to 'Notes' section
3. See incorrect information

**Screenshots**
![3.6.0 Release](https://user-images.githubusercontent.com/40601422/68939323-fdab8d00-07a8-11ea-8507-2f212b1900e8.png)

**Comment by hugovk** [comment]
This is now fixed, at least on https://www.python.org/downloads/release/python-360/

![SmartSelect_20200301-144805_Chrome](https://user-images.githubusercontent.com/1324225/75625956-c7fda900-5bcb-11ea-9159-fe2a3139772d.jpg)

Nit pick: replace the double ".." with a single "."

**Comment by ned-deily** [comment]
> Nit pick: replace the double ".." with a single "."

Grrr! Thanks for noticing!  Those should now be fixed on all 3.6.x and 3.7.x release pages.
