### ISSUE TITLE
"Report a Security Issue" link in footer redirects to wrong content, was /news/security

### ISSUE THREAD

**Issue by ned-deily** [python/pythondotorg#1537]
A user reports that clicking on the "Report a Security Issue" (https://www.python.org/news/security) link at the bottom of each web page now redirects to https://www.python.org/blogs/.   The link was added in #1375 back in January.  It looks like a redirect of /news has been added since then as the source for /news/security is still intact in the CMS Pages /news/security.

**Comment by ned-deily** [comment]
CC @ewdurbin

**Comment by ewdurbin** [comment]
`/news` redirect was updated to prepare for some upcoming blog work @jezdez intends. sorry for clobbering that url.

link has been updated to be `/dev/security` and a purge has been issued.

links in footer should resolve over the next few minutes.

**Comment by jezdez** [comment]
Oops, thanks for the report @ned-deily!

**Comment by ned-deily** [comment]
No problem: the old location was inherited from the legacy site and was nonintuitive.  It just points out, though, how easy it is to break things since it's so easy to change things; while the Django CMS for the web site is convenient, it makes it difficult to detect and audit conflicts like this.

**Comment by jezdez** [comment]
@ewdurbin Could we add a form validation step to the admin forms to check for overlaps between Django redirects and CMS page paths? It wouldn't catch nginx- or CDN-level redirects I guess. But maybe we could move some of those nginx redirects into a file that we can read from Python, too?

**Comment by ned-deily** [comment]
I was just going to mention that another point of confusion is that redirects are managed in more than one place.  It appears that this one, for example, is not in /admin/redirects/redirect/.
