### ISSUE TITLE
Where is the source for https://www.python.org/dev/?

### ISSUE THREAD

**Issue by ctb** [python/pythondotorg#1538]
Over on python-ideas we're talking about adding some information, and I'd like to know where to submit a PR if it gets that far. I can't find it anywhere on github, tho.

**Comment by berkerpeksag** [comment]
That page is stored in the [`Page`](https://github.com/python/pythondotorg/blob/d4d24c782b2770d4213b495352ea462213e045fa/pages/models.py#L47) model and its content can be updated via Django admin.

If you can upload your suggested changes here (in plain text or reST format) I'd be happy to update the page. We can also change the format of the content to HTML and even use a different template (like we did for [micro:bit project](https://github.com/python/pythondotorg/blob/d4d24c782b2770d4213b495352ea462213e045fa/templates/community/microbit.html))

Thanks!

**Comment by hugovk** [comment]
OK to close this issue?

**Comment by ctb** [comment]
yes
