### ISSUE TITLE
Invalid `success story create` link

### ISSUE THREAD

**Issue by suzaku** [python/pythondotorg#154]
In the bottom-right box of the page [Our Success Stories](http://python.org/success-stories/), the "Tell  us your story" link seems to be an escaped snippet of Django template.

![screen shot 2014-02-22 at 12 11 50 pm](https://f.cloud.github.com/assets/116473/2236937/7f83cefe-9b77-11e3-9302-1dd3352f4876.png)

**Comment by frankwiles** [comment]
Fixed, thanks!
