### ISSUE TITLE
pip install --upgrade pip, should be pip3 install --upgrade pip

### ISSUE THREAD

**Issue by fiedersz** [python/pythondotorg#1540]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fiedersz** [comment]
Python 3 the advice in Terminal should be: pip3 install --upgrade pip instead of pip install --upgrade pip. Tiny error but pip3 works, pip does not. :)

**Comment by berkerpeksag** [comment]
Could you give us a little bit more information on where you saw `pip install --upgrade pip`? Did you see it when you invoked `pip3 install <something>`? For example:

```sh
$ pip install astor
Collecting astor
  Downloading https://files.pythonhosted.org/packages/d1/4f/950dfae467b384fc96bc6469de25d832534f6b4441033c39f914efd13418/astor-0.8.0-py2.py3-none-any.whl
Installing collected packages: astor
Successfully installed astor-0.8.0
You are using pip version 19.0.3, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

If so, unfortunately this tracker isn't the best place to report it. I'd suggest discussing the issue with packaging folks at https://discuss.python.org/c/packaging first.

**Comment by fiedersz** [comment]
On a Mac mini with Mojave, the place was in the terminal. I was recommended to upgrade pip. I tried to do so and this was the result. Pip install --upgrade did not work and gave the message that it didn't work. pip3 install --upgrade pip did work. So everything is fine.
I do not want to discus this. I just wanted to point to it. Thanks for your reply.

**Comment by Biobandit** [comment]
On a Mac mini with Mojave, in the terminal. I have Python 3. this was after the upgrade of pip3 as was advised in the terminal.

**Comment by raghavkumar09** [comment]
Tool-x installing error please help
