### ISSUE TITLE
in pip or pip3 "opencv" not working as import on Raspberry Pi

### ISSUE THREAD

**Issue by pallavprince** [python/pythondotorg#1547]
**Describe the bug**
"opencv" File missing at path </usr/lib/python2.7>
or
</usr/lib/python3/dist-packages>
or
</usr/lib/python3.7>

**To Reproduce**
1. Go to 'terminal' on raspberry pi
2. type command "sudo apt-get update" on raspberry pi
3. type command "pip list" or "pip3 list" to show your installed pip package
4. Scroll down to find 'opencv-python' if you find the same, it means you have installed openCV
5. type command "python3" in terminal, if you have installed python 2.7, then type "python" only
6. now you are on python shell, type "import cv2" to check opencv is working or not.
7. now you see error <ImportError: libcblas.so.3: cannot open shared object file: No such file or directory>
4. See error here

**Expected behavior**
python shell should be execute without error

**Screenshots**
![Uploading openCV.jpg…]()

**Desktop (please complete the following information):**
 - OS: Raspbian
 - python3 or python 2.7
 - python 3 Version [Python 3.7.3 (default, Apr  3 2019, 05:39:12)]
 - python 2.7 Version [Python 2.7.16 (default, Oct 10 2019, 22:02:15)]

**Smartphone (please complete the following information):**
 - Device: Raspberry Pi 4]
 - OS: Raspbian
 - Python
 - Version [Python 3.7.3 (default, Apr  3 2019, 05:39:12)] or [Python 2.7.16 (default, Oct 10 2019, 22:02:15)]

**Additional context**
In my personal research I found there is missing file or folder at package location where it supose to be,
</usr/lib/python3.7>
or
 "opencv" File missing at path </usr/lib/python2.7>
or
</usr/lib/python3/dist-packages>

**Comment by pallavprince** [comment]
**Describe the bug**
"opencv" File missing at path </usr/lib/python2.7>
or
</usr/lib/python3/dist-packages>
or
</usr/lib/python3.7>

**To Reproduce**
Steps to reproduce the behavior:
1. Go to 'terminal' on raspberry pi
2. type command "sudo apt-get update" on raspberry pi
3. type command "pip list" or "pip3 list" to show your installed pip package
4. Scroll down to find 'opencv-python' if you find the same, it means you have installed openCV
5. type command "python3" in terminal, if you have installed python 2.7, then type "python" only
6. now you are on python shell, type "import cv2" to check opencv is working or not.
7. now you see error <ImportError: libcblas.so.3: cannot open shared object file: No such file or directory>
4. See error here

**Expected behavior**
python shell should be execute without error

**Screenshots**
![Uploading openCV.jpg…]()


**Desktop (please complete the following information):**
 - OS: Raspbian
 - python3 or python 2.7
 - python 3 Version [Python 3.7.3 (default, Apr  3 2019, 05:39:12)]
 - python 2.7 Version [Python 2.7.16 (default, Oct 10 2019, 22:02:15)]

**Smartphone (please complete the following information):**
 - Device: Raspberry Pi 4]
 - OS: Raspbian
 - Python
 - Version [Python 3.7.3 (default, Apr  3 2019, 05:39:12)] or [Python 2.7.16 (default, Oct 10 2019, 22:02:15)]

**Additional context**
In my personal research I found there is missing file or folder at package location where it supose to be,
</usr/lib/python3.7>
or
 "opencv" File missing at path </usr/lib/python2.7>
or
</usr/lib/python3/dist-packages>

**Comment by berkerpeksag** [comment]
1. This tracker is for issues with www.python.org website.

2. This SO question may help to install the missing dependencies: https://stackoverflow.com/questions/53347759/importerror-libcblas-so-3-cannot-open-shared-object-file-no-such-file-or-dire Please use support forums for further questions. Happy new year!
