### ISSUE TITLE
Event pages need to display description as HTML

### ISSUE THREAD

**Issue by malemburg** [python/pythondotorg#156]
The calendar teams uses HTML for formatting the event descriptions.

At the moment, the descriptions are displayed as text.

Example from https://www.python.org/events/python-user-group/95/

```
Guadalajara, Mexico PUG
25 Feb. from 1am to 3am, 2014

<a href="http://wiki.cabal.mx/wiki/PythonCabal/">Guadalajara PUG</a>
```

This applies to both the user group calendar and the events calendar.

**Comment by fcurella** [comment]
I've committed a data migration fixing this in d698303e6dbc607d54a61ffba9c4dea0c67a8bc3

**Comment by malemburg** [comment]
Flavio: I don't know how the site pulls in the calendar events from the Google calendars, but I could imagine that the script doing the sync will also need to be updated to set the description markup to 'html'.

Thanks.

**Comment by fcurella** [comment]
@malemburg the script already parses them as html: https://github.com/python/pythondotorg/blob/master/events/importer.py#L62

The issue is just for events that were imported before 17d23b58f3d7b05c4d57620e9378c005135fb6f5

**Comment by malemburg** [comment]
On 24.02.2014 21:55, Flavio Curella wrote:

> @malemburg the script already parses them as html: https://github.com/python/pythondotorg/blob/master/events/importer.py#L62
> 
> The issue is just for events that were imported before 17d23b58f3d7b05c4d57620e9378c005135fb6f5

Ah, ok. Thanks for the note.

## 

Marc-Andre Lemburg

**Comment by fcurella** [comment]
the migraion has been run and the events have been fixed. Closing.

**Comment by malemburg** [comment]
On 26.02.2014 22:27, Flavio Curella wrote:

> the migraion has been run and the events have been fixed. Closing.

Thanks, Flavio.

## 

Marc-Andre Lemburg

**Comment by malemburg** [comment]
For some reason, the problem has resurfaced now, e.g.

https://www.python.org/events/python-user-group/174/ 

https://www.python.org/events/python-user-group/168/ 

https://www.python.org/events/python-user-group/173/ 

Note: These are _new_ entries that have been added recently.

**Comment by malemburg** [comment]
Closing again and opening a new issue instead: #435.
