### ISSUE TITLE
Add another app to the iOS download section

### ISSUE THREAD

**Issue by ColdGrub1384** [python/pythondotorg#1560]
Not a bug, but I would like to suggest an app to add to the iOS section on https://www.python.org/download/other/ if possible. It's [Pyto](https://pyto.app), it has Python 3.8 and has more modules than Pythonista. For example: Pandas, SciPy, SciKit-Learn, SciKit-Image and OpenCV. It has also newer versions of Numpy and Matplotlib. On iOS, non pure Python libraries must be included on the app and cannot be installed dynamically due to the iOS sandbox.

**Comment by ned-deily** [comment]
Thanks for the suggestion!  I wasn't aware of Pyto up to now; it certainly looks like an interesting alternative to Pythonista.  I've added a link to it on the download/other page.
