### ISSUE TITLE
"Back to Top" does nothing on mobile

### ISSUE THREAD

**Issue by hugovk** [python/pythondotorg#1561]
**Describe the bug**
"Back to Top" not working on mobile. 

**To Reproduce**
1. Go to https://www.python.org/
2. Click on "Menu"
-> it scrolls down to the bottom
3. Click on "Back to Top" 
-> nothing happens

**Expected behavior**
Scrolls back to the top

**Screenshots**

![Screenshot_20200301-145435_Chrome](https://user-images.githubusercontent.com/1324225/75626061-e87a3300-5bcc-11ea-9525-d37dc37eb413.jpg)

![Screenshot_20200301-145446_Chrome](https://user-images.githubusercontent.com/1324225/75626082-05166b00-5bcd-11ea-9784-7cb15738c2fe.jpg)

**Desktop (please complete the following information):**
 - Not tested

**Smartphone (please complete the following information):**
 - Device: Samsung S8
 - OS: Android 9
 - Browser: Chrome 80

**Additional context**

Links are:
* https://www.python.org/#site-map
* https://www.python.org/#python-network

**Comment by ghost** [comment]
Oh it's because the JavaScript or html used to make the site can not work on androids and even might be on ios devices also...
And nothing else
Thanks

**Comment by cacoze** [comment]
This one was already solved.

**Comment by hugovk** [comment]
Confirmed, thanks for testing!
