### ISSUE TITLE
Add Last-modified: date and metadata to HTML view of PEPs

### ISSUE THREAD

**Issue by nealmcb** [python/pythondotorg#1564]
**Is your feature request related to a problem? Please describe.**
When looking at a PEP page on `python.org`, it isn't obvious when the PEP was last modified, or how to see recent revisions.

In addition, search engines often aren't displaying useful information. E.g. the Google result for a search of PEPs seems to show the `Created:` date, which may confuse searchers. E.g. the date listed for [PEP 518](https://www.python.org/dev/peps/pep-0518/) in a Google search is `May 10, 2016`, though this Provisional PEP was most recently updated on `Dec 13, 2019`.

**Describe the solution you'd like**
It would be great if the footer of the HTML rendering of each PEP, when served by `python.org`, included a `Last-Modified:` date, with a link to the GitHub history for more information.  It could go after the Source link at the bottom of the page. E.g.

 * Source: https://github.com/python/peps/blob/master/pep-0518.txt
 * Last-Modified: [Dec 13, 2019](https://github.com/python/peps/commits/master/pep-0518.txt)

Including relevant dates as metadata such as `datePublished` and `dateModified` should help search engines display more helpful information, as described at [Official Google Webmaster Central Blog: Help Google Search know the best date for your web page](https://webmasters.googleblog.com/2019/03/help-google-search-know-best-date-for.html)

Our documentation at [PEP Page Generation — Python\.org Website 1\.0 documentation](https://pythondotorg.readthedocs.io/pep_generation.html) describes the current process.

Given the `peps` git repo obtained via that process, it seems to take less than 20 seconds to get the latest modification date of all the PEPs via e.g. even using the shell pipeline listed at [How to retrieve the last modification date of all files in a git repository \- Server Fault](https://serverfault.com/a/774574/64546), so I don't think there would be much overhead to maintaining this information.

**Describe alternatives you've considered**
A discussion of some of the options for making PEP history clearer, or whether version numbers or changelogs for PEPs would be worthwhile, is at [Easier tracking of PEP changes, versions, or modification dates \- PEPs \- Discussions on Python\.org](https://discuss.python.org/t/easier-tracking-of-pep-changes-versions-or-modification-dates/3658/3). The approach described here expands on what I see as the result of that discussion.

Adding `Last-Modified` information to the [PEP 0](http://python.org/dev/peps) page might also be worthwhile, as suggested there.

**Comment by hugovk** [comment]
The PEPs now have their own repo: https://github.com/python/peps and own website: https://peps.python.org/ and also have "Last modified" footers that link to GitHub. For example: https://peps.python.org/pep-0750/

@nealmcb Please could you close this issue?
