### ISSUE TITLE
Allow users to change their username

### ISSUE THREAD

**Issue by daisylb** [python/pythondotorg#1566]
**Is your feature request related to a problem? Please describe.**

Currently I am unable to change my Python.org username. This feature is particularly important to me because I am transgender and my username is currently my deadname.

**Describe the solution you'd like**

It would be ideal if there was a self-service UI to change my username.

Failing that, a manual process that is described/documented on the "edit profile" page (e.g. a label there that says "to request a username change, email admin@example.org") would be good.

**Describe alternatives you've considered**

I could create a new profile, but it's unclear how I'd transfer my PSF membership across, and ~~there doesn't seem to be a way I can find to delete my old one~~ there was a big red button that I somehow totally missed.

**Additional context**

#706, #1263 were both resolved by someone manually editing the database, hence my suggestion of a manual process that's easy to figure out as an alternative above.

**Comment by brainwane** [comment]
I would love for us to implement this. @ewdurbin could we talk about this soon?

**Comment by daisylb** [comment]
Was there any progress on this in the end?

**Comment by ewdurbin** [comment]
PR opened. Should be self service soon.

**Comment by ewdurbin** [comment]
Self service username changes are now supported.

**Comment by daisylb** [comment]
Thank you Ee! <3
