### ISSUE TITLE
python version >=3.8.0 cannot jupyter install pysparkkerrnel

### ISSUE THREAD

**Issue by zesluo** [python/pythondotorg#1567]
**Describe the bug**
I'm doing a vscode extension tool. I just found that python version >=3.8.0 cannot jupyter install pysparkkerrnel. However, it can work if python <3.8.0.

![image](https://user-images.githubusercontent.com/46309533/77539639-b2368780-6edc-11ea-885d-3c1913bc58d5.png)
![image](https://user-images.githubusercontent.com/46309533/77539663-b793d200-6edc-11ea-96ff-2b759f03c425.png)
I tried some solutions such as  https://stackoverflow.com/questions/58422817/jupyter-notebook-with-python-3-8-notimplementederror and https://github.com/microsoft/vscode-python/issues/8634
But none of it can work for me
**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Mariatta** [comment]
I think it is a problem with either jupyter or with the vs code extension. Perhaps you need to file this with time. This issue tracker is for issues related to python.org website.

**Comment by zesluo** [comment]
Hello Mariatte, 

what do you mean by “file this with time"？ Do you mean that I need to add timestamp? By the way, could you do me a favor? I'm unsure where I should place this issue. could you give me a link? Thanks a lot!

**Comment by Mariatta** [comment]
Sorry, I had a typo! I meant to say "it should be filed with them" ( either jupyter /pysparkkernel / vs code) Those are third party tools and libraries.  From one of the links you provided, seems like it was a problem with Jupyter?  But I can't really tell..

Their GitHub repo is at https://github.com/jupyter
