### ISSUE TITLE
How to Uninstall Python3.7.3 using cmd in windows?

### ISSUE THREAD

**Issue by ghost** [python/pythondotorg#1568]
I tried using cmd: Msiexec /uninstall C:\Python37\python.exe But it giver me an error:
"This installation package could not be opened.  Contact the application vendor to verify that this is a valid Windows Installer package."
How do I uninstall it ?

**Comment by ghost** [comment]
@berkerpeksag : could you please help?

**Comment by tonybaloney** [comment]
@deepaleekhare31 this GitHub project is for the python.org website, not for the Python application.

**Comment by ned-deily** [comment]
Please see the [Help link](https://www.python.org/about/help/) on any python.org webpage for suggestions for getting help with Python.  Good luck!
