### ISSUE TITLE
Add the Real Python Podcast to podcast list

### ISSUE THREAD

**Issue by dbader** [python/pythondotorg#1570]
[Real Python](https://realpython.com/) is a repository of free and in-depth Python tutorials created by a team of professional Python developers around the world. RP recently launched a new [Python podcast](https://realpython.com/podcasts/rpp/) with community interviews.

**Can the podcast get added to https://www.python.org/doc/av/?**

Here's a headline + subtitle suggestion following the current format of the page:

> [The Real Python Podcast](https://realpython.com/podcasts/rpp/)
>
> *Hear what’s new in the world of Python programming and become a more effective Pythonista.*
>
> https://realpython.com/podcasts/rpp/

Thank you :)

**Comment by Mariatta** [comment]
Hmm I don't even know who owns/manage the content of python.org? Is this also something you would do @berkerpeksag?

**Comment by malemburg** [comment]
Updated the content. Will take a while to get published due to the CDN.

@Mariatta You need edit rights in the python.org CMS and then edit the right page under https://www.python.org/admin/pages/page/

**Comment by ned-deily** [comment]
> Hmm I don't even know who owns/manage the content of python.org? 

Various people/groups do. some have multiple owners, and some sections have no current owners

 I have suggested in the past that someone put together and add to one of the repos a page with a site map of the website and with places for the people to claim ownership, similar to what we do in the cPython Developers Guide (https://devguide.python.org/experts/) but that hasn't happened - yet.  It would be great if somebody could start it.

For the record, any python.org web page that involves information about cPython releases, in particular pages under /downloads and some under /doc, are generally maintained by the cPython Release Managers and, if not, they can usually figure out who does.  I don't always look at this issue tracker as often as I do others so feel free to nosy me on issues that release managers should be involved in.
