### ISSUE TITLE
Broken links on old pages

### ISSUE THREAD

**Issue by nayuki** [python/pythondotorg#1574]
On page https://www.python.org/downloads/release/python-240/ :
* The links to https://www.python.org/downloads/release/python-240/highlights are broken. They should be https://www.python.org/download/releases/2.4/highlights/ .

On page https://www.python.org/downloads/release/python-241/ :
* The links to https://www.python.org/2.4/highlights.html are broken. They should be https://www.python.org/download/releases/2.4/highlights/ .

On pages https://www.python.org/downloads/release/python-242/ , https://www.python.org/downloads/release/python-243/ , https://www.python.org/downloads/release/python-244/ , https://www.python.org/downloads/release/python-245/ , https://www.python.org/downloads/release/python-246/ :
* The links to https://www.python.org/downloads/release/2.4/ are broken. They should be https://www.python.org/download/releases/2.4/ .
* The links to https://www.python.org/downloads/release/2.4/highlights are broken. They should be https://www.python.org/download/releases/2.4/highlights/ .

On page https://www.python.org/downloads/release/python-250/ :
* The links to https://www.python.org/downloads/release/python-250/highlights are broken. They should be https://www.python.org/download/releases/2.5/highlights/ .
* The links to https://www.python.org/downloads/release/2.4/ are broken. They should be https://www.python.org/download/releases/2.4/ .

On pages https://www.python.org/downloads/release/python-251/ , https://www.python.org/downloads/release/python-252/ , https://www.python.org/downloads/release/python-253/ , https://www.python.org/downloads/release/python-254/ , https://www.python.org/downloads/release/python-255/ , https://www.python.org/downloads/release/python-256/ :
* The links to https://www.python.org/downloads/release/2.5/highlights are broken. They should be https://www.python.org/download/releases/2.5/highlights/ .

Thank you.

**Comment by marksweb** [comment]
@ned-deily Is this all database driven content rather than something that can easily be helped with?

**Comment by ned-deily** [comment]
The source for all of those release pages are in the database rather than in the GIt source. They were migrated over from the old website source at some point. The pages are really only of historical interest; I would hope that almost no one is trying to install long end-of-lifed versions of Python 2.4 or 2.5 from 10 to 15 years ago.
