### ISSUE TITLE
How can I edit the "python --help"?

### ISSUE THREAD

**Issue by Nino-95** [python/pythondotorg#1578]
Can you please tell me where can I find the text file from which "python --help" is build. And can I edit this file?

**Comment by ned-deily** [comment]
This isn't the right place to ask questions about Python code; this is about the python.org website.  See [the Help link](https://www.python.org/about/help/) on any python.org page for a good list of resources.  But the answer to your question is that the Python command line help text is embedded in the interpreter code here:  https://github.com/python/cpython/blob/master/Python/initconfig.c#L28
