### ISSUE TITLE
Download page for 3.6.10 doesn't have binary files

### ISSUE THREAD

**Issue by nutilius** [python/pythondotorg#1581]
Download page for 3.6.10 doesn't have binary files

1. Go to 'Download'
2. Click on 'All releases'
3. Scroll down to 'Looking for a specific release?'
4. Click 'Python 3.6.10'
5. Scroll down to 'Files'

There should be list of binary distributions for download, only source code packages for download are presented.

 - OS: Linux/Windows
 - Browser: Firefox

**Comment by Mariatta** [comment]
My understanding is 3.6.10 is a security fix release and therefore available as source download only. 3.6.8 was the last bugfix release for 3.6 and the last with binary installer. @ned-deily can perhaps confirm.

**Comment by ned-deily** [comment]
Yes, that is correct: once a release cycle reaches the security-fix-only phase, as 3.6.x has, we no longer provide binary installers for it.  3.6.8, the last bugfix release for 3.6, was released iat the end of 2018, almost a year-and-a-half ago. If at all possible, you should consider upgrading to 3.8.x, the current stable bugfix release cycle of Python 3..

Although various documents linked to from the [3.6.10 release page](https://www.python.org/downloads/release/python-3610/) mention that security fix releases are source only, the release page should mention it as well.  I've now added the following to it: "Security fix releases are source-only releases; binary installers are not provided."
