### ISSUE TITLE
Search using search engine with the keyword python and a library keyword returns v 2.0 documentation

### ISSUE THREAD

**Issue by cogmind** [python/pythondotorg#1582]
**Describe the bug**
Search engine with the keyword python and a library keyword returns v 2.0 documentation

**To Reproduce**
1. Go to www.duckduckgo.com
2. Search for python [some object/function]

**Expected behavior**
The current version docs listed among the top results

**Additional context**
Consider configuring robots.txt or the HTML/XML metadata, so that older versions are not indexed. (Alternatively, consider some form of white hat SEO.)

**Comment by Mariatta** [comment]
Thanks for the report. Issues related to Python documentation can be filed in bugs.python.org.
Also, I believe this is already being discussed in [bpo-40562](https://bugs.python.org/issue40562),  Perhaps you can add your suggestion there. Thanks.
