### ISSUE TITLE
Fail to build Solaris 8

### ISSUE THREAD

**Issue by munocat** [python/pythondotorg#1583]
Python/pylifecycle.c: In function ‘_coerce_default_locale_settings‘:
Python/pylifecycle.c:313:5:error: implicit declaration of function ‘setenv’ [-w error-implicit-function-declaration]

**Comment by ned-deily** [comment]
Hi, @munocat, This tracker is for issues with the python dot org website, not with the use or installation of Python itself.  See https://www.python.org/about/help/ for more information.

**Comment by munocat** [comment]
Python sucks then

**Comment by ned-deily** [comment]
@munocat, Sorry, I should have been more explicit: if you want to follow up on the issue, the place to report problems like this is on the Python bug tracker: https://bugs.python.org/.  As you have discovered, this tracker is not monitored closely.
