### ISSUE TITLE
PSF-Landing page

### ISSUE THREAD

**Issue by tieo** [python/pythondotorg#1587]
![image](https://user-images.githubusercontent.com/65707274/82540563-84be3100-9b4f-11ea-83e6-ed29d4b293b8.png)

"So far in 2018"

It's 2020 guys 🙃

**Comment by ewdurbin** [comment]
Thank you @SumriseHD, I've raised this to the PSF Staff [(which is majority women)](http://heyguys.cc/) and we will try to get updated copy soon.

**Comment by ewdurbin** [comment]
We've updated it with numbers from 2019. Thanks again @SumriseHD
