### ISSUE TITLE
Downloads should mention other platforms and alternative implementations

### ISSUE THREAD

**Issue by malemburg** [python/pythondotorg#159]
At the moment, Python only appears to be available for Windows, Mac OS X and Linux, which of course, isn't true.

I've already reenabled the "Other Platforms" link in the downloads menu, but there are several other places where the other platforms and alternative implementations like IronPython, PyPy, Jython, etc. should be listed:
- downloads menu
- doormat (bottom of the page layout)
- /downloads/ page

and possibly others.

The other platforms are listed on this page: http://www.python.org/download/other/

The alternative implementations currently don't have a separate page, but they are included as section on the legacy page: http://www.python.org/download/

**Comment by akuchling** [comment]
I took out /download/other/ because the links are far out of date, and I expect people will search for "python <operating system>" instead of coming to python.org and exploring the /download/ directory.  For example, we link to Python 2.1 for AIX, but when I search for "Python AIX", link #4 or 5 is http://www.perzl.org/aix/index.php?n=Main.Python, which is binaries of Python 2.7.5.  If we aren't going to maintain the page, we should just drop it.

re. the alternate implementations: I think they should be a separate page under the Downloads menu, replacing "Other Platforms" with "Other Implementations".

**Comment by malemburg** [comment]
On 22.02.2014 19:02, akuchling wrote:

> I took out /download/other/ because the links are far out of date, and I expect people will search for "python <operating system>" instead of coming to python.org and exploring the /download/ directory.  For example, we link to Python 2.1 for AIX, but when I search for "Python AIX", link #4 or 5 is http://www.perzl.org/aix/index.php?n=Main.Python, which is binaries of Python 2.7.5.  If we aren't going to maintain the page, we should just drop it.

We should definitely maintain it and update the links to more up-to-date
ones. Removing it would give a wrong picture of Python's portability.

> re. the alternate implementations: I think they should be a separate page under the Downloads menu, replacing "Other Platforms" with "Other Implementations".

Agreed.

## 

Marc-Andre Lemburg

**Comment by ned-deily** [comment]
Georg changed the "Linux" box to "Source".  To match I changed the box text: "Looking for Python with a different OS? Python for Windows, Linux, or Mac OS X." to "[...] Python for Windows, Mac OS X, Other"

**Comment by malemburg** [comment]
On 24.02.2014 11:34, ned-deily wrote:

> Georg changed the "Linux" box to "Source".  To match I changed the box text: "Looking for Python with a different OS? Python for Windows, Linux, or Mac OS X." to "[...] Python for Windows, Mac OS X, Other"

I think using the list from the menu would be more inclusive:

"Source code, Windows, Mac OS X, Linux, Other Platforms"

Please note that we want to promote and market how portable Python is. This
also means mentioning the names of the most popular platforms on the site.

## 

Marc-Andre Lemburg

**Comment by ned-deily** [comment]
But we only have three options as far release files go: Windows installers, OS X installers, and source tar balls. And the Release objects and Operating System objects seem to be tied together in deciding what files to present on the download buttons.  In that text in the box, we could add a duplicate for Linux that would also point to Source.  Other options?

**Comment by malemburg** [comment]
On 24.02.2014 11:53, ned-deily wrote:

> But we only have three options as far release files go: Windows installers, OS X installers, and source tar balls. And the Release widget and Operating System widgets seem to be tied together in deciding what files to present on the download buttons.  In that text in the box, we could add a duplicate for Linux that would also point to Source.

Sounds like a good idea. (Note: This is about marketing Python, not
functionality :-))

BTW: I think we need to add more text to those three generated download
pages. A lot on context and additional information which was available
on the legacy site under http://legacy.python.org/download/ is now
missing, e.g. the GPG key verification instructions, the mention that
Python is OSI certified, pointers to PyPI, documentation and other
resources a user new to Python may be interested in.

## 

Marc-Andre Lemburg

**Comment by malemburg** [comment]
I've added a new page for alternative implementations to the menu.

This is verbatim copy of the section under the old /download/ page.

## 

Marc-Andre Lemburg

**Comment by ned-deily** [comment]
The lack of GPG info was brought up a couple of days ago on the redesign mailing list.  It sounded like Frank was going to add a field for it to the release files object.

As suggested, I've added back a "Linux" button that also links to the source release page.

**Comment by frankwiles** [comment]
Hi Everyone, 

Just added options to allow pre_releases to be marked.  They'll be visible on the site, but not the default Python 2/3 versions in the Download Buttons.  Also added a URLField to link to the GPG Signatures.

**Comment by ncoghlan** [comment]
I don't quite recall why, but I ended up clicking through the download pages on Linux this evening, and linking just to the source releases for Linux isn't quite right - by far the easiest way to get Linux is through the system package manager, and most Linux systems will already have either Python 2 or 3 installed.

I'll grant most Linux users will already know that, but the fact that we don't provide pre-built Linux binaries because the individual distros already take care of doing so is worth emphasising. We may also want to ensure we explain how to get Python 3 on distros where it needs a bit of extra work (I'm mainly thinking of Software Collections on RHEL and Centos: http://wiki.centos.org/AdditionalResources/Repositories/SCL)

**Comment by berkerpeksag** [comment]
Can this issue be closed? I read the discussion again and it looks like there is nothing left to do in this issue.

**Comment by malemburg** [comment]
I think it would be helpful to add a page "Unix" and menu entry which then lists repo package pages of popular distributions for Linux, FreeBSD, etc.

Pointing people to the source distribution doesn't feel like a good approach.

But perhaps this should be tracked in a new ticket...

**Comment by ncoghlan** [comment]
I agree closing this would make sense - I filed #1156 to discuss the question of how to provide pointers to our downstream redistributors (both community-driven and commercial)

**Comment by berkerpeksag** [comment]
Closing this then, thank you for quick responses!
