### ISSUE TITLE
Update "pypi.python.org" to "pypi.org" on Download page

### ISSUE THREAD

**Issue by brainwane** [python/pythondotorg#1593]
**To Reproduce**

"Other Useful Items" within https://www.python.org/downloads/ says:
> Looking for 3rd party Python modules? The [Package Index](http://pypi.python.org/pypi) has many of them.

pointing to http://pypi.python.org/pypi , the old PyPI site.

**Expected behavior**
As of 2018, PyPI has moved to pypi.org; it would be nice to point directly there instead of causing a redirect.

**Additional info**
I seem to have the ability to edit the Downloads page within the CMS, but it seemed to have obsolete info within the page text, so I assume that's not the right place to edit this page's text.

**Comment by hugovk** [comment]
Please see PR https://github.com/python/pythondotorg/pull/1594.

**Comment by brainwane** [comment]
Thank you!
