### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by Nagarjuna05** [python/pythondotorg#1596]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Ex. It would be great if [...]

**Describe alternatives you've considered**

**Additional context**

**Comment by Nagarjuna05** [comment]
I have a doubt on installation of python.As my computer processor is intell related but after installation of python it is showing Amd64  ? is there any fault in my laptop?
![Screenshot (34)](https://user-images.githubusercontent.com/64464046/83387992-4d7f3800-a40b-11ea-928c-ab223d680910.png)
![Screenshot (35)](https://user-images.githubusercontent.com/64464046/83387998-4fe19200-a40b-11ea-89f8-9e92960b63ed.png)

**Comment by abhijeet-singh800** [comment]
@Nagarjuna05 


The AMD64 or x86-64 or x64 is a 64-bit processor architecture invented  by AMD. (But not just limited to AMD Processors) This allows your PC  to simultaneously process both 32-bit and 64-bit software at same time.


Finally it doesn't mean that you PC is faulty. 

Have an nice day..

**Comment by MANISH007700** [comment]
> I have a doubt on installation of python.As my computer processor is intell related but after installation of python it is showing Amd64 ? is there any fault in my laptop?
> ![Screenshot (34)](https://user-images.githubusercontent.com/64464046/83387992-4d7f3800-a40b-11ea-928c-ab223d680910.png)
> ![Screenshot (35)](https://user-images.githubusercontent.com/64464046/83387998-4fe19200-a40b-11ea-89f8-9e92960b63ed.png)



NO , there is no fault in you pc.Its just that amd can process both 32-bit and 64 bit simultaneously

**Comment by ned-deily** [comment]
Hi, @Nagarjuna05. This tracker is for issues with the python dot org website, not with Python or installing Python.  See https://www.python.org/about/help/ for more information.
