### ISSUE TITLE
Changes to PSF membership name/email not reflected by voting system

### ISSUE THREAD

**Issue by daisylb** [python/pythondotorg#1601]
**Describe the bug**

I have changed the "Legal name", "Preferred name", and "Email address" fields on the "Edit your PSF Membership" page some time ago, but mail is still being sent by "Helios Voting Administrator <system@heliosvoting.org>" to my deadname and old email address.

**To Reproduce**

1. Be a PSF member with voting rights.
2. Change the "Legal name", "Preferred name", and "Email address" fields to new values.
3. Wait for the next PSF election. 

**Expected behavior**

Mail is sent to the updated email address, and the updated preferred name is used to address the recipient in the email body.

**Screenshots**

![Screen Shot 2020-06-08 at 10 15 32](https://user-images.githubusercontent.com/473960/83983919-47d8a380-a971-11ea-9df4-1026b0780e1b.png)
![Screen Shot 2020-06-08 at 10 16 25](https://user-images.githubusercontent.com/473960/83983920-4a3afd80-a971-11ea-8699-f47b46e4af02.png)

**Desktop:**

 - OS: macOS Catalina
 - Browser Firefox
 - Version 77.0.1

**Smartphone:**

N/A

**Additional context**

I've also filed #1566 which is a separate but related issue.

**Comment by daisylb** [comment]
Two years later, I'm still getting deadnamed by Helios 🙃

**Comment by Mariatta** [comment]
I'm really sorry. I'm not sure who's involved in the Helios administration.
 @ewdurbin is this something you can look into?

**Comment by ewdurbin** [comment]
Hi! Please email psf-elections@python.org to get this rectified in the database where your record is stored. Please include the email address the ballot was sent to.

Records for membership unfortunately live in multiple systems and depending on membership type, python.org is not necessarily the source of truth in question.

**Comment by daisylb** [comment]
Thanks both for the response! I'll send an email, and hopefully that should resolve the situation for me specifically at least.

For the general case, given that there's no indication in the python.org UI that this is the case though, I'd like to suggest that the python.org UI should display:

- at least, some text explaining that python.org may not be the source of truth for the member in question; at best, exactly what system _is_ the source of truth for the currently logged-in member based on their membership type
- Instructions or advice on how to go about having the data changed

Ideally, PSF members who find themselves in my position in the future shouldn't have to go through the process of thinking their details have been updated, discovering much later that they haven't, and then having to go spelunking around GitHub to find this issue and Ee's comment above to discover the appropriate email to contact.
