### ISSUE TITLE
syntax error with the automatically printed message in python 3.8.3 and 3.8.2

### ISSUE THREAD

**Issue by Sleeper-73** [python/pythondotorg#1603]
The message that is automatically printed on the screen upon opening the program is being marked as "Invalid Syntax" even though there does not seem to be anything wrong.
here is a screenshot for reference:
![example for devs](https://user-images.githubusercontent.com/66646854/84081234-93a83e80-a9ab-11ea-9f7d-52aba7c48c08.PNG)

**Comment by Mariatta** [comment]
This issue tracker is for issues related to the python.org website. The issue tracker for Python programming language is at bugs.python.org.

From the screenshot, I did not see the "Invalid Syntax" error message, so it is not clear whether Python is the one producing the error message you complaining about, so maybe it is not even the bug with Python.

**Comment by Sleeper-73** [comment]
here is a better screenshot including the error message:
![example for devs 2](https://user-images.githubusercontent.com/66646854/84184888-26a0b180-aa5c-11ea-8ff9-cdcf2b813782.PNG)
