### ISSUE TITLE
Python 3.8.3 And Now For Something Completely Different

### ISSUE THREAD

**Issue by BoCoKeith** [python/pythondotorg#1606]
Okay.  It's not *really* a bug.  Nor is it is at all important.  But...

On the Python 3.8.3 release page (https://www.python.org/downloads/release/python-383/), Mr. Anemone was actually played by Graham Chapman and not John Cleese (https://montypython.fandom.com/wiki/Flying_Lessons).

**Comment by Mariatta** [comment]
cc @ambv

**Comment by ambv** [comment]
Haha, this is amazing. Thanks, man. I just fixed it 👯

**Comment by Mariatta** [comment]
Thanks! Closing since it's been fixed.

**Comment by BoCoKeith** [comment]
The Monty Python fans of the world applaud you heartily.
