### ISSUE TITLE
Package installation issue

### ISSUE THREAD

**Issue by iesperson** [python/pythondotorg#1608]
Installed easily on local desktop, dev , dr windows servers. Few packages installed with no issues on prod but few give: ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE.  Getting warning for pip version - Can't upgrade pip as well: **python -m pip install --upgrade pip   
Collecting pip   Downloading https://files.pythonhosted.org/packages/43/84/23ed6a1796480a6f1a2d38f2802901d078266bda38388954d01d3f2e821d/pip-20.1.1-py2.py3-none-any.whl
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine
 the package contents carefully; someone may have tampered with them.
    pip from https://files.pythonhosted.org/packages/43/84/23ed6a1796480a6f1a2d38f2802901d078266bda38388954d01d3f2e821d/pip-20.1.1-py2.py3-none-any.whl#sha256=b
27c4dedae8c41aa59108f2fa38bf78e0890e590545bc8ece7cdceb4ba60f6e4:
        Expected sha256 b27c4dedae8c41aa59108f2fa38bf78e0890e590545bc8ece7cdceb4ba60f6e4
             Got        b3446e608f8af9a9fe4151e8fbb261bfe66de6261868d20796a6a97f70df6e3b

WARNING: You are using pip version 19.2.3, however version 20.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command._

**Comment by hugovk** [comment]
This repo is for the python.org website. Please close this here and instead report at https://github.com/pypa/pip

**Comment by iesperson** [comment]
moved to https://github.com/pypa/pip
