### ISSUE TITLE
Update Windows download popup for 3.9

### ISSUE THREAD

**Issue by zooba** [python/pythondotorg#1611]
Getting this request in early: Python 3.9 will drop support for Windows 7, which still makes up about 20% of our downloads, and so we should warn users that it won't work.

Currently, this popup has a warning about Windows XP:
![image](https://user-images.githubusercontent.com/1693688/86855296-f62b5200-c0b1-11ea-9d00-01860c35161d.png)

We should update it to read "Note that Python 3.9+ cannot be used on Windows 7 or earlier"

I think we should also update the link to point at the 64-bit installer. All the best data I can get shows that 32-bit OS makes up less than 10% (less than 1%, depending on relevant filters), and I believe the issues we see with third parties not supporting 32-bit will now outweigh users attempting to install on 32-bit OS.

Alternatively, we can add a second button for the 32-bit installer and clearly label them both as "Python 3.9.x 64-bit" // "Python 3.9.x 32-bit" (adding @ambv in case this bit is under release manager control).

Also see #1592, regarding adding a link to the Store package (and #1370 from last time we did it). The link for 3.9 is https://www.microsoft.com/store/apps/9P7QFQMJRFP7

**Comment by aasthashukla1** [comment]
Hey, Zooba!

I am new to GitHub open-source contribution community and would love to have this as my first contribution.

Do you believe it would be possible for me to do this?

**Comment by ned-deily** [comment]
It's an easy matter to change which one of the release files per platform are associated with the existing download button.  The release manager can easily change existing releases; a minor change to one of the release scripts will update the default.  We can also easily update the warning text.  Adding a second download button or a hierarchy of download links would be much more involved, e.g. real code changes!  If you and @ambv are OK with those first two changes, I can make them.

**Comment by ned-deily** [comment]
@aasthashukla1, thanks for the offer!  The python.org website infrastructure is spread out over GitHub repos and a content management system database.  These proposed changes affect the latter so can't be done via the usual Github PR mechanism.  Keep an eye out for other opportunities!

**Comment by zooba** [comment]
Thanks Ned!
