### ISSUE TITLE
Incorrect menu border alignment

### ISSUE THREAD

**Issue by lospejos** [python/pythondotorg#1616]
**Describe the bug**
When visiting website https://www.python.org/downloads/release/python-384/ using browser Mozilla Firefox 79.0b8 (64-bit) on Windows 10 (64-bit), menu border seems to be rendered incorrectly (see screenshot).

**To Reproduce**
1. Go to https://www.python.org/downloads/release/python-384/
2. Hover mouse on "About" menu item
2. See error: "Python Brochure" bottom line is upper than right part of menu item, the bottom menu item line is not aligned properly.

**Expected behavior**
Menu item bottom line is aligned just like in other menu items.

**Screenshots**
![image](https://user-images.githubusercontent.com/4608475/87829330-8bcf9a00-c887-11ea-8e86-f0f1549a04b2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit
 - Browsers: Mozilla Firefox 79.0b8 (64-bit), Chromium version 85.0.4148.0 (official build),
 - Version: specified on browsers line

**Smartphone (please complete the following information):**
 - Device: None tested
 - OS: N/A
 - Browser N/A
 - Version N/A

**Additional context**
OS default language and locale: Russian

**Comment by iprasandeep** [comment]
Hey, I want to work on this issue please assign me?

**Comment by hugovk** [comment]
I can reproduce (Chrome, macOS):

<img width="1190" alt="image" src="https://github.com/user-attachments/assets/2632dfde-167e-4553-bc0f-8b831e91d865">

> Menu item bottom line is aligned just like in other menu items.

It's aligned the same as this menu, where the info box is also longer than the menu items:

<img width="1184" alt="image" src="https://github.com/user-attachments/assets/dfc04e08-7a80-41ca-b73c-8818b7019efa">

However, it's different to these other menus, but they have longer menu items than info box:

<img width="1192" alt="image" src="https://github.com/user-attachments/assets/24db3265-14ff-4a38-8d54-41b3b2bb4b2f">

<img width="1190" alt="image" src="https://github.com/user-attachments/assets/6ee93969-c698-4535-bd63-567ba9463569">

And so on.

So I think it's fine.

It could be argued that they should all align, but I think it's a minor thing and we can close this.

Thank you anyway for the report!
