### ISSUE TITLE
Python core-mentorship page's original proposal link is broken.

### ISSUE THREAD

**Issue by rishabh96b** [python/pythondotorg#1618]
**Describe the bug**
The link to the Python Core Mentorship's original proposal link is broken. Clicking on the link results in- 
```
The requested URL /mailman/python-dev/2011-March/110077.html was not found on this server.

Apache/2.4.39 (Ubuntu) Server at mail.python.org Port 443
```

**To Reproduce**
1. Go to: https://www.python.org/dev/core-mentorship/#introduction
2. Click on [`original proposal`](https://mail.python.org/pipermail/python-dev/2011-March/110077.html/)

**Expected behavior**
The link should show the proposal.

**Screenshots**

![SS](https://media.giphy.com/media/lQIy8gNSs14Dy4WFcC/giphy.gif)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: All
 - Version: NA

**Additional context**
The link adds `/` at the end of URL which is creating this issue. I can work on this if possible.

**Comment by hugovk** [comment]
Remove the `/` from the end of the URL:

:x: https://mail.python.org/pipermail/python-dev/2011-March/110077.html/
✅  https://mail.python.org/pipermail/python-dev/2011-March/110077.html

**Comment by rishabh96b** [comment]
Correct @hugovk ! But the original link in the page is with `/` only.

**Comment by hugovk** [comment]
Looks like this link isn't in the repo, so an admin will need to edit it in the database. Thanks for the report!

**Comment by rishabh96b** [comment]
Yep, I tried to :mag: the repo but didn't get the link anywhere.

**Comment by berkerpeksag** [comment]
Right, the contents of all pages are stored in database. I've just fixed the broken URL, thank you!
