### ISSUE TITLE
Need link to Glossary from https://www.python.org/doc/

### ISSUE THREAD

**Issue by robertbyers1111** [python/pythondotorg#1620]
**Describe the bug**

It is very difficult to find the glossary if the user starts his/her navigation from www.python.org/doc/. It is true that there is a link to the glossary from docs.python.org/3/, but many users start their document navigation from www.python.org/doc/

Almost every link on the front page of docs.python.org/3/ has an equivalent link in www.python.org/doc/. Why not the glossary? This creates a confusing inconsistency leaving the user wondering where is the correct place to start navigating the documents. In fact, www.python.org/doc/ _looks_ like a perfectly natural place to find a link to the glossary - therefore why would the user look anywhere else?

To compound matters, using the documentation search tool does not return any result with a link to the glossary either.

**To Reproduce**
1. Go to https://www.python.org/doc/
2. Click on (nothing)
3. Scroll down to end of page
4. See that there is no mention of a glossary

**Expected behavior**
I would have expected to be able to find a link to the glossary.

**Screenshots**
![image](https://user-images.githubusercontent.com/68861709/88560416-1a68b780-cffc-11ea-8863-5876d1f41d47.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge
 - Version  84.0.522.44

**Smartphone (please complete the following information):**

**Additional context**
n/a

**Comment by sk1122** [comment]
I will add this
