### ISSUE TITLE
module 'ibm_db_dbi' has no attribute 'Connection'

### ISSUE THREAD

**Issue by Sushmita-24** [python/pythondotorg#1621]
The same line of code was working fine before I upgraded pycharm from 2019.2.2 to 2020.0.0, then I again degrade to 2019.2.2 but still same issue.

**Comment by Sushmita-24** [comment]
DB = "DATABASE=" + config.get('BMS', 'DATABASE') + ";HOSTNAME=" + config.get('BMS', 'HOSTNAME') +";PORT=" + config.get('BMS', 'PORT') + ";PROTOCOL=TCPIP;UID=" + config.get('BMS', 'UID') + ";PWD=" + config.get('BMS','PWD') + ";"
conn = ibm_db.connect(DB,"","")
conn1 = ibm_db_dbi.Connection(conn)
 This is my code, which was working completely fine.

**Comment by berkerpeksag** [comment]
This tracker is for issues with www.python.org. We don't maintain any third-party Python packages. Please use https://github.com/ibmdb/python-ibmdb instead.
