### ISSUE TITLE
wrong date for our success story

### ISSUE THREAD

**Issue by adalke** [python/pythondotorg#1626]
I just received an odd email concerning my success story listed at https://www.python.org/success-stories/python-for-collaborative-drug-discovery/ .

I say "odd" because the author asked about my 2018 story. And indeed, that URL says "October 2018".

But we wrote that back in 2003, which you can see at https://legacy.python.org/about/success/astra/ .

In 2018, none of the authors were affiliated with the organizations listed there. And most of the C-Lab middle layer had been rewritten in Java.

Thus, that posting tells a misleading story.

If the date cannot be changed, I would rather that the success story be withdrawn.

Thanks in advance for your help,

Andrew Dalke <dalke@dalkescientific.com>

**Comment by hugovk** [comment]
At least this 2004 also has "October 2018":

* https://legacy.python.org/about/success/forecastwatch/
* https://www.python.org/success-stories/python-to-help-meteorologists/

**Comment by berkerpeksag** [comment]
That's the date that success stories moved to Django: https://github.com/python/pythondotorg/blob/e60fba59aa949838808fd6f28f5e146c77d550f0/templates/successstories/story_detail.html#L34 Showing `created` field doesn't make much sense so perhaps we can just remove it from the template.

**Comment by mwichmann** [comment]
Any news on this?

**Comment by Mariatta** [comment]
I've just created a PR for removing the date from the template. https://github.com/python/pythondotorg/pull/1635
