### ISSUE TITLE
The module 'collections' is deprecated since version 3.3

### ISSUE THREAD

**Issue by web-sys1** [python/pythondotorg#1627]
**Is your feature request related to a problem? Please describe.**
I woke up to the announcement. After I went to the [page](https://docs.python.org/3/library/collections.html), message says: _<ins>**Deprecated since version 3.3, will be removed in version 3.10**</ins>: Moved Collections Abstract Base Classes to the collections.abc module. For backwards compatibility, they continue to be visible in this module through Python 3.9._

**Describe the solution you'd like**
It would be great if something changed in the interface. the functions like **namedtuple**() that assign meaning to each position in a tuple and allow for more readable, self-documenting code or naming subclasses would be merged to python 3.10 as **TupleType** instead, to collections.abc in another way. Otherwise it would be missed. It would be also great if Python versions are up-to-date and the **definition class** should work with same function for defining subclasses.

**Comment by Mariatta** [comment]
For issues with Python documentation, please file at bugs.python.org.
