### ISSUE TITLE
No way to do prereleases

### ISSUE THREAD

**Issue by birkenfeld** [python/pythondotorg#163]
There is no way to mark a release as a prerelease.
Prereleases should be handled differently in a number of ways:
- not used as the main "download newest version" target
- not listed in the normal "list of releases", but somewhere different

**Comment by ned-deily** [comment]
Update: We (in release management) have struggled through trying to get the 3.3.5rc1 and 3.4.0rc2 pre-releases out the door this weekend.  As a partial workaround to the lack of pre-release support, I've added a new "download/pre-releases" page (http://python.org/download/pre-releases/) and added a link to it from the main "downloads" page (http://www.python.org/downloads/): "Want to help test development versions of Python? Pre-releases".  That doesn't solve the issue of only two download buttons on the downloads page or the downloads pop-up.  By creating a 3.3.5rc1 Release object, that has replaced the desired "3.3.4" button.  To avoid further problems, Larry did not create a "3.4.0rc2" Release object; that can wait until the final release unless something is fixed before then.

**Comment by fcurella** [comment]
We could add a boolean `is_a_release` flag on the `Download` model, and only list releases in the pop-over. That will also allow us to visually differentiate releases from non-releases on the downloads page

**Comment by fcurella** [comment]
the field should be named something different than `is_a_release`, since the model is actually called `Release` and `Release.is_a_release` wouldn't make much sense. So feel free to suggest better names.

**Comment by birkenfeld** [comment]
`is_prerelease` should be fine.

While we're changing the Release model, I would also add a text description that replaces the body of the separate release page (the text on http://www.python.org/download/releases/3.3.4/ up to the "download" heading).

**Comment by fcurella** [comment]
waiting on #200 to be merged, then I'll add a migration and add the field to the API

**Comment by fcurella** [comment]
closed in 9db3019be8cd59444e8e3fcd66de324a60759277

**Comment by ned-deily** [comment]
See Issue #241.
