### ISSUE TITLE
Front-page code example wording

### ISSUE THREAD

**Issue by 8vasu** [python/pythondotorg#1637]
When https://www.python.org/ is visited, the user is presented with sample code that says
"# Python 3: Fibonacci series up to n...". A "series" is a limit of a sum. This should be changed
to "# Python 3: Fibonacci sequence up to n...".

**Comment by aeros** [comment]
This was roughly posted by me earlier on the core-mentorship ML thread where this was originally brought up, but I'll go into a bit more detail here.

I can agree that the example on the front of python.org may not perfectly fit the mathematical definition of a "series" ("a limit of a sum"). However, it's worth also considering the more casual/commonplace definition of "series", which is likely what the example was using:

According to [Mariam-Webster](https://www.merriam-webster.com/dictionary/series), a series can be defined as "a number of things or events of the same class coming one after another in spatial or temporal succession".

While the specific mathematical definition is generally more relevant in an academic context and some engineering fields, in the context of a very broad example that's targeted at potential first-time Python users, I think the more casual definition is perfectly suitable. More importantly, I don't think that changing "series" -> "sequence" would significantly benefit that target audience.

(It wouldn't necessarily hurt them either, but it requires a tangible practical benefit to justify making the change to a front page example. I'm personally not seeing that benefit.)

**Comment by aeros** [comment]
Also, I'd suggest making the title of the issue a bit more specific, e.g. "Front-page code example wording" or something along those lines. "Wording bug" could refer to any page on python.org.

**Comment by 8vasu** [comment]
I understand what you mean. This was just a suggestion. You may close this if you think it is unnecessary trouble.

**Comment by aeros** [comment]
I'm actually unable to close the issue in pythondotorg, as the website is considered outside of the "python core repositories". But, it doesn't hurt to have a second opinion here.

Regardless of the eventual outcome of the issue, thanks for investing your time in making a suggestion. It's appreciated either way. :-)

**Comment by 8vasu** [comment]
:)
