### ISSUE TITLE
download page still shows 3.8.5 instead of 3.8.6

### ISSUE THREAD

**Issue by helmarw** [python/pythondotorg#1642]
![image](https://user-images.githubusercontent.com/10408121/94422778-e474ba80-0187-11eb-80dc-1f4951486e22.png)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mhsmith** [comment]
The source and binary files can be downloaded here: https://www.python.org/downloads/release/python-386/

However, 3.8.6 is still missing from most other pages:
* The default download links still point at 3.8.5.
* https://www.python.org/downloads/source/ says "No files for this release"
* https://www.python.org/downloads/ doesn't list 3.8.6 at all.

This means that 6 days after the release of 3.8.6, virtually all users must still be downloading 3.8.5.

**Comment by Mariatta** [comment]
cc @ambv. Is this something you usually do?

**Comment by mhsmith** [comment]
https://www.python.org/dev/peps/pep-0569/ hasn't been updated either.

**Comment by hugovk** [comment]
> [python.org/dev/peps/pep-0569](https://www.python.org/dev/peps/pep-0569/) hasn't been updated either.

Please see PR https://github.com/python/peps/pull/1635 to update the PEP.

**Comment by xrisk** [comment]
This issue seems to have been resolved, but there’s still an incorrect link here:

(the Python 3 link in the Sources panel)

![image](https://user-images.githubusercontent.com/10669859/95021518-0c37b700-068f-11eb-8147-15aa8b9c93b8.png)

Perhaps we could automate this process?

**Comment by mhsmith** [comment]
On a Windows machine, the yellow download button at the top of https://www.python.org/downloads/ now points to 3.8.6, but when you hover over "Downloads" in the top bar, the button that pops up still points to 3.8.5.

**Comment by ghost** [comment]
Kindly check  now the bug is now resolved

**Comment by mhsmith** [comment]
Yes, 3.8.6 is now listed everywhere it should be, and 3.9.0 is the default version, so this issue can be closed.
