### ISSUE TITLE
make python3 as default in macOS 

### ISSUE THREAD

**Issue by anukaal** [python/pythondotorg#1652]
alias python==python3 ?? Is this command is enough for making the python3 as the default in macOS??

**Comment by marksweb** [comment]
https://opensource.com/article/19/5/python-3-default-mac

**Comment by ned-deily** [comment]
Hi, there has been much discussion about whether and when to make such a change. See, for example, https://bugs.python.org/issue41996.  This issue tracker is for problems with the python.org website, not for issues with Python itself.
