### ISSUE TITLE
The Download pop-up buttons do not always get updated promptly

### ISSUE THREAD

**Issue by ned-deily** [python/pythondotorg#167]
While we've experimented with various solutions to the Release objects issues noted elsewhere, the release managers made various changes to the set of published releases (using the Downloads -> Releases interface).  This has had the effect of changing the contents of the buttons on the Downloads pop-up.  It seems that the values of the buttons do not change immediately when the releases are deleted or possible updated (possibly with a release that was not fully populated with release files for the operating system being viewed from).  On several occasions, the Python 3 button has had no text or link associated with it; this is the case at the moment for me.  It's not clear how to reproduce easily without negatively impacting the site.

**Comment by ned-deily** [comment]
This is currently a problem again at the moment: the python 3 buttons on the download supernav popup are empty after the 3.4.2 release was entered.  Can somebody fix this please?

**Comment by ned-deily** [comment]
It looks like the button should get updated in downloads/models.py update_download_supernav.  Is this being triggered?  Or is there a problem with all affected pages not being regenerated?  Or a caching issue?

**Comment by frankwiles** [comment]
This is actually caused by #487 closing this as that fix will resolve it.
