### ISSUE TITLE
https://www.python.org/downloads/ fails to load JS/CSS

### ISSUE THREAD

**Issue by The-Compiler** [python/pythondotorg#1672]
When opening https://www.python.org/downloads/, the JS/CSS files fail to load with a 404, causing the webpage to look like this:

![image](https://user-images.githubusercontent.com/625793/98946176-d5f22080-24f3-11eb-81a1-8cc011fb4428.png)

This seems to happen because the following files are missing:

https://www.python.org/static/stylesheets/style.30afed881237.css
https://www.python.org/static/js/main-min.54f74dc425e5.js

Thanks to Michael Felt for originally [reporting this](https://mail.python.org/archives/list/python-dev@python.org/message/6TFD7LVJOA33YFXSI4RGLBWRC7STFYCV/) on the python-dev mailinglist.

**Version information:**

 - OS: Archlinux
 - Browser: Chromium
 - Version: 86.0.4240.198

**Comment by crwilcox** [comment]
Looks to be resolved for me :)

**Comment by ewdurbin** [comment]
This appears to have been due to some bad pages being cached while a deploy was underway.

I'm going to investigate and see what happened, but a new deploy of the site resolved the issue.

**Comment by jeffreymcclain** [comment]
The sub-pages still seem to have the issue:

- https://www.python.org/downloads/windows/
- https://www.python.org/downloads/source/
- https://www.python.org/downloads/mac-osx/

**Comment by jeffreymcclain** [comment]
@ewdurbin , multiple sub-pages still have this problem.
Apologies for bothering you, but I wasn't sure if you saw my comment from yesterday and/or are aware of the problem.

**Comment by ewdurbin** [comment]
I'm no longer seeing those pages as broken, it may have still been cached as we perform "soft purges".

This will definitely be further investigated and addressed at some point.

**Comment by jeffreymcclain** [comment]
All good, I actually just refreshed the three sub-pages again and now they all appear normal, so it likely was just cached on my local machine since yesterday.

**Comment by pnfcre** [comment]
Hi there, I can reproduce this issue again (June 7, 2021).

**Comment by The-Compiler** [comment]
I should probably be closing this, as the original issue has long been resolved - thanks everyone! :slightly_smiling_face:
