### ISSUE TITLE
Adding number to a declared 2 dimension list

### ISSUE THREAD

**Issue by ghost** [python/pythondotorg#1686]
**Describe the bug**
So basically the bug that I found was about adding a number to a sub-list.
If you declare li1 as li1=[[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]] in the code below then the code is working as it should do.
Although if you create the list called li1 with the same way how I did in the code below (which has the same outcome in terms of looking at that 2 dimension list) then the output is different and in fact false.

**To Reproduce**
`li1=[[0]*4]*4
for x in range(4):
    li1[0][1]+=1
    print(li1)`

**Expected behavior**
Expected output:
[[0, 1, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
[[0, 2, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
[[0, 3, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
[[0, 4, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
The output that I got:
[[0, 1, 0, 0], [0, 1, 0, 0], [0, 1, 0, 0], [0, 1, 0, 0]]
[[0, 2, 0, 0], [0, 2, 0, 0], [0, 2, 0, 0], [0, 2, 0, 0]]
[[0, 3, 0, 0], [0, 3, 0, 0], [0, 3, 0, 0], [0, 3, 0, 0]]
[[0, 4, 0, 0], [0, 4, 0, 0], [0, 4, 0, 0], [0, 4, 0, 0]]

**Screenshots**
[https://ibb.co/6YG5LTm](url)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version  86.0.4240.198

**Smartphone (please complete the following information):**
 - Device: iPhone SE (2016 version)
 - OS: 14.0.1
 - Browser Safari
 - Version 14

**Comment by Mariatta** [comment]
This issue tracker is for issues with python.org website, not for issues about CPython itself.

Perhaps you can first raise your issue in the python-list mailing list. If it is indeed a bug with CPython, then it can be reported at bugs.python.org.
