### ISSUE TITLE
Add RISC OS to 'Other Platforms'

### ISSUE THREAD

**Issue by c-jo** [python/pythondotorg#1694]
I have just released a port of Python 3 for the RISC OS operating system - could it please be added to the "Other Platforms" page (https://www.python.org/download/other/)

The old version 2 entry is still there (but commented out) - suggested new entry

<h1>Python for RISC OS</h1>
<p>Python is available for RISC OS, and can be obtained using the PackMan package manager.

**Comment by ewdurbin** [comment]
Updated. Thank you @c-jo
