### ISSUE TITLE
Main doc portal has a weird instance of plain text

### ISSUE THREAD

**Issue by jcgoble3** [python/pythondotorg#1697]
On https://www.python.org/doc/ I notice that on the right side, under the heading "Porting from Python 2 to Python 3", there is one bullet point that is not linked to anywhere and just sits as plain text: "Determine what projects are blocking you from porting to Python 3". It seems like a weird place to have a bullet point of plain text that's quite a bit more specific than surrounding bullets.

Is this line of text supposed to be on a different page? Is it supposed to be linked to another page that explains how to find which projects are blocking you? If the answer to both is no, why is it sitting somewhere where (to me, at least) it looks out of place, and what can be done to make it less jarring and less confusing?

- OS: Debian bullseye
- Browser: Firefox latest stable

**Comment by hugovk** [comment]
Thanks for the report! There's a misplaced `</a>` tag, please see PR https://github.com/python/pythondotorg/pull/1698 to fix it.

**Comment by jcgoble3** [comment]
Thanks for the quick response! I figured that it was some sort of typo, but didn't have the time to investigate the source code.
