### ISSUE TITLE
Run time error

### ISSUE THREAD

**Issue by aishwaryavn** [python/pythondotorg#1699]
RuntimeError: The current Numpy installation ('C:\\Users\\Aishwarya\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86

i have been facing this error inspite of installing all packages properly
please let me know what this error is and how it is to be overcome

**Comment by ewdurbin** [comment]
Hello, this appears to be an issue with either python itself or the numpy package. Please file it with bugs.python.org or https://github.com/numpy/numpy/issues

This tracker is for the python.org website.
