### ISSUE TITLE
https://pypi.org/simple/glob3/ 404 not found

### ISSUE THREAD

**Issue by slapcodes** [python/pythondotorg#1700]
Hi,

Just trying to install Glob3 on a fresh install of Python 3.7 and I am getting an error.

1. Open CMD in admin
2. cd \Python37\Scripts
3. pip3 install glob3

Then I get this error:
ERROR: Could not find a version that satisfies the requirement glob3 (from versions: none)
ERROR: No matching distribution found for glob3

Check https://pypi.org/simple/glob3/, and there is a 404 error

Please fix, thanks.

**Comment by Mariatta** [comment]
This issue tracker is for the python.org website, and not for PyPI. We don't maintain every single packages on PyPI.

If you know who created the glob3 package, you should contact them directly.
It is also possible that the glob3 package does not exists/has never been published to PyPI, therefore the 404 would be accurate.

**Comment by hugovk** [comment]
As it happens the glob3 package was deleted, presumably by the owner, and there wasn't much in it anyway: https://twitter.com/hugovk/status/1332449388950675456

The project used to be at https://github.com/camabeh/glob3.
