### ISSUE TITLE
Calendar events should show the year for events which are not in the current year

### ISSUE THREAD

**Issue by malemburg** [python/pythondotorg#1701]
See e.g. https://www.python.org/events/ the EuroPython conference entries.

![image](https://user-images.githubusercontent.com/6735498/101673932-1a6fce00-3a58-11eb-9ff5-84f0885139b2.png)

**Comment by alvindera97** [comment]
I've sent in a PR: https://github.com/python/pythondotorg/pull/1714 to address this issue. Hopefully it gets reviewed soon as the maintainer of repository is available.

**Comment by alvindera97** [comment]
#1714
