### ISSUE TITLE
planet.python.org is no longer updating

### ISSUE THREAD

**Issue by tseaver** [python/pythondotorg#1703]
The last update was December 07, 2020 04:48 PM UTC (see attached screenshot).
![Screenshot from 2020-12-11 14-10-02](https://user-images.githubusercontent.com/242750/101944414-b1ed3200-3bba-11eb-8529-f6814c7f3d93.png)

**Comment by Mariatta** [comment]
Duplicate of https://github.com/python/planet/issues/446

**Comment by vmuriart** [comment]
its working again. probably ok to close issue
