### ISSUE TITLE
[Download for Mac OS X] Update version

### ISSUE THREAD

**Issue by dduong42** [python/pythondotorg#1704]
The version should be 3.9.1 instead of 3.9.0.

<img width="695" alt="Screen Shot 2020-12-14 at 11 17 10" src="https://user-images.githubusercontent.com/6153296/102091783-0b916e80-3dfe-11eb-8551-b58b23104d94.png">

**Comment by scdub** [comment]
This issue is also present for Windows, the version on the supertab shows 3.9.0:

![image](https://user-images.githubusercontent.com/46331011/102244087-dfdbba80-3ec9-11eb-9987-44fa8f06313a.png)

**Comment by ned-deily** [comment]
Thanks for the reports. Sometimes parts of the website get cached either by the Content Delivery System python.org uses or by individual web browsers.  I believe that was the case here.  Generally, the up-to-date value appears in the button within a few days.
