### ISSUE TITLE
I discovered a bug in python

### ISSUE THREAD

**Issue by HalemoGPA** [python/pythondotorg#1718]
I discovered a bug while using python I checked the code, but it was right.then, I checked the compiler,but it was right. So, I noticed that it is a bug in the language itself

**Comment by Mariatta** [comment]
The bug tracker for Python is at bugs.python.org, not here.

When you file a bug, please be specific, describe the actual behavior, and your expected output. You may want to provide example code or stack trace.

**Comment by HalemoGPA** [comment]
of course I have outputs and checked the code also checked the compiler but
thought I will get paid for this lol

في الخميس، ٧ يناير ٢٠٢١ ٤:١٠ ص Mariatta <notifications@github.com> كتب:
