### ISSUE TITLE
Text overflow on mobile

### ISSUE THREAD

**Issue by tusharsadhwani** [python/pythondotorg#1721]
**Describe the bug**

![image](https://user-images.githubusercontent.com/43412083/104034297-b545fe80-51f6-11eb-93b4-12ad2214af07.png)

When viewed on mobile, there's slight overflow to the right on certain PEP pages, and possibly on other pages as well.

The issue seems to be occuring because of [this](https://github.com/python/pythondotorg/blob/master/static/sass/style.scss#L303) class in the CSS, being used to render inline code snippets or commands within the PEP markdown.

**Expected behavior**

![image](https://user-images.githubusercontent.com/43412083/104035691-744ee980-51f8-11eb-840b-c843c8ae4049.png)

I tinkered with the CSS on [PEP 517 page](https://www.python.org/dev/peps/pep-0517/), and I figured that adding `word-break: break-word` to `<a>` tags, and removing the CSS from the `.pre` tag seems to fix the issue.

**Comment by iprasandeep** [comment]
I want to work on this issue, It is open for contribution ?

**Comment by ewdurbin** [comment]
@prsndp certainly.

**Comment by iprasandeep** [comment]
@ewdurbin Thanks :)

**Comment by cacoze** [comment]
It seems this one was already solved. I couldn't reproduce responsive issues on this link: https://peps.python.org/pep-0517/
