### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [python/pythondotorg#1722]

**Comment by hugovk** [comment]
Duplicate of https://github.com/python/pythondotorg/issues/1278 and https://github.com/python/pythondotorg/issues/1561?

There's a PR: https://github.com/python/pythondotorg/pull/1446

**Comment by tripleee** [comment]
Please revert the title change; it just creates extra work for everyone if we have to click open the issue to figure out what it's about.

**Comment by jai-dewani** [comment]
Should this issue be closed if we already have 2 duplicate issues and a PR already in review?
