### ISSUE TITLE
Python-3.9.1: generate-posix-vars failed for MIPS32 toolchain 

### ISSUE THREAD

**Issue by abhijitsahu** [python/pythondotorg#1723]
Following below steps for cross-compilation for mips32 toolchain.

**Step-1:**
touch config.site
gedit config.site
	Add below two line:
	ac_cv_file__dev_ptmx=no
	ac_cv_file__dev_ptc=no
**Step-2:**
CONFIG_SITE=config.site CC=mipsel-linux-gcc CXX=mipsel-linux-g++ AR=mipsel-linux-ar RANLIB=mipsel-linux-ranlib ./configure --host=mipsel-linux --build=mipsel-linux-gnu --prefix=/home/work_bench/PYTHON/Test-01/Python-3.9.1/my_build --disable-ipv6 --with-openssl=/home/work_bench/ssl/openssl-1.0.2o CPPFLAGS=-L/home/work_bench/ssl/libs CPPFLAGS=-I/home/work_bench/ssl/openssl-1.0.2o/ssl CPPFLAGS=-L/home/work_bench/ssl/openssl-1.0.2o
**Step-3:**
make HOSTPYTHON=./hostpython HOSTPGEN=./Parser/hostpgen BLDSHARED="mipsel-linux-gcc -shared" CROSS_COMPILE=mipsel-linux- CROSS_COMPILE_TARGET=yes HOSTARCH=mipsel-linux BUILDARCH=mipsel-linux-gnu
### Compilation Issue:
Compilation breaks with below error. But compilation works fine for gcc in PC(Ubuntu 18.04).
Could you please suggests? 

```
mipsel-linux-gcc     -Xlinker -export-dynamic -o python Programs/python.o libpython3.9.a -lcrypt -lpthread -ldl  -lpthread -lutil -lm   -lm 
_PYTHON_PROJECT_BASE=/home/abhijit/work_bench/PYTHON/Test-01/Python-3.9.1 _PYTHON_HOST_PLATFORM=linux-mipsel PYTHONPATH=./Lib _PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata__linux_ python -S -m sysconfig --generate-posix-vars ;\
if test $? -ne 0 ; then \
	echo "generate-posix-vars failed" ; \
	rm -f ./pybuilddir.txt ; \
	exit 1 ; \
fi
/bin/sh: 1: python: not found
generate-posix-vars failed
Makefile:615: recipe for target 'pybuilddir.txt' failed
make: *** [pybuilddir.txt] Error 1
```

**Comment by ned-deily** [comment]
This issue tracker is for problems with the python.org website, not for problems with Python itself.  If this issue hasn't yet been resolved, please search first on https://bugs.python.org and, if necessary, open an issue there. Thanks.

**Comment by kunalfleethawks** [comment]
Please install pyton on host machine
