### ISSUE TITLE
"instructions for reporting a Security Issues" link in about/help redirects to wrong content, was /news/security

### ISSUE THREAD

**Issue by dschwoerer** [python/pythondotorg#1724]
**Describe the bug**
The link to reporting a security issue on https://www.python.org/about/help/ is broken, similar to #1537 

**To Reproduce**
1. Go to https://www.python.org/about/help/
2. Click on 'the instructions for reporting security issues.'
3. Be redirected to https://www.python.org/blogs/

**Expected behavior**
Find instructions on how to report security issues.

**Comment by Mariatta** [comment]
Thanks for the report. The correct URL for reporting security issue is at https://www.python.org/dev/security/

Can someone with access update the page, please? 
I don't have the permission to do that. Thanks.

**Comment by sk1122** [comment]
I tried finding https://www.python.org/about/help/ this file in repository, but couldn't find.
Does it exists in this repo or it is on server?

**Comment by tripleee** [comment]
For what it's worth, it looks like the actual contents are hosted inside a private CMS database. I guess @Mariatta's comment above is directed towards whoever has access to that database.

**Comment by Mariatta** [comment]
@berkerpeksag or @ewdurbin is this something one of you can help with? I don't have access to update the CMS content.

Thanks.

**Comment by berkerpeksag** [comment]
Done! Thanks for the report and for the ping.
