### ISSUE TITLE
Refresh of UserDetail view

### ISSUE THREAD

**Issue by ewdurbin** [python/pythondotorg#1729]
When navigating to "Your account" after signing in to www.python.org, a very bare bones "dashboard" is visible to the user.

With #1728 adding additional information/views that will likely be accessed via this area, we should take a look at reorganizing this area of the site and potentially making other improvements to rendering and styling.

At the very least, we should update navigation to be more intuitive, currently the sections are just kind of plopped in there. We should probably organize them in some hierarchy to allow for future expansion.

With the addition of sponsorship, something like:

* Your Account
    * View/Edit Profile
    * Change Password
* Membership
    * View/Edit PSF Membership
    * Nominations
* Sponsorship (if applicable
    * View Sponsorships

Where possible, we should reuse other navigation components and styling.

**Comment by aryanxk02** [comment]
Hey @ewdurbin I am new to Open Source Contribution and would like to contribute to the issues present in this repository. Could you please help me guide through this?? Thank You!

**Comment by ewdurbin** [comment]
Hello @aryanxk02! @berinhard will be working on this. It's also not an _ideal_ candidate for a first issue. If you can identify something else that you might be interested in taking on, please let me know.
