### ISSUE TITLE
Tried to subscribe to newletter but it failed.

### ISSUE THREAD

**Issue by Vulhuter25** [python/pythondotorg#1739]
**Describe the bug**

**To Reproduce**

**Expected behavior**
Tired to subscribe to the newsletter but the subscribe button did not do anything after filling out the form.

**Screenshots**
![image](https://user-images.githubusercontent.com/79723932/109354310-9efa0d80-784b-11eb-8958-403304b969b4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser [e.g. chrome, safari] Firefox 78.7.1esr (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hugovk** [comment]
@Vulhuter25 Did you ever manage to subscribe? If you try again now, does it work? If not, do you have any ad blockers enabled?

https://www.python.org/psf/newsletter/

**Comment by hugovk** [comment]
Let's close this, but please let us know if you need some help.
