### ISSUE TITLE
Python 3.4(RC2) missing from the download page

### ISSUE THREAD

**Issue by vstinner** [python/pythondotorg#174]
It cannot see Python 3.4RC2 on the download page. I cannot see in the news: issue #172. It's like it doesn't exist :-(

The 3.4 release candidate must be present on the download page.

**Comment by ned-deily** [comment]
This is due to #163.  As an interim workaround, we've added a link to Pre-releases in the text at the top of the Downloads page (http://www.python.org/downloads/) "Want to help test development versions of Python? Pre-releases"

**Comment by vstinner** [comment]
Oh missing this sentence, in fact, I didn't click on the Download page. I expected a "Prerelease" item directly in the menu.
