### ISSUE TITLE
Loss of content in simple (but oversize) SAX parsing

### ISSUE THREAD

**Issue by ridgerat** [python/pythondotorg#1745]
== The Problem ==

I have observed a "loss of data" problem using the Python SAX parser, when processing an oversize but very simple xhtml file. The file represents a single N x 11 data table.  W3C "tidy" reports no xml errors.  The table is constructed in an entirely plausible manner, using *table*, *tr,* and *td* tags to define the table structure, and *p* tags to bracket content, which consists of small chunks of quoted text.  There is nothing pathological, no extraneous whitespace characters, no empty data fields. 

Everything works perfectly in small test cases.  But when a very large number of rows are present, a few characters of content strings are occasionally lost.  But here's the strange part.  The pathological behavior disappears (or moves to another location) when one or more non-significant whitespace characters are inserted at an arbitrary location early in the file... e.g. an extra linefeed before the first *<tr>* tag. 

== Context ==

I have observed identical behaviors on desktop systems using an Intel Xeon E5-1607 or a Core-2 processor, running 32-bit and 64-bit Linux operating systems, using Python 3.8.5, 3.8, 3.7.3, and 3.5.1.  

== Reproducing the Problem ==

Run the following command line.  Sorry that the test data is so bulky (even at 0.5% of original size), but bulk appears to be a necessary condition to observe the problem. 
~~~  
python3  EnchXMLTest.py  EnchTestData.html 
~~~ 
[EnchXMLTest.py.zip](https://github.com/python/pythondotorg/files/6133717/EnchXMLTest.py.zip)
[EnchTestData.html.zip](https://github.com/python/pythondotorg/files/6133718/EnchTestData.html.zip)

The script invokes the SAX parser and generates messages on stdout. Using the original test data as provided, the test should run correctly to completion.  Now modify the test data file, deleting the extraneous comment line (there is only one) found near the top of the file.  Repeat the test run, and this time **look for missing content characters** in parsed content fields.

== Any guesses? ==

I speculate that something abnormal can occur at the seams between large blocks of buffered text.  The presence or absence of an extra character early in the data stream results in a corresponding shift in content location at the end of the buffer, enough to incite or avoid problematic behavior.  Other clues:  is it relevant that the problem always appears in a string field that contains slash characters?

**Comment by Mariatta** [comment]
This tracker is for python dot org website. Since your issue is related to Python standard library, can you please file it at bugs.python.org?

Thanks
