### ISSUE TITLE
New Memeber sign-up not working

### ISSUE THREAD

**Issue by quantfineart** [python/pythondotorg#1746]
i tried to sign up on PSF as a new member (free). I entered my email/username/password and clicked on submit. The page shows a confirmation email has been sent however i never received an email. 

After waiting for several minutes and following instructions i tried to login to my account to send another verification email and this time the systems shows that account does not exist.

**Comment by ewdurbin** [comment]
hello @quantfineart was this psfmember.org or python.org?

**Comment by NJITman** [comment]
On [python.org](python.org), if you click PSF, Membership, Sign-Up as new member, you get redirected to the following url with no way to sign-up (you can only sign-in):
[https://www.python.org/accounts/login/?next=/users/membership/](https://www.python.org/accounts/login/?next=/users/membership/)

If you go to [psfmember.org](psfmember.org), you can sign-up as a new member, but those credentials do not work on the python.org sign-in page (the link above).

**Comment by ewdurbin** [comment]
Hi @NJITman! The "Create Account" button on the right allows you to create an account on python.org, indeed credentials are not shared between python.org and psfmember.org.

**Comment by NJITman** [comment]
On FireFox (latest version) - no create button or panel on the right.
![python org FF](https://user-images.githubusercontent.com/10375636/143320326-ec79f021-61f8-4c40-a1b1-7f2a186ee38b.jpg)

On Chrome (latest version) - create button and panel visible.
![python org CHROME](https://user-images.githubusercontent.com/10375636/143320367-8b8e1bbb-d5f0-4eca-b271-5b69ce1a3532.jpg)

I will use Chrome to create the account for now.

**Comment by istudyvc** [comment]
<img width="1680" alt="Screenshot 2022-03-01 at 10 25 59 AM" src="https://user-images.githubusercontent.com/95381944/156107717-3d9afb71-8341-4281-8a26-ec5bce81c5de.png">

In Safari(latest version ), It's visible like "become a member", On clicking It's showing both login and register option.

**Comment by hugovk** [comment]
Let's close this issue because it's quite old, but @quantfineart please do let us know if you still need some help signing up.

https://psfmember.org/
