### ISSUE TITLE
Capture who approved sponsorship in change history

### ISSUE THREAD

**Issue by ejodlowska** [python/pythondotorg#1748]
**Is your feature request related to a problem? Please describe.**
This is not necessarily a problem, but being able to track approvals to staff is important for our upcoming audit. Right now when a sponsorship is updated in /admin, it captures who made changes to fees, dates, and benefit items. It doesn't explicitly call out the change of approval. Can we add that in? 

Here's a snippet of what it looks like for one of our sponsors:

<img width="1145" alt="Screen Shot 2021-03-17 at 1 51 47 PM" src="https://user-images.githubusercontent.com/2590029/111523617-78801180-8729-11eb-9685-3da91f25779d.png">

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Ex. It would be great if [...]

We'd like "approved" or "approved sponsorship" added to the action column so we can see which staff person approved a sponsorship.

**Comment by berinhard** [comment]
Dropping this link as a possible reference on how to implement this: https://stackoverflow.com/a/15404372
