### ISSUE TITLE
Broken Links on "Download Python 2.7.6 Documentation" Page

### ISSUE THREAD

**Issue by ssiano** [python/pythondotorg#1755]
**Describe the bug**
The https://docs.python.org/release/2.7.6/download.html page has eight broken download links.

In each, the scheme needs to be changed from http to https.

**To Reproduce**
1. Click on the link
2. Copy the link and change http to https to download the doc

**Expected behavior**
The doc should be downloaded when clicking on the link.

**Screenshots**

**Desktop (please complete the following information):**
 - macOS 10.15.7
 - Chrome 89.0.4389.114
 - Python 2.7.6

**Smartphone (please complete the following information):**
 
**Additional context**
Please check other Python releases as well when updating these doc links.

**Comment by Mariatta** [comment]
They all seem to work for me.
I wrote a script to fetch those urls, and they all returned 200 status.
We're also not doing anything in Python 2.7 anymore.

**Comment by ssiano** [comment]
@Mariatta, now I see that if I copy the link address and paste it in another tab, it does download the doc even though the scheme is http.

I'm not sure why the eight download links don't work when clicked within the https://docs.python.org/release/2.7.6/download.html page.

But I understand that Python 2.7 is end-of-life.  I did need the 2.7.6 docs the other day, and just figured that you would want to update python.org since the old docs are still being used.

**Comment by Mariatta** [comment]
Hmm I didn't try to download the files, simply did a GET and HEAD requests to them. In my mind, the URLs are "broken" if they returned 4xx or 5xx, so I didn't further try.

In any case, 2.7 is already EOL. We don't fix anything in that branch anymore.
