### ISSUE TITLE
[wembaster is not a Python language support channel!!!] should webmaster ... ...

### ISSUE THREAD

**Issue by puzengmv** [python/pythondotorg#1757]
https://wiki.python.org/moin/BeginnersGuide/Help
=================================
... ...
... ...
Contacting the Webmaster
**wembaster** is not a Python language support channel!!!   --->>>  should be **webmaster** is not a Python ...

The webmaster should only be contacted if you have found a problem with the python.org website such as a broken link, typographic error, or other problem.
For such problems, also check the github issue tracker for the website

**Comment by berinhard** [comment]
Hm, I'm not sure if issues about the `wiki` should be here. @ewdurbin do you know where I can find more instructions about wiki editing? That way @puzengmv will be able to fix the typo and we can close this issue.

**Comment by mwichmann** [comment]
The wiki has some minimal instructions, https://wiki.python.org/moin/WikiEditingGuidelines, and you email pydotorg-www@python.org to get authorization to edit, once you've created a wiki account.  I've fixed that particular silly typo, this can be closed.

**Comment by berinhard** [comment]
Thanks @mwichmann!
