### ISSUE TITLE
Download page: where are old versions?

### ISSUE THREAD

**Issue by vstinner** [python/pythondotorg#176]
Hi,

Sometimes, I want to download old Python versions for tests. I cannot see Python 2.5, 2.6 or 3.2 on the download page. Would it be possible to give access to such list?
http://legacy.python.org/download/releases/

**Comment by birkenfeld** [comment]
We'll have to enter these releases into the database.

Until that can be done in an automated fashion, nobody will want to do that work (and I don't blame them).

**Comment by ned-deily** [comment]
There is a link to the list at the bottom of the Downloads pages:  "View older releases".  Not ideal but ...

**Comment by vstinner** [comment]
> There is a link to the list at the bottom of the Downloads pages: "View older releases". Not ideal but ...

I click on the download page. In fact, I didn't see the of releases (2.7, 3.3). So I didn't see the small "View older releases" link.

**Comment by benjaminp** [comment]
Using a variety of sketchy heuristics, I have now imported Python releases since 2.1 into the database.
