### ISSUE TITLE
Python Security: Mention that PSRT/PSF is not running a bug bounty program for cash

### ISSUE THREAD

**Issue by tiran** [python/pythondotorg#1764]
**Is your feature request related to a problem? Please describe.**

Users are contacting the Python Security Response Team in regular intervals to ask us if and how they are getting paid for bug bounties. The number of inquiries is increasing. In the last week we had two mails just about cash rewards.

**Describe the solution you'd like**

Please add a paragraph with heading to https://www.python.org/dev/security/ that explains that PSF does neither run a bug bounty program nor does the PSF pay cash for security bugs. In the past I have replied to inquiries like this:

> the Python Software Foundation doesn't run any bug bounty program. We are a nonprofit organization that depends on donation and support from the community.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by berinhard** [comment]
Thanks for opening this @tiran!

@ewdurbin quick question about this issue: this shouldn't require no change in the code, since page's content comes from a `Page` object, correct? If so, this could be changed via admin.

**Comment by ned-deily** [comment]
Thanks for the suggestion, @tiran! I've added the following paragraph to the security page:

**Bug bounties**

_While we sincerely appreciate and encourage reports of suspected security problems in supported Python releases and the PSF web infrastructure, please note that the Python Software Foundation does not run any bug bounty programs. We are a nonprofit organization, depending on donation and support from the community._
