### ISSUE TITLE
MRO essay has poorly formatted ASCII art and diagrams

### ISSUE THREAD

**Issue by BlckKnght** [python/pythondotorg#1768]
There is an essay explaining how Python's MRO system works, which lives at: https://www.python.org/download/releases/2.3/mro/

That page is obviously from the days of Python 2.3, and undoubtedly the Python website has changed quite a bit since that version of the interpreter was released in 2003. Unfortunately, some of those changes have broken the formatting of the ASCII art diagrams included in the essay. Lines have unnecessarily large spaces between them, and all the text seems to be rendering in an italic font, which makes line art using the |, /, and \ characters not appear as it is supposed to.

While a few of those diagrams are non-essential illustrations of various happy Pythons, others show inheritance hierarchies that are important to understanding the article. I don't think any of the diagrams are entirely unreadable in their current state, but they're not great.

It would improve the utility of that page if the formatting of the diagrams was fixed. It need not be exactly how it used to look when the article was first published, but any method of showing the mono-spaced diagrams in a non-italic font and with narrow line spacing would be a big improvement.

**Comment by berinhard** [comment]
Thanks for opening this issue @BlckKnght!

@ewdurbin from what I've seen, the issue is in [this CSS `font`property](https://github.com/python/pythondotorg/blob/master/static/sass/style.scss#L140). As you can see, it's defining the font to be `italic`. After removing it via firefox console, the ASCII diagrams got improved. The commit which introduced this dates from 8 years ago. 

So, can we remove this `italic` reference?

**Comment by hugovk** [comment]
I've edited the RST markup for the page. There were spaces before a lot of the literal block markers (` ::`) which caused them to be inside blockquotes and therefore italic from the blockquote:

```rst
 ::

                                                                     __
               (\   .-.   .-.   .-.   .-.   .-.   .-.   .-.   .-.   /_")
                \\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//
            jgs  `"`   `"`   `"`   `"`   `"`   `"`   `"`   `"`   `"`
```

![image](https://github.com/user-attachments/assets/48a715fd-9521-49f1-b8e0-285e4bb76194)


I deleted the spaces (`::`) to remove the blockquote and italics:

```
::

                                                                     __
               (\   .-.   .-.   .-.   .-.   .-.   .-.   .-.   .-.   /_")
                \\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//
            jgs  `"`   `"`   `"`   `"`   `"`   `"`   `"`   `"`   `"`

```

![image](https://github.com/user-attachments/assets/71c61f15-6e6a-4d0f-a518-8c5231eb786c)
