### ISSUE TITLE
"Socialize on github" - please remove

### ISSUE THREAD

**Issue by birkenfeld** [python/pythondotorg#177]
Under the "Socialize" menu there's a "Github" entry which leads to a non-official mirror of the hg repo.

Why is that there? Our VCS is Mercurial, and not Git, and Python is not hosted on GitHub. That mirror is not usable for any "socializing" (such as issues or pull requests).

**Comment by benjaminp** [comment]
I'm going to subsume under #135.

**Comment by birkenfeld** [comment]
Yeah, sorry for the duplicate.
