### ISSUE TITLE
Maintenance status for python 3.8

### ISSUE THREAD

**Issue by clslgrnc** [python/pythondotorg#1773]
**Describe the bug**
Maintenance status for python 3.8 is incoherent between https://www.python.org/downloads/ and [https://devguide.python.org/](https://devguide.python.org/#status-of-python-branches).

**To Reproduce**
1. Go to https://www.python.org/downloads/ Python 3.8 has maintenance status `bugfix`;
2. Go to [https://devguide.python.org/](https://devguide.python.org/#status-of-python-branches) Python 3.8 has maintenance status `security`.

**Expected behavior**
Status should be the same, I believe the correct one is `security`.

**Comment by dukecat0** [comment]
Hi, this issue is fixed so it can be closed.

**Comment by Mariatta** [comment]
Thanks for reporting the issue and for checking. Closing since it's been resolved.
