### ISSUE TITLE
Download from site did not work (certificate instructions broke)

### ISSUE THREAD

**Issue by gitcnd** [python/pythondotorg#1774]
**Describe the bug**
Certificates appear to fail

**To Reproduce**
1. Install the mac download and follow instructions carefully

**Expected behavior**
works

**Screenshots**

Last login: Sat May  8 17:08:01 on ttys005
/Applications/Python\ 3.9/Install\ Certificates.command ; exit;
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LC_ALL = (unset),
	LC_CTYPE = "en_AU.UTF-8.UTF-8",
	LANG = "en_AU.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
[cnd@mac ~]$ /Applications/Python\ 3.9/Install\ Certificates.command ; exit;
 -- pip install --upgrade certifi
/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9: No module named pip
Traceback (most recent call last):
  File "<stdin>", line 44, in <module>
  File "<stdin>", line 24, in main
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9', '-E', '-s', '-m', 'pip', 'install', '--upgrade', 'certifi']' returned non-zero exit status 1.
logout

[Process completed]

I have screenshots - looks like this bug tracker cannot accept screenshots

**Desktop (please complete the following information):**
 - Mac 10.13

**Additional context**

**Comment by gitcnd** [comment]
The error happened when I followed this instruction at the end:-

"  You can download and install a current curated set from the Certifi project by double-clicking on the Install Certificates icon in the Finder window.   "

**Comment by gitcnd** [comment]
If you want to make instructions that work, you probably need to adjust:
a) how the installer works, so the instructions will work, or
b) adjust what the instructions run, so it sets itself up properly to actually work when run as a "double-clicking" invocation.

**Comment by ned-deily** [comment]
Thanks for the report and sorry for the belated reply. This issue tracker is for issues with the python.org website not with the use or installation of Python itself.  Please open an issue on [the Python Bug Tracker](https://bugs.python.org) so this isn't overlooked further.

https://www.python.org/about/help/
