### ISSUE TITLE
Broken link to Libera.chat in Community/IRC

### ISSUE THREAD

**Issue by raek** [python/pythondotorg#1776]
Community -> IRC -> First paragraph

There is a link titled "libera". It goes to "http://libera.chat/t" (which is a 404 page), but should probably go to "http://libera.chat/". (The "t" at the end of the current link is the difference.)

**Comment by zware** [comment]
I've fixed the content, though I don't have permissions to close this issue :)

**Comment by Mariatta** [comment]
Thanks @raek for the report and @zware for looking into it.
