### ISSUE TITLE
Python 3.7.10 for Windows 10

### ISSUE THREAD

**Issue by vivekkrthakur25** [python/pythondotorg#1787]
hi,

Currently, I see that Python 3.7.10 is available to be installed on Linux only with the .tar file on the official Python Download page. Do we have any timeline for releasing the same for Windows 10? It would be really helpful if that happens. 
If not, can someone please guide on how to install python using .tar file on Windows 10 OS?

Python 3.7.10 Downloads page: https://www.python.org/downloads/release/python-3710/

**Comment by mwichmann** [comment]
Once a given Python release reaches the security-fix stage, installers are no longer provided.  There are various resources describing how to build from source on Windows, maybe see if this is enough?  https://devguide.python.org/

That same page contains the status of each of the release series so you can quickly see whether installers are being produced for new versions or not.
