### ISSUE TITLE
dict.fromkeys with lists as the values has the same key ids

### ISSUE THREAD

**Issue by zeonn** [python/pythondotorg#1788]
If you try to create a new dict by "dict.fromkeys" method, you will get the dict with the same key ids
Let me show an example:

```python
new_dict = dict.fromkeys(['a', 'b'], [])
print(new_dict)  # {'a': [], 'b': []}
print(id(new_dict['a']), id(new_dict['b']))  # 139905809368192 139905809368192
new_dict['a'].append(1)
print(new_dict)  # {'a': [1], 'b': [1]}
```

As you can see this dict has the same key ids and you can't use is in a normal way.

But a dictionary created in the old good comprehension way will behave as expected:

```python
normal_dict = {key: [] for key in ['a', 'b']}
print(normal_dict)  # {'a': [], 'b': []}
print(id(normal_dict['a']), id(normal_dict['b']))  # 139905808484672 139905809403712
normal_dict['a'].append(1)
print(normal_dict)  # {'a': [1], 'b': []}
```

I've tested this behavior on python versions 3.7.1 and 3.9.1

**Comment by Mariatta** [comment]
Not sure if you have an actual question or issue here.
It seems like you're describing the intended behavior of dict.fromkeys as [documented](https://docs.python.org/3/library/stdtypes.html#dict.fromkeys)

> All of the values refer to just a single instance, so it generally doesn’t make sense for value to be a mutable object such as an empty list. To get distinct values, use a dict comprehension instead.

In any case, this issue tracker is not the appropriate venue for such discussion. This tracker is for the python.org website itself.
