### ISSUE TITLE
Hi, I'm trying to setup the project but I have an issue checking webhook, when I execute

### ISSUE THREAD

**Issue by d066z** [python/pythondotorg#1789]
Hi, I'm trying to setup the project but I have an issue checking webhook, when I execute 

 `curl -X GET "<YOUR HOST>/webhook?hub.verify_token=<YOUR VERIFY TOKEN>&hub.challenge=CHALLENGE_ACCEPTED&hub.mode=subscribe&init_bot=true"`

replacing `<YOUR HOST>` by `localhost:5000` and `<YOUR VERIFY TOKEN>` by the string I wrote on .env file 
I only receive "CHALLENGE_ACCEPTED", executing  `curl -X GET "<YOUR HOST>/webhook?hub.verify_token=<YOUR VERIFY TOKEN>&init_bot=true"
`

returns  an error stack finishing with this message: `ValueError: FB_VERIFY_TOKEN does not match.`
I've already set other variables in .env file but nothing seems to change. Is there anything I'm skipping?

__Originally posted by @LuisFerTR in https://github.com/fbdevelopercircles/open-source-edu-bot/issues/124__

**Comment by Mariatta** [comment]
Looks like a bot. Please don't test your bot here, you can test it on your own personal repo.
