### ISSUE TITLE
PSF landing page menu needs to be restructured

### ISSUE THREAD

**Issue by malemburg** [python/pythondotorg#179]
The assignment of various entries currently isn't very intuitive, e.g. the grants program is listed under donations, awards under media, etc.

If someone could point me to right place to modify the menu, I can have a go at updating it. Thanks.

**Comment by ned-deily** [comment]
Marc-André, the Site Tree (sitetree/tree/1/) object is probably the place to start.

**Comment by malemburg** [comment]
On 24.02.2014 11:12, ned-deily wrote:

> Marc-Andre, the Sitetree object is probably the place to start.  

Thanks. I'll have a look.

## 

Marc-Andre Lemburg

**Comment by berkerpeksag** [comment]
> the grants program is listed under donations

It's now listed under "Donations & Grants"

> awards under media

Is there a better place to move the "Awards" link?

@malemburg can this be closed or do you have more suggestions? I can address them if you don't  have time.

**Comment by malemburg** [comment]
I think "Awards" is better under "Membership". The rest is mostly ok for now, so you can close the ticket, thanks.

**Comment by berkerpeksag** [comment]
> I think "Awards" is better under "Membership".

+1, moved it under "Membership" and renamed to "Community Awards". Thanks!
