### ISSUE TITLE
PSF menu should be shown on all PSF pages

### ISSUE THREAD

**Issue by malemburg** [python/pythondotorg#180]
The PSF subsite menu is currently only displayed on the PSF landing page. As soon as you click on one of the links, the standard python.org menu shows again, leaving the visitors with a poor website experience.

Is there a way to have subpages display the PSF menu banner instead ? One that can be enabled on the subpages somehow, or even better have enabled automatically for all pages under the URL /psf/\* ?

**Comment by frankwiles** [comment]
This was fixed long ago, just didn't get closed.
