### ISSUE TITLE
New line '\n' in f-string

### ISSUE THREAD

**Issue by akhileshthite** [python/pythondotorg#1802]
f'{output1} \n {output2}'
--> \n for new line doesn't work in f-string.

**Comment by marksweb** [comment]
Hi @AkhileshThite, this issue tracker is not the appropriate forum for issues with python itself. This tracker is for the python.org website.

**Comment by heysujal** [comment]
> f'{output1} \n (output2}'
> --> \n for new line doesn't work in f-string.

your syntax is wrong @AkhileshThite

**Comment by ned-deily** [comment]
https://www.python.org/about/help/
