### ISSUE TITLE
Check the links on the A/V pages

### ISSUE THREAD

**Issue by malemburg** [python/pythondotorg#181]
Page: http://python.org/doc/av/, http://python.org/doc/av/5minutes, http://python.org/doc/av/howto

The links to audio/video resources on the web need to be checked. Andrew mentioned in #117 that some of them are no longer working.

The formatting could also need some update. There are many unnecessary yellow lines on that page.

**Comment by berkerpeksag** [comment]
I've fixed a couple of issues related to these pages in #821, #880, #899.

I've moved 5-Minutes with Python into a new section "Inactive video series" and removed the link to the howto guide.

And finally, I've simplified markup a bit and removed unnecessary content (e.g. "audio" and "video" annonations)
