### ISSUE TITLE
I have never seen such a dumb API design

### ISSUE THREAD

**Issue by GF-Huang** [python/pythondotorg#1812]
https://docs.python.org/3/library/itertools.html#itertools.groupby

> itertools.groupby(iterable, key=None)¶
Make an iterator that returns consecutive keys and groups from the iterable. The key is a function computing a key value for each element. If not specified or is None, key defaults to an identity function and returns the element unchanged. Generally, the iterable needs to already be sorted on the same key function.

I don't know who design this stupid API, You have to sort your data first before using `groupby` avoid the unexpected behavior. Why not tell me design and make a CPU by myself before use python? Take a look the `GroupBy` of C#, why you so stupid?

**Comment by nanjekyejoannah** [comment]
Please see similar comments on : https://github.com/python/devguide/issues/723
