### ISSUE TITLE
Broken link to svg in image source  in downloads section of https://staging.python.org/ 

### ISSUE THREAD

**Issue by heysujal** [python/pythondotorg#1814]
**Describe the bug**
The source of image which is expected to link to a svg is broken. 
https://assets.windowsphone.com/85864462-9c82-451e-9355-a3d5f874397a/English_get-it-from-MS_InvariantCulture_Default.svg

**To Reproduce**
1. Go to https://staging.python.org/
2. Hover on Downloads section

**Screenshots**
Source code
![image](https://user-images.githubusercontent.com/55016909/125645507-25956c32-4ee4-4f37-b741-77af7ae15903.png)

On https://staging.python.org/ 
![image](https://user-images.githubusercontent.com/55016909/125644594-e8ec5d64-f2ab-4e6e-9ba9-7c5804610e24.png)

 

**Additional context**
I want to work on this issue. But I need to know what image link needs to entered here. Also I am not able to find the code to the https://staging.python.org/  . Can someone guide me how to do this ?

**Comment by ned-deily** [comment]
Thanks for the report. staging.python.org is a testbed for developing the official python.org web site. Any content seen there is transient. As far as I can tell, the link you referred to is no longer present there nor published on the official website.
