### ISSUE TITLE
Outdated instructions for Vim for Python

### ISSUE THREAD

**Issue by Ryuno-Ki** [python/pythondotorg#1815]
As I was to help out a code newbie in getting started with Vim for Python, I discovered documentation on the python.org website.
Sadly, it appears to be outdated.

**Describe the bug**

Looking at https://www.python.org/doc/editors/vim/ it reads

> There are example customisation files for Vim available in the Misc/Vim directory in the Python source tree.

Searching the CPython code base for details, I found
https://github.com/python/cpython/blob/bb3e0c240bc60fe08d332ff5955d54197f79751c/Doc/whatsnew/3.4.rst#api-and-feature-removals

**To Reproduce**

Open the above links in a web browser.

**Expected behavior**

Up-to-date information (ALE or CoC for code completion).

**Additional context**

If there is no recommended approach to setting up Vim for Python, perhaps remove the page altogether.
Or point to some community efforts in this regard.

**Comment by ned-deily** [comment]
Thanks for the report. The editors section of the website is a carryover from the old python.org website and, as you note, is woefully out-of-date. I've disabled the editors, vim, and emacs pages. At a quick glance, I didn't find any links to those pages from elsewhere on the website but, if anyone finds any, please note them here so we can remove them.
