### ISSUE TITLE
Link to alternative Python versions on /downloads/ needs to be updated

### ISSUE THREAD

**Issue by malemburg** [python/pythondotorg#182]
The link points to /download/other, but it should point to /download/alternatives now that this pages exists (see #159).

**Comment by birkenfeld** [comment]
Done (the content can be modified here: http://python.org/admin/boxes/box/35/)

**Comment by malemburg** [comment]
On 24.02.2014 17:48, Georg Brandl wrote:

> Done (the content can be modified here: http://python.org/admin/boxes/box/35/)

Thanks for the pointer.

Perhaps we should give those box widget a more intuitive name
than "download-widget3" :-)

## 

Marc-Andre Lemburg
