### ISSUE TITLE
Input-text elements have cursor turned into a pointer on hover.

### ISSUE THREAD

**Issue by code-reaper08** [python/pythondotorg#1820]
**Describe the bug**
Input-text elements have cursor turned into a pointer on hover.

**To Reproduce**
1. Go to 'https://www.python.org/' or 'https://www.python.org/accounts/login/?next=/users/membership/'
2. Click on 'Search bar on the top right area' or 'username input and password input'
3. Cursor there turns into a pointer like this ![pointer-cursor](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor/pointer.gif)
 on hover.

**Expected behavior**
It is expected that input-text could have a text cursor like this ![](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor/text.gif).

**Screenshots**
**_In search bar (Home)_**
![pointer-cursor1](https://user-images.githubusercontent.com/64256342/126685770-a0b3d5ac-ff21-4d06-b602-1beff38e489f.png)
**_In member sign in password_**
![pwd1](https://user-images.githubusercontent.com/64256342/126686353-a37adeec-432e-4ea3-8b80-8d36ea731fec.png)
**_In member sign in username**
![sign-in1](https://user-images.githubusercontent.com/64256342/126686361-3ecf86b9-42a8-4ade-aa01-1ca5f6806ffb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: chrome Version 91.0.4472.164, firefox 89.0.2 (64-bit)
 

**Smartphone (please complete the following information):**
 - Device: NA
 - OS: NA
 - Browser: NA
 - Version: NA

**Additional context**
If something isn't right, please forgive me, I am just starting out contributing to projects.

**Comment by Ryuno-Ki** [comment]
Caused by https://github.com/python/pythondotorg/blob/7556542b58d9c90717757c9fa997637752d6dd85/static/sass/_functions.scss#L321

`input { cursor: text; }` would give the correct cursor.

**Comment by code-reaper08** [comment]
> Caused by
> 
> https://github.com/python/pythondotorg/blob/7556542b58d9c90717757c9fa997637752d6dd85/static/sass/_functions.scss#L321
> 
> `input { cursor: text; }` would give the correct cursor.

## Hello @Ryuno-Ki 👋
Thanks for pointing it out.
Can I correct it ?
It would be my first contribution in python.org

Hoping for a response from you 😄

**Comment by Ryuno-Ki** [comment]
I'm not a contributor to this project (yet). I can't find a CONTRIBUTION.md either.
@berinhard seem to have proposed CSS changes in the past so might be better to answer.

My research was meant as a shortcut to save some time (since I knew how to drill down to the root cause).

**Comment by Mariatta** [comment]
Pull requests are always welcome. Please do propose a PR to help fix this. Thanks.

**Comment by code-reaper08** [comment]
> I'm not a contributor to this project (yet). I can't find a CONTRIBUTION.md either.
> @berinhard seem to have proposed CSS changes in the past so might be better to answer.
> 
> My research was meant as a shortcut to save some time (since I knew how to drill down to the root cause).

Thanks, @Ryuno-Ki 😄

**Comment by code-reaper08** [comment]
> Pull requests are always welcome. Please do propose a PR to help fix this. Thanks.

Awesome @Mariatta 🥇 
I'll come up with a PR

**Comment by Mariatta** [comment]
>  I can't find a CONTRIBUTION.md either.

For reference, our contributing documentation is here https://pythondotorg.readthedocs.io/contributing.html
