### ISSUE TITLE
Visible CSS on /blogs page

### ISSUE THREAD

**Issue by AdamBrianBright** [python/pythondotorg#1823]
**Describe the bug**
CSS is visible as text, instead of applying / hiding at [`python.org/blogs`](https://www.python.org/blogs/)

**To Reproduce**
1. Go to 'https://www.python.org/blogs/'
2. See CSS

**Expected behavior**
I presume, that in that case, CSS should be striped from newsletter text.

**Screenshots**
![image](https://user-images.githubusercontent.com/15821800/127003473-6689ad00-272d-43f9-9d56-c7623d4878d4.png)

**Desktop (please complete the following information):**
 - OS: MacOS BigSur 11.0.1
 - Browser Chrome
 - Version 91.0.4472.164 (Official build), (x86_64)

**UPD:** resolved by @ewdurbin with https://github.com/python/pythondotorg/pull/1824

**Comment by ewdurbin** [comment]
Thank you for your report @AdamBrianBright
