### ISSUE TITLE
Broken google form in the community survey

### ISSUE THREAD

**Issue by Joshuah143** [python/pythondotorg#1825]
**Describe the bug**
When you visit [the python community servey](https://www.python.org/community/survey/) you cant see the actual survey do to an error in the linked google form.

**To Reproduce**
1. Go to [https://www.python.org/community/survey/](https://www.python.org/community/survey/)
2. Scoll down to the form
3. Try to fill in the google form

**Expected behavior**
You should see the google form without any errors inside of the webpage. 

**Screenshots**
<img width="1440" alt="Screen Shot 2021-07-26 at 7 00 53 PM" src="https://user-images.githubusercontent.com/83801098/127043934-bade974e-2a73-4674-a528-b702ae14b801.png">

**Desktop (please complete the following information):**
 - OS: MacOS 11.4
 - Browser: Safari 14.1.1

**Comment by ned-deily** [comment]
@ewdurbin Is this survey form still relevant?

**Comment by ewdurbin** [comment]
No, the nav links have been removed and the page updated for anyone who lands there via a direct link.
