### ISSUE TITLE
add additional sponsorship contact type and adjust copy

### ISSUE THREAD

**Issue by ewdurbin** [python/pythondotorg#1833]
Currently we have: 
<img width="1173" alt="Screen Shot 2021-08-09 at 8 33 05 AM" src="https://user-images.githubusercontent.com/1200832/128706803-f59ca677-cc82-4490-a9d4-30bd8e9497a9.png">

We have the "Administrative" contacts but it's not clear what that means and I'm unable to find them in notes. 

We should add an "accounting" contact type so that sponsors can identify who is notified regarding invoices and payments for sponsorship.

@JackieAugustine, can you help clarify any of the following?

What specific copy should be added for contact types? I propose:

Primary: "The primary contact for a sponsorship will be responsible for managing deliverables we need to fulfill benefits. Primary contacts will receive all email notifications regarding sponsorship."

Accounting: "Accounting contacts will only be notified regarding invoices and payments."

Administrative: "Administrative contacts will only be notified regarding contracts."

**Comment by JackieAugustine** [comment]
@ewdurbin The proposed copy for the contacts section is exactly correct.  Thank you!
