### ISSUE TITLE
Support associting existing contracts with Sponsorships, to finalize

### ISSUE THREAD

**Issue by ewdurbin** [python/pythondotorg#1836]
Most of our sponsorship contracts have been generated outside of the system up to this point, as such allowing for finalizing/executing by uploading an existing signed contract will be needed to consolidate all of our sponsorships into the python.org database.

**Comment by ewdurbin** [comment]
I think admin options should effectively end up being:

  - Generate Contract for signing
  - Upload Finalized Contract

**Comment by berinhard** [comment]
Rename signed contract filenames to be a valid UUID only.
