### ISSUE TITLE
PSF Board members info is not up to date

### ISSUE THREAD

**Issue by Mariatta** [python/pythondotorg#1857]
The page: https://www.python.org/psf/records/board/history/ does not seem to be up to date.
It does not list the board members for 2021-2022. An election was already held and result announced at https://discuss.python.org/t/2021-python-software-foundation-board-of-directors-election-results/9418

It would be great to update the page with the latest info. Thanks.

**Comment by ned-deily** [comment]
@ewdurbin, Any suggestions for who should followup on this?

**Comment by ewdurbin** [comment]
The page was updated with latest information in November by the Assistant Secretary, who will continue to curate the page.
