### ISSUE TITLE
 Upgrade to Django 3.2 LTS version

### ISSUE THREAD

**Issue by berinhard** [python/pythondotorg#1860]
**Is your feature request related to a problem? Please describe.**
The PR #1830 upgrades the project up to 2.2 LTS version. But, as described in #1819, the support time lasts until next April. We're still under a maintained version until there, but it's something to have in mind. 

**Describe the solution you'd like**
An upgrade to Django 3.2 (3.* LTS version) which shall be maintained until April's 2024.

**Additional context**
The PR by @luzfcb #1830 has a lot of documentation on things that have already been addressed and further discussions are in #1819

**Comment by hugovk** [comment]
By now, Django 3.2 LTS is supported until next month (EOL 30 Apr 2024), so let's retarget for 4.2 LTS (EOL 30 Apr 2026). 

* https://endoflife.date/django

**Comment by RafaelWO** [comment]
I am interested in taking a closer look and trying to upgrade Django to 4.2 LTS :)

**Comment by RafaelWO** [comment]
Well, it seems that I was too slow with my PR :sweat_smile: I let you continue, @JacobCoffee
