### ISSUE TITLE
very strange lstrip behavior

### ISSUE THREAD

**Issue by vgdh** [python/pythondotorg#1866]
windows 10 x64
python 3.7.9 x64

I'm got very strange code behavior.
When I try to cut a part of a string it returns a wrong result

```
path= "C:\\ProgramData\\pp\\pp\\log" 
in_zip_file_name = "C:\\ProgramData\\pp\\pp\\log\\main.log.20210728".lstrip(path)
print(in_zip_file_name)
```

in theory, I should get **main.log.20210728**
but it returns **in.log.20210728**

**Comment by poojamk17** [comment]
hello,

1. Python String lstrip() method returns a copy of the string with leading characters removed (based on the string argument passed)
2. All combination of first characters are removed until first mismatch 

consider 2nd point mainly in ur path string there is a "m" and "a" letter present, so it matched the string so it strip out that next it comes to letter "i" of "main" which is not present in path string so the final output string will be "in.log.20210728".

Sorry if i'm wrong
thank you

**Comment by git-lijo** [comment]
You can use ntpath package.

```
import ntpath
path = "C:\\ProgramData\\pp\\pp\\log\\main.log.20210728" 
print(ntpath.basename(path))
```

This will give your required output:
**'main.log.20210728'**
