### ISSUE TITLE
Add text captchas to the site signup form

### ISSUE THREAD

**Issue by malemburg** [python/pythondotorg#190]
Looking at the feedbacks table it seems that we have attracted a lot of link spammers to the site.

It may be worthwhile adding some form of captcha to the registration form. For the wikis we are using text captchas that ask Python specific questions. Those have turned away a lot of spammers. I think this may be a solution for the www.python.org site as well.

**Comment by malemburg** [comment]
Here's an implementation method we could use even with the site repo being openly accessible on github: http://textcaptcha.com/how_it_works

**Comment by benjaminp** [comment]
If we used recaptcha or something, we would store the API keys secretly like we do the database credentials, so that's not an issue.

**Comment by fcurella** [comment]
how about using a honeypot field?

**Comment by malemburg** [comment]
On 24.02.2014 23:26, Flavio Curella wrote:

> how about using a honeypot field?

Hmm, how would this work and help with human link spammers ?

## 

Marc-Andre Lemburg

**Comment by fcurella** [comment]
wouldn't work with humans, but it would be a quicker way to cut down a good quantity of the spam

**Comment by fcurella** [comment]
I guess we can close this now that there isn't a feedbacks app anymore

**Comment by malemburg** [comment]
Flavio: This tickets refers to the site's signup page, not the feedback form.

Hmm, it seems the signup page is not longer accessible on the site. I currently just see a "Sign In" page.

**Comment by malemburg** [comment]
We will also need such a textcha on the PSF membership signup page: http://www.python.org/users/membership/

I think I'm not beginning to understand that the system uses a user database for site access and that the PSF membership form is a completely different subsystem that just records signups. You don't even have to be logged into the site in order to sign up for PSF membership.

I'll open a separate ticket for that: #196.
