### ISSUE TITLE
Add "edit page" shortcut to admin interface somewhere on a page

### ISSUE THREAD

**Issue by birkenfeld** [python/pythondotorg#191]
It would make it much more convenient to edit Pages if the page included a link to go to the respective edit form in /admin/.

If wanted the link could only be displayed for logged in users to avoid annoying those without admin credentials.

**Comment by malemburg** [comment]
+1, that would help a lot.

## 

Marc-Andre Lemburg

**Comment by birkenfeld** [comment]
Thanks!
