### ISSUE TITLE
PSF membership form is open to spammers

### ISSUE THREAD

**Issue by malemburg** [python/pythondotorg#196]
The PSF membership form is usable by anyone on the site, even those who have not registered for a site account (which currently appears to be disabled). You don't need to be logged in to use it and "sign up" as PSF member.

As a result, the barrier for entry as PSF basic member is so low, that we are apparently getting lots of arbitrary visitors to signup as PSF members. At least that's the picture I'm getting from looking at the membership table on the site.

To at least show some level of knowledge about Python, we should make this a little more difficult, e.g. by asking a few test questions about Python and asking how Python is being used by the person.

**Comment by tbm** [comment]
You now have to be logged in in order to sign up as a PSF member.  This was part of the changes Frank Wiles committed yesterday.

I'm not sure if this addresses your concerns or if you'd like to have additional checks, as the knowledge tests you mention about Python.
