### ISSUE TITLE
Raw HTML shown instead of ESign Form

### ISSUE THREAD

**Issue by sahutd** [python/pythondotorg#198]
http://www.python.org/psf/contrib/contrib-form-python/

I have recently signed the contrib form and remember seeing a esign form.
I currently see raw html.as i am not well versed in web dev, i am only able to report this issue
![screenshot from 2014-02-25 19 35 03](https://f.cloud.github.com/assets/5676959/2258273/281caf9e-9e26-11e3-8d8b-cba4ed66b3fa.png)

**Comment by malemburg** [comment]
Should be fixed now. I changed the content type to "html".

The site uses heavy caching so the effect will take a while to show.
