### ISSUE TITLE
Cannot install python-tds

### ISSUE THREAD

**Issue by ifuchs** [python/pythondotorg#1996]
I am trying to install the modules needed to communicate with a MS SQL server. PyPi install of python-tds appears to work but import pytds says python-tds distribution not found not found

**Comment by abhishekghz** [comment]
**### Required Pip for installing tds to communicate with MySql:**

- pip install python-tds
- pip install pyOpenSSL
- pip install bitarray
 then import,
import pytds
with pytds.connect('server', 'database', 'user', 'password') as conn:
    with conn.cursor() as cur:
        cur.execute(" ")
        cur.fetchall()

**Comment by ifuchs** [comment]
Thank you!
