### ISSUE TITLE
"Blog" menu entry should be refactored into a "News" entry

### ISSUE THREAD

**Issue by malemburg** [python/pythondotorg#206]
The "News" section could then have entries for (at least):
- Python Insider Blog
- PSF Blog
- Planet Python

We might also want to add a new blog for community news to maintain what we used to manually add to the news file on the legacy site using a blog.

**Comment by techtonik** [comment]
Blog is good. It is now necessary the news - it can be good old things, especially for Planet.

**Comment by malemburg** [comment]
Added the three blogs to the news menu items.

**Comment by malemburg** [comment]
Also added the PyCon Blog to the menu as "PyCon News".
