### ISSUE TITLE
Extend the blogs app to allow aggregating blog entries from other RSS feeds

### ISSUE THREAD

**Issue by malemburg** [python/pythondotorg#207]
At the moment, the blogs app only pulls in the Python Insider blog feed.

It would be great to extend it in a similar way to the events app to support more than one feed resource (based on the slug) and have e.g. /blogs/python-insider/, /blogs/psf-blog/, /blogs/planet-python/, etc. readily available.

**Comment by justinabrahms** [comment]
This should be possible with #516
