### ISSUE TITLE
Add a link to site source from the bottom

### ISSUE THREAD

**Issue by techtonik** [python/pythondotorg#209]
Site needs a link to source code. Right now there is no way people can see it is open source. It can be made with :octocat: icon and include icons for other channels used for site development.

? how can I add easy-pickling label to the issue, or who does that

**Comment by nedbat** [comment]
A colophon page laying out the technologies used to make the site would be great, and the link to the source code could go on that page.  No need to link from the bottom of each page.

**Comment by techtonik** [comment]
I think that is a bad UX decision. When user sees an error, that user should click the link and go to the page where the user can edit the file and send a pull request. YMMV, but dedicated pages with vast texts are outdated. tl;dr revolution came somewhere in the middle of old and new python.org design. I personally don't like to search for pages that enable this primary feature for community operated site.

? still who can add easy-pickling labels here

**Comment by merwok** [comment]
I agree with Ned.  An edit link on each page makes sense when each page can be edited (e.g. Sphinx documentation source), but for a website where some things are in templates, some things in PO or JSON files and most of the contents in the database, there isn’t such a 1:1 mapping.  (A “report bugs” link on each page is valuable though.)

**Comment by birkenfeld** [comment]
I agree that there should be a link to this github repo.

**Comment by techtonik** [comment]
> there isn’t such a 1:1 mapping

Not yet. I smb. wants python.org to be educational resource also, they should have this in mind. Cloud editors already allow to represent more than one file. Chrome provides list of all used resources, so having such mapping (along with DB content patch editor) is just a matter of time.

But for the scope of this issue I'd just put octocat to the basement and think about anything else later.

**Comment by nedbat** [comment]
These pages all have a lot of page-noise on them, and sending people directly to github means that we've lost the opportunity to explain the site to them first.  Before we dump them into a pile of source code, let's give them a page where we get to explain how the site was made, why those technologies were chosen, etc.

The percentage of people who will want to modify the source is tiny: <0.5%.   The number of people who will want to learn how the site was made is much larger: ~10%  (these numbers are made up!)

**Comment by techtonik** [comment]
> (these numbers are made up!)

That's the point. We won't reach the consensus until there is poll system running (or, ideally, statistics).

Now for the specific change. You don't explain Twitter icon, why do you want to explain Github? This button is for folks like me who get it. You're free to explain site source to those who are not able to get Github (and my guess that 95% of those won't be able to setup the site anyway), but it is a separate feature. Let's do things incrementally. If you feel it is important - it is better to open a separate enhancement request. There I will tell you that the site carries much less educational value than it could, because it carries the code that you won't reuse in your projects.

**Comment by nedbat** [comment]
I guess we see things differently, and it isn't our decision anyway.  I'd add a link to the bottom the page that says "How we made this site" or something like that.  It would link to a colophon page with details of all the tech, including a link to github.  The people who understand github would find what they need.

**Comment by techtonik** [comment]
Source code should be one click away. That's important.

**Comment by malemburg** [comment]
On 28.02.2014 12:11, anatoly techtonik wrote:

> Source code should be one click away. That's important.

Anatoly, use a bookmark, then it's one click away ;-)

Not everyone visiting the site wants to see the code running it.

I agree with the others that a colophon page would be a good place
to put such a link.

## 

Marc-Andre Lemburg

**Comment by techtonik** [comment]
> Not everyone visiting the site wants to see the code running it.

It is programming language site. Of course everybody wants to see the code. You want, so why do you think that everybody else is less smart?

**Comment by malemburg** [comment]
On 28.02.2014 12:17, anatoly techtonik wrote:

> > Not everyone visiting the site wants to see the code running it.
> 
> It is programming language site. Of course everybody wants to see the code. You want, so why do you think that everybody else is less smart?

The site is intended for a much larger audience than just developers:

http://pythonorg-redesign.readthedocs.org/en/latest/#audiences

It's good to have a link to the repository on the site, but it doesn't
have to be on every single page.

## 

Marc-Andre Lemburg

**Comment by techtonik** [comment]
I am not asking for top level stripe "Fork me on GitHub". Among all stuff the link to repository is more useful than anything else in the footer. I'd move those from the bottom.

**Comment by CarlFK** [comment]
I found this page:

https://www.python.org/community/sigs/current/meta-sig/
which has a bunch of html tags rendering.

It bothers me that i don't know how to report it. 
I looked to the bottom of the page, didn't see anything.
I opened About in a new tab, pfft.. huge wall of text.  skim skim, didn't see anything.
So I searched my inbox for this email I seem to remember.  found a link to this issue, so here I am.

I'll go post a proper issue now, but this one I think is way more important. 

Please put a link to the repo on every page.

**Comment by merwok** [comment]
> I found this page: https://www.python.org/community/sigs/current/meta-sig/
> which has a bunch of html tags rendering.

Could you post a screenshot?  The page looks fine for me.  (I hope the site doesn’t use client-side markdown-to-html conversion like the PyCon website!)

> It bothers me that i don't know how to report it.

Agreed.  Half a dozen issues were opened about the contact form that was present at site launch; I’m sure consensus will be reached and a clear link will be added to the appropriate place.

> I opened About in a new tab, pfft.. huge wall of text. skim skim, didn't see anything.

I think that page is “About Python”, not “About this website”.

**Comment by CarlFK** [comment]
On Wed, Mar 12, 2014 at 5:53 PM, Éric Araujo notifications@github.comwrote:

> I found this page: https://www.python.org/community/sigs/current/meta-sig/
> which has a bunch of html tags rendering.
> 
> Could you post a screenshot? The page looks fine for me. (I hope the site
> doesn't use client-side markdown-to-html conversion like the PyCon website!)
> 
> Looks like it just got fixed:

https://github.com/python/pythondotorg/issues/287  closed.

>  It bothers me that i don't know how to report it.
> 
> Agreed. Half a dozen issues were opened about the contact form that was
> present at site launch; I'm sure consensus will be reached and a clear link
> will be added to the appropriate place.
> 
> I opened About in a new tab, pfft.. huge wall of text. skim skim, didn't
> see anything.
> 
> I think that page is "About Python", not "About this website".
> 
> Will someone with commit privs put a link to somewhere.   No one should not
> have to dig around in my inbox trying to figure out how to report issues.
> I am curious what anyone thinks people should do who do not have access to
> my inbox ;)

if a committee figures out something better later, that can be implemented
too.

## 

Carl K

**Comment by techtonik** [comment]
Ok. I see that PR #217 didn't get linked here, so I propose to do this in small steps and start with merging octocat first. Feature creepers can be filled as separate issues and merged when documentation about site architecture is ready. So far everybody agreed that we need this bikeshed. Let's hope that it is possible to apply incremental process to it.

**Comment by berkerpeksag** [comment]
I'd prefer to add a link to contributing guide instead of raw GitHub repo url. We already have _almost_ complete contributing guide in `docs/`. See #627.

**Comment by techtonik** [comment]
Contributing guide is relevant only to the Python itself, not to the web site.

**Comment by berkerpeksag** [comment]
I meant https://github.com/python/pythondotorg/tree/master/docs/source, not the CPython devguide.

**Comment by birkenfeld** [comment]
> Looks like a usability FAIL to me. The docs should be easily reachable.

When they are on RTD, they are easily reachable.

> Why people insist on using reST for that? GitHub has a good Markdown rendering, ...

Nobody insists. People use what they know / feel comfortable with. Browsing docs in GitHub is not the holy grail.

**Comment by techtonik** [comment]
Reachable is not the argument when speaking about usability. 

Usability requires context with what, when, where, who. We are speaking about Python website development hosted on GitHub, so when people create a PR or decide to contribute, they need to read guidelines, which can be conveniently referenced to markdown page in project settings, and it is a common well established practice for all GitHub projects.

Besides, evolution needs alternatives.

**Comment by nedbat** [comment]
GitHub supports .rst files just fine.

**Comment by techtonik** [comment]
> GitHub supports .rst files just fine.
> 
> So why I don't see the docs here?
> https://github.com/python/pythondotorg/tree/master/docs/source
> And here
> https://github.com/python/pythondotorg/blob/master/docs/source/index.rst

**Comment by nedbat** [comment]
It isn't a goal to have to have the docs hosted at GitHub.  The Python world use .rst in many places.  There's an advantage to sticking to one tool.  Writing this documentation in Markdown merely so it can be read conveniently on GitHub seems like a bad tradeoff.

Another option: you could file a issue with GitHub asking them to improve their .rst support.

**Comment by techtonik** [comment]
> It isn't a goal to have to have the docs hosted at GitHub.

Right. The goal is to make the site development guidelines accessible and discoverable from GitHub.

**Comment by CarlFK** [comment]
"Add a link to site source from the bottom"

done, closed, good.

Please take the docs chatter to a new issue.

On Wed, Mar 18, 2015 at 7:45 AM, Ned Batchelder notifications@github.com
wrote:

> It isn't a goal to have to have the docs hosted at GitHub. The Python
> world use .rst in many places. There's an advantage to sticking to one
> tool. Writing this documentation in Markdown merely so it can be read
> conveniently on GitHub seems like a bad tradeoff.
> 
> Another option: you could file a issue with GitHub asking them to improve
> their .rst support.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/python/pythondotorg/issues/209#issuecomment-82953931.

## 

Carl K
