### ISSUE TITLE
IRC links are odd: #pylocal ?

### ISSUE THREAD

**Issue by nedbat** [python/pythondotorg#210]
I'm not sure what got fixed in #116 (links to commits, or a way to know what code is running on the live site, would be great).
The IRC link is to "irc.freenode.net", which isn't an http destination.
But also: on the IRC page, "#pylocal" is mentioned as "for local user groups".  I went to that channel, and there are three people there including me, it seems not to be a real thing.

**Comment by benjaminp** [comment]
I removed the #pylocal listing and updated the Freenode instructions.
