### ISSUE TITLE
/docs/essays/ppt page missing

### ISSUE THREAD

**Issue by voidspace** [python/pythondotorg#211]
The following page is a 404: http://python.org/doc/essays/ppt/

It is linked to (internally) from this page: http://python.org/doc/essays/

**Comment by ned-deily** [comment]
All of the internal links in the http://python.org/doc/essays/ were broken.  They should now all be fixed, either pointing to pages on the new web site or to the old directories on the legacy web site, including the one with ppt files.  At some point those directories and files will need to be systematically migrated from legacy.
