### ISSUE TITLE
Problems with Python homepage www.python.org

### ISSUE THREAD

**Issue by smontanaro** [python/pythondotorg#215]
Got this from Harald Lüßen in an email to webmaster@python.org:

The new page www.python.org looks ugly in the search bar
under "aA  Socialize  Sign In". The menu items 
"Smaller, Larger, Reset" and "Google+, Facebook, Twitter, IRC on Freenode"
are overlapping everything.

Best regards, Harald Lüßen

![image](https://f.cloud.github.com/assets/3427745/2277778/d9ca3582-9f47-11e3-92f7-27bf476000c3.png)

In a subsequent reply he wrote:

I was just using Firefox with NoScript and Adblock Plus on Windows 8.1.

**Comment by luanfonceca** [comment]
Can you set the Label: `frontend`, because is more easy to everyone see issues that is easier for himself.

**Comment by smontanaro** [comment]
On Thu, Feb 27, 2014 at 10:47 AM, Luan Fonseca de Farias
notifications@github.com wrote:

> Can you set the Label: frontend, because is more easy to everyone see issues that is easier for himself.

I have no idea what you're referring to. Is this something you can do?

Skip

**Comment by fcurella** [comment]
i've set the label for you

**Comment by luanfonceca** [comment]
Oh, ok. In Github, we have the concept of Labels which are something like Tags is the Tasks (Issues) to aggregate and make the management more easier to other people to see the kind of Issue that they are comfortable to do.
![screen shot 2014-02-27 at 2 14 21 pm](https://f.cloud.github.com/assets/1490875/2285267/a341e6b4-9fd2-11e3-9af6-a23939254746.png)

**Comment by frankwiles** [comment]
I believe this is fixed now.
