### ISSUE TITLE
Link Redirect Fraud Manipulation 

### ISSUE THREAD

**Issue by ceoalphonso** [python/pythondotorg#2215]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Hackers are publishing highly misleading installment instructions via WordPress and Illegally redirecting Traffic to their affiliate platforms via misleading cron jobs, webhooks and more

**Comment by tiidadavena** [comment]
@ceoalphonso I'm not sure if I understood well what you mean at this issue: Do you mean that the some links e.g. instead to redirect to the Pandas package, might redirect the user to a unsafe page?

**Comment by Mariatta** [comment]
I'm closing this unless you can provide more details.
