### ISSUE TITLE
http://www.python.org/doc/essays/styleguide.html gives 404

### ISSUE THREAD

**Issue by malemburg** [python/pythondotorg#224]
Here's the legacy version: http://legacy.python.org/doc/essays/styleguide.html

Note that the essay list does not include a link to the style guide, but PEP 257 still does.

**Comment by malemburg** [comment]
Note that the page is available as http://www.python.org/doc/essays/styleguide/ 

Perhaps the PEP needs to be updated instead :-)

**Comment by benjaminp** [comment]
I updated the link to PEP 8.

**Comment by malemburg** [comment]
Hmm, the link still gives a 404.

**Comment by malemburg** [comment]
Ah, now I understand: you misunderstood my comment :-)

I was referring to the PEP 257 using a wrong URL, not the PEP 8 link in the page that actually is available on the new site.

**Comment by benjaminp** [comment]
I updated the PEP.

**Comment by malemburg** [comment]
On 27.02.2014 23:45, Benjamin Peterson wrote:

> I updated the PEP.

Thanks, Benjamin.

## 

Marc-Andre Lemburg
