### ISSUE TITLE
Add a way to enter redirects through the admin interface

### ISSUE THREAD

**Issue by malemburg** [python/pythondotorg#229]
While porting from the old site or external resources, we often find that some links no longer work because they point to locations which the new site doesn't know about.

It would be great if we could have a way of easily entering redirects for given URLs.

E.g. http://www.python.org/community/jobs/index.html should redirect to http://www.python.org/community/jobs/

At the moment these redirects have to be done via chef recipes which live in a separate repository, AFAIK.

**Comment by malemburg** [comment]
Perhaps the Django redirects app could be enabled:

http://django.readthedocs.org/en/1.6.x/ref/contrib/redirects.html

This should solve the problem nicely.

**Comment by fcurella** [comment]
On one hand, I don't like the idea of hitting the db for redirects. On the other hand, it can be too slow of a worflow having to add them in psf-chef.

I don't know how often the 'to-be-redirected' URLs are hit. If it's significant, `contrib.redirects` might be end up being heavy on the database.

I would like to hear the opinion from the ops team on how adding `contrib.redirects` could impact performances.

**Comment by malemburg** [comment]
Flavio: I don't think the redirect system would add much new load to the system. The redirects add just as much load as any other page request with database queries going to the system.

**Comment by fcurella** [comment]
@malemburg I'm OK with adding the redirects app. I've already submitted a PR in #263

**Comment by malemburg** [comment]
On 14.03.2014 15:04, Flavio Curella wrote:

> @malemburg I'm OK with adding the redirects app. I've already submit a PR in #263 

Thanks, Flavio.

## 

Marc-Andre Lemburg
