### ISSUE TITLE
Undo the python.org/jobs redirect

### ISSUE THREAD

**Issue by briancurtin** [python/pythondotorg#230]
I just noticed the job board is being redirected to the legacy site. The new site's /jobs page has been on an equal footing to the legacy site since a couple of hours into launch day, so we don't actually need this.

**Comment by malemburg** [comment]
@gutworth I think there's another place where this needs to be fixed:

https://github.com/python/psf-chef/blob/master/cookbooks/pydotorg-redesign/templates/default/nginx.conf.erb#L152 ff.

**Comment by benjaminp** [comment]
The redirect has been removed but I don't actually see anything at python.org/jobs/ now....

**Comment by briancurtin** [comment]
I guess there was _another_ redirect that pushed that url to http://python.org/community/jobs/, where the jobs are actually posted. You can see it if you go to http://legacy.python.org/jobs

**Comment by malemburg** [comment]
Please remove all redirects for /jobs/. These are blocking the job board Django app which we want to start using.

The site still redirects /jobs/ to /community/jobs/, which is not what we want. I don't know where this originates or whether this is a transient cache thing, but it needs to go away :-)

Thanks.

**Comment by briancurtin** [comment]
The /jobs/ to /community/jobs/ redirect was in place on the old site for as long as I can remember. If the job postings are actually going to be shown at /jobs/, then we'll need to redirect /community/jobs/ back to /jobs. People were reporting issues with the /community/jobs/ page being out of date within hours of the new site launch, even though nothing was pointing to or redirecting to it.

**Comment by malemburg** [comment]
On 02.03.2014 21:17, Brian Curtin wrote:

> The /jobs/ to /community/jobs/ redirect was in place on the old site for as long as I can remember. If the job postings are actually going to be shown at /jobs/, then we'll need to redirect /community/jobs/ back to /jobs. People were reporting issues with the /community/jobs/ page being out of date within hours of the new site launch, even though nothing was pointing to or redirecting to it.

Yes, but on the new site, the job app is tied to the /jobs/ URL and we
need to get that working first before we can start using it.

The existing jobs page content under /community/jobs/ will get ported
into the database in the next few days.

## 

Marc-Andre Lemburg

**Comment by benjaminp** [comment]
I moved the jobs app to /newjobs temporarily for testing.

**Comment by malemburg** [comment]
On 03.03.2014 01:30, Benjamin Peterson wrote:

> I moved the jobs app to /newjobs temporarily for testing.

Thanks, Benjamin.

## 

Marc-Andre Lemburg
