### ISSUE TITLE
Frontpage after build

### ISSUE THREAD

**Issue by originalankur** [python/pythondotorg#232]
![frontpage](https://f.cloud.github.com/assets/11364/2301421/8953acee-a142-11e3-8fd7-4abb96492421.png)

inspect element is showing all js have been loaded properly except ajax.googleapis.com ...

**Comment by originalankur** [comment]
The site menu appears if this https://github.com/versesane/pythondotorg/commit/ca4ea41b4b0a62da24908c00f5871a21d5355729 fix is applied however the carsouel doesn't work.

**Comment by berkerpeksag** [comment]
This should be fixed a while ago. Also, we now have a `load_dev_fixtures` command.
