### ISSUE TITLE
unclear how to submit problems with the website

### ISSUE THREAD

**Issue by cpgray** [python/pythondotorg#236]
All I could find was the link to "Help & General Contact" at the bottom of pages.  On the page /about/help (which is not listed under the "About" menu), nothing specifically mentions problems with the web site.  The last item on the page "Did we miss your concern?" offers a link to webmaster@python.org.  I submitted my problem and got an email that redirected me to the pythondotorg issue tracking on GitHub.

You could make it easier for people to help.

**Comment by ncoghlan** [comment]
+1

I think a third "Report a problem" link in the bottom footer that goes directly to the GitHub issue tracker might work.

**Comment by ncoghlan** [comment]
This may be a duplicate of #189

**Comment by ned-deily** [comment]
Thanks for you suggestions.  `Help` has been added to the `About` cascade and the `/about/help` page now contains links to this issue tracker.  I think any further discussion could be carried out on #189.
