### ISSUE TITLE
The Security Advisories page is broken

### ISSUE THREAD

**Issue by ntrrgc** [python/pythondotorg#239]
Have a look here: http://www.python.org/news/security/

There are only two security advisories, which are incredibly old (missing many recent ones), and if you click any of them you'll find lots of escaped HTML.

This, for sure, does not give a good impression on the security of Python.

**Comment by benjaminp** [comment]
I removed the old security advisories.

**Comment by ntrrgc** [comment]
Where could they be queried now?

**Comment by benjaminp** [comment]
We don't generally issue advisories, and there's no master list. Security fixes for a particular release are usually listed in the release announcement.

**Comment by ntrrgc** [comment]
Oh, I see...
