### ISSUE TITLE
Help page should be featured more prominently

### ISSUE THREAD

**Issue by smontanaro** [python/pythondotorg#240]
Among other URLs, the auto-reply for the webmaster@python.org email alias mentions this help page:

http://www.python.org/about/help/

Looking on the about page, I see it down at the bottom, under all sorts of other guesses as what the user might be looking for. Might this text and link be better moved to the top and reworded like so?

```
Can’t find what you’re looking for below? Try our comprehensive Help section
```

**Comment by sdeibel** [comment]
I think this should be added to the About menu as a new menu item -- that's where I would look for it, anyway.

**Comment by frankwiles** [comment]
This was fixed long ago, just didn't get closed.
