### ISSUE TITLE
Windows Python Downloads on Website

### ISSUE THREAD

**Issue by DarrenWatson** [python/pythondotorg#241]
Should the windows download be showing the Release Candidate (3.3.5rcxx)?  I thought it was always policy to show the latest production release of Python on the homepage direct links?

**Comment by ned-deily** [comment]
It looks like the new _pre-release_ field added in the fixes for #163 is not being taken into account when generating the platform-specific _downloads_ pages, e.g. http://www.python.org/downloads/windows/, http://www.python.org/downloads/mac-osx/, http://www.python.org/downloads/source/.  The _Latest Python_ links at the top should not include pre-releases.  The complete list below is fine.
