### ISSUE TITLE
Add new company?

### ISSUE THREAD

**Issue by smontanaro** [python/pythondotorg#246]
I can't tell how to add a new company to the job submission form.

**Comment by benjaminp** [comment]
You can do it from the admin, which is silly. It should just be a free form text field.

**Comment by malemburg** [comment]
On 03.03.2014 19:23, Benjamin Peterson wrote:

> You can do it from the admin, which is silly. It should just be a free form text field.

Agreed.

I think the company table mostly exists for success stories and was
reused for the jobs app, but it is not needed there either.

We will just need the "about" description and company name on the jobs
table; same for the success stories.

## 

Marc-Andre Lemburg

**Comment by jutrasm** [comment]
I have been working on migrating old jobs to the new system.

I think it makes sense to have a company table from a database design perspective. Consider the case where one company is posting multiple different job positions. 
The only issue is the company attributes need to remain generic (ie. company website url, company email, company contact) and the job posting itself has specifics (contact url, contact email, contact name)

**Comment by malemburg** [comment]
On 10.03.2014 18:51, jutrasm wrote:

> I have been working on migrating old jobs to the new system.
> 
> I think it makes sense to have a company table from a database design perspective. Consider the case where one company is posting multiple different job positions. 
> The only issue is the company attributes need to remain generic (ie. company website url, company email, company contact) and the job posting itself has specifics (contact url, contact email, contact name)

There are a few problems with this approach:
- only few people will be able to add new companies to the database
  due to (obviously needed) permission restrictions
- if you display a list of companies for e.g. job submissions, it will
  look as if we only accept jobs for those companies, which is not
  true
- larger companies often have several distinct groups/sections/divisions
  with different descriptions, URLs, etc.; we'd need separate entries
  for each of those

IMO, the company table is not all that useful.

## 

Marc-Andre Lemburg

**Comment by jutrasm** [comment]
Ok - that makes sense. It is a lot more work to maintain company tables.  

When this change is made - I don't know if it would be useful to have a field for company url and a field for jobpost url. (I've seen both in the job postings we are migrating).

**Comment by smontanaro** [comment]
Any progress on allowing submitters to just type the company name? A nice (second phase?) enhancement of such an entry would be to identify other company names already in the database that are similar to whatever the user enters, allowing mistakes to be identified, and duplicates to be avoided.

**Comment by gpjt** [comment]
Do we have a consensus on what this should look like?  Are we planning to simply have a free-form text field for the company name?  If so, where should the company description go?  (The job description sounds like an obvious place.)

Also, if we do denormalise this (which, BTW, I think is an excellent idea -- decoupling the jobs board from the companies table will make things easier) then we will need to migrate the data for the jobs that have been entered already,.

**Comment by joncle** [comment]
I've posted on the jobs mailing list for feedback regarding a development version of the job board at http://pydotorg.sopython.com/newjobs/ which allows a free form company name. If required, the reviewer can always create a company record and/or associate it with a company record. The form can be seen at http://pydotorg.sopython.com/newjobs/create/ and related code/migration at https://github.com/joncle/pythondotorg/tree/company_name

**Comment by frankwiles** [comment]
This was fixed in a previous release.
