### ISSUE TITLE
Agency checkbox

### ISSUE THREAD

**Issue by smontanaro** [python/pythondotorg#248]
The "agency" checkbox should be a property of the company info. Either a company hires its own workforce directly, or is an agency hiring on behalf of other companies. I've yet to see an agency advertising for Python programmers to fill its own needs.

**Comment by LuRsT** [comment]
I dunno, I understand that but just because you haven't seen it, doesn't mean that they don't exist, I don't think that checkbox should be tied to the company.

**Comment by smontanaro** [comment]
> I dunno, I understand that but just because you haven't seen it, doesn't mean that they don't exist, I don't think that checkbox should be tied to the company.

In my experience helping maintain the job board in the manual past,
agencies were sometimes not perfectly clear about their relationship
to the jobs they posted. Perhaps there should be an agency checkbox in
both the company's record and in each listing. The value in the
company record should be the default setting for each listing. Would
that be a reasonable compromise?

**Comment by LuRsT** [comment]
It appears you have more experience with job boards than me (I have none), so I would agree with you, but not with putting two check-boxes, that would be quite the user experience nightmare. I believe we should have only one check-box, either on the company page or in the job post.

**Comment by jutrasm** [comment]
We just had a discussion regarding the "Agencies" checkbox on the jobs board email group.  We collectively talked through it and decided the checkbox must imply Agencies are OK to contact the job poster, not that the company itself doing the posting is an Agency.  This goes against the discussion here.

**Comment by frankwiles** [comment]
We've removed the relationship to Companies on jobs, so this no longer really applies. Closing
