### ISSUE TITLE
A.sai.com

### ISSUE THREAD

**Issue by Tassanee14** [python/pythondotorg#2481]
Sai.net@a.sai.com

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Tassanee14** [comment]
Sai.net@a.sai.com

**Comment by Tassanee14** [comment]
A.sai.com

**Comment by ezio-melotti** [comment]
@python/organization-owners :point_up_2: 
The user has been reported to GitHub.
They also opened other 2 spammy issues in this repo.
I suggest banning the user, closing the issues and removing the messages.

**Comment by Tassanee14** [comment]
Nate2534@tassanee14.sai.net
