### ISSUE TITLE
Job board should have usable query URLs

### ISSUE THREAD

**Issue by smontanaro** [python/pythondotorg#249]
I'm about to suggest that job postings no longer be accepted on the chicago@python.org mailing list. In general, I think a location-based query URL should substitute for that convenience. For this to be useful, however, we will need to be able to query by location in the URL, and ideally, people should be able to get results in rss (I suspect rss is out of favor these days - I'm way behind the curve on this stuff) or other similar ouput formats.

**Comment by webbyfox** [comment]
agreed

**Comment by justinabrahms** [comment]
This works in the newer jobs board.

https://www.python.org/newjobs/location/london-london-uk/ as an example.

**Comment by frankwiles** [comment]
Yep, @justinabrahms is right this works now. Closing
