### ISSUE TITLE
Identify duplicates?

### ISSUE THREAD

**Issue by smontanaro** [python/pythondotorg#250]
Sometimes two different agencies will post the same opening. This can be hard to detect. Can we offer moderators help identifying potential duplicates?

**Comment by LuRsT** [comment]
I guess this should be part of the process while their job posting get accepted or not, we could have a "Duplicate" option in the workflow.

**Comment by ubernostrum** [comment]
I doubt there's going to be any really effective solution to this, unless someone wants to break out stats and NLP and heuristics, which probably would be overkill; until then I think we need to rely on human beings watching out for dupes.
