### ISSUE TITLE
Site not updating after content changes via admin

### ISSUE THREAD

**Issue by briancurtin** [python/pythondotorg#252]
I updated http://python.org/admin/pages/page/450/ over the weekend and just poked the page a few minutes ago, and have not seen the results of that change go live to http://www.python.org/psf/records/board/minutes/ - it should be showing meeting minutes through the end of 2013 instead of stopping in August.

I'm not familiar with all of the moving parts here, so I'm not sure if it's an admin page thing, a site build thing, other infra things, etc. At first I thought it was just a caching or CDN thing, but changes aren't coming through more than a day later, and I believe some form of caching used to only hold things for several minutes.

**Comment by benjaminp** [comment]
That's because the minutes listing is generated automatically. Try adding minutes here instead: http://python.org/admin/minutes/minutes/

**Comment by briancurtin** [comment]
Did not know about that - cool, fixed.
