### ISSUE TITLE
"Latest News" on front page has incorrect dates, events are out of order in any case

### ISSUE THREAD

**Issue by MattDMo** [python/pythondotorg#253]
On the front page, in the "Latest News" section, all the events are currently listed as having occurred on 2014-02-20, when they in fact did not all occur on that day:

![python org news](https://f.cloud.github.com/assets/1776358/2322765/d3e16c28-a3b4-11e3-80c6-d108d6e308fd.png)

The order is also messed up: 2.6.9 was released in October of 2013, 2.7.6 and 3.3.3 were released last November (2.7.6 was first), 3.3.4 came out Feb 9, 2014, and 3.4.0rc1 was announced Feb 10, 2014.

**Comment by fcurella** [comment]
News publication dates are imported from the feed at http://feeds.feedburner.com/PythonInsider, where they are set as posted on 2014-02-20.
Dates will need to be fixed on the RSS feeds and the cron job will update the stories accordingly.

**Comment by cclauss** [comment]
Just creating new posts on PythonInsider that Python 3.3.5 and Python 3.4.0rc3 have been released will make this issue far less bothersome.  Then next weekend add one more saying that Python 3.4.0 has been released.

**Comment by birkenfeld** [comment]
http://blog.python.org/  -- the posts are now done. What do we have to do to make them appear on www.python.org?

**Comment by cclauss** [comment]
The two new posts are now on the main page...  Perhaps there is a nightly process that does the RSS sync.  Perhaps the Python release process should be updated to add the creation of a blog entry on the day of each release.

**Comment by cclauss** [comment]
My sense is that this should be closed as not_a_bug...  The content of the Latest News section is just an RSS feed out of the blog.  It is unfortunate that the blog posts were not done on the day of the releases (see my note above) and not posted in the same order as the releases were issued but... There is no actual bug to be fixed.

**Comment by MattDMo** [comment]
@cclauss that's fine with me. I was just wondering if there was a way to fix the dates on the blog posts/RSS feed, but if there isn't then there isn't. And, as you mentioned earlier, enough new posts have been and will be posted to push this off the main page. Going forward, I would assume that the blog posts will be scheduled to appear on the actual day of the event, so this is no longer an issue.

**Comment by cclauss** [comment]
Python 3.4 has just been released so someone with sufficient access rights should create a related post to http://blog.python.org
