### ISSUE TITLE
Accented characters broken for Python donor list

### ISSUE THREAD

**Issue by nickjacobson** [python/pythondotorg#254]
On http://legacy.python.org/psf/donations/ it lists donors to the PSF. But accented characters are broken and show up as question mark boxes:

Henrik Kramsh�j
Klaus H�ppner
Torsten K�hnel

See screenshot.

![accent_is_question_mark](https://f.cloud.github.com/assets/4753618/2329356/d34917fe-a416-11e3-9f1c-a85ccd62c163.png)

**Comment by berkerpeksag** [comment]
Thank you for the report. legacy.p.o is unmaintained and there is an open issue to move the donor list to new python.org. See #709 for details. The raw data doesn't look like broken at http://legacy.python.org/psf/donations-data.html so this is going to be fixed when we resolve #709:

```
Henrik Kramshøj
Klaus Höppner
Torsten Kühnel
```
