### ISSUE TITLE
ReStructuredText demonstrate the power and flexiblity of Python?

### ISSUE THREAD

**Issue by CarlFK** [python/pythondotorg#256]
http://www.python.org/doc/av/5minutes/#video2
"""
5 Minutes with Python: A Video Series
Checking out Python but don't have the time to read the manuals? Relax and watch a video or two that demonstrate the power and flexiblity of Python.
        First 5 Minutes with Python
        Python and the Interactive Shell 'IPython'
        A Demonstration of ReStructuredText
"""

I like Jeff and all, but seems like an odd choice for here,

**Comment by untitaker** [comment]
rst is used in sphinx, the most popular documentation tool for python libraries.

**Comment by CarlFK** [comment]
no argument about its value, but it doesn't seem to demonstrate any Python.

**Comment by berkerpeksag** [comment]
That is basically an archived page and I don't see a reason to change its content. I suggest emailing Jeff Green if you'd like give your feedback on "A Demonstration of ReStructuredText" episode. Thank you for the report.
