### ISSUE TITLE
Email sent by the site has an invalid email address

### ISSUE THREAD

**Issue by smontanaro** [python/pythondotorg#258]
Through circuitous means, I got an email bounce this morning that purported to be from webmaster@localhost.python.org. Patrick Ben Koetter, one of the python.org postmasters said that the "localhost." part needs to go. This seems fairly high-priority, as it will likely affect all email generated by the site.

**Comment by smontanaro** [comment]
I can't attach a .txt file, so here's the full bounce message I received.

Delivered-To: skip.montanaro@gmail.com
Received: by 10.64.31.166 with SMTP id b6csp241178iei;
        Thu, 6 Mar 2014 05:34:20 -0800 (PST)
X-Received: by 10.140.30.230 with SMTP id d93mr12874772qgd.51.1394112859849;
        Thu, 06 Mar 2014 05:34:19 -0800 (PST)
Return-Path: <>
Received: from c-pb-mx-quonix.pobox.com (c-pb-mx-quonix.pobox.com. [208.72.237.23])
        by mx.google.com with ESMTPS id 45si3045213qgg.155.2014.03.06.05.34.19
        for skip.montanaro@gmail.com
        (version=TLSv1 cipher=RC4-SHA bits=128/128);
        Thu, 06 Mar 2014 05:34:19 -0800 (PST)
Received-SPF: pass (google.com: best guess record for domain of c-pb-mx-quonix.pobox.com designates 208.72.237.23 as permitted sender) client-ip=208.72.237.23;
Authentication-Results: mx.google.com;
       spf=pass (google.com: best guess record for domain of c-pb-mx-quonix.pobox.com designates 208.72.237.23 as permitted sender) smtp.mail=
Received: from c-pb-mx-quonix.pobox.com (localhost [127.0.0.1])
    by c-pb-mx-quonix.pobox.com (Postfix) with ESMTP id 48C851AC35
    for skip.montanaro@gmail.com; Thu,  6 Mar 2014 08:34:19 -0500 (EST)
X-Pobox-Loop-ID: 04782b5cad6ec7372730f836f4089b8a27e6147f
Delivered-To: skip@pobox.com
X-Pobox-Delivery-ID:
 E285A2-AE8B41AC32-1394112859-00107187!c-pb-mx-quonix.pobox.com
Received: from mail.python.org (mail.python.org [82.94.164.166])
    by c-pb-mx-quonix.pobox.com (Postfix) with ESMTPS id AE8B41AC32;
    Thu,  6 Mar 2014 08:34:18 -0500 (EST)
Received: by mail.python.org (Postfix)
    id 3fftGd3fCzz7LjW; Thu,  6 Mar 2014 14:34:17 +0100 (CET)
Delivered-To: webmaster@localhost.python.org
Received: by mail.python.org (Postfix)
    id 3fftGd3ZSTz7LjR; Thu,  6 Mar 2014 14:34:17 +0100 (CET)
Date: Thu,  6 Mar 2014 14:34:17 +0100 (CET)
From: MAILER-DAEMON@mail.python.org (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: webmaster@localhost.python.org
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
    boundary="3fd1RG75Fwz7LjW.1394112857/mail.python.org"
Message-Id: 3fftGd3ZSTz7LjR@mail.python.org

This is a MIME-encapsulated message.

--3fd1RG75Fwz7LjW.1394112857/mail.python.org
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host mail.python.org.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

```
               The mail system
```

skip@pobox.com (expanded from skip@python.org): host
    mx-4.pobox.com[208.72.237.23] said: 450 4.1.8
    webmaster@localhost.python.org: Sender address rejected: Domain not found
    (in reply to RCPT TO command)

--3fd1RG75Fwz7LjW.1394112857/mail.python.org
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; mail.python.org
X-Postfix-Queue-ID: 3fd1RG75Fwz7LjW
X-Postfix-Sender: rfc822; webmaster@localhost.python.org
Arrival-Date: Mon,  3 Mar 2014 13:50:18 +0100 (CET)

Final-Recipient: rfc822; skip@pobox.com
Original-Recipient: rfc822;skip@python.org
Action: failed
Status: 4.1.8
Remote-MTA: dns; mx-4.pobox.com
Diagnostic-Code: smtp; 450 4.1.8 webmaster@localhost.python.org: Sender
    address rejected: Domain not found

--3fd1RG75Fwz7LjW.1394112857/mail.python.org
Content-Description: Undelivered Message
Content-Type: message/rfc822

Return-Path: webmaster@localhost.python.org
Received: from albatross.python.org (localhost [127.0.0.1])
    by mail.python.org (Postfix) with ESMTP id 3fd1RG75Fwz7LjW
    for skip@python.org; Mon,  3 Mar 2014 13:50:18 +0100 (CET)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=python.org; s=200901;
    t=1393851019; i=@python.org;
    bh=AKW+d0+RFM/ebTGdaIoTaJvOvCcGBZFySNWDzqoZtqE=;
    h=Subject:From:To:Date:From;
    b=Ge1h0jy/kP658CROPyROtTmwdXY5w0GA8bSMEpdSZei2T2dLcyjixbOkOukXNSBRG
     leDoLtrYoBmO6vCS8XcVOp8RJSSIiKifrTbI/tZdupQxNGBj8SwBGeSS91X+viX/6E
     1F2wCn+32EN4DdJzcSL0O8hybdOwhV+hg29iSEFU=
Received: from localhost (HELO mail.python.org) (127.0.0.1)
  by albatross.python.org with SMTP; 03 Mar 2014 13:50:18 +0100
Received: from virt-q0dzqq.psf.osuosl.org (unknown [140.211.10.95])
    by mail.python.org (Postfix) with ESMTP
    for skip@python.org; Mon,  3 Mar 2014 13:50:18 +0100 (CET)
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Subject: [python.org] Confirm E-mail Address
From: webmaster@localhost.python.org
To: skip@python.org
Date: Mon, 03 Mar 2014 12:50:18 -0000
Message-ID: 20140303125018.5210.68437@virt-q0dzqq.psf.osuosl.org

User smontanaro at python.org has given this as an email address.

To confirm this is correct, go to http://www.python.org/accounts/confirm_email/5e3b8ade0f6398160df688d1441d87aef0b5b89a446caf502a5d34c26e64a8f6/

--3fd1RG75Fwz7LjW.1394112857/mail.python.org--

**Comment by fcurella** [comment]
@gutworth can this issue be closed?
