### ISSUE TITLE
Replace turbogears with other options

### ISSUE THREAD

**Issue by pydanny** [python/pythondotorg#259]
![screen shot 2014-03-06 at 9 33 26 pm](https://f.cloud.github.com/assets/62857/2354254/78323d6e-a5ba-11e3-834f-14efb3bcffd2.png)

What about more popular frameworks like web.py, web2py, bottle, aspen, or cherrypy?

**Comment by ncoghlan** [comment]
Or else just remove TurboGears from the list, without replacing it with anything. (Yes, WSGI enables a plethora of options, but unless you're already deeply involved in Python web programming, it probably makes sense to go with one of the main three)

**Comment by pydanny** [comment]
According to PyPI, bottle alone has 10s of thousands of downloads per month. Seems like it's got traction to me!

**Comment by amol-** [comment]
I'm not against this, it's perfectly sensed that only the three major options are listed and TurboGears has far smaller community. Just pointing out that PyPi metrics should not be considered reliable for such choices as they disadvantage packages that historically relied on a private index to make dependencies versions predictable (like TurboGears does, many people are still used at installing it with -i option). 

This is obviously not the case in TG vs Django, Flask or Pyramid as the difference is big in any case, but should be kept in mind when performing other comparisons.

**Comment by pydanny** [comment]
I think Bottle and Tornado should be on this list. Why? They are distinctive and popular:
- Bottle is a single file application framework.
- Tornado is a straight-forward asynchronous framework.

On the other hand, Turbogears, AFAIK, is a stack on top of Pylons, which has been subsumed by the Pyramid project. It's not distinctive in any way and it's just not that popular.

**Comment by amol-** [comment]
Actually TurboGears is not on Pylons since version 2.3.0, summer 2013, which also introduced support for Python3. It's now a stand alone framework (fully backward compatible with previous version) with a microframework mode (called minimal mode) which only depends on WebOb, crank, repoze.lru and decorators.

Again, I'm not in any way pushing for TG being on that list, just clarifying things :D

**Comment by benjaminp** [comment]
I added Bottle and Tornado.
