### ISSUE TITLE
Add Salt, Ansible, OpenStack, et al to front page

### ISSUE THREAD

**Issue by pydanny** [python/pythondotorg#260]
![screen shot 2014-03-06 at 9 43 45 pm](https://f.cloud.github.com/assets/62857/2354282/88812c7e-a5bb-11e3-87d6-668e5bab35ab.png)

Software Development lists buildout, trac, and roundup. What about the projects that are changing lives and bringing jobs to Python developers around the world?

**Comment by gourneau** [comment]
:+1:

**Comment by ncoghlan** [comment]
Good idea. I think a separate "System Administration" entry would likely make sense for those.

**Comment by rkulla** [comment]
Agreed. Even http://en.wikipedia.org/wiki/List_of_Python_software doesn't mention Saltstack or Ansible currently

**Comment by benjaminp** [comment]
I guess OpenStack is more than System administration, but I'm not sure what else I would put in a cloud category.

Also, lol at tkinter.

**Comment by pydanny** [comment]
![screen shot 2014-03-10 at 9 25 32 am](https://f.cloud.github.com/assets/62857/2375957/0eb83672-a871-11e3-8aec-b5bcae8bcd78.png)

Bad punctuation for the system administration list.

**Comment by benjaminp** [comment]
Fixed. It turns out commas look very similar to periods in the admin font. :P

**Comment by thyrgle** [comment]
I believe there is another period (right after Flask): 
![screen shot 2014-07-11 at 10 49 19 pm](https://cloud.githubusercontent.com/assets/349918/3560743/4b62aa4e-0988-11e4-9c68-42a035266e2d.png)

**Comment by ned-deily** [comment]
Yes, there was. Thanks.
