### ISSUE TITLE
c.l.p.a posting guidelines not found

### ISSUE THREAD

**Issue by phdru** [python/pythondotorg#264]
At the page http://www.python.org/community/lists/ there is a link "comp.lang.python.announce posting guidelines", but the page it points to (http://www.python.org/community/clpya-guidelines.txt) doesn't exist; the link gets redirected to http://www.python.org/community/clpya-guidelines.txt/ which reports Error 404.

The old site has the file: http://legacy.python.org/community/clpya-guidelines.txt

Please copy the file to the new site.

**Comment by malemburg** [comment]
Done. I converted the page to ReST.
