### ISSUE TITLE
Image on community page sets the wrong tone

### ISSUE THREAD

**Issue by nedbat** [python/pythondotorg#265]
I understand that imagery is the most subjective issue to raise, but here goes:  I find the image on the Community page off-putting.  It seems religious in tone.  Python is not heaven-sent, and the point of the community is not to join together to reach for something in the sky.

Could we get a picture of people working together, talking, smiling, something like that?

**Comment by birkenfeld** [comment]
I agree.

**Comment by nilslindemann** [comment]
I agree. Just reverse the sun rays, so that they go bottom up instead of top down. ~~If you have a svg i can do that.~~changed my mind. Dont like this project.

**Comment by jhogue** [comment]
We have a graphic forthcoming. Will be adding it as a Pull Request to the repo as soon as I can test its responsiveness at all breakpoints.

**Comment by pitrou** [comment]
I agree as well.

**Comment by benjaminp** [comment]
Has the responsiveness testing been completed?
