### ISSUE TITLE
a bug and some things i dont like about new python site layout

### ISSUE THREAD

**Issue by nilslindemann** [python/pythondotorg#266]
http://www.python.org/community/sigs/retired/parser-sig/towards-standard/
- Formatting bug
- Needs breadcrumb navigation ("Where am i?") (i came there via http://theory.stanford.edu/~amitp/yapps/)
- blue background makes top links invisible when i look on laptop screen from a 60% angle. Prefer white.
- 1 third of space on y-axis is used for 15 navigation links and a search bar.
- 1 third of space on x-axis is used for one sentence about and a link to PSF.
- I can not easily get rid of this by using e.g. HackTheWeb (https://addons.mozilla.org/de/firefox/addon/hack-the-web/). Please compare with e.g. Wikipedia, it is easy there to isolate the main content.

**Comment by nilslindemann** [comment]
Addon:
this is how the above article (and every other page of the new python.org website) looks on my laptop when i make a local copy using [scrapbook](https://addons.mozilla.org/de/firefox/addon/scrapbook/), javascript deactivated (activating does not help):

![screen](https://f.cloud.github.com/assets/6892179/2366374/e00789c6-a6ff-11e3-80c5-79d7250ae08e.jpg)

**Comment by jhogue** [comment]
There is a large navigation redesign in the works that will address many of these issues, Living with the site for a year and having people use it have given us some better ideas on how to structure the site tree. Hopefully this will address other use cases like your Scrapbook issue. Thanks for reporting.

**Comment by hugovk** [comment]
Thanks for the report. This is now 10 years old and some of these things have been addressed by fixes or by displays getting bigger and higher resolution since then.

Let's close this, and if there's some specific outstanding issues, please create a new issue.
