### ISSUE TITLE
New-style classes not yet documented? Really?

### ISSUE THREAD

**Issue by ntrrgc** [python/pythondotorg#267]
In the _Intermediate_ section from http://python.org/documentation/ there is a link: [New Style Classes](http://python.org/doc/newstyle/). It reads:

> Unfortunately, new-style classes have not yet been integrated into Python's standard documention. Fear not, however; many people have worked to provide useful information on creating and using new-style classes:

And then there are many old &mdash;yet amazingly not broken&mdash; links.

Shouldn't this be updated? I haven't checked it myself, but given we're about to reach Python 3.4, new-style classes should be already explained in the official documentation.

**Comment by birkenfeld** [comment]
I've taken that link out now. It is not really relevant anymore.
