### ISSUE TITLE
Job Board: "Region" should not be a required field

### ISSUE THREAD

**Issue by gtback** [python/pythondotorg#271]
In some cases (particularly US states), this field has value, but in others a job submission will have just a City and Country. This should be allowed, rather than forcing the submitter to put something in this field.

This might require a database migration; I'm not sure.

**Comment by jutrasm** [comment]
I have been working on migrating existing job postings.
I'm not sure what this field is for, but I picture sorting or filtering similar to jobs on craigslist.

If the field is simply to supply extra information then all we need to do is make the mandatory property false.

If we plan to use this field for sorting/filtering, it seems that some basic choices should be given. For example, we could populate a dropdown with items:
USA: North East
USA: Mid West
...
Other
None Selected
etc...
If we don't provide the basic choices they may get entered slightly different depending on the user (For example, someone might list a job in Massachusetts in the region East Coast or East or New England or North East)

**Comment by SarahPythonista** [comment]
Just submitted a patch to make it nullable. 

A separate ticket should be opened to convert the field to dropdown.
