### ISSUE TITLE
Downloads are unecessarily hard to find

### ISSUE THREAD

**Issue by Ivoz** [python/pythondotorg#275]
Use case: I am a Windows user, and I know that I want to download the latest Python {2,3}.

Expected result: I am able to quickly and easily navigate to and download an appropriate installer.

Actual result: Pictures are better than words, here. from http://python.org, I have a number of avenues to find a download.

First, there is the 'Download' section blurb:
![download](https://f.cloud.github.com/assets/199266/2376462/ed3066a4-a876-11e3-9d82-5c05ccfaff24.jpg)

This links to Python 3.3.4; at time of writing current is 3.3.5. Why is this not automatically updated?

Note that the links here present the same problem I will note shortly.

Secondly, I could click on the prominent 'Download' button of the header bar, or on the 'Windows' dropdown of that button. They take me respectively to http://www.python.org/downloads/ and http://www.python.org/downloads/windows/.

On both of these pages, there are **NO** links that take me to any sort of download. _All_ links are to **release notes**. Here is a [typical release notes page](http://www.python.org/download/releases/3.3.5/):

![relnotes](https://f.cloud.github.com/assets/199266/2376517/92c737fa-a877-11e3-90be-ef1048ed622d.jpg)

Note that on my 1920x1080 screen, there is **no** information viewable on this page on how to actually download a python of some sort. If I am clever, and not immediately confused after navigating here from various "Download <python X>" links, I will be able to scroll down to the very bottom of the page and find the one normal size link that actually takes me to [downloads of pythons](http://www.python.org/downloads/release/python-335/).

Now note that this page has managed to miss both
- automatically detecting my operating system and recommending a download, like [git-scm.org](http://git-scm.com/)
- Being in any way specialised after I came from a [Download windows](http://www.python.org/downloads/windows/) page to realize that I would like a Windows download and highlighting the actual installers (and same for OS X).

Indeed, the first Windows-relevant link in the table of downloads is to debug information. Due to this, as it stands I see almost no point in the "All releases", "Source code", "Windows" and "OS X" entries in the Download drop down, since they all, through release notes links, lead to exactly the same _actual download_ page for the particular version of Python one would like.

As an aside, there is no advice as to whether to pick an x86 or x64 installer. I don't particularly have an opinion on what this advice is, just that the lack of it may continue to leave newbies confused as to which one to pick. AFAIK, in the _most_ general sense the x86 verson will be more compatible with other things in Windows, and the x64 should be highlighted for 99% of OS X users.

Lastly, one can note that the [All releases](http://www.python.org/downloads/) page is particularly misleading:

![all-downloads](https://f.cloud.github.com/assets/199266/2377295/15f0a694-a881-11e3-8d76-4b4094766cb4.jpg)

If I see a link titled `download` with a little downloading icon next to it, in a table of releases, I don't expect to be taken to release notes!

Proposed solutions:
- Modify `/downloads/<os>/` pages to _actually include links to downloadable items_.
- Modify other pages to stop pointing to release notes. Have the download page note them (it already does).
- Allow the downloads page of a Python version to highlight the installers for a particular OS, whether from automatic detection or from coming from an OS-specific link.

I am dismayed to find that the 2014 redesign features particularly un-2014 usability and reachability if I simply want to download python.

**Comment by birkenfeld** [comment]
All your suggestions are good. Believe me, as release manager I was also frustrated by the redesign at the beginning; we are aware of this and are trying to improve the situation (slowly -- on the side while also doing releases :)

**Comment by chriskeeble** [comment]
In addition, when you arrive at the downloads page for a release (e.g. https://www.python.org/downloads/release/python-341/) and you scroll down, there is a heading which says "Downloads" - it tells me to "Please proceed to the downloads page" …. which when clicked takes me back to the top of the same page. Very frustrating.

It's easy to miss that the links to download files are in fact even further down the page under the "Files" heading.

Proposed solution:
1. The release page should not contain a link to itself.
2. The files heading should read "Downloads"
3. There should be a link near the top of the page to take the user down to the Files ("Downloads") section.

**Comment by birkenfeld** [comment]
I removed the links to self.

**Comment by chriskeeble** [comment]
Already heaps better! (Thanks birkenfeld)

**Comment by frankwiles** [comment]
I believe all of these issues were addressed awhile ago, but please re-open if we missed anything.  Thanks!

**Comment by Ivoz** [comment]
Incase you'd like it, feedback on the newer site design:

at https://www.python.org/downloads/windows/  and similar pages it would add clarity to have two columns, one listing 2.x releases and one releasing 3.x releases.

At https://www.python.org/downloads/ there are links for release notes, I'd speculate that the pages like [these](https://www.python.org/downloads/release/python-342/) are nicer than the ones currently linked to.

But otherwise it looks a lot better than previously :+1:
