### ISSUE TITLE
Should be setting cookies on .python.org

### ISSUE THREAD

**Issue by coderanger** [python/pythondotorg#276]
Currently you get logged out if you switch between www.python.org and python.org

**Comment by malemburg** [comment]
No, doing so would open up the python.org web site to cookie stealing attacks using sub-domains.

python.org should redirect to www.python.org and Django should only set the cookies on www.python.org.

See #122.

**Comment by coderanger** [comment]
@malemburg This is already the case if you login on python.org.

**Comment by malemburg** [comment]
@coderanger Right, which is a huge security issue at the moment. See #122.

**Comment by coderanger** [comment]
Unfortunately such a redirect (aside from the aesthetic issues) would still leave rogue services on python.org able to perform a session fixation attack. There is no way I know of to insulate services on the same TLD, so we should at least make the UX nicer.

**Comment by malemburg** [comment]
Not if we make sure that all services use proper fully qualified subdomains in their service URLs by forcing redirects. Using cookies on "python.org" or ".python.org" is an absolute no-go, since any subdomain service will then receive the cookies.

**Comment by dstufft** [comment]
Any site hosted on a python.org sub domain can set a cookie for .python.org, which www.python.org will read and use as the session ID, and make it possible to make a session fixation. Moving pydotorg to www.python would prevent a session stealing attack, just not a session fixation attack.

The only way I'm aware of to fully insulate between different apps running on the same domain name is to register that as a public suffix (http://publicsuffix.org/) which will make it possible to set a python.org cookie. But this is something we probably don't want to do and even if we did it would still leave out IE afaik.

**Comment by dstufft** [comment]
Whoops, s/possible/impossible/

**Comment by malemburg** [comment]
I'm not after session fixation here. The main concern is session stealing.

Please close the ticket again. This is not a good idea. UX should not get priority over security.

Thanks.

**Comment by malemburg** [comment]
Note that the redirect requested in #122 will remove the UX issue you are having, since you won't be able to log in on http://python.org.

**Comment by benjaminp** [comment]
Everything goes to www.python.org, so I think we're good.
