### ISSUE TITLE
"Download" link on the download must point to files, not to the release page

### ISSUE THREAD

**Issue by vstinner** [python/pythondotorg#278]
On the http://www.python.org/downloads/ page, the [Download] button of the 3.4rc3 line should point to http://www.python.org/downloads/release/python-340rc3/ not to http://www.python.org/download/releases/3.4.0/

My navigation: home page > click on [downloads], scroll down and click on [download] of the Python 3.4.0rc3 line, click on [download page], here you have. It's weird to have to click on download 3 times.

See also issue #275.

**Comment by birkenfeld** [comment]
Not "see also", but "duplicate" :)
