### ISSUE TITLE
"Download" box on the main python.org webpage should be autogenerated

### ISSUE THREAD

**Issue by cclauss** [python/pythondotorg#279]
Python3 release 3.3.3 is mentioned once on the main page and 3.3.4 is mentioned twice but there is no mention of 3.3.5 (the current release) unless the user mouses over the "downloads" tab.

In particular, the "Download" and "Latest News" text on the main page must be updated to reflect that Python 3.3.5 is the latest:

"Download

Python source code and installers are available for download for all versions! Not sure which version to use? Check here.

Latest: Python 2.7.6 - Python 3.3.4"

**Comment by birkenfeld** [comment]
I fixed the box on the front page. (How to update the "news" section is beyond me.)

However, this box should really be autogenerated.

**Comment by cclauss** [comment]
Nice!  See the comments at the bottom of https://github.com/python/pythondotorg/issues/253 for a workaround to the "Latest News" issue.

**Comment by cclauss** [comment]
Closing based on the "Download" text fix above and https://github.com/python/pythondotorg/issues/253 which covers the "Latest News" issue.

**Comment by birkenfeld** [comment]
Let's not close it yet; as I said I want the "Download" box autogenerated.

**Comment by frankwiles** [comment]
Add auto-generation for the homepage-downloads box.
