### ISSUE TITLE
Job reviews should be possible for group "Job Board Admin"

### ISSUE THREAD

**Issue by malemburg** [python/pythondotorg#280]
Or more specifically: users with permission to change the Jobs table records.

At the moment the views for dealing with the reviews use the SuperuserRequiredMixin which prevents the job board team members in the user group to review jobs.

Locations:
https://github.com/python/pythondotorg/blob/master/jobs/views.py#L114
https://github.com/python/pythondotorg/blob/master/jobs/views.py#L168

**Comment by malemburg** [comment]
Thanks, Benjamin. How long will it take for this change to become live on the site ?

**Comment by benjaminp** [comment]
Should hit it by 22:32.

**Comment by malemburg** [comment]
On 11.03.2014 23:25, Benjamin Peterson wrote:

> Should hit it by 22:32.

Great :-)

## Cheers,

Marc-Andre Lemburg
