### ISSUE TITLE
Duplicate pages for PSF contributor agreement

### ISSUE THREAD

**Issue by merwok** [python/pythondotorg#282]
There are between two and four pages for the contributor agreement.  The page linked from the devguide is not the new web form, but one of the older versions telling people to send snail mail or a fax.

**Comment by berkerpeksag** [comment]
The [devguide](https://docs.python.org/devguide/committing.html#contributor-licensing-agreements) now directly links to https://www.python.org/psf/contrib/contrib-form/ and https://www.python.org/psf/contrib/ lists the online form as the first option. I think this can be closed now, thanks for the report!
