### ISSUE TITLE
Links in footer should be better separated

### ISSUE THREAD

**Issue by merwok** [python/pythondotorg#283]
There are currently three links in the footer that seem to be one run-on link (“Copyright ©2001-2014. Python Software Foundation Legal Statements Privacy Policy”).  It would be more readable and follow accessibility best practices to have non-link characters or at least spaces between the different links.

Implementation suggestion: transform the div/small(!)/span elements into ul/li and use CSS to style them.

If given a +1, I could make a PR for that.

**Comment by frankwiles** [comment]
Hacky, but adding a &nsbp; for now until we can get real CSS for this.

**Comment by merwok** [comment]
Thanks!  FTR the changeset is 330b8d73bf41 and it is deployed at the moment.
