### ISSUE TITLE
Site caching doesn't honor forced reloads / admin pages don't show changes

### ISSUE THREAD

**Issue by malemburg** [python/pythondotorg#284]
When working on the site, I often find that the browser is hitting cached pages with old content, sometimes even on pages that should always be dynamically regenerated when loading them like e.g. the admin page for the site tree.

In order to check edits to the site and make admin pages like the site tree usable, it is important that:
- the admin page do not get cached and that
- all other cached pages do get recreated when using forced reload from the browser.

**Comment by benjaminp** [comment]
I've removed all caching from the admin, so that should help.

**Comment by malemburg** [comment]
On 21.03.2014 15:49, Benjamin Peterson wrote:

> I've removed all caching from the admin, so that should help.

Thanks, Benjamin.

## 

Marc-Andre Lemburg
