### ISSUE TITLE
Job navigation should not include non-approved job postings

### ISSUE THREAD

**Issue by webbyfox** [python/pythondotorg#285]
Currently (12/3/14 10:12 GMT) Two jobs showing on top counter of Job section. if you click on job page there is navigation at bottom for next and previous job which explore more job and surely more then two jobs.

There are some jobs not published correctly or they are not meant to show online ??

**Comment by malemburg** [comment]
You are currently looking at the staging area of the new job board. This is still in the porting process (see https://wiki.python.org/moin/PSF%20Python%20Job%20Board). We will go live once we have sorted out the backend.

Until then, please see the old job board at http://www.python.org/community/jobs/

**Comment by malemburg** [comment]
Thanks for the bug report. Those additional job postings should indeed not be shown in the navigation until they are in the approved status.

**Comment by webbyfox** [comment]
Thanks.

**Comment by gpjt** [comment]
The "More jobs in XXX" list to the top right also has unapproved jobs in it.  Two problems:

a) Unapproved ones should not show up there.
b) The links are wrong -- the all go to the company page for the current job.

**Comment by jacobb** [comment]
I've submitted a fix for the prev/next -- It seems the category listings have been fixed already.

**Comment by justinabrahms** [comment]
Looks like this can be closed, thanks to @jacobb's commit on 25afae5.
