### ISSUE TITLE
Caching and CSRF protection don't like each other

### ISSUE THREAD

**Issue by malemburg** [python/pythondotorg#289]
The system heavily caches the jobs board interface under /newjobs/. This apparently creates problems with the CSRF protection mechanisms used by Django in web forms:

 <input type='hidden' name='csrfmiddlewaretoken' value='CyVJix8GA2SlVUAeD5AKyqtPJLConvzP' />

As example, I tried to file a comment on this test job posting:

http://www.python.org/newjobs/98/review/

and failed. Django always returns a 403 "CSRF verification failed. Request aborted.".

I tried reloading the review page and reentering the data, but the problem persists. This renders the jobs app system unusable.

Could someone please turn off this heavy caching for pages that use Django forms ?

For the jobs board the URLs live under /jobs/ and /newjobs/.

Also see #284.

Thanks.

**Comment by benjaminp** [comment]
It will probably work if you start on a https:/// page.

**Comment by malemburg** [comment]
Benjamin: Thanks for the hint. It actually does.

I presume the HTTPS access is not as heavily cached as the HTTP access. Unfortunately, the Django system quickly redirects back to the HTTP URLs when using the HTTPS URLs (see #122 et al.). I've now turned on strict transport security (HSTS) in my browser to have it force use of HTTPS and work around this.

**Comment by benjaminp** [comment]
We force https now.
