### ISSUE TITLE
Page editing doesn't work anymore

### ISSUE THREAD

**Issue by malemburg** [python/pythondotorg#291]
I tried to edit the PSF grants page (http://www.python.org/psf/grants/) using the "Edit" button. This redirected me to the enty form (http://www.python.org/admin/pages/page/420/). I then entered the change (fixing the last Q/A).

Hitting "Save" always returns an empty page and the URL stays at http://www.python.org/admin/pages/page/420/ instead of redirecting to http://www.python.org/admin/pages/page/ as it did before.

**Comment by benjaminp** [comment]
This should be cleaned up now.
