### ISSUE TITLE
Becoming member of Python Software Foundation gives 403 error

### ISSUE THREAD

**Issue by softinio** [python/pythondotorg#294]
Becoming member of Python Software Foundation gives 403 error once you submit the application.

Following error appears: 

Forbidden (403)
CSRF verification failed. Request aborted.

**Comment by benjaminp** [comment]
You need to make sure you're doing it over https.

**Comment by softinio** [comment]
You are right. 

Shall I close this issue or do you want it left open so you can have the relevant url redirect to https to make it more user friendly ?

**Comment by benjaminp** [comment]
Soon we'll force everyone to use https and life will be better.
