### ISSUE TITLE
License page non-redirect

### ISSUE THREAD

**Issue by nicktimko** [python/pythondotorg#296]
A very minor issue: I was linked to https://www.python.org/psf/license/ by [a wiki page](https://wiki.python.org/moin/PythonSoftwareFoundationLicenseFaq) which has the following debug-looking contents:

> ### Python License
> 
> On the live site, this page now redirects to http://docs.python.org/license.html.

A quick search of "On the live site, this page now redirects to" doesn't yield anything else, so I don't know if this is an isolated thing or suggests there may be some other "legacy" redirect pages that are also broken.

**Comment by ned-deily** [comment]
Thanks for the report.  The URL should now be redirecting to the appropriate license page.
