### ISSUE TITLE
PEPs are redirecting to the legacy site

### ISSUE THREAD

**Issue by ncoghlan** [python/pythondotorg#297]
The PEP URLs are still redirected to "legacy.python.org" at this point, which makes it a pain to get the proper canonical URL while looking at a PEP.

Do we have an ETA for when the PEPs will be integrated into the new site?

**Comment by warsaw** [comment]
Why don't we create a top-level peps.python.org and use that as the canonical location for the PEPs?

**Comment by untitaker** [comment]
> Why don't we create a top-level peps.python.org and use that as the canonical location for the PEPs?

Are there any advantages to this over keeping the current URL structure?

**Comment by gvanrossum** [comment]
I would recommend keeping the original URL scheme. PEPs are widely referenced from static documents that won't likely be updated, ever, and we don't want to break all those links.

And yes, I know you can add redirects to make that work, but that only works until the next time someone cleans up the python.org hierarchy and thinks these redirects are only for "backwards compatibility" and that it's been long enough that they won't be needed any more.

Please. Let the PEPs keep the _de facto permanent_ URLs they already have.

**Comment by loewis** [comment]
If moving the PEP build process to the new site is difficult, an intermediary solution could be a reverse proxy configuration for the /peps directory structure, which would give the illusion that the files are actually hosted on the new site.

**Comment by ncoghlan** [comment]
It turns out there's an actual _breakage_ at the moment: https://www.python.org/dev/peps (without the trailing slash) doesn't redirect at all.

Could someone with the appropriate access please set up the reverse proxy (or relocate the PEP build process) so I can stop handediting copied URLs to replace the "legacy" with "www"?

/cc @coderanger @birkenfeld

**Comment by ned-deily** [comment]
AFAICT, the missing trailing slash is a general problem for all redirects to the legacy site.  It would be good to fix.

**Comment by ncoghlan** [comment]
How do we prioritise getting this addressed? It's been a problem since the site went live, but still looks really bad (all our design proposals have "legacy" right there in the URL).

**Comment by ncoghlan** [comment]
(Note I've escalated this to the board as well, in case there's something we can do from that side to get it looked at)

**Comment by ned-deily** [comment]
It needs to be escalated to the board.  Someone needs to share what plans, if any, there are to resolve this and the many other unresolved issues with migrating off of the legacy web site.  Since the new web site went live, some of us had to step in so that we could get new releases out the door since that was quite broken and, as problems have been discovered, we've done some work to fix up some of the content that was incorrectly migrated from the old site.  But there's still plenty to do and it isn't clear who is going to make it happen and how the site is going to be managed moving forward.

**Comment by ncoghlan** [comment]
OK, thanks for that - I'll pass that feedback along to the rest of the board.

**Comment by justinabrahms** [comment]
This is no longer an issue. 

https://www.python.org/dev/peps doesn't redirect to the legacy site.
PEPs are hosted from the new system.

**Comment by untitaker** [comment]
I suggest redirecting `http://legacy.python.org/dev/peps/*` to the new site, in the meantime a lot of people have linked to PEPs from the legacy-site.

**Comment by untitaker** [comment]
Another issue i've found is that the PEP index is accessible both with and without trailing slash. The legacy site actually has a redirect from non-slash to slash in place (which is sort-of broken because of the domain change, but it doesn't matter)

**Comment by gvanrossum** [comment]
RE: redirect: only if the pep number is preserved in the redirect. If someone gets a legacy link to a specific PEP we'd be doing them a disservice by redirecting to the new pep index.

Until issue #505 is fixed (it seems #503 does it) the legacy site is also better for PEPs with images.

**Comment by ncoghlan** [comment]
#510 is another minor glitch in the display of PEPs on the new site.

However, the core issue here has been addressed - PEPs are generally accessible on the main site now. Whether or not to ever start redirecting the interim legacy URLs (rather than just letting their use fade out over time) would be a separate question.
