### ISSUE TITLE
Required fields not highlighted as such on job submission page

### ISSUE THREAD

**Issue by gpjt** [python/pythondotorg#298]

**Comment by ubernostrum** [comment]
Could we get a description of what the expected form of "highlighting" is? Is this just a request for some CSS tweaks on the initial form load? Is it a request for more information after an invalid submission attempt? Need more info to really work out where the issue is.

**Comment by gpjt** [comment]
When I submitted this, there was no way to tell which fields on the job submission form were required and which were not.  Not sure if that still holds.

**Comment by SarahPythonista** [comment]
After an invalid submission, the form tells you which fields are required (although the display is confusing - I'd rather the mapping be more obvious). Until you submit, however, it tells you nothing. 

I think it's traditional to do a red asterisk after the required fieldname, no (before submission)?

See image below for result of invalid submission attempt. 
![screen shot 2015-03-07 at 7 06 56 pm](https://cloud.githubusercontent.com/assets/4283226/6543971/58f9ea42-c4fd-11e4-9003-92dc80c45cb6.png)
