### ISSUE TITLE
Validation errors in job submission page rendered in wrong place

### ISSUE THREAD

**Issue by gpjt** [python/pythondotorg#299]
Confirmed in latest Chrome and Firefox on Windows 7.

**Comment by frankwiles** [comment]
I can't reproduce this, they all seem in the right place to me.  If you can reproduce can you send a screen shot thanks!

**Comment by gpjt** [comment]
I can't repro it now, so I guess you can close it :-)

On 13 November 2014 at 23:24, Frank Wiles notifications@github.com wrote:

> I can't reproduce this, they all seem in the right place to me. If you can
> reproduce can you send a screen shot thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/python/pythondotorg/issues/299#issuecomment-62985405.

## 

Giles Thomas
giles@giles.net
http://www.gilesthomas.com/
http://www.pythonanywhere.com/
