### ISSUE TITLE
"Jobs" link at top of home page is incorrect

### ISSUE THREAD

**Issue by smontanaro** [python/pythondotorg#303]
This is kind of urgent. We have two jobs pages:

http://www.python.org/community/jobs/

and

http://www.python.org/newjobs/

The latter URL is linked from the top of (apparently) every page on the site. It must not be live yet! All links should be to the community/jobs page for the time being.

**Comment by joncle** [comment]
Am I experiencing caching issues or does the top nav bar still go to
http://www.python.org/newjobs/ ?

**Comment by benjaminp** [comment]
It will probably take a while for caches to refresh.

**Comment by smontanaro** [comment]
On Fri, Mar 14, 2014 at 12:56 PM, Jon Clements notifications@github.com wrote:

> Am I experiencing caching issues or does the top nav bar still go to
> http://www.python.org/newjobs/ ?

It's now more than 45 minutes since Benjamin closed the ticket. If I
shift-reload the front page or the old jobs page then click the Jobs
link at the top of either page, I get the old jobs page. On the
newjobs page, the same procedure gets me the newjobs page. I think
that behavior is likely correct.

Skip

**Comment by malemburg** [comment]
This is weird:

If I go to https://www.python.org/, I see the "Jobs" top bar link to /newjobs/.

If I go to e.g. https://www.python.org/about/, I see the "Jobs" top bar link to /community/jobs/

**Comment by smontanaro** [comment]
I think you will need to shift-reload the home page to thwart your browser's cache.

**Comment by joncle** [comment]
Nevermind... I was getting confused... I'm quite surprised by the [
jobs.python.org -> python.org/jobs -> python.org/jobs/ ->
python.org/community/jobs/] redirections though, but I'm guessing that's
historical. It is a little strange that if the ultimate target is
python.org/community/jobs/ that the jobs section on the main page blatantly
says "jobs.python.org" but the menu links to the later.
