### ISSUE TITLE
Redirect from http://www.python.org/editors/ is broken

### ISSUE THREAD

**Issue by ned-deily** [python/pythondotorg#304]
See http://bugs.python.org/issue20938.  The Python FAQ included in the Python Documentation set (for example, http://docs.python.org/3/faq/general.html#is-python-a-good-language-for-beginning-programmers) have a link to http://www.python.org/editors/ which currently 404s.  http://legacy.python.org/editors/ redirects to https://wiki.python.org/moin/PythonEditors. www.python.org should, too.

**Comment by ned-deily** [comment]
The current documentation sets have been changed to link directly to the wiki entry so a redirect is no longer needed.

**Comment by merwok** [comment]
Isn’t this a problem for people reading offline docs shipped with previous releases?

**Comment by ned-deily** [comment]
Probably, but then there are likely other, possibly more important broken links in legacy documentation.  This seems to me like a good time to clean up some of the crufty redirects that have been carried around for a long time.  The FAQ itself is pretty crufty in spots.
