### ISSUE TITLE
No direct link in /documentation section to complete list of documentation versions

### ISSUE THREAD

**Issue by ned-deily** [python/pythondotorg#305]
https://www.python.org/doc/versions/ is the legacy list of all versions.  AFAICT, at the moment the only way to navigate to that info is through links in the Python docs, e.g. the Docs for other versions -> Old versions link in the left sidebar of http://docs.python.org/3/.  The "Complete Documentation by Version" link sounds to me like it would give that info but only links to the Python 3.x and Python 2.x Resources section on the same page: https://www.python.org/documentation/#docs-by-version.  There should be a way to get the complete list from the main /Documentation page and/or pop-up window.

**Comment by benjaminp** [comment]
I put a link on https://www.python.org/doc/.
