### ISSUE TITLE
bogus ssl redirect on legacy.python.org member

### ISSUE THREAD

**Issue by dotysan** [python/pythondotorg#307]
Not sure if this is the proper place to report this...

```
+ wget -N http://python.org/ftp/python/3.3.5/Python-3.3.5.tgz
--13:11:36--  http://python.org/ftp/python/3.3.5/Python-3.3.5.tgz
           => `Python-3.3.5.tgz'
Resolving python.org... 140.211.10.69
Connecting to python.org|140.211.10.69|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.python.org/ftp/python/3.3.5/Python-3.3.5.tgz [following]
--13:11:36--  https://www.python.org/ftp/python/3.3.5/Python-3.3.5.tgz
           => `Python-3.3.5.tgz'
Resolving www.python.org... 199.27.77.143
Connecting to www.python.org|199.27.77.143|:443... connected.
ERROR: Certificate verification error for www.python.org: unable to get local issuer certificate
ERROR: certificate common name `*.b.ssl.fastly.net' doesn't match requested host name `www.python.org'.
To connect to www.python.org insecurely, use `--no-check-certificate'.
Unable to establish SSL connection.
```

**Comment by benjaminp** [comment]
Works for me. Maybe you have an old version of gnutls/wget?

**Comment by dotysan** [comment]
Yeah, I do. But would have expected a different error.

```
Resolving www.python.org (www.python.org)... 199.27.77.143
Connecting to www.python.org (www.python.org)|199.27.77.143|:443... connected.
ERROR: The certificate of ‘www.python.org’ is not trusted.
ERROR: The certificate of ‘www.python.org’ hasn't got a known issuer.
```

Did your DNS return the same 199.27.77.143 and still pass https validation? If so, I'll close.

What baffled me is that from a 3rd location I don't get the tls redirect on the http request.

**Comment by benjaminp** [comment]
`--2014-03-16 15:38:29--  http://python.org/ftp/python/3.3.5/Python-3.3.5.tgz
Resolving python.org... 140.211.10.69
Connecting to python.org|140.211.10.69|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.python.org/ftp/python/3.3.5/Python-3.3.5.tgz [following]
--2014-03-16 15:38:34--  https://www.python.org/ftp/python/3.3.5/Python-3.3.5.tgz
Resolving www.python.org... 199.27.76.143
Connecting to www.python.org|199.27.76.143|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://legacy.python.org/ftp//python/3.3.5/Python-3.3.5.tgz [following]
--2014-03-16 15:38:34--  http://legacy.python.org/ftp//python/3.3.5/Python-3.3.5.tgz
Resolving legacy.python.org... 82.94.164.162, 2001:888:2000:d::a2
Connecting to legacy.python.org|82.94.164.162|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 16881688 (16M) [application/x-tar]
Saving to: ‘Python-3.3.5.tgz’`

**Comment by malemburg** [comment]
@dotysan You're using an old version of wget which doesn't support alternative names in SSL certificates. There's nothing we can do about this on our side, sorry. I'd suggest upgrading to a more recent version or using curl instead.

**Comment by dotysan** [comment]
OK, closer inspection reveals the same/valid CN=*.b.ssl.fastly.net cert with DNS extensions on both. Sorry for the noise.
