### ISSUE TITLE
Python 3.4 docs in EPUB are compressed so they can't be directly opened on an iPad

### ISSUE THREAD

**Issue by cclauss** [python/pythondotorg#310]
http://docs.python.org/3/download.html has an EPUB version of the the Python 3.4.0 docs but it is compressed so iPad users can not directly download and read this document in iBooks or other EPUB-compatible apps.  It would be better if there was an uncompressed EPUB document available for download.  File size is 4.6MB uncompressed vs. 3.5MB for compressed so not a huge difference.

Perhaps the "Unpacking" section of the page should be expanded to discuss issues for iOS, Android, MS Mobile users.

**Comment by cclauss** [comment]
Where in GitHub can I find the source code for the page http://docs.python.org/3/download.html ?

**Comment by benjaminp** [comment]
It's in the in Python source tree.

**Comment by merwok** [comment]
This file is hosted on the python.org website, but the code to create the epub is not in this repository.  Could you report this to https://bugs.python.org/ so that @birkenfeld can see if it’s something that can be configured in the Python docs settings or a bug in Sphinx?

**Comment by cclauss** [comment]
The code to create the ePub is at https://github.com/python/pythondotorg/tree/master/docs but this issue is not a problem of ePub generation.  This issue is about the webpage not offering an uncompressed version of the ePub for download.

**Comment by birkenfeld** [comment]
Believe us, there is nothing related to it in this repository :)

**Comment by birkenfeld** [comment]
OK, fixed in the Python repo and trying out now...
