### ISSUE TITLE
Box not found

### ISSUE THREAD

**Issue by untitaker** [python/pythondotorg#314]
When doing

```
python manage.py syncdb
python manage.py runserver
```

The following console output appears on the first request:

```
box not found: label=homepage-introduction
box not found: label=homepage-get-started
box not found: label=homepage-downloads
box not found: label=homepage-documentation
box not found: label=homepage-jobs
box not found: label=widget-use-python-for
box not found: label=widget-about-psf
```

**Comment by joncle** [comment]
Have you run `./manage.py loaddata fixtures/boxes.json` prior to that... the boxes are in a fixture file (and that is somewhat out of data anyway)

**Comment by untitaker** [comment]
Yes i tried that too.

**Comment by untitaker** [comment]
Your previous edit sayed `python manage.py migrate`. The command from the second edit made it work. Will submit PR for README.
