### ISSUE TITLE
Resolutions of the Board of Directors = 500, once

### ISSUE THREAD

**Issue by CarlFK** [python/pythondotorg#320]
start at
https://www.python.org/psf/grants/  

You can also find historical grant approvals in the Python Software Foundation Resolutions of the Board of Directors

click 
https://www.python.org/psf/records/board/resolutions/
502 Bad Gateway
nginx

I tried again, it worked.  
huh.

**Comment by benjaminp** [comment]
You had the back luck to hit the server in the middle of a redeploy.
