### ISSUE TITLE
Author of EPUB docs is set to Unknown instead of PSF

### ISSUE THREAD

**Issue by cclauss** [python/pythondotorg#322]
http://docs.python.org/3/download.html has an EPUB version of the Python docs but the Author of the document is set to Unknown so this text appears on the cover page and is repeated on the top of every other page throughout the document (in the iBooks app at least). Perhaps something like The Python Software Foundation would be better than Unknown.

To fix this issue, both Makefile and make.bat in https://github.com/python/pythondotorg/blob/master/docs would need to be modified to add the [Sphinx -A option](http://sphinx-doc.org/invocation.html#cmdoption-sphinx-apidoc-A) to the EPUB make.  Perhaps the Release (-R) and/or Version (-V) should also be set to the relevant Python version number.

**Comment by benjaminp** [comment]
This should be reported on the Python tracker.

**Comment by cclauss** [comment]
Moved to http://bugs.python.org/issue20969
