### ISSUE TITLE
Django admin gives an internal server error for the jobs table

### ISSUE THREAD

**Issue by malemburg** [python/pythondotorg#324]
It looks like the migrations we merged yesterday caused a problem:

https://github.com/python/pythondotorg/pull/319

Could one of the admins please paste the traceback here, so that we can have a look. It would also be good to get a table dump of the jobs, job type and job category tables in order to debug the problem on the test server we have setup for the jobs app development.

Thanks.

**Comment by malemburg** [comment]
It seems that the database migration of the job table failed, so now the database schema of the job table is a different one than the one used by Django.

**Comment by benjaminp** [comment]
Somehow the migrations got stuck.

**Comment by malemburg** [comment]
Thanks, Benjamin.
