### ISSUE TITLE
Its harder to download in Chrome than in Firefox

### ISSUE THREAD

**Issue by epseh** [python/pythondotorg#325]
I'm not sure if it was reported yet, but here it goes:

Issue:
- Website looks different in Chrome and Firefox

How to reproduce:
- Open both Chrome and Firefox in http://www.python.org
- Hover over  the downloads button

There's a difference between Firefox:
![2014-03-18_10-22-36](https://f.cloud.github.com/assets/4641579/2448059/528a7744-aea1-11e3-80ce-5257d3007ec6.png)

And Chrome:
![2014-03-18_10-14-09](https://f.cloud.github.com/assets/4641579/2448058/528a0c00-aea1-11e3-82fe-c0eebb512d52.png)

**Comment by merwok** [comment]
Can you explain how it’s harder to download with Chrome?  The images don’t say enough for me to understand.

**Comment by epseh** [comment]
Hi merwok,

Those two buttons that are missing are "quick download" buttons. In Chrome the scenario to download is like this:

Starting from Chrome picture I posted:
- You need to select the platform you wish;
- If you click on Windows, you are redirected to this page: https://www.python.org/downloads/windows/
- Then you need to click on another link so you are redirected to this page:  https://www.python.org/download/releases/3.4.0
- And then, to finally get to the download page you need to scroll down the new features in 3.4 and click on a new link: https://www.python.org/downloads/release/python-340/
- Then you are finally able to download the version you wish

I made this "compilation" so you understand a little better (as I think it's quite hard to explain) the flow to download in Chrome versus Firefox:
![pythondotorg](https://cloud.githubusercontent.com/assets/4641579/2558386/6be552f8-b744-11e3-879d-4617be19ee80.png)

**Comment by frankwiles** [comment]
This was fixed long ago, but not closed.
