### ISSUE TITLE
We need a test/staging server to try out new patches before merging them into production

### ISSUE THREAD

**Issue by malemburg** [python/pythondotorg#326]
The test/staging server should be sync'ed to the live system (both code and database wise) every night, so that it can be used to try out PRs, including database migration testing, adding new apps, etc.

Alternatively, we should provide a stripped down database dump that people can use to setup their own test servers.

At the moment, it's very difficult to run tests against the site's code, since it's not possible to test drive the system using the database data that actually runs the site.

**Comment by joncle** [comment]
I agree - at the moment it's rely on the out of date fixtures, or if you have access, scrape data out - neither are practical or desirable.

Would it help to identify which portions of the DB can't be disclosed publicly (user table most likely etc...), and those tables/certain columns can be anonymised while retaining all relationships and constraints? 

One other possible option I'll throw out there is another group/role permission for those with access to the admin interface. Add another end point (I see tastypie isn't quite there yet), that does the equivalent of `manage.py dumpdata` so testers/developers can either loaddata when /if they need it, or have the potential to automate it if needed to keep relatively in sync.

**Comment by frankwiles** [comment]
I thought preview.python.org existed for this reason?

**Comment by malemburg** [comment]
On 03.04.2014 23:36, Frank Wiles wrote:

> I thought preview.python.org existed for this reason? 

I guess it could now be reused for this, but it's missing the database
content sync we'd need for active testing.

## 

Marc-Andre Lemburg

**Comment by malemburg** [comment]
On 09.07.2014 21:27, Frank Wiles wrote:

> Closed #326.

Why was this ticket closed ?

AFAIK, we still don't have a test/staging server. Or is this a
duplicate of some other ticket ?

## Thanks,

Marc-Andre Lemburg

**Comment by frankwiles** [comment]
preview.python.org WAS the staging system, but the DNS seems to have been taken down.

**Comment by malemburg** [comment]
On 10.07.2014 21:34, Frank Wiles wrote:

> preview.python.org WAS the staging system, but the DNS seems to have been taken down. 

Indeed, since it was confusing people and we didn't want to have
the search engines pick up its content.

preview.python.org also never received the updates from the github master
and did not have a database copy of the live database to play with.

I think those things are essential for a staging server.

## 

Marc-Andre Lemburg

**Comment by frankwiles** [comment]
I believe staging.python.org is now setup correctly and pulling from master. Please re-open if there is anything wrong with it.
