### ISSUE TITLE
Membership FAQ is out of date

### ISSUE THREAD

**Issue by ncoghlan** [python/pythondotorg#328]
https://www.python.org/psf/membership/ still covers the old membership model rather than the new one.

**Comment by ncoghlan** [comment]
This whole flow is likely still in progress (since the open membership model is so new), but there's also no "Join the PSF" button under the "Become a Member" info box on the main PSF page.

On the PSF page, clicking the "Membership" subsection button kicks you back to the main Python section.

I'm also not clear on _how_ to join. The "edit your membership" page appears even when not logged in (as noted in #196), and while there are a number of "Sign In" links, I can't find a Sign _Up_ link.

I'll go look up the info sent to existing PSF members at some point, but it should be a bit cleaner on the site itself :)

**Comment by malemburg** [comment]
Agreed. The whole PSF site needs a complete overhaul.

Most people find their way into the PSF via the frontpage, which has a direct link to the signup form. For some reason, this doesn't even require registering on the website. See e.g. #196.

**Comment by regebro** [comment]
I think the classes are updated on the FAQ, but not the membership roster.

**Comment by berkerpeksag** [comment]
It looks like the content has been updated and "Sign up as member" link has been updated to go https://www.python.org/users/membership/. Closing this as outdated.
