### ISSUE TITLE
Updated Sphinx theme for main docs

### ISSUE THREAD

**Issue by ncoghlan** [python/pythondotorg#330]
The current CPython docs don't match the new theme, and also don't render well on mobile devices. It would be desirable to update the Python 3.4 and dev docs to a new mobile friendly theme.

http://hg.python.org/cpython/file/default/Doc/tools/sphinxext/

**Comment by ericholscher** [comment]
+1. The Read the Docs theme looks great on mobile, if you need prior art. The alabaster theme also has good mobile styles:

https://github.com/snide/sphinx_rtd_theme
https://github.com/bitprophet/alabaster

**Comment by benjaminp** [comment]
This should really be on bugs.python.org.

**Comment by ncoghlan** [comment]
Jesse & Georg asked to have it here, since the intent is to get the pydotorg folks to put it together for us.

**Comment by benjaminp** [comment]
Oh, I see, you want a Sphinx theme designed to match the new www.python.org site. I thought you wanted to use a different builtin sphinx theme.

**Comment by hugovk** [comment]
The https://docs.python.org theme has changed a lot over the last 10 years and is now responsive and has a dark them.

@ncoghlan I think this issue can be closed now? 

We can use https://github.com/python/python-docs-theme for new issues about the theme, and there's also some discussion in https://github.com/python/docs-community/issues/1.
