### ISSUE TITLE
Text in "our blogs" page getting placed one over another

### ISSUE THREAD

**Issue by sahutd** [python/pythondotorg#331]
https://www.python.org/blogs/

I am talking about the text to the left of the latest blog post.
Issue occurs in latest Google Chrome and Iceweasel(firefox).

![screenshot from 2014-03-19 20 00 46](https://f.cloud.github.com/assets/5676959/2461143/c9853c26-af73-11e3-85fd-e8872085995c.png)

**Comment by luanfonceca** [comment]
Hi @sahutd this is dupe of #93 and i think i already solved that in my #218 pull-request.
it would be nice if someone review and maybe accept it or give some feedback about it.
