### ISSUE TITLE
Old docs links broken.

### ISSUE THREAD

**Issue by Yhg1s** [python/pythondotorg#332]
Since the docs.python.org overhaul, the old links for docs.python.org subdirectories (http://docs.python.org/tut, http://docs.python.org/lib, http://docs.python.org/ref, http://docs.python.org/ext, http://docs.python.org/api) have been redirects to the newer locations ('/tutorial', '/library', '/reference', '/extending' and '/c-api'.) These redirects seem to have vanished recently, breaking a lot of references to the old locations. Can we get them restored, or should we be doing a rush job in updating links and retraining brains to type the longer URLs? :)

**Comment by benjaminp** [comment]
You'll have to ask @birkenfeld about that. This is what I see on the server.

```
# Map old, 2.5-and-earlier directory names to 2.6-and-later names.
# Should be phased out maybe 2014.
#RedirectMatch permanent ^/lib/?$ http://docs.python.org/library/
#RedirectMatch permanent ^/tut/?$ http://docs.python.org/tutorial/
#RedirectMatch permanent ^/api/?$ http://docs.python.org/c-api/
#RedirectMatch permanent ^/ext/?$ http://docs.python.org/extending/
#RedirectMatch permanent ^/dist/?$ http://docs.python.org/distutils/
#RedirectMatch permanent ^/inst/?$ http://docs.python.org/install/
#RedirectMatch permanent ^/doc/?$ http://docs.python.org/documenting/
#RedirectMatch permanent ^/ref/?$ http://docs.python.org/reference/
```

**Comment by Yhg1s** [comment]
Was any analysis of use done before commenting them out? If there's only sporadic use I probably know the majority of sources for them (IRC, for example) but I have a gut feeling that they still get used quite a bit.

**Comment by smontanaro** [comment]
> but I have a gut feeling that they still get used quite a bit.

Not to mention they have been around for about forever, so many places
on the web probably reference them.

Skip

**Comment by birkenfeld** [comment]
This was mostly a test balloon, to see if anyone complained. The old URLs have been serving "Moved permanently" redirects for a lot of time now, and we can't support all old URLs forever.

But since it was noticed that quickly, the time to remove these redirects has not come yet.

**Comment by smontanaro** [comment]
On Wed, Mar 19, 2014 at 11:39 AM, Georg Brandl notifications@github.com wrote:

> and we can't support all old URLs forever.

Perhaps not, but Google searches like this

link:docs.python.org/ref -site:python.org
link:docs.python.org/tut -site:python.org
link:docs.python.org/lib -site:python.org

suggest there is still a fair amount of value in keeping them in working order.

Skip

**Comment by Yhg1s** [comment]
This seems broken again; docs.python.org/tut and docs.python.org/lib at least are producing 404s.

**Comment by birkenfeld** [comment]
This is likely caused by the move to a CDN; Benjamin will know more about that.

**Comment by benjaminp** [comment]
https://docs.python.org/tut/ and their ilk work.
