### ISSUE TITLE
Some events are missing in the calendar events listings

### ISSUE THREAD

**Issue by malemburg** [python/pythondotorg#335]
If you compare the listing on the frontpage with the calendar view on http://pycon.org/ there are several user group events not shown in the box.

It is not completely clear whether this is related to repeating events or not, since e.g. the "Guadalajara, Mexico PUG" event is shown and is repeating, while e.g. the "London Python Code Dojo" event on April 2 is not shown. The problem seems to have to do with repeating events, though, since the "Python Meeting Düsseldorf" on April 29 is the first non-repeating event after PyCon US 2014.

**Comment by malemburg** [comment]
The user group calendar on page https://www.python.org/events/python-user-group/ has the same issues, so this appears to be a general issue.

**Comment by malemburg** [comment]
We added a new event to the user group calendar yesterday ("PyGuj (Python User Group - Gujarat) - Kick Start Event") and it doesn't show up in the listing on the front-page and neither on the user group calendar page.

**Comment by fcurella** [comment]
I've checked in the admin and there's no trace of that event. I then tested the command on my local machine, and here the event was imported correctly into the database.

This makes me think the problem is in importing the data, not in showing it (ie: a wrong query).

It would be great if someone with access to the production db could double check to see if the record is there, or if there's some failure in the logs.

**Comment by benjaminp** [comment]
I think the problem is just that the importer runs rather infrequently (every 24 hours). I just ran it manually and the event has appeared.

**Comment by malemburg** [comment]
@gutworth Could this be changed so that the importer runs e.g. once an hour.

People are wondering where their event is listed after we (the Python Calendar Team) tell them that we've added it to the calendars. It would be good to know exactly how long it's going to take for the importer to catch up after we've made a change.

**Comment by malemburg** [comment]
Something is still wrong with the importer: e.g. the "London Python Code Dojo" which is scheduled for April 2 is not listed and lots of others aren't listed either (see http://pycon.org#calendar as reference).

**Comment by malemburg** [comment]
@gutworth Thanks, but it doesn't seem to have helped much. I added two events to the calendar yesterday and they are still not showing up (after more than 12 hours). One of the is the "PyOhio PyCamp", the other "Wisconsin PyCamp". They should have appeared on the https://www.python.org/events/python-events/ page(s) long ago.

**Comment by jacobb** [comment]
Re-researching this issue, I can't seem to find new examples of this (which, of course, doesn't mean it's not happening). @malemburg, have you been experiencing this recently? If so, could you provide me some examples that I can investigate?

**Comment by malemburg** [comment]
On 16.07.2014 23:43, Jacob Burch wrote:

> Re-researching this issue, I can't seem to find new examples of this (which, of course, doesn't mean it's not happening). @malemburg, have you been experiencing this recently? If so, could you provide me some examples that I can investigate?

As example, simply compare the page

https://www.python.org/events/python-user-group/

with the entries in the calendar on http://www.pycon.org/#calendar

MadPUG is not listed for today (2014-07-17), Python Northwest is also
missing. Chattanooga for tomorrow as well, etc.

The site's parser appears to have problems with recurring events,
since all of these are recurring.

## 

Marc-Andre Lemburg

**Comment by malemburg** [comment]
The problem still persists and becoming more and more of a bummer, since we are getting recurring events for user groups more often.

E.g. today the https://www.python.org/events/python-user-group/ shows a single event for Thursday (2015-02-26) next week (which is not recurring), while not showing the three user group meeting on Tuesday (2015-02-24).

**Comment by malemburg** [comment]
Opened a new issue for this to give the problem a bit more attention again after having waited 1.5 years... please follow up on #849.
