### ISSUE TITLE
Broken and inconsistent links to Python FAQ

### ISSUE THREAD

**Issue by smontanaro** [python/pythondotorg#336]
From a mail to webmaster@python.org:

Hello,

First off, thanks for all of your work!
The FAQ link on https://www.python.org/about/gettingstarted/ is broken. Is http://www.python.org/doc/faq/, should be http://docs.python.org/2/faq/. (Unless it should be http://docs.python.org/3/faq/index.html... see the next point.)
Also, the FAQ link on https://www.python.org/about/help/ (under "Got a Python problem or question?") goes to Python 3's FAQ: http://docs.python.org/3/faq/index.html.
Best,
Fureigh

**Comment by fureigh** [comment]
Thanks for opening this!

**Comment by benjaminp** [comment]
Thanks for the report. The link on https://www.python.org/about/gettingstarted/ has been changed to go to the Python 3 FAQ.

**Comment by fureigh** [comment]
Thanks!

Best,
Fureigh

---

fureigh.com
2014 Code for America fellow
fureigh on skype, twitter, irc, drupal.org
347.469.0925

On Thu, Mar 20, 2014 at 4:24 PM, Benjamin Peterson <notifications@github.com
