### ISSUE TITLE
Add About this Website to the About menu

### ISSUE THREAD

**Issue by sdeibel** [python/pythondotorg#338]
Finding how to contribute to the website or report bugs is hard. Adding a menu item to the About menu would solve this.  The page at https://www.python.org/about/website also needs to be updated and would be the landing page for this.

**Comment by ned-deily** [comment]
We've recently added `Help` to the `About` menu and added items on the `Help` page about reporting bugs.  There isn't anything there, though, about how to contribute to the website.  It could be added there or a link added to the `about/website` page and update it.  In any case, the current content of `about/website` is carried over from the legacy site and is out-of-date.  It should either be deleted or updated.  I'm not sure what to suggest for people who want to contribute.  @malemburg, do you want to tackle this?  (Also see related issues #339 and #340.)

**Comment by berkerpeksag** [comment]
There is now a "Submit Website Bug" link in every page on www.python.org.

I've added the following paragraph to https://www.python.org/about/help/

> To contribute to the official Python website, see the About the Python Web Site page or read the developer guide on Read the Docs.

And I've updated the "Joining the python.org Team" section at https://www.python.org/about/website/

I think we can now close this issue. Thank you for the report!
