### ISSUE TITLE
Add How to Contribute item to Community menu

### ISSUE THREAD

**Issue by sdeibel** [python/pythondotorg#339]
The site makes it very hard to find how to contribute to Python, the bug tracker, etc.  Adding a menu item to the Community menu would solve this.  I'm not sure of the landing page for this; possibly a new page is needed with the Want to Contribute list from https://www.python.org/about/help and a link to or inclusion of material from https://www.python.org/about/website (which also needs to be updated).

**Comment by scottilee** [comment]
@berkerpeksag or @ewdurbin I think this can be closed.

**Comment by sdeibel** [comment]
Yes, this is an ancient item.  Closing it.
