### ISSUE TITLE
Remove grey menu area at bottom

### ISSUE THREAD

**Issue by sdeibel** [python/pythondotorg#341]
The grey menu area at the bottom is redundant with the area at the top and could be removed.  For non-graphical browsers the menus are already at the top as well.  Quoting the Zen:  "There should be one-- and preferably only one --obvious way to do it."

**Comment by KartikKannapur** [comment]
@sdeibel In case you are talking about the homepage, I suppose that issue does not exist anymore. If not, could you share the link of the page you are referring to.

**Comment by sdeibel** [comment]
The home page and every other page on python.org (as far as I can tell) has the blue dropdown menu bar at the top (where you mouse over to see the menus appear) and the gray box at the bottom that contains the same menu names and items in expanded form.  I don't see the point of this.  It just duplicates the menus in a text-base browser (and thus doesn't seem to serve accessibility well) and adds a lot of visual bulk to pages.

**Comment by KartikKannapur** [comment]
Yes I agree. The grey area at the bottom can be restructured.

**Comment by frankwiles** [comment]
Restructuring is fine, but while Zen is right in terms of code.  It's wrong to attempt to use coding guidelines for web UI/usability
