### ISSUE TITLE
Remove extra content from drop down menus

### ISSUE THREAD

**Issue by sdeibel** [python/pythondotorg#342]
The drop down menus really don't need the extra popup content area, which is hard to mouse to anyway since you have to track the mouse just right to get to it.  The ones under About, Community, and Events are either semi-irrelevant, obvious, or just fluff to fill the space; the one under Downloads and Documentation can just be two added menu items for the two Python versions; the one under Success Stories is too large and could be an inset on https://www.python.org/about/success/ instead.  Without this content, the menus would appear a lot less clunky and people can concentrate on what they are trying to find and get to it without moving the mouse in tricky ways to click in the content area.

**Comment by malemburg** [comment]
On 21.03.2014 15:09, Stephan Deibel wrote:

> The drop down menus really don't need the extra popup content area, which is hard to mouse to anyway since you have to track the mouse just right to get to it.  The ones under About, Community, and Events are either semi-irrelevant, obvious, or just fluff to fill the space; the one under Downloads and Documentation can just be two added menu items for the two Python versions; the one under Success Stories is too large and could be an inset on https://www.python.org/about/success/ instead.  Without this content, the menus would appear a lot less clunky and people can concentrate on what they are trying to find and get to it without moving the mouse in tricky ways to click in the content area.

I find them quite useful, since they allow direct access to
what people are looking for, so -1 on removing them.

Note that these entries are generated from the site tree and also
show up in the doormat at the bottom of the layout.

## 

Marc-Andre Lemburg

**Comment by sdeibel** [comment]
The content from Downloads and Documentation would still be there as easier-to-click-on menu items and the other content is not useful or not what I'm looking for when I click there.

**Comment by scottilee** [comment]
@MarkMangoba @berkerpeksag Is this still relevant?

**Comment by sdeibel** [comment]
The content looks relevant and I'm not seeing mousing issues so I'd say close this.  In general terms, all the bug reports I added in 2014 were very early in the development of the current website and likely have been fixed or superceded.

**Comment by sdeibel** [comment]
Closing issue, since apparently I can.
