### ISSUE TITLE
Old Jobs Board Indexed by Google

### ISSUE THREAD

**Issue by SarahPythonista** [python/pythondotorg#344]
Google indexed jobs.python.org/ 

So when I Google "Python Jobs", I get that url. It redirects to https://www.python.org/jobs

Which gives me a 404. 

Not sure what you wanna do here, but it seems sub-optimal. Maybe redirect to the new one?

**Comment by malemburg** [comment]
I've added a redirect from /jobs/ to https://www.python.org/community/jobs/ (the old job board page), which should be live after the cached catch up.

Later on, we will host the new jobs app at /jobs/ and remove the redirect again.

**Comment by malemburg** [comment]
For the record: I used the new redirects app for adding the redirect - https://www.python.org/admin/redirects/redirect/
