### ISSUE TITLE
Add web2py to web programming (use python for... section)

### ISSUE THREAD

**Issue by reingart** [python/pythondotorg#345]
As pydanny commented in issue #259, could you please add web2py to the list of web frameworks?

Some facts to support their relevance and popularity:
- web2py had accepted talks, tutorials and posters in several PyCon US editions
- web2py has at least two updated books published: "The Official web2py Book" with 5 editions, last ISBN 978-0-578-12021-8, and "web2py Application Development Cookbook" from Packt Publishing ISBN : 1849515468)
- web2py has an active active community, with [several users groups](http://web2py.com/init/default/usergroups) (English counting more thant 5K members, Spanish 375, Brazilian 510, and also Japanses, French, Chinese and surely many other not listed formally)
- web2py has more than a hundred [contributors](http://web2py.com/init/default/who) and several commercial supporting [companies](http://web2py.com/init/default/support)
- web2py has also been used for official/afiliated PSF pages, like PyCon registration system in 2009/2010 and PyCon Argentina conferences 2011/2012/2013: [web2conf](https://code.google.com/p/web2conf/), and also a votation system IIRC
- web2py has also many unique technical merits aidmed for novice and also enterprise users, like having a complete online IDE including a [debugger](http://reingart.blogspot.com.ar/2012/02/new-web2py-online-python-debugger.html) (based on python debugging modules), a complete webservice infrastructure (including JSONRPC and SOAP XML), and many third party modules (PDF generation, social login methods, caching, pure python database drivers, etc.)
- In 2011 InfoWorld ranked web2py highest among the [top six Python web frameworks](http://www.infoworld.com/d/application-development/pillars-python-six-python-web-frameworks-compared-169442), awarded web2py the Bossie award 2011 for [best open source application development software](http://www.infoworld.com/d/open-source-software/bossie-awards-2011-the-best-open-source-application-development-software-171759-0&current=10&last=1#slideshowTop). In 2012 web2py won the [technology of the year award](http://www.infoworld.com/slideshow/24605/infoworlds-2012-technology-of-the-year-award-winners-183313#slide23) with the following motivation Web2py installs everything you need—even a Python interpreter—for building a Python-based Web application. 

I can provide more facts if you need to evaluate their importance.
TIA

**Comment by benjaminp** [comment]
Added.

**Comment by reingart** [comment]
Thanks you very much!

Just another minor related issue: in "Applications for Python" it still shows Turbogears, as of #259 and this one maybe it should be updated too

https://www.python.org/about/apps

Thanks again
