### ISSUE TITLE
My home page is broken

### ISSUE THREAD

**Issue by gvanrossum** [python/pythondotorg#346]
The url "python.org/~guido" (which I've been using in my email signature for over a decade) has suddenly stopped working. The files still live on dinsdale (I've checked) so I suppose there's an issue in the redirect. IIRC this was broken once before when the new site went live, but quickly fixed (someone tweeted me that it was fixed before I even knew that it was broken). But now it's broken again. (Adding "www." in front doesn't help.)

If you think hosting the content is no longer appropriate I can understand, and I will look for an alternative, but that will take a while, and I'd still like the URL itself to remain valid (it's referenced from millions of archived email messages).

**Comment by malemburg** [comment]
I've added a redirect from /~guido to http://legacy.python.org/~guido which should be live in a few minutes. In the mid-term it may be better to move the content from dinsdale over to the new site by adding pages for it.

**Comment by malemburg** [comment]
Hmm, looks like the redirect system (or some other part of the site) doesn't like the leading tilde in the URL /~guido. I've added a redirect from /guido to http://legacy.python.org/~guido which works without problems. The other redirect goes straight to https://www.python.org - probably at the web server level.

**Comment by joncle** [comment]
Sounds like it'll possibly be easier to change the nginx config to try to match ~homedir and either redirect or potentially reverse proxy instead of using the redirect app. It's not really a route the Django system should be interested in evaluating.

**Comment by benjaminp** [comment]
Fixed now.

Sorry about that. We should probably move away from tilde-homedirs eventually (you're certainly welcome to bdfl.python.org if you want), but we definitely didn't mean to just break your site like that. Its breakage was the result of a configuration change elsewhere.

**Comment by benjaminp** [comment]
Also, now that python.org is served over https, you may want to change the "http://www.googlesyndication.com/relcontent/show_rc.js" link on your homepage to be https, too. Otherwise, most modern browsers block it for being mixed content.

**Comment by malemburg** [comment]
Removed the redirects app entries again.

**Comment by gvanrossum** [comment]
I'll think about hosting elsewhere later. I changed the googlesyndication link to https but this hasn't shown up on the site yet -- is there a copying delay?

**Comment by benjaminp** [comment]
Well, the googlesyndication link looks dead anyway.

**Comment by gvanrossum** [comment]
OK, deleted. But no changes are showing up. Is the source of truth no longer on dinsdale? (legacy.python.org doesn't show my changes either.)

**Comment by gvanrossum** [comment]
The changes are now live.

**Comment by benjaminp** [comment]
There's rather aggressive caching. You can force a cache purge with

``` sh
$ curl -X PURGE https://www.python.org/~guido/
```

Otherwise, it's refreshed every hour.
