### ISSUE TITLE
Jobs admin page gives a 503 error

### ISSUE THREAD

**Issue by malemburg** [python/pythondotorg#347]
Going to https://www.python.org/admin/jobs/job/ gives the 503. All pages using the jobs app also give a 503.

It looks like the system doesn't like automatic migrations, since this is the second time that a migration has failed on us (see #324).

The problem was caused by this pull request: #343.

**Comment by joncle** [comment]
As far as I'm aware this is the last migration that's needed for the jobs app development at this stage - so it's probably a non-issue, but is there some way we can be doing this that doesn't cause issues? After the first failed migrations, I did add a note to #343 to highlight it was a migration but I'm not sure what's required at either end to ease this process...

I'm thinking along the lines that we may wish to consider any learnings here in context outside of the job board app, and take it on board when/if other parts of the system need migrations running.

**Comment by benjaminp** [comment]
I deployment code should be running

> $ manage.py syncdb --migrate --settings pydotorg.settings.prod

I guess I can watch more closely next time there is a migration.

**Comment by malemburg** [comment]
Thanks, Benjamin. Should we perhaps add a label "migration" to signal PRs with migrations ?

**Comment by benjaminp** [comment]
If you want, but usually see them organically anyway.

**Comment by malemburg** [comment]
On 24.03.2014 14:40, Benjamin Peterson wrote:

> If you want, but usually see them organically anyway.

I've added a label "migration". Perhaps it helps.

## Thanks,

Marc-Andre Lemburg
