### ISSUE TITLE
Jobs links tweeted raise 404 errors

### ISSUE THREAD

**Issue by jutrasm** [python/pythondotorg#351]
This may not matter since the jobs board content will all soon be new... BUT I just noticed if you click on a job link tweeted with our jobs board twitter handle @pyjobo, for a job whose content is actually still on our site - it raises a 404 Errror File Not Found.

For example here is one : http://t.co/gGNXP9zX4h for a job with the company Influenster

**Comment by malemburg** [comment]
On 26.03.2014 13:59, jutrasm wrote:

> This may not matter since the jobs board content will all soon be new... BUT I just noticed if you click on a job link tweeted with our jobs board twitter handle @pyjobo, for a job whose content is actually still on our site - it raises a 404 Errror File Not Found.
> 
> For example here is one : http://t.co/gGNXP9zX4h for a job with the company Influenster

I have added a redirect from /community/jobs/index.html
to /community/jobs/, but for some reason the redirects app
doesn't like the query parameters in the URL that come from the
Twitter feed, so the redirect doesn't work as expected.

## 

Marc-Andre Lemburg
Director
Python Software Foundation
http://www.python.org/psf/

**Comment by jutrasm** [comment]
The URL has a series of get parameters so I would have expected to see us using request.GET in the views code. Here is a discussion on stackoverflow.

http://stackoverflow.com/questions/3209906/django-return-redirect-with-parameters

Hoping to be able to help out here more soon but I am still going through a big learning curve at this point... doing what I can to help out on jobsboard in the meantime.

**Comment by muellert** [comment]
The problem seems to be buried in Feedburner because all RSS links yield a 404. Example (Influenster):

http://feedproxy.google.com/~r/python/pyjobo/~3/Jjil1pJzLy0/index.html

The link is not clickable, anyway.
