### ISSUE TITLE
My local dev setup is broken when I do pip install requirements.

### ISSUE THREAD

**Issue by ArcTanSusan** [python/pythondotorg#354]
http://pastebin.com/10Q5yCM5 

You can see that in the python3 virtualenv called `susan_ev`, the dependencies have failed to install. Does anyone else get this issue? 

As a temporary solution, I've uninstalled python3 using `brew uninstall python3` system-wide and finally, I went to my virtualenv and the `pip install -r requirements` also failed mid-way.

**Comment by joncle** [comment]
This doesn't look like anything to do with the site/code and more your local setup. At a quick glance you need to:
- fix your local SSL support (no shortage of articles there - have seen this many a time on forums etc...)
- check which executable your venv is using and which pip (2.7 as indicated by your paths)

**Comment by frankwiles** [comment]
Yep this is a local environment issue with building one of the requirements.
