### ISSUE TITLE
Jobs RSS feed broken

### ISSUE THREAD

**Issue by smontanaro** [python/pythondotorg#355]
(Sorry if this is a duplicate. I tried searching for "RSS" and got a number of hits which didn't seem related to that topic.)

From a mail to webmaster:

---

I tried to read the job adverts through the RSS feed, but all links
generated by Feedburner are broken. Clicking them is impossible, and if
I copy them to the location bar, I get a 404 error.

Btw, in the old site, there was a specific link for reporting bugs for
the website. At least it's not obvious what to do in the new site,

**Comment by malemburg** [comment]
It's probably the same issue as for the Twitter feed (#351).

**Comment by frankwiles** [comment]
Was fixed awhile ago, but didn't close this issue.
