### ISSUE TITLE
Peek usertesting feedback

### ISSUE THREAD

**Issue by untitaker** [python/pythondotorg#357]
Found the [Peek](http://peek.usertesting.com) service on HN and entered python.org for fun.

The result can be found here: http://peek.usertesting.com/result/513506161102?autoplay=true

Summary:
- PyCon US site didn't open in a new tab, useless "middle-page" (4:20)
- Sphinx docs don't have the main navbar of python.org (see also #330)
- Everything else is fine (yay?)

**Comment by berkerpeksag** [comment]
Thanks, I've just watched the video. The HTML link for "PyCon US 2014" comes from the Google calendar so we don't have control on the data. We could potentially tweak the event importer code or add some JavaScript to open external links in a new tab, but I don't think it's worth the effort.
