### ISSUE TITLE
Python related conferences

### ISSUE THREAD

**Issue by malemburg** [python/pythondotorg#359]
Sent to pydotorg-www:

Hi,

I'm Dmitry Filippov, the product marketing manager for PyCharm at JetBrains.
Currently I'm reviewing upcoming Python related conferences to visit with sponsorship and found that info on this page is almost useless:
https://www.python.org/community/workshops/

it links to
1. http://oreilly.com/conferences/oscon/ which was held in 2001 and no longer exist
2. http://pyarkansas.org/  - the last conference was in 2012 and no such conference nowadays.
3. PyCon Brazil should now point to http://2014.pythonbrasil.org.br/
4. RuPy - as far as I know the latest conference in 2013 was the last of RuPy.
5. UKUUG Spring Conference 2008  - too old.

other entries from the list are just partially duplicate the list from http://www.pycon.org/
## 

Dmitry Filippov
Product Marketing Manager
Jetbrains, Inc
http://www.jetbrains.com
"Develop with pleasure!"

**Comment by berkerpeksag** [comment]
Removed IPC, PyArkansas, RuPy, UKUUG, Python Academy Workshop links.
