### ISSUE TITLE
Download URL with a query string 404’s

### ISSUE THREAD

**Issue by benspaulding** [python/pythondotorg#360]
A recent email newsletter linked to the Python 3.4.0 release, but I found that the link returned a 404. Removing the query string produced the expected page.

Good:
https://www.python.org/download/releases/3.4.0
https://www.python.org/download/releases/3.4.0/
https://www.python.org/download/releases/3.4.0/?

404:
https://www.python.org/download/releases/3.4.0/?foo

**Comment by malemburg** [comment]
The query parameter problem is also present when redirecting from a URL with query parameters. See #351.
