### ISSUE TITLE
Homepage: Interactive console doesn't restore slideshow after exiting

### ISSUE THREAD

**Issue by lepot311** [python/pythondotorg#364]
### Description

Launching the PythonAnywhere interactive console on the homepage replaces the contents of the FlexSlider slideshow with an iframe. Upon exiting the console the slideshow is not restored and the console remains at an idle state indefinitely.
### Suggestion

Upon exiting the console, the iframe element should be removed and the slideshow restarted.

**Comment by frankwiles** [comment]
Don't believe there is a way to detect that reliably to make this happen.
