### ISSUE TITLE
RSS link in blog broken

### ISSUE THREAD

**Issue by smontanaro** [python/pythondotorg#371]
From a mail message to webmaster:

---

Hi webmaster of Python.org,

Just a message to tell you that the RSS feed link on the Python.org blog (https://www.python.org/blogs/) is not working because the link is bad (see attached screenshot).
## Best regards,

Quentin THEURET
+33 (0)6 33 23 20 84
![demo_003](https://cloud.githubusercontent.com/assets/3427745/2592030/619d5c5c-ba71-11e3-8c03-6513b02b1901.jpeg)

**Comment by frankwiles** [comment]
Fixed.
