### ISSUE TITLE
Events are shown one day longer than scheduled

### ISSUE THREAD

**Issue by malemburg** [python/pythondotorg#375]
See e.g. https://www.python.org/events/python-events/?page=2

PyCon UK is from Sept 19-22, but the listing shows Sept 19-23.

I guess this has to do with timezones again. Note that most events in the events calendar are full day events.

**Comment by jacobb** [comment]
This actually seems to be a misunderstanding with the ics format than timezones -- from what I can tell, the .ics file stores full-day events with a DTEND value of (to use the given example):

DTSTART;VALUE=DATE:20140919
DTEND;VALUE=DATE:20140923

That is, they "end" (exclusively) at midnight the day after the last day of the event.

Best way to solve this, I think, is to see if DTEND is a date (as opposed to a datetime), and if so, backtrack the end of the event by one day.

Would like to get a confirmation on this before merging, but I'll write up code for it and tag this issue tonight.

**Comment by malemburg** [comment]
This is most likely related to #560.

**Comment by CianciuStyles** [comment]
I have submitted a PR with a possible fix in https://github.com/python/pythondotorg/pull/1161.
