### ISSUE TITLE
Broken image links

### ISSUE THREAD

**Issue by smontanaro** [python/pythondotorg#376]
## From mail to webmaster from Daniel Rech (dr@netsyno.com):

Hi Python.org webmaster-Team,

I was browsing throught the success pages when I noticed there are links to images which don't work:
1. The page https://www.python.org/about/success/journyx/ references
   https://www.python.org/files/success/journyx/te1-half.jpg
2. https://www.python.org/about/success/carmanah/ references
   https://www.python.org/files/success/carmanah/xwalk-closeup-web.jpg

I love python and it's the best programming language in the world. Keep up the good work!

**Comment by frankwiles** [comment]
This was fixed a long time ago, but not closed.
