### ISSUE TITLE
Bad RSS Feed Link

### ISSUE THREAD

**Issue by CurtisLeeBolin** [python/pythondotorg#379]
The RSS Feed Link on page https://www.python.org/blogs/ is bad.
I think maybe it is suppose to be http://feeds.feedburner.com/PythonInsider which can be found at http://blog.python.org/.

Thank You For Your Time

**Comment by sdeibel** [comment]
This is a duplicate of issue #371

**Comment by frankwiles** [comment]
Fixed thanks!
