### ISSUE TITLE
No link to "Sign Up" and "Sign In" Button Tooltip Claims it is, but isn't

### ISSUE THREAD

**Issue by hobson** [python/pythondotorg#380]
"Sign In" button has tool tip that says "Sign In or Sign Up to python.org" but "Sign Up" is not possible at the /signin/ URL which the button launches, at least on Fedora 19 in Chrome browser. The only way I was able to sign up was to manually type the /signup/ URL

![image](https://cloud.githubusercontent.com/assets/292855/2689776/27f2d5a4-c31d-11e3-9a5b-138fd78d824e.png)

**Comment by tbm** [comment]
I just ran into the same issue.

Can you change the title of this issue to make it clearer what's going on.  Maybe something like "no link to sign up page".

**Comment by hobson** [comment]
Webmaster, Michael Foord,  replied that lack of "Sign Up" link is intentional, so this is not a bug. However, the misinformation in the button tooltip could still be considered a bug. "Sign In" is only intended for website maintainers. The "Sign Up" page and backend logic hasn't been implemented yet.
More seriously, the sign up page front end is enabled and sends an e-mail when the form is submitted. I was able to create an account and received notification by e-mail, but my credentials weren't recognized). Malicious folks could use this signup page to flood someone with unwanted e-mails from python.org, so it should be disabled until the proper business logic is implemented.

**Comment by tbm** [comment]
That's imho a pretty serious issue because you have to be logged in in order to sign up as a PSF member (see issue #196).

PSF announced individuals can sign up as members, but there's no easy way to do so...

**Comment by hobson** [comment]
Indeed.

**Comment by frankwiles** [comment]
Fixed awhile ago, but didn't see this ticket.  There is now a drop down menu on 'Sign In' that gives Sign Up option.

**Comment by hobson** [comment]
Awesome. Thanks!
