### ISSUE TITLE
Password Reset Failing

### ISSUE THREAD

**Issue by hobson** [python/pythondotorg#381]
When I reset my password, copying the password from the clipboard to both fill the 2 fields in the reset password form as well as to subsequently attempt to Sign In, the log in fails.  "The user name or password are not correct."  I've verified that the reset-password e-mail and the email I use to Sign In are the same. I've also disabled lastpass in the chrome browser and waited 10 minutes before attempting Sign In. I'm running Fedora 19.

![image](https://cloud.githubusercontent.com/assets/292855/2689820/9858bb5e-c31f-11e3-92f4-632152c4ef7a.png)

**Comment by justinabrahms** [comment]
Unable to reproduce this.

Ran Vagrant box, reset my user's password. It worked using copy + paste.

**Comment by hobson** [comment]
Bug has been fixed. Can be closed.
