### ISSUE TITLE
HTML is displayed at Paypal donation page

### ISSUE THREAD

**Issue by OrangeTux** [python/pythondotorg#382]
The HTML on the [Payal donation page](https://www.python.org/psf/donations/paypal) isn't parsed and will be shown.
![pythondotorg](https://cloud.githubusercontent.com/assets/1565144/2693221/f6d5398c-c3b0-11e3-9f21-8cc354358c21.png)

**Comment by ned-deily** [comment]
Thanks for the report.  It should be working OK now.
