### ISSUE TITLE
PSF Distinguished Service Awards page needs to be updated for 2014

### ISSUE THREAD

**Issue by ned-deily** [python/pythondotorg#384]
https://www.python.org/community/awards/psf-distinguished-awards/

Add Raymond H.  @briancurtin?

**Comment by merwok** [comment]
Last update of the three awards pages is 2012.

**Comment by merwok** [comment]
Brian Curtin indicated on a mailing list he’ll work on that.

**Comment by briancurtin** [comment]
Raymond is now added.
