### ISSUE TITLE
Images missing from Frank Willison Memorial Award page

### ISSUE THREAD

**Issue by ned-deily** [python/pythondotorg#385]
https://www.python.org/community/awards/frank-willison/

On the legacy site, there were images available for some (not all) of the award recipients over the years.  On the new site, these were broken links.  I've removed those by commenting out the image references in the reST source and opening this issue as a reminder.  It can be closed if the status quo is acceptable, i.e. no images for anyone.

**Comment by merwok** [comment]
IMHO the images add a nice human touch.  They can be recovered here: http://web.archive.org/web/20130301193727/http://www.python.org/community/awards/frank-willison/

**Comment by ned-deily** [comment]
The image files are still available in the legacy web site, it's not that they are lost.  It's more a question of how to serve them on the new web site.  AFAICT, media from the old web site did not get transferred over to the new one during the conversion, leaving broken links like these scattered throughout the legacy pages.  Also, it would be fairer to try to provide pictures for everyone, not just those from some years ago.

**Comment by malemburg** [comment]
It is possible to add images to CMS pages and have the CMS maintain
them. I think that's better than going through the repository via pull
requests.

## 

Marc-Andre Lemburg

**Comment by berkerpeksag** [comment]
I've ported all photos to the new site and updated the page. I've also noticed that we don't style `image` directive correctly and opened #1110. Thank you for the report!

**Comment by ned-deily** [comment]
Thanks, @berkerpeksag and @malemburg!  I didn't realize that files and photos could be uploaded through the CMS Page like that.  Nice!

**Comment by berkerpeksag** [comment]
And I think we probably can move all images to the new site automatically. The tricky part is to replace all `.. image:: foo.jpg` usages with `.. image:: $MEDIA_URL_PREFIX/foo.jpg`.
