### ISSUE TITLE
PSF: Broken output on membership FAQ

### ISSUE THREAD

**Issue by tbm** [python/pythondotorg#386]
The membership FAQ at https://www.python.org/psf/membership has broken output under question "What membership classes are there?", point 3:

```
System Message: WARNING/2 (<string>, line 69)

Definition list ends without a blank line; unexpected unindent.
```

**Comment by sigmavirus24** [comment]
If someone wants to point me in the right direction to fix this, I'd be happy to help.

**Comment by ned-deily** [comment]
To modify content pages, you need admin access to the online site.  The bad formatting is now corrected.

**Comment by sigmavirus24** [comment]
Thanks @ned-deily ! :cake:
