### ISSUE TITLE
PSF: membership page links to psfmember.org -- still active?

### ISSUE THREAD

**Issue by tbm** [python/pythondotorg#389]
Point 2 in the FAQ "What membership classes are there?" at https://www.python.org/psf/membership says:

```
    Supporting members make an annual donation to the PSF
    to sustain the Foundation and support the Python community. You
    can sign up as an supporting member at <http://www.psfmember.org>.
```

Is psfmember.org still the right page to link to?  It talks about PyCon 2011.  Also, it uses the term "Associate Member" whereas the main PSF page talks about "supporting member".

If so, it would make sense to link to it from https://www.python.org/users/membership/

**Comment by KartikKannapur** [comment]
The answer for the FAQ - _What membership classes are there?_ has been updated. So this issue has been solved.

I agree. Redirecting https://psfmember.org/ to https://www.python.org/users/membership/ would make more sense.

**Comment by MarkMangoba** [comment]
Consolidating psf-membership tickets with the new integration with CiviCRM.
