### ISSUE TITLE
PSF: Mission links to membership FAQ entry that no longer exists

### ISSUE THREAD

**Issue by tbm** [python/pythondotorg#392]
The mission at https://www.python.org/psf/mission links to https://www.python.org/psf/membership/#how-does-one-become-a-member-of-the-psf which no longer exists (although I think it should; see issue #391).

**Comment by berkerpeksag** [comment]
Thanks for the report. https://www.python.org/psf/membership/ has been updated to cover the PSF's new membership format so there is no "How does one become a member of the PSF?" section anymore. The first section is titled "What does it mean to be a member of the PSF?" now. I've removed `#how-does-one-become-a-member-of-the-psf` part from the URL.
