### ISSUE TITLE
PSF: tax return for 2012 (form 990) missing

### ISSUE THREAD

**Issue by tbm** [python/pythondotorg#394]
The tax return for 2012 (form 990) is not listed at https://www.python.org/psf/records/#irs-tax-returns-990-open-for-public-inspection even though PSF must have filed it several months ago.

I assume the 2013 tax return hasn't been completed yet, otherwise please add that too.

**Comment by ejodlowska** [comment]
The 2012 990 has been added: https://www.python.org/psf/records/#irs-tax-returns-990-open-for-public-inspection
