### ISSUE TITLE
PSF member sign up: why require postal address?  Privacy policy?

### ISSUE THREAD

**Issue by tbm** [python/pythondotorg#396]
Signing up as a PSF member at https://www.python.org/users/membership/ asks for city, state, country and postal code.

Are these details really necessary?  If they are, you should at least explain how they are going to be used (are you going to spam people?) and there should be a privacy policy (are you going to share my details with companies that might spam me?).

**Comment by tbm** [comment]
Probably a question for Van.

**Comment by MarkMangoba** [comment]
We gather this for internal statical reports and growth indicators.
