### ISSUE TITLE
"Become a member" link points to the wrong page

### ISSUE THREAD

**Issue by adewes** [python/pythondotorg#397]
Currently the "Become a member" link in https://github.com/python/pythondotorg/blob/776bf6df8976b24fadb8c1ea3955ee49d0a5eb7b/fixtures/boxes.json points to `users:user_membership_edit`, which redirects to the login page if the user is not logged in. Should probably point to the signup page instead in that case?

**Comment by tbm** [comment]
Possibly related to issue #380

**Comment by kenbolton** [comment]
I emailed webmaster about this last week. If you have a hybrid signup/login page, that would be the place to redirect.

**Comment by frankwiles** [comment]
Fixed long ago actually.  Thanks for reporting it!
