### ISSUE TITLE
Chef/Vagrant: susy gem not getting installed

### ISSUE THREAD

**Issue by wbachnik** [python/pythondotorg#404]
susy gem (along with compass)is not getting installed by chef, despite being declared in [chef/cookbooks/pythondotorg/recipes/prereq.rb](https://github.com/python/pythondotorg/blob/master/chef/cookbooks/pythondotorg/recipes/prereq.rb).

**How to reproduce:**

```
vagrant up
vagrant ssh
gem list
```

`gem list` returns empty list. Because of this gem missing Django fails to serve pages.

**Workaround:**
Install susy gem manually (it will install compass as a dependency): 

```
sudo gem install susy
```

After doing that Django is able to serve pages.

**Comment by justinabrahms** [comment]
Confirmed that this is happening. Spent some time trying to diagnose it, but was unfruitful. The prereq cookbook is being loaded. The commands are being run. `gem_package` isn't working, however.
