### ISSUE TITLE
Error 404 for pgp keys

### ISSUE THREAD

**Issue by voidspace** [python/pythondotorg#407]
On the download page, the following two links are 404s.

Ned Deily (key id: 6F5E1540)
Larry Hastings (key id: F73C700D)

From: https://www.python.org/download 

Note that these links may also appear on other pages.

**Comment by ned-deily** [comment]
I've fixed the link to mine and have asked Larry to make his available at a new URI.  A quick search of the legacy web site source did not find any other references to these links.

**Comment by ned-deily** [comment]
And Larry has now done that.  So I think this issue can be closed.
