### ISSUE TITLE
Python, About text = PSF, About text

### ISSUE THREAD

**Issue by CarlFK** [python/pythondotorg#411]
https://www.python.org/

hover over About, see:

"""
The Python Software Foundation maintains and supports open-source Python software
The PSF runs PyCon, supports conferences around the world, and funds Python-related development with a grants program. Learn more about the PSF. 
"""

Same text as PSF, About - so I am guessing there should be different text for Python, About.

**Comment by techtonik** [comment]
It became all about PSF corp. recently and less about Python and community.

**Comment by ned-deily** [comment]
Thanks for the report. This seems to be an oversight from when the new website was originally populated.  I've adapted some text from the legacy site's home page.
