### ISSUE TITLE
Link to 3.4 release incorrect on download page

### ISSUE THREAD

**Issue by voidspace** [python/pythondotorg#413]
On the download page ( https://www.python.org/download/ ), the main download link goes to:

https://www.python.org/download/download/releases/3.4.0/

It obviously should be https://www.python.org/download/releases/3.4.0/

**Comment by merwok** [comment]
@gutworth As a newcomer to Django development, I often wonder whether something is fixed with an edit to code, settings, templates or manually in the admin.  Would it add too much burden to the website team to e.g. give a changeset ID when closing a bug report?  Thanks in advance.

**Comment by ned-deily** [comment]
The problem is that most of the bugs, like this one, have to do with the content of pages.  They are stored in the database and managed through the Django admin interface. They have nothing to do directly with the website code base and are not revision controlled.
