### ISSUE TITLE
Certificate failure?

### ISSUE THREAD

**Issue by ghost** [python/pythondotorg#415]
I tried this today.

$ wget https://www.python.org/ftp/python/3.4.0/Python-3.4.0.tgz
--2014-05-01 16:56:59--  https://www.python.org/ftp/python/3.4.0/Python-3.4.0.tgz
Resolving www.python.org... 199.27.73.175
Connecting to www.python.org|199.27.73.175|:443... connected.
ERROR: certificate common name “*.c.ssl.fastly.net” doesn’t match requested host name “www.python.org”.
To connect to www.python.org insecurely, use ‘--no-check-certificate’.

I got that address from the www.python.org web site using "Copy link location" and pasting to the command line.

Is there a different server from which I can/should be getting source tar balls?

Thanks,  -- bennet

**Comment by benjaminp** [comment]
You probably have an old version of wget.

**Comment by ghost** [comment]
Updating to wget 1.15 from gnu.org and building from source resolved the
certificate-not-matching issue, but introduced others, as reported
elsewhere.

The problem appears to have been, instead, the openssl version, not wget.
Updating to the latest and greatest openssl available for RHEL 6 makes wget
1.12 work without any error messages.
In case the information is of use to someone else, for RHEL 6, this version
exhibited the error,

```
openssl-1.0.1e-16.el6_5.x86_64
```

whereas the latest update to

```
openssl-1.0.1e-16.el6_5.7.x86_64
```

does not.
