### ISSUE TITLE
Add Conda/Anaconda to "Alternative Packages for ..."

### ISSUE THREAD

**Issue by paidhi** [python/pythondotorg#416]
I would like to suggest adding Conda/Anaconda to the list of "Alternative Packages for Mac OS X" and "Alternative Packages for Windows":
https://www.python.org/download/mac#alternative-packages-for-mac-os-x
https://www.python.org/download/windows#alternative-packages-for-windows

http://docs.continuum.io/anaconda/index.html
http://conda.pydata.org/docs/

Conda seems to become increasingly popular. Especially for replacing ActivePython and Enthought.

**Comment by ned-deily** [comment]
Thanks for the suggestion.  Links to Anaconda have been added to the two download pages.
