### ISSUE TITLE
Checksum mismatch for Python-3.1.5 download

### ISSUE THREAD

**Issue by wosc** [python/pythondotorg#419]
On https://www.python.org/downloads/release/python-315/
for the gzipped source tarball the MD5 sum is given as
3a55bd994a081cea8e68d1773a7ea0d6 and the file size as 51537920,
but when I download the linked file https://www.python.org/ftp/python/3.1.5/Python-3.1.5.tgz I get a file of size 11798798 and a checksum of 02196d3fc7bc76bdda68aa36b0dd16ab.

Could you look into what's going on here?

**Comment by ned-deily** [comment]
Those values on that page are incorrect.  The proper ones - what you saw - are on the old website: http://legacy.python.org/download/releases/3.1.5/

**Comment by ned-deily** [comment]
It's fixed now.  Thanks for the report.
