### ISSUE TITLE
Dead link and typo

### ISSUE THREAD

**Issue by voidspace** [python/pythondotorg#422]
Reported to webmaster:

The screenshot link at https://www.python.org/about/success/mayavi/ doesn’t work.

Also, at https://www.python.org/about/success/#scientific-programing, isn’t it “programming” rather than “programing”, even in US spelling?

**Comment by justinabrahms** [comment]
This doesn't appear to be an issue any longer.

**Comment by KartikKannapur** [comment]
The screenshot link seems to work now. 
I suppose we can close this issue.
