### ISSUE TITLE
Suggested additions to Mac download page

### ISSUE THREAD

**Issue by voidspace** [python/pythondotorg#423]
Reported to webmaster@python.org

I would like to suggest adding Conda/Anaconda to the list of "Alternative Packages for Mac OS X" on https://www.python.org/download/mac
http://docs.continuum.io/anaconda/index.html
http://conda.pydata.org/docs/

It seems to become increasingly popular. Especially for replacing ActivePython and Enthought.

**Comment by ned-deily** [comment]
Duplicate of #416
