### ISSUE TITLE
Layout problems on centos firefox

### ISSUE THREAD

**Issue by voidspace** [python/pythondotorg#424]
Reported to webmaster@python.org
![display_problem](https://cloud.githubusercontent.com/assets/127179/2909754/462d6778-d637-11e3-9132-a83ae8368b9d.png)

I couldn't find where to report this, so I'm reporting it directly to 
you. The new layout is _terribly_ corrupted on this page:

https://www.python.org/download/releases/2.2.3/descrintro

See attached screenshot.

I'm using Firefox 24.3.0 on Centos (Linux), and the corruption isn't 
fixed by turning Javascript on or off.

The display seems to screw up about 80% of the way down the page, when 
you reach the "Metaclasses" section.

**Comment by ned-deily** [comment]
That page renders OK for me with both FF 30 (beta) and Safari 7.0.3 (both on OS X).  Is anyone else seeing this problem?

**Comment by ghost** [comment]
add linux or centos label, so its easy to search this.
layout is not corrupted on windows 10 1903 in google chrome 77

**Comment by hugovk** [comment]
It's now looking fine in Chrome, Firefox and Safari on macOS.
