### ISSUE TITLE
Checksum for Python 3.1.5

### ISSUE THREAD

**Issue by voidspace** [python/pythondotorg#425]
Reported on webmaster@python.org

on https://www.python.org/downloads/release/python-315/ for the
gzipped source tarball the MD5 sum is given as 
3a55bd994a081cea8e68d1773a7ea0d6 and the file size as 51537920, but
when I download the linked file
https://www.python.org/ftp/python/3.1.5/Python-3.1.5.tgz I get a
file of size 11798798 and a checksum of
02196d3fc7bc76bdda68aa36b0dd16ab.

Could you look into what's going on here?

looks fishy since the bz2 and xz sizes are much closer to what you
got, gz expected to be just a little bigger, not more than 5x bigger :(

**Comment by ned-deily** [comment]
Duplicate of #419

**Comment by voidspace** [comment]
Oops, sorry.
