### ISSUE TITLE
Incorrect Hyperlink on Python Download Page

### ISSUE THREAD

**Issue by barronstone** [python/pythondotorg#426]
On the bottom of the Python download page, footnote [2] is supposed to link to a page with additional information about IDLE, Tkinter, and Tcl/Tk on Mac.

This is the current link address it points to which causes a 404 error:
https://www.python.org/mac/tcltk

I believe it should actually link to here:
https://www.python.org/download/mac/tcltk

**Comment by ned-deily** [comment]
Which download page are you referring to?

**Comment by barronstone** [comment]
This is the download page I'm referring to:
https://www.python.org/download

**Comment by ned-deily** [comment]
Thanks!  Now fixed.

**Comment by barronstone** [comment]
Thanks Ned :)

**Comment by abhishekgahlot** [comment]
Hi again, I believe its again 404 now on page https://www.python.org/download/ 
Link to Tcl/Tk at bottom of page is  https://www.python.org/download/download/mac/tcltk/ 
with extra download string in the url. Removing that fix the issue.

**Comment by ned-deily** [comment]
Thanks for the report: it's fixed again.
