### ISSUE TITLE
docutils admonitions no longer stand out

### ISSUE THREAD

**Issue by briancurtin** [python/pythondotorg#428]
The change to the new site seemed to have dropped whatever style changes were making admonitions stand out from regular text. For example, the top of https://www.python.org/download/releases/2.7 is currently just plain "Note:" text pointing to the latest release, but changing it to ".. Note::" doesn't seem to matter - makes it worse, actually. Ideally that text would stand out more to make it seen that it's not the latest release.

The note at the bottom of https://www.python.org/psf/codeofconduct/ also used to standout.

**Comment by Mariatta** [comment]
I just made a pull request for adding box around the Note in code of conduct page.
However, as pointed out in the ticket, the Note field in the download page is not using `.. Note::` directive, but rather just a plain note. Therefore it will remain as is.
I'm wondering if the document should be updated to use the `.. Note::` directive?
