### ISSUE TITLE
PSF recognizes *three* categories of members

### ISSUE THREAD

**Issue by CarlFK** [python/pythondotorg#429]
"Below are the PSF Members. The PSF recognizes three categories of members:"
https://www.python.org/psf/members/#members

"There are six classes of members..."
https://www.python.org/psf/membership#what-membership-classes-are-there

**Comment by berkerpeksag** [comment]
The section now starts with

> The PSF recognizes several categories of members:
> * Fellows are elected on merit
> * Emeritus Fellows are no longer active in the PSF
> * Contributing / managing members support the PSF's mission by actively engaging in bringing Python forward

And ends with

> Only the first three membership categories are listed on this page, until we find a way to add the others as well.

However, it only lists Fellows and Emeritus Fellows (I don't count "Deceased Fellows" as a membership category) so I updated "Only the first three" to "Only the first two".

Thank you for the report.
