### ISSUE TITLE
PSF: donations page refers to missing credit card donation form

### ISSUE THREAD

**Issue by ned-deily** [python/pythondotorg#431]
"Donate by credit card using the form at upper right."

https://www.python.org/psf/donations/
http://legacy.python.org/psf/donations/

**Comment by ned-deily** [comment]
It's another specially-generated page that did not get ported fully from the legacy web site: http://legacy.python.org/psf/donations/.  The legacy site has a cgi script in the form and obviously there are privacy issues so it is important that it be implemented properly.  Perhaps the thing to do until someone takes this on is to just comment out the donate-by-credit card text.  Does that sound reasonable, @alex?

**Comment by alex** [comment]
Removing the confusing text definitely would be good.

**Comment by ned-deily** [comment]
OK, the credit card section is now commented out.

**Comment by malemburg** [comment]
I've added it back, but with a referral to the old site. We don't want to lose those CC donations.

Did the same for the donors list at the bottom of the page (this still gets updated on the legacy site).

Regarding the form: we could simply add it back to the page, but it uses HTTP, not HTTPS, so the user would see a warning... not good for CC payments :-( The CGI script itself is not in the legacy repo. I think Kurt or Andrew wrote it, so we'd have to ping them about it.

**Comment by ned-deily** [comment]
The form on the legacy site appears to be broken as well.  I'll see if I can make it work again.

**Comment by malemburg** [comment]
Ouch, yes. It points to the www.python.org address. Perhaps using legacy.python.org would make it work again.

**Comment by ned-deily** [comment]
Yeah, I've changed it but it hasn't updated the page yet.  Of course, it will still be insecure since https is not supported on legacy.python.org.

**Comment by malemburg** [comment]
Try a site rebuild, but this didn't update the form either. Turns out that there's a permission problem on dinsdale:

```
$ svn update new-build/
svn: Can't open file 'new-build/fragments/.svn/tmp/entries': Permission denied
```

The tmp/ dir doesn't have group write permissions. This causes the svn update to fail and that's the reason why the form update doesn't make it into the build.

**Comment by ned-deily** [comment]
Oh, right. I ran into that before.  Alas, I don't have root permission.  Perhaps @gutworth can fix it in the morning.

**Comment by malemburg** [comment]
I'll ping Andrew. Perhaps he can help. There are several files/dirs in the new-build/ dir which don't have the group permissions setup correctly.

**Comment by ned-deily** [comment]
OK, good luck!

**Comment by malemburg** [comment]
After lots of back and forth, I've now finally managed to get the legacy site updated. Turns out, all this effort was useless, because the script reports:
"""
Your Input Contains the Following Errors

```
Sorry, donations using this method are temporarily disabled due to a fraud attack. Please use the PayPal button (it accepts credit cards, too) or contact kbk@shore.net
```

"""

I'll remove the CC section from the page for good now.

**Comment by malemburg** [comment]
Done. I added text to refer to the PayPal button, since this can also be used for CC donations without a PayPal account.
