### ISSUE TITLE
404 on 2.6 releases pages

### ISSUE THREAD

**Issue by romuald** [python/pythondotorg#433]
On the 2.6.x release pages, the "NEWS file" links points to a non-existing page.

Example:  https://www.python.org/download/releases/2.6.9

Points to https://www.python.org/download/releases/NEWS.txt that doesn't exists

The most relevant link would by IMHO a link to the source tree: http://hg.python.org/cpython/file/v2.6.9/Misc/NEWS

**Comment by ned-deily** [comment]
Thanks for the report.  I believe all of the broken links on the 2.6.9 release page are now fixed.
