### ISSUE TITLE
Calendar event pages show description as plain text

### ISSUE THREAD

**Issue by malemburg** [python/pythondotorg#435]
This was already fixed some time ago in #156, but has now resurfaced for all events entered more recently.

See e.g.

https://www.python.org/events/python-user-group/174/
https://www.python.org/events/python-user-group/167/
https://www.python.org/events/python-user-group/169/

The problem does not exist for older entries.

**Comment by malemburg** [comment]
This must be a bug in the script adding these events, or perhaps one with a migration not having run through on the production system.

**Comment by frankwiles** [comment]
I just dove into this and it's caused by the html_escape=True flag [here](https://github.com/python/pythondotorg/blob/master/events/models.py#L97).  

Turning it off would expose the site to the possibility of a calendar owner or bad actor injecting unsafe markup.  Thoughts on how we should proceed with this one?

**Comment by malemburg** [comment]
On 11.09.2014 00:09, Frank Wiles wrote:

> I just dove into this and it's caused by the html_escape=True flag [here](https://github.com/python/pythondotorg/blob/master/events/models.py#L97).  
> 
> Turning it off would expose the site to the possibility of a calendar owner or bad actor injecting unsafe markup.  Thoughts on how we should proceed with this one? 

We own the calendars which the site uses as input, so this is safe.

## 

Marc-Andre Lemburg

**Comment by frankwiles** [comment]
Cool, I'll fix it then.

**Comment by jefftriplett** [comment]
I think it's safe to change since we currently do not let arbitrary users add events to the system. When we had the security report I think I was over zealous and I marked all three models which reference `MarkupField` fields just to make sure nothing fell through the cracks. MY BAD.
