### ISSUE TITLE
PDF link to CLA is a 404

### ISSUE THREAD

**Issue by alex** [python/pythondotorg#437]
This is the "PDF version" link on https://www.python.org/psf/contrib/contrib-form/

**Comment by alex** [comment]
http://legacy.python.org/psf/contrib/contrib-form/contributor-agreement.pdf is a link to the right content AFAICT

**Comment by ned-deily** [comment]
Thanks for the report. The link now points to that PDF on legacy.  (Eventually, files like this will need to be moved onto the new website.)
