### ISSUE TITLE
Dead Links to Signatures for 2.7, 3.0, 3.1

### ISSUE THREAD

**Issue by skletzk** [python/pythondotorg#439]
The links to signatures for the downloads of Python 2.7, 3.0 and 3.1 all seem to be dead and return 404s. I believe that the paths are incorrect. For instance, the link to the signature for the gzipped source tar ball is:
https://www.python.org/download/releases/Python-2.7.tgz.asc
which 404s, but the actual file can be found here:
https://www.python.org/ftp/python/2.7/Python-2.7.tgz.asc

I think the paths just need to be changed for the pages that have this issue. The page for version 2.7.6 does not have this issue (that's how I found the correct paths).

**Comment by ned-deily** [comment]
Thanks for the report.  I think all of the signature links for these releases are now fixed.
