### ISSUE TITLE
Errors in C++ sig page

### ISSUE THREAD

**Issue by smontanaro** [python/pythondotorg#440]
From webmaster mail:

---

I'm not sure where to report bugs about the Python.org web site. If
this is the wrong place please tell we the right one so I can do better
next time :-)

The page https://www.python.org/community/sigs/current/cplusplus-sig/
contains lots of error messages from docutils and is hardly readable. It
looks like someone accidentally used HTML as input for docutils.

As it doesn't seem to have seen any updates in the last 12 years it
probably should be removed anyway.

**Comment by ned-deily** [comment]
Now fixed
