### ISSUE TITLE
bad link

### ISSUE THREAD

**Issue by CarlFK** [python/pythondotorg#444]
https://www.python.org/psf

Contents
    PSF Details & Contacting the PSF

https://www.python.org/psf#psf-details-contacting-the-psf
Please see ...  href="about/#how-do-i-reach-the-psf">About the Python Software Foundation</a>.
click
https://www.python.org/about/#how-do-i-reach-the-psf
That is "About Python" not the PSF.

_maybe_ https://www.python.org/psf/about/#how-do-i-reach-the-psf
but that isn't really about.

**Comment by frankwiles** [comment]
Fixed thanks!
