### ISSUE TITLE
newjobs/review  	statusaction

### ISSUE THREAD

**Issue by CarlFK** [python/pythondotorg#447]
https://www.python.org/newjobs/review/

colum headers:      status  action
    the styling has them next to each other so it looks like one word.

**Comment by SarahPythonista** [comment]
Can someone who knows CSS take a look at this?

**Comment by berkerpeksag** [comment]
Working on this.

**Comment by berkerpeksag** [comment]
Ok, please feel free to work on this. The problem is simple. I've fixed it via some plain CSS work, but the whole sass/compass/susy thing gave me brain damage.

**Comment by berkerpeksag** [comment]
I've fixed the problem. Here is a screenshot:

![py2](https://cloud.githubusercontent.com/assets/26338/6546830/f5a8484c-c5cb-11e4-81fd-0e5018f819b1.png)

I'll send it in a PR if it looks good.

**Comment by SarahPythonista** [comment]
That looks awesome! Thanks!

**Comment by malemburg** [comment]
@berkerpeksag Looks very nice. 

Could you perhaps also make the link to the job posting record (the ID on the left) more obvious or perhaps even add an "Edit" button on the right. The reviewers will have to use this link/button a lot, since it's the only way to access the complete job data.

Thanks.

**Comment by berkerpeksag** [comment]
> perhaps even add an "Edit" button on the right.

Hi, thanks for the feedback. Already added that in the PR.

**Comment by malemburg** [comment]
Thanks for the PR. I just merged it and it should be live on staging in a while (not sure exactly how long it takes).

**Comment by malemburg** [comment]
Hmm, the "edit" button doesn't seem to work. It gives a 404.

Perhaps it would be better to name it "review" and have ti go to the /jobid/review page ?!

**Comment by malemburg** [comment]
The reason for the 404 seems to be that I'm not the creator of the job entry. If I create a job while logged in, the edit button works as is.

Now, for the review workflow that's not very useful, since a reviewer will just want to have a look at the data, not necessarily edit it.

**Comment by malemburg** [comment]
Filed #617 for the 404 issue.

**Comment by berkerpeksag** [comment]
Will take a look at it. Thanks.

**Comment by malemburg** [comment]
I fixed the button now. Should be live in a short while to check.

**Comment by malemburg** [comment]
Hmm, looks like the CSS needs some fixing as well :-)

**Comment by malemburg** [comment]
Also added a button for the "archive" action.

**Comment by berkerpeksag** [comment]
Can this be closed now?

**Comment by malemburg** [comment]
I guess so, unless someone want to tweak the CSS some more to make the buttons a little smaller or the button area wider.

**Comment by berkerpeksag** [comment]
Ah, sorry I missed your earlier comment. Will tweak CSS a bit.

**Comment by malemburg** [comment]
@berkerpeksag Thanks :-)

**Comment by berkerpeksag** [comment]
Done: https://github.com/python/pythondotorg/commit/9bbee198234bb82687e7fc7761722af5cda610c1 Changed layout of the table a bit.

**Comment by malemburg** [comment]
Nice :-) Thank you.
