### ISSUE TITLE
Upgrade to the latest Django CMS 3.0

### ISSUE THREAD

**Issue by malemburg** [python/pythondotorg#448]
The site currently seems to use a very old version of the Django CMS.

The current version 3.0 has lots more to offer, in particular, it is possible to see page revisions, which the deployed system on python.org does not provide. It also comes with Python 3.3 support.

Resources:
- https://www.django-cms.org/en/
- http://docs.django-cms.org/en/3.0.1/upgrade/3.0.html

**Comment by benjaminp** [comment]
We should also upgrade Django itself, since python.org is 2 versions
behind now.

**Comment by frankwiles** [comment]
python.org doesn't use django-cms upgranding Django versions is definitely worth doing however.  Will open new ticket on that.
