### ISSUE TITLE
Various minor issues with web site

### ISSUE THREAD

**Issue by mark-summerfield** [python/pythondotorg#450]
(1)

On this page:
https://www.python.org/

The Latest New's most recent entry is:
2014-03-17 Python 3.4.0 has been released today. 

But there's no entry for 3.4.1 even though there is one for 3.3.5.

(2)

On this page:
https://www.python.org/blogs/

Dates appear to be given in US format, e.g.,

Python 3.3.5 released
03/11/2014

which looks like 3rd November to a European. It should use ISO 8601
format like the main page does.

Also this page doesn't mention the release of 3.4.0 let alone the 3.4.1
point release.

(3)

Back on the main page.

Example (3) might benefit from a comment at the end:
# Naturally, an efficient fibonacci function is available

Example (5) uses % formatting

I'd argue that this:

```
print('Hi, %s.' % name)
```

though shorter, looks a lot more intimidating and technical than this:

```
print('Hi, {}.'.format(name))
```

although this might be better:

```
print('Hi, {you}.'.format(you=name))
```

I also find the dark gray on black comments almost unreadable.

Example (2): "fruit" is the plural of "fruit"; no need to write
"fruits".

Example (4): I really dislike this; using 'list' and 'sum' as variables
is going to end up confusing people and driving them nuts!
How about this instead:

```
# For loop on a list
>>> evens = [2, 4, 6, 8]
>>> total = 0
>>> for number in evens:
>>>     total = total + number
>>> print("The total is:", total)  
The total is: 20
# This can also be done in one statement
>>> print("The total is:", sum(evens))  
The total is: 20
```

(4)

I'm using Firefox (Iceweasel) 24.5.0 on Debian and on the home page
instead of getting some Unicode character to the left of Getting
Started, Download, etc., I just get a rectangle with the Unicode code
point U+E616 and U+E609 I think (it is v. hard to read).

(5)

It is difficult to find the bugs page from the main page. As far as I
can tell you have to:
    (i) Scroll to the bottom
    (ii) Click Developer's Guide (how could anyone know that!)
    (iii) Scroll down to Quick Links (ditto)
    (iv) Click Issue Tracker

I think there should be a direct link to the issue tracker under the
Community list of links.

(6)

Overall I think the new site looks more professional than the old one:-)

**Comment by frankwiles** [comment]
1) All content for the News pages comes from the PSF blog directly when there is new content there it gets on python.org a few minutes later (see http://blog.python.org/)

2) Fixed date format, will go live shortly

**Comment by frankwiles** [comment]
I believe all of these are fixed now.  Please re-open individual issues if I'm wrong! Thanks!
