### ISSUE TITLE
Release Notes link don't work on https://www.python.org/downloads/

### ISSUE THREAD

**Issue by yeiniel** [python/pythondotorg#451]
The "Release Notes" link when clicked on page https://www.python.org/downloads/ only reloads the same page.

**Comment by ned-deily** [comment]
Can you be more specific?  There are "Release Notes" links for each release and the latest ones, at least, seem to open the right page.

**Comment by yeiniel** [comment]
for example the release notes for python 3.3.3, 2.6.9, 3.3.2, 2.7.5 are some of them.

**Comment by ned-deily** [comment]
Thanks, I had just looked at the most recent ones.  With a little bit of hackery, I've updated the release entries so that they now all should have valid "Release Notes" links.
