### ISSUE TITLE
OpenID not working? Attack or bug?

### ISSUE THREAD

**Issue by nerdoc** [python/pythondotorg#452]
I tried to login at python.org with OpenID using Launchpad, clicked on the launchpad icon, filled in my launchpad credentials at launchpad's and confirmed. I came back to python.org, the username was prefilled with "login.launchpad.net_145", OpenID and email address too.. but when I clicked on "register", I only get a white screen saying: "OpenID
response has been tampered with:NotAuthenticated('Replay attack detected', 9)"

What is this?  A bug? Why is it not possible to login via OpenID?

**Comment by frankwiles** [comment]
No idea if this was supported before or desired in the future.  Adding psf-review label to have a decision made.

**Comment by asfaltboy** [comment]
I'm having trouble adding a google OpenID, returns error: `OpenID discovery failure, not a valid OpenID`. Interesting, it seems google has [stopped supporting OpenID](https://support.google.com/accounts/answer/6206245?p=openid&rd=1)

Also: `myopenid.com` seems to be an invalid option, the url and icon are broken,

**Comment by malemburg** [comment]
Google has switched off OpenID support. Please use Launchpad if you want to use OpenID, or user id and password to log into the wiki.

MyOpenID.com has shut down as well, so Launchpad is the only working option left.

**Comment by lac22** [comment]
In a message of Mon, 05 Oct 2015 06:22:15 -0700, Marc-Andre Lemburg writes:

> Google has switched off OpenID support. Please use Launchpad if you want to use OpenID, or user id and password to log into the wiki.
> 
> MyOpenID.com has shut down as well, so Launchpad is the only working option left.

I am using verisigns openid.
https://pip.verisignlabs.com/login.do

Does this not work?

Laura

**Comment by asfaltboy** [comment]
Perhaps they are maintaining the existing openid user urls, but new signups are disabled: https://pip.verisignlabs.com/register.do

> In a message of Mon, 05 Oct 2015 06:22:15 -0700, Marc-Andre Lemburg writes:
> Google has switched off OpenID support. Please use Launchpad if you want to use OpenID, or user id and password to log into the wiki.
> 
> MyOpenID.com has shut down as well, so Launchpad is the only working option left.
> I am using verisigns openid.
> https://pip.verisignlabs.com/login.do
> 
> Does this not work?
> 
> Laura
