### ISSUE TITLE
iPython session broken by typing 'help'

### ISSUE THREAD

**Issue by Oooklout** [python/pythondotorg#453]
I attach the following transcript of what seems to be  a broken session I had with your home page iPython. It all seemed to go wrong about where I typed 'help?'. I then entered a few <CR>s and got the confused text about 'magic' this and that. After that I hit ^C to try to restore control but it did not help as you can see.  
I hope this is useful.
Best regards
Simon Ashby (Oooklout)

Python 3.3.2+ (default, Feb 28 2014, 00:52:16)
Type "copyright", "credits" or "license" for more information.
IPython 1.0.0 -- An enhanced Interactive Python.
? -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help -> Python's own help system.
object? -> Details about 'object', use 'object??' for extra details.
In [1]: help?
Type: _Helper
String Form:Type help() for interactive help, or help(object) for help about object.
File: /usr/lib/python3.3/site.py
Definition: help(self, _args, *_kwds)
Docstring:
Define the builtin 'help'.
This is a wrapper around pydoc.help (with a twist).
Call def: help(self, _args, *_kwds)
In [2]: %q
ERROR: Line magic function `%q` not found.
In [3]: %quickref
# IPython -- An enhanced Interactive Python - Quick Reference Card

obj?, obj?? : Get help, or more help for object (also works as
?obj, ??obj).
?foo._abc_ : List names in 'foo' containing 'abc' in them.
%magic : Information about IPython's 'magic' % functions.
Magic functions are prefixed by % or %%, and typically take their arguments
without parentheses, quotes or even commas for convenience. Line magics take a
single % and cell magics are prefixed with two %%.
Example magic function calls:
%alias d ls -F : 'd' is now an alias for 'ls -F'
alias d ls -F : Works if 'alias' not a python name
:---------------------------------------------------------------------------
KeyboardInterrupt Traceback (most recent call last)
<ipython-input-3-94238ad11ba8> in <module>()
----> 1 get_ipython().magic('quickref')
/usr/local/lib/python3.3/dist-packages/IPython/core/interactiveshell.py in magic(self, arg_s)
2165 magic_name, _, magic_arg_s = arg_s.partition(' ')
2166 magic_name = magic_name.lstrip(prefilter.ESC_MAGIC)
-> 2167 return self.run_line_magic(magic_name, magic_arg_s)
2168
2169 #-------------------------------------------------------------------------
/usr/local/lib/python3.3/dist-packages/IPython/core/interactiveshell.py in run_line_magic(self, magic_name, line)
2086 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
2087 with self.builtin_trap:
-> 2088 result = fn(_args,__kwargs)
2089 return result
2090
/usr/local/lib/python3.3/dist-packages/IPython/core/magics/basic.py in quickref(self, arg)
/usr/local/lib/python3.3/dist-packages/IPython/core/magic.py in <lambda>(f, *a, *_k)
190 # but it's overkill for just that one bit of state.
191 def magic_deco(arg):
--> 192 call = lambda f, _a, *_k: f(_a, *_k)
193
194 if isinstance(arg, collections.Callable):
/usr/local/lib/python3.3/dist-packages/IPython/core/magics/basic.py in quickref(self, arg)
416 from IPython.core.usage import quick_reference
417 qr = quick_reference + self._magic_docs(brief=True)
--> 418 page.page(qr)
419
420 @line_magic
/usr/local/lib/python3.3/dist-packages/IPython/core/page.py in page(strng, start, screen_lines, pager_cmd)
230 strng, encoding=pager_encoding))
231 finally:
--> 232 retval = pager.close()
233 except IOError as msg: # broken pipe when user quits
234 if msg.args == (32, 'Broken pipe'):
/usr/lib/python3.3/os.py in close(self)
1020 def close(self):
1021 self._stream.close()
-> 1022 returncode = self._proc.wait()
1023 if returncode == 0:
1024 return None
/usr/lib/python3.3/subprocess.py in wait(self, timeout, endtime)
1536 else:
1537 while self.returncode is None:
-> 1538 (pid, sts) = self._try_wait(0)
1539 # Check the pid and loop as waitpid has been known to return
1540 # 0 even without WNOHANG in odd situations. issue14396.
/usr/lib/python3.3/subprocess.py in _try_wait(self, wait_flags)
1493 def _try_wait(self, wait_flags):
1494 try:
-> 1495 (pid, sts) = _eintr_retry_call(os.waitpid, self.pid, wait_flags)
1496 except OSError as e:
1497 if e.errno != errno.ECHILD:
/usr/lib/python3.3/subprocess.py in _eintr_retry_call(func, _args)
477 while True:
478 try:
--> 479 return func(_args)
480 except InterruptedError:
481 continue
KeyboardInterrupt:
alist = %alias : Get list of aliases to 'alist'
:
cd /usr/share : Obvious. cd -<tab> to choose from visited dirs.
:
%cd?? : See help AND source for magic %cd
:
%timeit x=10 : time the 'x=10' statement with high precision.
:
%%timeit x=2**100
x**100 : time 'x_100' with a setup of 'x=2_*100'; setup code is not
:
counted. This is an example of a cell magic.
:

**Comment by frankwiles** [comment]
I just tried to reproduce this and I think the issue is that it uses more/less to page the output of %quickref, which is the expected behavior in an IPython shell.  Confusing perhaps, but not a bug.
