### ISSUE TITLE
Error 404: File not Found error

### ISSUE THREAD

**Issue by mmarbury** [python/pythondotorg#456]
I’m trying to get the Python version 1.6.1 for windows from this link:

https://www.python.org/download/releases/download_win

I’m getting a 404:

"Error 404: File not Found
We couldn’t find what you were looking for. This error has been reported and we will look into it shortly."

Please help!

Thanks! - Matt

**Comment by ned-deily** [comment]
Thanks for the report.  The 1.6.1 download pages were mangled in the transition from the legacy website.  If you now go to the release page, https://www.python.org/download/releases/1.6.1/, the various download links should now work as originally intended.  For technical reasons, the URL for the Windows download was changed to https://www.python.org/download/releases/1.6.1/download-win.
