### ISSUE TITLE
CSS issue: background turns black for long pages

### ISSUE THREAD

**Issue by malemburg** [python/pythondotorg#457]
See the PSF resolutions page for an example:

https://www.python.org/psf/records/board/resolutions/

About 2/3 of the page are rendered with black background. Tested on Firefox and SeaMonkey.

**Comment by ned-deily** [comment]
There is invalid reST source there.  Note:

System Message: WARNING/2 (<string>, line 61)

Title underline too short.

**Comment by malemburg** [comment]
On 18.06.2014 22:18, ned-deily wrote:

> There is invalid reST source there.  Note:
> 
> System Message: WARNING/2 (<string>, line 61)
> 
> Title underline too short.

True, but I don't think that's related. I'll fix it.

## 

Marc-Andre Lemburg

**Comment by ned-deily** [comment]
Fixed already.  Does it look OK now?

**Comment by malemburg** [comment]
On 18.06.2014 22:25, ned-deily wrote:

> Fixed already.  Does it look OK now?

Thanks. The error message is gone, but the black background still
appears after about 2/3 of the page.

## 

Marc-Andre Lemburg

**Comment by ned-deily** [comment]
FWIW, the page seems to render fine in both Safari 7.0.4 and FF 30.0 on OS X 10.9.

**Comment by malemburg** [comment]
Just checked on a different machine: The page displays fine.

This must be a bug on the video driver of my notebook. Sorry for the noise.
