### ISSUE TITLE
No link to bug tracker

### ISSUE THREAD

**Issue by cjw296** [python/pythondotorg#458]
To:
webmaster@python.org

Hi Guys,

Doing a text search for "bug" or "tracker" on the front page doesn't find anything.

Please can you consider linking to the bug tracker from somewhere people might be able to find?

cheers,

Chris

**Comment by ned-deily** [comment]
In addition to the existing `Help & General Contact` link at the bottom of pages, there is now a `Help` item in the `About` menu/tree cascade.  That page contains links to both the Python Issue Tracker and this issue tracker for the website itself.  Does that help?

**Comment by mark-summerfield** [comment]
IMO that isn't sufficient. There should be a specific link in the footer for "Issue Tracker" (or "Bug Tracker"). It would be reasonable to put this at the bottom of the About column since bugs are certainly "about" python:-)

**Comment by pitrou** [comment]
See #488 for a more general request.

**Comment by frankwiles** [comment]
Fixed in https://github.com/python/pythondotorg/commit/af79caffdd7a46797e1b48329f7e4b4e611b3ac2
