### ISSUE TITLE
SIG pages all use the wrong text type

### ISSUE THREAD

**Issue by malemburg** [python/pythondotorg#461]
The SIG pages are all stored as HTML, but the pages are setup as ReST, so you get HTML markup as output.

https://www.python.org/admin/pages/page/?pathlimiter=community/sigs

**Comment by malemburg** [comment]
I fixed a few, but don't feel like doing this for 66 pages...

**Comment by ned-deily** [comment]
It may be possible to change the type fields using the API.  I'll try to take a whack at it.

**Comment by ned-deily** [comment]
Alas, the markup type is included as part of a MarkupField object and it doesn't look to me like that can be easily modified via the API. A little Django code could do the change directly if someone wants to take this on.

**Comment by frankwiles** [comment]
Those pages are actually a mixture of ReST, HTML, and plain text so was faster to just go through all 66.  Fixed.
