### ISSUE TITLE
www.python.org/doc/ redirect is broken

### ISSUE THREAD

**Issue by techtonik** [python/pythondotorg#462]
This:
    http://www.python.org/doc/2.2.3/whatsnew/node5.html
used to be a redirect to:
    https://docs.python.org/release/2.2.3/whatsnew/node5.html

**Comment by ned-deily** [comment]
Links to the documentation for all releases, including 2.2.3, is available from the `Documentation Releases By Version` link (https://www.python.org/doc/versions/) on the main documentation page (https://www.python.org/doc/) reached by clicking on the `Documentation` tab on main pages.  Is there a reference somewhere on the website that uses the first URL?

**Comment by techtonik** [comment]
I found the reference in pypng sources, and I expect much more of them all
over the web.

On Wed, Jun 25, 2014 at 11:54 AM, ned-deily notifications@github.com
wrote:

> Links to the documentation for all releases, including 2.2.3, is available
> from the Documentation Releases By Version link (
> https://www.python.org/doc/versions/) on the main documentation page (
> https://www.python.org/doc/) reached by clicking on the Documentation tab
> on main pages. Is there a reference somewhere on the website that uses the
> first URL?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/python/pythondotorg/issues/462#issuecomment-47076063.

## 

anatoly t.

**Comment by berkerpeksag** [comment]
Added a redirect for http://www.python.org/doc/2.2.3/whatsnew/node5.html.

**Comment by techtonik** [comment]
@berkerpeksag thanks. What is the commit?
