### ISSUE TITLE
Move repo to PSF organization

### ISSUE THREAD

**Issue by coderanger** [python/pythondotorg#47]
Reminder to myself, we should move this to the python org.

**Comment by jefftriplett** [comment]
If you create the bare repo we can at least point the people on hacker news, reddit, twitter, irc, etc to open github issues to keep things organized. We can sort out the license and push the code later.

**Comment by coderanger** [comment]
@jefftriplett I'm going to do an actual Github repo move so we get redirects et al.

**Comment by coderanger** [comment]
But waiting for the initial flurry of fixes to die down since its not critical.

**Comment by jefftriplett** [comment]
Gotcha. Didn't realize the proevo account was public. /me moves along

**Comment by peterlandry** [comment]
Let me know if you need anything from us (proevo account) in the switchover.

**Comment by jefftriplett** [comment]
Moved by @coderanger
