### ISSUE TITLE
No obvious way to update user profile

### ISSUE THREAD

**Issue by ncoghlan** [python/pythondotorg#470]
After logging in, I couldn't see any obvious way to get to my user profile and update it (most significantly, I couldn't see how to change my password)

I eventually found it at https://www.python.org/users/ncoghlan/, but it would be helpful if there was a traditional "My Account" (or similar) link next to the "Sign Out" button (or else make that button the My Account link, and move "Sign Out" to a dropdown).

**Comment by cydrobolt** [comment]
+1. I think we should switch the `Sign Out` button for a dropdown with the username, which then includes `Profile` and `Log Out`. I'll try to send a pull request soon :)

**Comment by frankwiles** [comment]
Signout has been a drop down for awhile now, didn't see this ticket.  However it still says "Signout".  usernames could get problematic as some email addresses are long and would break the layout.  Open to suggestions.
