### ISSUE TITLE
Reparenting Code of Conduct from PSF to Community section

### ISSUE THREAD

**Issue by audreyfeldroy** [python/pythondotorg#471]
This is a trivial nav menu change: can https://www.python.org/psf/codeofconduct/ be reparented from the PSF to the Community section, as https://www.python.org/community/codeofconduct/

From a usability and logical standpoint, I think "Python Community Code of Conduct" makes more sense under the Community section. It's a nice guide and might as well be easier to find.

Also, thank you to all the pythondotorg maintainers! :yellow_heart:

**Comment by malemburg** [comment]
On 29.07.2014 21:55, Audrey Roy wrote:

> This is a trivial nav menu change: can https://www.python.org/psf/codeofconduct/ be reparented from the PSF to the Community section, as https://www.python.org/community/codeofconduct/
> 
> > From a usability and logical standpoint, I think "Python Community Code of Conduct" makes more sense under the Community section. It's a nice guide and might as well be easier to find.
> 
> Also, thank you to all the pythondotorg maintainers! :yellow_heart: 

It's not as easy as moving the document. The version that's under
the PSF part of the site refers to the CoC the PSF adopted for itself.

We have a similar text with additional intro textthat the PSF suggests
for adoption by Python community groups. AFAIK, this version was not
published on the website.

FWIW: The version under the PSF is the correct one for the PSF, so it
should _not_ be moved.

## 

Marc-Andre Lemburg

**Comment by audreyfeldroy** [comment]
Oh, I see, thanks @malemburg. Sorry, please do not move it. Closing this issue since the document is in the correct place.

**Comment by malemburg** [comment]
On 30.07.2014 22:06, Audrey Roy wrote:

> Oh, I see, thanks @malemburg. Sorry, please do not move it. Closing this issue since the document is in the correct place.

We should probably publish the recommendation under the URL you
mentioned.

## 

Marc-Andre Lemburg
