### ISSUE TITLE
broken links in https://www.python.org/psf/records/board

### ISSUE THREAD

**Issue by brainwane** [python/pythondotorg#472]
Hi! I wanted to look at the lists of current and past Python Software
Foundation board officers. I clicked on https://www.python.org/psf-landing/ (the PSF link at the top of Python.org) and then hovered over About, then clicked on the Public Records dropdown which led me to  https://www.python.org/psf/records/ , and then clicked on "Board of Directors" and got to https://www.python.org/psf/records/board . The links at
https://www.python.org/psf/records/board are broken:

https://www.python.org/members/
https://www.python.org/psf/records/history/
https://www.python.org/psf/records/minutes/
https://www.python.org/psf/records/resolutions/
https://www.python.org/psf/records/treasurer/
https://www.python.org/psf/records/conference/

Since https://www.python.org/psf/records/ has a bunch of links that work (that have "/board/" in them, e.g., https://www.python.org/psf/records/board/treasurer/ ), I think one would just need to interpolate "/board" into the links that don't work.

**Comment by sheeshmohsin** [comment]
I want to work on this issue, anyone please guide me about this bug.

**Comment by brainwane** [comment]
sheeshmohsin: I don't know this codebase, but I searched the repository for the string `board` and found [urls.py](https://github.com/python/pythondotorg/blob/be7f04002f8a2c3d9adbb5f07ba44fed4b8140d1/pydotorg/urls.py) which looks like a promising place to start!

**Comment by frankwiles** [comment]
Thanks for pointing this out to us.  The content in question is in the CMS itself and not in the code, so I just fixed it.

**Comment by acsr** [comment]
on Page 
https://www.python.org/psf/records/board

The link [[https://www.python.org/members/|Current Officers & Directors]] is broken.

It should point to https://www.python.org/psf/members

I file in a new ticket #504 as well. Reopen this or take the new one.

**Comment by malemburg** [comment]
Fixed. Thanks.
