### ISSUE TITLE
PSF -> Media shows sample page

### ISSUE THREAD

**Issue by ned-deily** [python/pythondotorg#479]
As reported in http://bugs.python.org/issue22509:

On the python.org website, if you follow the link to PFS on the top, then click on the media tab (not any of the items in the dropdown menu), it takes you to this web page: https://www.python.org/inner/

It looks to be a sample page.

**Comment by ProfOak** [comment]
I didn't realize it should be posted here. Thanks for posting it for me.

**Comment by justinabrahms** [comment]
This appears to be a bigger issue. All instances of the phrase `"inner"` in [this file](https://github.com/python/pythondotorg/blob/master/fixtures/sitetree_menus.json) need to be updated. There appear to be 69 of them.

**Comment by berkerpeksag** [comment]
Changed that link to https://www.python.org/psf/press-release/ since there is no landing or parent page for /media/. Thanks!
