### ISSUE TITLE
Fix sponsor widget - Placeholder Image League of Awesome

### ISSUE THREAD

**Issue by jefftriplett** [python/pythondotorg#48]
Reminder to fix image holder place holder in bottom right sidebar: https://www.dropbox.com/s/vuqrsg8rr8jzefv/Screenshot%202014-02-19%2018.21.26.png

on page: http://www.python.org/sponsors/

**Comment by jefftriplett** [comment]
See #129 for mentions.

**Comment by birkenfeld** [comment]
Appears fixed now?

**Comment by malemburg** [comment]
Yep.
