### ISSUE TITLE
"Latest release" is determined by release date not version

### ISSUE THREAD

**Issue by berkerpeksag** [python/pythondotorg#487]
![downloads](https://cloud.githubusercontent.com/assets/26338/4615132/8f82e902-52e7-11e4-93c7-c74dd11aa17f.png)

The latest Python 3 release in the download supernav should be 3.4.1, not 3.3.6.

**Comment by benjaminp** [comment]
The problem is that the app determines the "latest" release by release date.

**Comment by benjaminp** [comment]
I've "fixed" the immediate problem by moving the release date for 3.4.2 forward and am repurposing this issue to fix the underlying problem.

**Comment by dstufft** [comment]
FTR the packaging library can sort Python versions!

**Comment by frankwiles** [comment]
Yep, I'm on this.

**Comment by dstufft** [comment]
To be clear, I meant this library: https://warehouse.python.org/project/packaging/

Should be as simple as:

``` python
import packaging.version

sorted([...], key=packaging.version.parse)
```

Modify to suit how you're sorting now!

**Comment by frankwiles** [comment]
FYI all you need to do now is when saving a new Release is check the 'Is this the latest release' checkbox.

**Comment by benjaminp** [comment]
Thanks a lot!
