### ISSUE TITLE
Contribution links not visible in start page

### ISSUE THREAD

**Issue by pitrou** [python/pythondotorg#488]
On the new homepage, the only link for contributing, the developer's guide, is buried inside the docs section, with no clear delineation (other doc links are for user docs).

I think it would be nice to have a separate "Contributing" section in the navbar, with the devguide and the bug tracker (am I forgetting something? PEPs perhaps, and python-ideas?).

**Comment by frankwiles** [comment]
Fixed in https://github.com/python/pythondotorg/commit/af79caffdd7a46797e1b48329f7e4b4e611b3ac2

**Comment by berkerpeksag** [comment]
https://github.com/python/pythondotorg/commit/af79caffdd7a46797e1b48329f7e4b4e611b3ac2 is not actually fixes this issue. There is still no link to CPython's issue tracker: https://bugs.python.org/ Here is a quick and dirty example to show what's in my mind:

![](https://cloud.githubusercontent.com/assets/26338/5776577/4379a834-9d92-11e4-87a6-22f0e0658eae.png)

**Comment by frankwiles** [comment]
Ah that's just a content issue.  Just fixed it.

**Comment by berkerpeksag** [comment]
Looks amazing, thanks! :) Two minor issues:
- "Core -> Mentorship" -> "Core Mentorship"
- There is a style glitch in the footer:
  
  ![](https://cloud.githubusercontent.com/assets/26338/5778940/8346b42e-9da7-11e4-988f-ebb4cd1241c0.png)

**Comment by berkerpeksag** [comment]
Perhaps we can use the masonry technique to fix the CSS. A quick demo: http://jsfiddle.net/u9f7tjzn/

**Comment by frankwiles** [comment]
Yeah I wasn't happy with the layout, but figured getting the links up was more important than the "look" of the footer.  I fixed the link text, will assign to the design team.
