### ISSUE TITLE
python.org/tutorial doesn't exist

### ISSUE THREAD

**Issue by ncrowell** [python/pythondotorg#489]
Can python.org/tutorial be a page or at least a useful redirect? As far as existing pages to redirect to, it could point to [docs.python.org/tutorial]() or [python.org/doc](). I really like [python.org/doc]() as far as general UX. Although it's not a tutorial-specific page, it looks really nice, links to both the Python 2 and Python 3 tutorials and has a lot of information-rich links in general. On the other hand, [docs.python.org/tutorial]() is actually a tutorial, but completely skips over the choice of the Python 2 vs Python 3 tutorial, which is captured by [python.org/doc]().

**Comment by benjaminp** [comment]
I don't see the point. Web searches point to the correct place. People linking should just use the docs.python.org URI.
