### ISSUE TITLE
Old python download overview page with pgp keys etc is no longer accessible

### ISSUE THREAD

**Issue by ned-deily** [python/pythondotorg#492]
On the legacy website, there is a "Download Python" page at http://legacy.python.org/download/ that contains important overview information, including links to alternative implementations and links to the release team members PGP public signing keys.  This information is important for users who download Python releases from python.org.  An updated version of this page exists as a Page object in the new website, with a URL of "download", but attempting to access https://www.python.org/download or https://www.python.org/download/ seem to end up at https://www.python.org/downloads/, the new downloads master page.   Some of the info on the old page does not exist anywhere else (in particular, the PGP keys info), AFAIK.  I believe that the "download" URL worked at some point on the new website.  I don't see an explicit Redirect for it in the Admin interface so I don't know why the page is not accessible now.   Because of the URL name conflicts between the old and new download hierarchy, it probably makes sense to move the unique pieces from the old page to one or more new pages and figure out how best to link them into the new hierarchy.

**Comment by malemburg** [comment]
On 02.11.2014 10:15, Ned Deily wrote:

> On the legacy website, there is a "Download Python" page at http://legacy.python.org/download/ that contains important overview information, including links to alternative implementations and links to the release team members PGP public signing keys.  This information is important for users who download Python releases from python.org.  An updated version of this page exists as a Page object in the new website, with a URL of "download", but attempting to access https://www.python.org/download or https://www.python.org/download/ seem to end up at https://www.python.org/downloads/, the new downloads master page.   Some of the info on the old page does not exist anywhere else (in particular, the PGP keys info), AFAIK.  I believe that the "download" URL worked at some point on the new website.  I don't see an explicit Redirect for it in the Admin interface so I don't know why the page is not accessible now.   Because of the URL name conflicts between the old and new download hi
>  er
>  archy, i
>  t probably makes sense to move the unique pieces from the old page to one or more new pages and figure out how best to link them into the new hierarchy.

This is probably the effect of a recent change Frank Wiles implemented:

"""
...  We purposefully moved the
"dynamic" download pages to /downloads/ (note plural) to not inadvertently
mask any of the existing /download/ content.  Most importantly the long
history of releases that aren't easily importable into the new structure.

However, the PageRank still existed for common URLs like /download/,
/download/source/, etc. which made both the plural and non plural URLs show
up as #1 and #2 respectively.  I've added 301 redirects in for:

/download/ -> /downloads/
/download/source/ -> /downloads/source/
/download/mac/ -> /downloads/mac-osx/
/download/windows/ -> /downloads/windows/

Which should cover the "major" pages people are looking for with less
confusion. They're living on staging now, and will go live on production
asap.
"""

+1 on readding the currently lost information to the downloads
page, esp. the GPG keys.

## 

Marc-Andre Lemburg

**Comment by frankwiles** [comment]
Good catch, the Alternative info is there in the 3rd box to the right after download table.

I've added two new boxes to this page one to again highlight the OS/Source release pages and another for the GPG information.  I'll go live today.
