### ISSUE TITLE
Error 404 when accessing PEPs' urls without trailing slash

### ISSUE THREAD

**Issue by julienvitard** [python/pythondotorg#494]
Accessing PEPs' urls without trailing slash raise Error 404

For example:
https://www.python.org/dev/peps/pep-0257/ works
https://www.python.org/dev/peps/pep-0257 does'nt

It seems to be the same for cross-references between PEPs.
For example, for PEP-258:

```
...
Requires : 256 257
...
```

Both urls in "Requires" section aren't accessible (no trailing slash).

**Comment by smontanaro** [comment]
I don't know if this is a recent regression, but it would seem to be a worthwhile redirect to add to the Apache (or whatever) config. In general, I think it's bad practice to require a trailing slash on leaf elements of URLs.

**Comment by julienvitard** [comment]
You're right. Maybe both urls should be accessible, I guess numerous websites redirect to PEPs both ways.

**Comment by davidszotten** [comment]
as of right now, a google search for e.g. "pep 425" is returning links without slashes, which are then 404'ing

**Comment by benjaminp** [comment]
I guess something is interfering with `APPEND_SLASH`.
