### ISSUE TITLE
Sample code box is too tall

### ISSUE THREAD

**Issue by munificent** [python/pythondotorg#50]
On the compound data types example, the code pushes the bottom of the box down:

![screenshot](http://i.imgur.com/I117LK2.png)

This is in Chrome on a retina Mac.

**Comment by jhogue** [comment]
I can tackle this one in the next day or two. There is also some RWD funkiness that I want to address (got clobbered maybe awhile ago).

**Comment by luanfonceca** [comment]
@jhogue So, You will do that?!
Cause I want to get in, help in any place so I was searching for easy issues. :)
- Just PSF members can contribute or it's open to all?

**Comment by fcurella** [comment]
@luanfonceca feel free to fork and submit a pull request. Everybody can contribute! :)

**Comment by krrr** [comment]
I see this bug has been fixed( #454 ), should this issue be closed?
