### ISSUE TITLE
Delay in new PEP appearing relative to other updates

### ISSUE THREAD

**Issue by ncoghlan** [python/pythondotorg#500]
Thanks for getting the new PEP pages working!

Pushing PEP 480 up this evening, there seems to be an odd delay between other pages updating (PEP 0 and PEP 458 were updated in the same commit) and the new PEP appearing (at time of writing, PEP 480 is still returning a 404 error, even with Ctrl-F5, several minutes after the other pages updated).

**Comment by ncoghlan** [comment]
Appeared now - about 45 minutes later, so somewhere just under an hour total.

It appeared just after I went and checked in the admin interface to see if it was at least in the database (it was), but that may have been a coincidence.

**Comment by benjaminp** [comment]
The PEP update job only runs once an hour.

**Comment by ncoghlan** [comment]
I wasn't sure what the update frequency was, but the weird part was the delay between the existing PEPs updating, and the 404 error going away for the new PEP. Perhaps there's something odd happening with the cache settings? (although if that was the case, I would have expected Ctrl-F5 to fix it)

**Comment by benjaminp** [comment]
Yeah, that's probably the CDN cache.

**Comment by frankwiles** [comment]
Yep Fastly is set to cache for an hour, including 404 pages apparently.  I just adjusted the code to reduce cache times on 404s to 5 minutes.
