### ISSUE TITLE
Search seems to omit PEPs at least

### ISSUE THREAD

**Issue by sdeibel** [python/pythondotorg#501]
I tried searching on "release schedule" with the search area at the top from the home page and got "no results" but there is https://www.python.org/dev/peps/pep-0478 among others with 'release schedule' right in the title.

**Comment by justinabrahms** [comment]
Confirmed. `PyPI Mirror Authenticity` returns no results, though it should match https://www.python.org/dev/peps/pep-0464/ . 

The [import script](https://github.com/python/pythondotorg/blob/master/peps/management/commands/generate_pep_pages.py#L51) for peps generates Page objects [here](https://github.com/python/pythondotorg/blob/master/peps/converters.py#L157). It seems to maintain the default of `is_published=True` which should pass the [index precondition](https://github.com/python/pythondotorg/blob/master/pages/search_indexes.py#L30). 

The code looks pretty correct as best I can tell. My next thought would be to look at the search index to validate those entries are being created.

**Comment by benjaminp** [comment]
See python/psf-chef#138.
