### ISSUE TITLE
Accessing the explicit PEP 0 URL results in incorrect relative links

### ISSUE THREAD

**Issue by ncoghlan** [python/pythondotorg#510]
https://www.python.org/dev/peps/pep-0000/ renders, but the relative links are incorrect (as they expect the page to be at https://www.python.org/dev/peps/)

Either the relative links should be different when the page is accessed this way, or else the explicit PEP 0 URL should redirect to the more typical PEP index URL.

**Comment by justinabrahms** [comment]
I think I fixed this in one of my patches. Which links in particular?

**Comment by benjaminp** [comment]
Yep, it looks good now. Thanks!
