### ISSUE TITLE
emacs link on download page is 404

### ISSUE THREAD

**Issue by voidspace** [python/pythondotorg#512]
On the downloads page is a link to "a collection of Emacs packages". This link is 404. 

Exact link is https://www.python.org/emacs

**Comment by smontanaro** [comment]
Should probably just redirect here:

https://wiki.python.org/moin/EmacsEditor

**Comment by ned-deily** [comment]
I changed the downloads page link to link to the wiki page.  I'm assuming that there isn't a compelling reason to maintain a top-level "emacs" redirecting URL.

**Comment by smontanaro** [comment]
> I changed the downloads page link to link to the wiki page. I'm assuming that there isn't a compelling reason to maintain a top-level "emacs" redirecting URL.

In this particular case, it looks like maintaining a redirect isn't
necessary (Googling for "link:www.python.org/emacs" returns nothing),
but in general, maintaining compatibility with URLs out in the wild
would seem to be "compelling." For example, Google mentions over 300k
references to www.python.org/dev/peps which come from outside the
python.org domain ("link:www.python.org/dev/peps -site:python.org").
If you decided you wanted the PEPs somewhere else on the site, I think
it would be wise to leave behind a permanent redirect. There's no way
you would be able to convince all those referrers to update there
(possibly ancient) references.

Skip

**Comment by ned-deily** [comment]
Agreed
