### ISSUE TITLE
Confirmation emails should not use webmaster as from address

### ISSUE THREAD

**Issue by voidspace** [python/pythondotorg#513]
We are regularly (a couple a day at least) getting replies to the address confirmation email sent to the webmaster alias. A "noreply" from address, with a bounce if users try to reply to it, would be more useful to our users and be less effort for those on the webmaster alias.

**Comment by smontanaro** [comment]
Most sites you sign up on have a working auto-reply address, so you can confirm by reply or by clicking a provided link. (Consider Mailman, for example.) If possible, it would be better if replying to these emails (whatever they are) functioned as if the user had clicked the link. If that's not possible, then I agree with Michael that a "no reply" address should be used.

**Comment by voidspace** [comment]
I don't object to a clickable link for users to use to contact someone (a mailto: link to webmaster for example). That would at least require the user to _read_ the email to get that far. 

What happens currently is that they don't read the email (beyond the title) and  think that replying to the email is confirming it. So the reply is just noise on webmaster and we either have to reply to them telling them they haven't read the email, or we ignore it. Either option is a disservice to our users.

**Comment by voidspace** [comment]
A working address that does confirmation from replies is a better solution. :+1:
