### ISSUE TITLE
Minor blank oddity on pep references

### ISSUE THREAD

**Issue by ghost** [python/pythondotorg#514]
There seems to be some minor blank issues on the references.

See for e.g. the reference 4 on pep479 (screenshot below from 2014.12.09) 
an how is different from the reference 2 ([4] ... Tracker and [2] . Initial or
[5] . Pure)

![pep0479_screenshot_references_20141209](https://cloud.githubusercontent.com/assets/10132629/5362283/2deecba8-7fd2-11e4-84ed-06d3e8f88c7e.png)

**Comment by justinabrahms** [comment]
If you mean the spacing, this was fixed in #507

**Comment by benjaminp** [comment]
There's still some weirdness going on e.g. https://www.python.org/dev/peps/pep-0477/#references

**Comment by justinabrahms** [comment]
That code has apparently not been deployed yet.
