### ISSUE TITLE
Dropdown menus with disabled JS

### ISSUE THREAD

**Issue by chuwy** [python/pythondotorg#52]
Someone can consider that open "socialize" menu is a feature, not a bug. But open font-scale submenu is definetly useless with disabled JavaScript.

**Comment by jhogue** [comment]
Can you explain a little bit more about this? I can't seem to parse what you are talking about exactly. I'm probably being dense about it, but it's been a long day.

**Comment by jhogue** [comment]
The Social nav drop down is open on which browser? I haven't seen that behavior. The Font Size adjust drop down is only shown for devices with touch screens, and again, I have not seen it stuck in the open position yet in iOS or Android (newer). Are you running an older Android system or something else?

**Comment by chuwy** [comment]
Oh, in browsers with disabled JS (I mentioned it in title) https://dl.dropboxusercontent.com/u/16981601/pythonorg.png
Of course it can be discussed, whether site should display the same in non-JS browser. But I consider this as a bug.

**Comment by jhogue** [comment]
You would be right. There were things in place to make the nave work without JS, so this is not working as intended. In fact, the drop down actions are all CSS so the fact that there is a "display:none" that isn't getting turned off is annoying (we hide the top nav bar at small screen sizes). As soon as I get access to the repo again I can investigate this.

**Comment by onpon4** [comment]
This still hasn't been fixed.

**Comment by onpon4** [comment]
https://mediacru.sh/DjQ-ge3Fq0gi
