### ISSUE TITLE
no path to brochure

### ISSUE THREAD

**Issue by CarlFK** [python/pythondotorg#530]
I can't find a path from python.org to 
https://encrypted.evenios.com/en/mediadata/cart/order-forms/community-order-form

**Comment by berkerpeksag** [comment]
There is a link to http://brochure.getpython.info/ at https://www.python.org/about/success/, but we can add a link to more visible place. @malemburg do you have a suggestion? Can we add a link to the About section in footer?

**Comment by berkerpeksag** [comment]
Added a link to footer.
