### ISSUE TITLE
RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by holdenweb** [python/pythondotorg#533]
Using a freshly-provisioned copy on vagrant, the first time I access the site I see the message

```
RuntimeError: dictionary changed size during iteration
```

There is no indication of where this error is occurring, and the home page does nevertheless seem to appear. However, this is not a satisfactory state of affairs.

**Comment by frankwiles** [comment]
I remember seeing that a few times myself, but somewhat randomly.  It's likely one of the third party app we're using.

**Comment by berkerpeksag** [comment]
I don't see this error for a couple of months. It probably was fixed by some of those commits: https://github.com/python/pythondotorg/commits/master/requirements.txt
