### ISSUE TITLE
No Community Involvement

### ISSUE THREAD

**Issue by holdenweb** [python/pythondotorg#534]
I believe the intention of the web site re-implementation was to democratize the site. This has not happened.

The Foundation should seriously look at whether the resources it is committing to the site's completion and onward maintenance are appropriate to the ambitions and responsibilities of the organization. Python is now driving a significant proportion of the world's IT infrastructure. It needs to be properly represented on the web.

It seems that lack of input to contracting organizations combined with complete failure to effectively seek end-user feedback and incorporate it into future efforts has led to a stagnant site with close to zero community involvement. Since this is an issue tracker I will spare you the polemic.

I have established a new milestone, because I believe until maintenance of the site is properly budgeted for no further effective progress can be made. At the moment the site reflects badly on the Foundation, and on the contractors who signed up to help it at far from extortionate rates. I urge the PSF Board to publicly re-commit to the success of this project.

**Comment by techtonik** [comment]
@holdenweb over the year the issue became worse.

![image](https://cloud.githubusercontent.com/assets/515889/13905957/96a1aab8-eede-11e5-8883-4fe9bf5eb11d.png)

https://github.com/python/pythondotorg/graphs/contributors 

This data doesn't show any reasons. Need stats about site visits (#901) as a starting point to research why site visitors are not interested to become contributors.

**Comment by techtonik** [comment]
From my side I can say that it is low incentive to contribute, because:
1. it is not fun - too enterprisey compared to typical python project - looks like enterprise bloat
2. the barrier for contribution is too high - setting up the stuff is a lengthy process, and it is impossible to contribute without extensive django experience
3. all credits are taken by PSF
4. license, which doesn't give the freedom to get back changes for the code submitted, so investing time in learning that codebase is not wise

**Comment by holdenweb** [comment]
And, depressingly, I'd say it looks like nobody in the PSF management
hierarchy cares about changing this, whether through time availability
issues or lack of interest I am not well-enough connected to discern. The
original idea was to have a system where individuals could take care of
specific resources and be acknowledged in the community and on the web site
as managers/contributors. This was intended to invite community involvement
end encourage contributions both large and small.

The whole site appears to have become a stodgy collection of complex bits
and pieces that contributors have to understand even just to edit content.
This is so far from the original conception as to be a terrible
disappointment.

regards
 Steve

On Mon, Mar 21, 2016 at 1:23 PM, anatoly techtonik <notifications@github.com

> wrote:
> 
> From my side I can say that it is low incentive to contribute, because:
> 1. it is not fun - too enterprisey compared to typical python project
> 2. looks like enterprise bloat
> 3. the barrier for contribution is too high - setting up the stuff is
>    a lengthy process, and it is impossible to contribute without extensive
>    django experience
> 4. all credits are taken by PSF
> 5. license, which doesn't give the freedom to get back changes for the
>    code submitted, so investing time in learning that codebase is not wise
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/python/pythondotorg/issues/534#issuecomment-199274527

## 

Steve Holden        +1 571 484 6266  +1 800 494 3119
Holden Web LLC             http://www.holdenweb.com/

**Comment by malemburg** [comment]
Steve, we know all this. I think the right way to address your concerns is to engage in and actively contribute to a PSF work group with the aim of making the site more community friendly. Opening up a complaint ticket on the tracker won't change anything much, except make the contributors we do have even less interested in investing time into making the site better. Thanks.

**Comment by techtonik** [comment]
@malemburg you are not right here. There is an issue and you want to hide it. As if it is your job security. In fact - this tracker is the only public channel to openly discuss the fact of absence of new people.

**Comment by holdenweb** [comment]
Hi Marc-Andre,

I didn't "open a complaint," I made a comment on a version-control issue
and copied the board in case they weren't aware of it. I no longer have
much time to spend on PSF business, though I do what I can. Please don't be
concerned that this represents the beginning of any kind of campaign. I've
done all I'm going to.

regards
 Steve

On Mon, Mar 21, 2016 at 6:07 PM, Marc-Andre Lemburg <
notifications@github.com> wrote:

> Steve, we know all this. I think the right way to address your concerns is
> to engage in and actively contribute to a PSF work group with the aim of
> making the site more community friendly. Opening up a complaint ticket on
> the tracker won't change anything much, except make the contributors we do
> have even less interested in investing time into making the site better.
> Thanks.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/python/pythondotorg/issues/534#issuecomment-199406503

## 

Steve Holden        +1 571 484 6266  +1 800 494 3119
Holden Web LLC             http://www.holdenweb.com/

**Comment by techtonik** [comment]
@holdenweb why PSF management hierarchy controls the way web-site development works?

My understanding that the role of foundation is to envision ecosystem and support initiatives, not lead and control them. So I don't see why PSF is entitled to control the work of the volunteers? For example, why people should ask to remove the (c) PSF from the web site footer? Did people transferred their copyright to PSF? No. Did PSF asked for it? No. So there is a certain decision paralysis when everybody thinks that PSF is in charge.

Also I see that if PSF is both a decision an actor that pushes things, it becomes a subject of critics (like if law-making and executive authorities were not separated), and no matter who will work there, they will receive the blame. So they will start to avoid the blame and start censoring using their right of authority. It is a natural process to save some energy on discussions.

**Comment by holdenweb** [comment]
Anatoly, we have had this conversation before, and we are not going to have
it again.

On Mon, Mar 21, 2016 at 6:50 PM, anatoly techtonik <notifications@github.com

> wrote:
> 
> @holdenweb https://github.com/holdenweb why PSF management hierarchy
> controls the way web-site development works?
> 
> My understanding that the role of foundation is to envision ecosystem and
> support initiatives, not lead and control them. So I don't see why PSF is
> entitled to control the work of the volunteers? For example, why people
> should ask to remove the (c) PSF from the web site footer? Did people
> transferred their copyright to PSF? No. Did PSF asked for it? No. So there
> is a certain decision paralysis when everybody thinks that PSF is in charge.
> 
> Also I see that if PSF is both a decision an actor that pushes things, it
> becomes a subject of critics (like if law-making and executive authorities
> were not separated), and no matter who will work there, they will receive
> the blame. So they will start to avoid the blame and start censoring using
> their right of authority. It is a natural process to save some energy on
> discussions.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/python/pythondotorg/issues/534#issuecomment-199422562

## 

Steve Holden        +1 571 484 6266  +1 800 494 3119
Holden Web LLC             http://www.holdenweb.com/

**Comment by techtonik** [comment]
@holdenweb can you give me a link for a refresher in 2016?
1. PSF has no public discussion space, why?
2. PSF micromanages community and web sites, why?

Just for example - the configuration for community mailman is hosted on http://infra.psf.io/ - not on http://infra.python.org/ As a contributor, I don't want to submit code to some corporation, even if it is comprised of trusted community members (whom I don't know). If it is open, it should be open in both ways.
