### ISSUE TITLE
https://issues.roundup-tracker.org/ serves https://bugs.python.org/

### ISSUE THREAD

**Issue by techtonik** [python/pythondotorg#539]
https://issues.roundup-tracker.org/ should serve http://issues.roundup-tracker.org/ securely.

**Comment by frankwiles** [comment]
Huh? Neither of these are www.python.org I'm confused, can you give us some more info about where you're seeing the link to issues.roundup-tracker.org?

**Comment by techtonik** [comment]
Nowhere, actually. I just want to login into the site from insecure network.

On Sun, Jan 11, 2015 at 4:00 PM, Frank Wiles notifications@github.com
wrote:

> Huh? Neither of these are www.python.org I'm confused, can you give us
> some more info about where you're seeing the link to
> issues.roundup-tracker.org?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/python/pythondotorg/issues/539#issuecomment-69493646.

## 

anatoly t.

**Comment by birkenfeld** [comment]
Please report to the roundup team or the Python meta tracker.

**Comment by techtonik** [comment]
Roundup team can not handle SSL cerificates. Whoever admins pydotorg,
should take action.

On Sun, Jan 11, 2015 at 7:05 PM, Georg Brandl notifications@github.com
wrote:

> Please report to the roundup team or the Python meta tracker.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/python/pythondotorg/issues/539#issuecomment-69499411.

## 

anatoly t.
