### ISSUE TITLE
stale pages about python.org maintenance

### ISSUE THREAD

**Issue by gvanrossum** [python/pythondotorg#540]
A Google search for "python.org maintenance" turns up two stale pages:
- https://www.python.org/dev/pydotorg/website/
- https://www.python.org/dev/pydotorg/

Here's my search: https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#sourceid=chrome-psyapi2&ie=UTF-8&q=site%3Awww.python.org%20maintenance

**Comment by benjaminp** [comment]
This is really the same as #532.

**Comment by gvanrossum** [comment]
Sorry. :-(
