### ISSUE TITLE
Request: copy target of www.python.org/download/releases/early/ from legacy

### ISSUE THREAD

**Issue by gvanrossum** [python/pythondotorg#543]
The legacy site has a copy of Python 0.9.1 (the earliest version released). The new site has the page with the descriptive text but the link 404s.

**Comment by ned-deily** [comment]
I made a copy of it into the python/releases/src download directory where other ancient source releases are kept and adjusted the link accordingly.

**Comment by gvanrossum** [comment]
Thank you!
