### ISSUE TITLE
IronPython news item

### ISSUE THREAD

**Issue by voidspace** [python/pythondotorg#548]
Email received on webmaster@python.org:

Could you please add an announcement to the python.org home page about
the IronPython 2.7.5 release? Something mimicking the normal Python
release announcements:

IronPython 2.7.5 released
<a href="http://ironpython.codeplex.com/releases/view/169382">IronPython
2.7.5</a> has been released.

Thanks,
Jeff

**Comment by benjaminp** [comment]
http://blog.python.org/2015/01/ironpython-275-released.html will appear on the frontpage eventually.
