### ISSUE TITLE
News and Events on Homepage are still sample text

### ISSUE THREAD

**Issue by jhogue** [python/pythondotorg#55]
There is a Trello card for this as well, under "To Do: Content". Partially a content issue, partially a code issue.

**Comment by fcurella** [comment]
#68 is a dupe of this

**Comment by peterlandry** [comment]
I've attempted to address this in PR https://github.com/python/pythondotorg/pull/139

**Comment by ncoghlan** [comment]
Any idea when the version with the fix will go live? News and Events on the home page are currently still showing info from 2012.

**Comment by peterlandry** [comment]
I've just submitted https://github.com/python/pythondotorg/pull/144 for review, which loads news from the database. The events fix is already live.

**Comment by peterlandry** [comment]
There's one outstanding PR to change the date format used, but the latest news and upcoming events are now loading from the database.
