### ISSUE TITLE
No real issue here....

### ISSUE THREAD

**Issue by ghost** [python/pythondotorg#550]
I just wanted to say to whomever did the site design for python.org, I think it's absolutely beautiful.  Nice job.

**Comment by frankwiles** [comment]
I'll make sure the designers at Project Evolution know you submitted this issue.  And I think this is going to be the first I label 'wont-fix'!

**Comment by jhogue** [comment]
Thanks! Working on some tweaks for 2015 as well, so stay tuned for that.

**Comment by berkerpeksag** [comment]
Thank you! I'm closing this as I'm re-triaging open issues to have a more up-to-date backlog.
