### ISSUE TITLE
Suggestion for 'w' and 'a' modes

### ISSUE THREAD

**Issue by ghost** [python/pythondotorg#551]
I think the current 'w' mode should be renamed to 'ow' (overwrite) and the current 'a' mode should be renamed to 'w' (write). This way, the begginers won't get confused by those modes.

**Comment by birkenfeld** [comment]
This would be a suggestion not for the website but the Python language (whose tracker is at http://bugs.python.org). But I can already tell you that these modes are not going to change since that would break literally tens of thousands of modules...

**Comment by ghost** [comment]
Sorry, I didn't know that there is another repository for the language. You're right about the other modules so I won't post it again.
