### ISSUE TITLE
Powered by Python 140px by 56px badge is missing

### ISSUE THREAD

**Issue by aleksihakli** [python/pythondotorg#552]
Hey,

Powered by Python has a [dead link for a missing badge](https://www.python.org/community/logos/python-powered-w-140x56.png) on the [logo page](https://www.python.org/community/logos/).

PS. Good job with the open Github project and issue tracker for the page guys :+1: 

Regards,
Aleksi

**Comment by frankwiles** [comment]
Great thanks for letting us know, I just fixed it!
