### ISSUE TITLE
Error in Python 3 tutorial (fencepost error)

### ISSUE THREAD

**Issue by lac22** [python/pythondotorg#553]
In https://docs.python.org/3/tutorial/introduction.html
It says:
    One way to remember how slices work is to think of the indices as
    pointing between characters, with the left edge of the first character
    numbered 0. Then the right edge of the last character of a string of n
     characters has index n, for example:

```
 +---+---+---+---+---+---+
 | P | y | t | h | o | n |
 +---+---+---+---+---+---+
 0   1   2   3   4   5   6

-6  -5  -4  -3  -2  -1

The first row of numbers gives the position of the indices 0...6 in the
string; the second row gives the corresponding negative indices. The
slice from i to j consists of all characters between the edges labeled i
 and j, respectively.
```

Index 6 does not exist in the string “Python":

```
Michaels-MacBook-Pro:~ michael_d_mays$ python3.4
Python 3.4.2 (v3.4.2:ab2c023a9432, Oct  5 2014, 20:42:22) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> m = "Python"
>>> m[1]
'y'
>>> m[6]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: string index out of range
>>> 
```

**Comment by benjaminp** [comment]
This really ought to be on https://bugs.python.org, where doc bugs are handled. That said, I don't think this example is claiming that the index 6 _exists_ in the string "Python", just that the "right edge of the last character of a string of n characters has index n,".
