### ISSUE TITLE
Allow members to sign up as Contributing Members

### ISSUE THREAD

**Issue by ncoghlan** [python/pythondotorg#555]
Basic members signed up on python.org should have the capacity to self-identify as contributing members. This is as simple as making the following statement (e.g. by checking a box on web form):

"I commit to working at least five hours per month on projects that advance the mission of the Python Software Foundation, where the work relates to the creation or maintenance of open source software available to the public at no charge."

We may also want to provide a free text field and encourage users to identify which projects they participate in.

**Comment by ncoghlan** [comment]
This feature and issue #556 may also require the ability to track voting membership status directly (as eligible Contributing and Managing may choose not to exercise their voting rights, or may let them lapse through repeated failures to vote)

**Comment by ncoghlan** [comment]
David Mertz has created an appropriate Google Form as an interim workaround until the main website is able to handle the task: http://pyfound.blogspot.com.au/2015/02/enroll-as-psf-voting-member.html

**Comment by treyhunner** [comment]
:+1: I went digging for that form to send to a contributing member who hadn't heard of this process.  I think linking this form directly on the official [Membership FAQ page](https://www.python.org/psf/membership/#what-membership-classes-are-there) would be great.

As for a non-Google form solution, maybe python.org could be sprinted on during future PyCons?  I know a Django developer or two (and front-end devs/designers) who might like to sprint on this website.

**Comment by berkerpeksag** [comment]
> As for a non-Google form solution, maybe python.org could be sprinted on during future PyCons?

+1! That's one of my goals if I can make it to PyCon US 2016 :)

**Comment by hugovk** [comment]
It's now possible to sign up as a Contributing Member at https://www.python.org/psf/membership/

@ncoghlan Please could you close this issue?
