### ISSUE TITLE
PEP updates slow to come live

### ISSUE THREAD

**Issue by Rosuav** [python/pythondotorg#557]
I'm not sure if something needs to be done manually or if it's just delayed, but I created a new PEP nearly two hours ago, and it's not live on the main site yet:

https://www.python.org/dev/peps/pep-0485/

The legacy site shows it much more promptly, and also updates as changes get pushed:

http://legacy.python.org/dev/peps/pep-0485/

Is there something that needs to be done to trigger the update?

**Comment by Rosuav** [comment]
Oh, NOW it comes live... nearly two hours. Huh.

**Comment by gvanrossum** [comment]
This seems an ongoing problem. Probably Benjamin kicked a daemon when he read your issue (he doesn't sleep apparently :-).

**Comment by Rosuav** [comment]
Heh, neither do I :-) So, can we get an enchantment that says "Whenever a player casts a commit, kick target Daemon"? A bit of Magic (The Gathering, or otherwise) wouldn't go amiss here.

**Comment by frankwiles** [comment]
Currently the site does this 10 minutes after the hour. Have a PR on with infrastructure to make this every 15 minutes.  https://github.com/python/psf-salt/pull/34

**Comment by frankwiles** [comment]
They now happen every 15 minutes, which should speed things up considerably.

**Comment by Rosuav** [comment]
Cool. I pushed a change about 20 mins ago so I should see it come through soon.
