### ISSUE TITLE
Search in docs.python.org/2 is stuck

### ISSUE THREAD

**Issue by shlomoa** [python/pythondotorg#558]
typed 'wait' in the quick search text entry and hit enter.
The page is stuck in "Searching . . ."
It has been like this for a few days now.

Update: https://docs.python.org/2.6/ works just fine

**Comment by birkenfeld** [comment]
Indeed. https://docs.python.org/2/searchindex.js is 403 Forbidden.

**Comment by benjaminp** [comment]
Somehow all the `seachindex.js` files got set without a world-readable mode.

**Comment by shlomoa** [comment]
Thanks @gutworth , you rock!
