### ISSUE TITLE
Add information for mobile-sig to /community/sigs/

### ISSUE THREAD

**Issue by jdhardy** [python/pythondotorg#559]
There is now a mobile-sig and I would like it added to the list of SIGs on /community/sigs/.

The initial page text should be similar to (based on the distutils-sig page):
# Topic

Python for mobile devices
# Charter

The Mobile-SIG exists to improve the usability of Python on mobile devices, as mobile platforms have their own unique requirements and constraints.

There are two goals:
- To collaborate on porting CPython to mobile platforms and ensure that other Python implementations (i.e. Jython, IronPython) present much the same environment as CPython when running on mobile devices.
- To collaborate on the design of modules for mobile-centric features such as cameras, GPS, accelerometers, and other sensors to ensure cross-platform and cross-implementation compatibility.

The intent is to work on mobile-centric features in this group before proposal to python-dev, similar to how the distutils-sig operates.

Questions of how to use Python on mobile platforms currently are considered off-topic as there are many other existing places for those questions.
# What's Available
- [Mobile-SIG Info Page](https://mail.python.org/mailman/listinfo/mobile-sig/)
- [Mobile-SIG Archives](https://mail.python.org/pipermail/mobile-sig/)

**Comment by benjaminp** [comment]
Done.
