### ISSUE TITLE
jobs.python.org DNS failure

### ISSUE THREAD

**Issue by carljm** [python/pythondotorg#56]
Hello,

I realize this isn't a problem with this codebase per se, but I'm not sure where else to report bugs with the new website (which looks great, btw!). If there is a "where else" feel free to close this and direct me to it.

jobs.python.org is linked from the front page of the new website, but (for me at least) that subdomain fails to resolve in DNS.

**Comment by benjaminp** [comment]
Goes to old jobs site for now.
