### ISSUE TITLE
Calendar event pages for full day event show (wrong) times

### ISSUE THREAD

**Issue by malemburg** [python/pythondotorg#560]
See e.g. https://www.python.org/events/python-events/246/

This is an event for the days March 28 and 29. The calendar entry uses all day entries for this, without specifying times on each day. Yet the python.org site displays "From 28 March at 12am UTC through 30 March at 12am UTC, 2015", so it's 12 hours off.

The all day event should really only show up as "From 28 March through 29 March".

The iCal entry for the events starts with:

BEGIN:VEVENT
DTSTART;VALUE=DATE:20150328
DTEND;VALUE=DATE:20150330
DTSTAMP:20150202T092425Z
...

without timezone information.

**Comment by malemburg** [comment]
This problem keeps popping up again and again for full day events (all conferences we add to the Google calendars), e.g. most recently here:

https://www.python.org/events/python-events/467/

The event is from April 3-7 and shown correctly in the Google calendar widget:

http://www.pycon.org/#calendar

**Comment by malemburg** [comment]
This bug still exists: https://www.python.org/events/python-events/800/ vs. http://www.pycon.org/#calendar

The problem is that full day events should be displayed using times (or time zones for that matter), but just the dates, which are correctly entered into the Google calendars.

**Comment by berkerpeksag** [comment]
IIRC, this hasn't been deployed to production yet. Could you please check it at staging.python.org?

**Comment by malemburg** [comment]
Looks fine for EuroPython on staging: https://staging.python.org/events/python-events/794/

So I guess all that needs to be done is deploy on production :-)

Thanks, Berker !

**Comment by hugovk** [comment]
This is now in production, for example https://www.python.org/events/python-events/1738/ reads:

> From 18 Sept. through 20 Sept., 2024

with no clock times, as expected.
