### ISSUE TITLE
broken search result links in www.python.org

### ISSUE THREAD

**Issue by shlomoa** [python/pythondotorg#570]
Hi,

I entered a search string in www.python.org: "upgrage python version"
Which produced this url:
"https://www.python.org/search/?q=upgrade+python+version&submit="

When I clicked the first result:
https://www.python.org/dev/peps/pep-0297/

It gave me a "502 Bad Gateway" error.

Update: https://www.python.org/dev/ is where it happens

Thanks,
Shlomo

**Comment by berkerpeksag** [comment]
Thanks for the report. This should be fixed by https://github.com/python/pythondotorg/commit/608c2c73aebe1ef22356d2248c1cd8ea4d0d406d.
