### ISSUE TITLE
>>> Python Enhancement Proposals: The future of Python link broken

### ISSUE THREAD

**Issue by GrosSacASac** [python/pythondotorg#572]
">>> Python Enhancement Proposals: The future of Python"
https://www.python.org/dev/peps/

502 Bad Gateway
nginx

**Comment by berkerpeksag** [comment]
Thanks for the report. This should be fixed by https://github.com/python/pythondotorg/commit/608c2c73aebe1ef22356d2248c1cd8ea4d0d406d.
