### ISSUE TITLE
HTML Tags showing up on python 2.6.x license pages 

### ISSUE THREAD

**Issue by abdulmuneer** [python/pythondotorg#576]
case 1 (at the top):

```
<h1>Python 2.6.2 license</h1>

<p>This is the official license for the Python 2.6.2 release:

<pre> A. HISTORY OF THE SOFTWARE ==========================
```

Case 2 (at the bottom):

```
<p><a href="http://www.opensource.org/"> <img src="/images/opensource-110x95.png" border="0" width="110" height="95"></a>
```

This is seen on the page https://www.python.org/download/releases/2.6/license/ and also for other 2.6.x series.

**Comment by ned-deily** [comment]
Thanks for the report.  During conversion from the legacy web site, most of the license pages for releases were incorrectly tagged as reST files rather than as pre-formatted HTML.  They should now all be rendering properly.
