### ISSUE TITLE
Collecting tweets from 03-20 Aug, 2014 for a particular location

### ISSUE THREAD

**Issue by hasanuzzamanucbn** [python/pythondotorg#577]
Hello,

I am a PhD student. I am new to python and using TwitterSearch to collect tweets from 03-20 Aug for a particular location (geocode). I am trying to run the following piece of code.

twitter = Twython(CONSUMER_KEY,CONSUMER_SECRET,ACCESS_KEY,ACCESS_SECRET)
results = twitter.cursor(twitter.search, q='ferguson', max_id='501488707195924481', count=100, geocode='38.00,-91.00')

for result in results:
print (result['id_str'])

However, it is not returning anything. Please help me in this regard. Can I collect old tweets without any keyword for a particular location?

Thanks in advance.

Regards,
Mohammed

**Comment by benjaminp** [comment]
This is an issue tracker for the Python website not general Python programming questions. Consider mailing python-list@python.org or using StackOverflow.
