### ISSUE TITLE
502 Bad Gateway when attempting to edit Membership FAQ

### ISSUE THREAD

**Issue by ncoghlan** [python/pythondotorg#578]
I'm attempting to update the PSF Membership FAQ to add appropriate references to http://pyfound.blogspot.com.au/2015/02/enroll-as-psf-voting-member.html

However, I am getting a 502 Bad Gateway error from nginx when attempting to save the results.

The text I am attempting to add to the entries for Managing and Contributing members (replacing the current notes):

>    For details on signing up as a managing member, refer to `this post <http://pyfound.blogspot.com.au/2015/02/enroll-as-psf-voting-member.html>`__ on the PSF blog.

**Comment by frankwiles** [comment]
Odd perhaps there was something going on with the infrastructure, was just able to remove the existing notes and replace the text as is without issue.
