### ISSUE TITLE
Contacting the PSF is buried  where media people cannot find it.

### ISSUE THREAD

**Issue by lac22** [python/pythondotorg#581]
Paul Krill at infoworld couldn't find contact information for the PSF.  He was looking for 'media contact' in particular.

If you start by Googling "Python Software Foundation" you go here:
https://www.python.org/psf/ 

There is a 'Contact the PSF' section, but it doesn't have the contact information, just a link.

Clicking on the link gets you to:
https://www.python.org/psf/about/#how-do-i-reach-the-psf

which does have the information (though the one line is tiny).

Do we want all requests to the psf to do to one address, or do we want media queries to get special treatment?

**Comment by lac22** [comment]
Correction¸ I no longer think he startede with a Google.  I think he started by going to python.org directly.

The psf information is at the very bottom of the page -- so you have to scroll to read it, and 
doesn't have a 'Contact the PSF' or a 'Media Contact the PSF' button which would be useful
additions.  The best he could have done was go to 'learn more' which gets you to
https://www.python.org/psf/

(i.e. the same place that Google would have taken you).

**Comment by berkerpeksag** [comment]
We could add a new section called "Want to contact the PSF?" at https://www.python.org/about/help/ (this is the page that's linked in footer of every www.python.org page) and refer users to https://www.python.org/psf/about/#how-do-i-reach-the-psf

**Comment by MarkMangoba** [comment]
Added to help:  Need to contact the Python Software Foundation
Contact psf@python.org and let us know how we can help!
