### ISSUE TITLE
No python 3 source download button

### ISSUE THREAD

**Issue by hexum** [python/pythondotorg#584]
When mouse hover "Download" button only python 2 sources shown for download.
![image](https://cloud.githubusercontent.com/assets/6324742/6393092/3c0ef1c4-bdd8-11e4-9eaf-a752ab7c8bba.png)

**Comment by ned-deily** [comment]
It's not just the Source Code: the Python 3.4.3 button (newly released) is also missing from the Windows and Mac OS X tabs.  Here's the current contents of box `supernav-python-downloads` as seen in the admin interface:

```
<!-- download supernav from templates/downloads/supernav.html -->
<li class="tier-2 super-navigation">

    <div class="download-os-mac-osx" style="display: none;">

        <h4>Download for Mac OS X</h4>

        <p>
            <a class="button" href=""></a>
            <a class="button" href="https://www.python.org/ftp/python/2.7.9/python-2.7.9-macosx10.6.pkg">Python 2.7.9</a>
        </p>
        <p>Not the OS you are looking for? Python can be used on 21 different operating systems and environments. <a href="/downloads/">View the full list</a>.</p>
    </div>

    <div class="download-os-source" style="display: none;">

        <h3>Python Source</h3>

        <p>
            <a class="button" href=""></a>
            <a class="button" href="https://www.python.org/ftp/python/2.7.9/Python-2.7.9.tar.xz">Python 2.7.9</a>
        </p>
        <p>Not the OS you are looking for? Python can be used on 21 different operating systems and environments. <a href="/downloads/">View the full list</a>.</p>
    </div>

    <div class="download-os-windows" style="display: none;">

        <h4>Download for Windows</h4>

        <p>
            <a class="button" href=""></a>
            <a class="button" href="https://www.python.org/ftp/python/2.7.9/python-2.7.9.msi">Python 2.7.9</a>
        </p>
        <p>Not the OS you are looking for? Python can be used on 21 different operating systems and environments. <a href="/downloads/">View the full list</a>.</p>
    </div>

    <div class="download-unknown">
        <h4>Download Python for Any OS</h4>
        <p>Python can be used on 21 different operating systems and environments.</p>
        <p>
            <a class="button" href="/downloads/operating-systems/">View the Full List</a>
        </p>
    </div>
</li>
```

It seems to me we've had this problem before when new releases have gone out; perhaps some update is not getting triggered when the release managers use the `add-to-pydotorg.py` script (https://hg.python.org/release/file/default/add-to-pydotorg.py) rather than adding release entries manually through the admin interface?

**Comment by frankwiles** [comment]
It seems to be working now, @benjaminws it seems you were the last one to edit that supernav box.  Did you do it manually or was it a missing 'download button' checkbox in the admin?

**Comment by benjaminp** [comment]
I did it manually.

**Comment by ned-deily** [comment]
FWIW, at the time I wrote the previous comment (when the button was missing), the checkboxes for the 3.4.3 release entry in the admin interface all appeared to be in the correct states, e.g. "latest release", "published", and "show on download page" all set, "pre-release" not.  (Thanks for manually editing the box, @gutworth.)

**Comment by ned-deily** [comment]
OK, it looks like the problem may be CDN caching of https://www.python.org/box/supernav-python-downloads/ after it is auto-updated.  Perhaps the autoupdate can autopurge the cache for that?  For now, we'll manually do it.

**Comment by berkerpeksag** [comment]
Perhaps we can can add URLs of those boxes to https://github.com/python/pythondotorg/blob/master/downloads/models.py#L209

**Comment by berkerpeksag** [comment]
The following URLs will be purged automatically:

* https://www.python.org/box/download-sources/
* https://www.python.org/box/homepage-downloads/
* https://www.python.org/box/supernav-python-downloads/

**Comment by ned-deily** [comment]
Thanks, @berkerpeksag!  We just ran into this again with the release of 3.6.2.
