### ISSUE TITLE
My entry on the humor page is formatted badly

### ISSUE THREAD

**Issue by roysmith** [python/pythondotorg#585]
Please see https://www.python.org/doc/humor/#bad-habits (screen-capture attached).  The formatting is  key here, so having the lines folded badly kind of ruins it.

![image](https://cloud.githubusercontent.com/assets/704337/6401708/497313f2-bdd0-11e4-8308-dfd61d5391a4.png)

**Comment by berkerpeksag** [comment]
Thank you for the report. This is best I can do to improve its formatting: https://www.python.org/doc/humor/#bad-habits Unfortunately, I can't do much because this is basically the only broken entry so I'm not too keen about changing CSS.
