### ISSUE TITLE
reading a PEP on mobile page repeatedly jumps to the top 

### ISSUE THREAD

**Issue by alexjeffburke** [python/pythondotorg#595]
Hi,

I've had a frustrating time trying to read any PEP published on the new site on mobile - my specific device is an iPhone 5S running iOS 8.1.3

At some moment having scrolled down the PEP something triggers the page to scroll all the way to the top making it impossible to read. I wish I knew what the trigger was, but it is very reproduceable by just reading a PEP on such a device.

Please let me know if I can provide any further information.

Thanks, Alex J Burke.

**Comment by ned-deily** [comment]
Thanks for the report.  This problem is being tracked in #531.

**Comment by alexjeffburke** [comment]
Ah cool, thanks for looking at it. Apologies for the duplicate report.
