### ISSUE TITLE
502 Bad Gateway when attempting to access PEP 3131

### ISSUE THREAD

**Issue by ncoghlan** [python/pythondotorg#596]
Bad Gateway errors again. @dstufft, @coderanger, @gutworth  could this be CDN related?

Would it be possible to hook the main site up to the same monitoring setup that covers PyPI?

**Comment by dstufft** [comment]
Rackspace is going through reboots right now - https://status.python.org/incidents/5w523lrn3587.

**Comment by dstufft** [comment]
Although I just realized that status is specific to PyPI, but it shouldn't be.

**Comment by dstufft** [comment]
@ewdurbin did notice that the pingdom checks were hitting python.org instead of www.python.org, which meant they'd basically only ever fail if our HAProxy setup (which is Active-Active HA) died.

**Comment by ncoghlan** [comment]
Yeah, that would likely explain it. (I seem to be doing well with getting Gateway errors out of python.org lately...)

**Comment by frankwiles** [comment]
Yep was a reboot or deployment of sort.  Fine now, closing.
