### ISSUE TITLE
Add note in README for how to contribute

### ISSUE THREAD

**Issue by mattoc** [python/pythondotorg#60]
- How to get in touch with developers
- Style guide/PEP8
- Testing guidelines

Suggest also considering a CONTRIBUTING doc in repo per https://github.com/blog/1184-contributing-guidelines

**Comment by jefftriplett** [comment]
Great suggestion :+1:

**Comment by birkenfeld** [comment]
I think this is mostly done in README and the docs/.

**Comment by pfctdayelise** [comment]
There should be a link to the mailing list https://mail.python.org/mailman/listinfo/pydotorg-www in the README.
