### ISSUE TITLE
job submission form is broken, gives you a File Not Found AFTER you complete the required data

### ISSUE THREAD

**Issue by ssbarnea** [python/pythondotorg#600]
Job submission form is broken, gives you a File Not Found AFTER you complete the required data

https://www.python.org/newjobs/create/

In addition to the not working anymore submission of job by email now we have this new cool form which seems to give you a File Not Found error page once you manage to complete all the required data. Same happens for Save as Draft or Submit for Approval.

Also is not clear if the email address from the form would become public (as we may not want to give our email address, preferring to ask people to use the provided url to submit CVs).

**Comment by SarahPythonista** [comment]
The new jobs board isn't up yet. In fact, http://www.python.org/newjobs shouldn't be used at all yet. The python.org site shouldn't be linking to it at all. May I ask how you ended up there?

Right now, there is no way to submit a job. There hasn't been for over a year. And yes - that is sad.

If you want to help, we're doing all of our work on the staging server at:
http://staging.python.org/newjobs 

If you create an account on the staging server, you should be able to create test jobs (although they won't appear on the actual site). If you want them to appear on the staging server once you've submitted them, an admin can approve them; feel free to ping one of us and we can do it.

I understand why you might not want your email to become public, where bots could crawl for it. I'll bring it up in discussion.

**Comment by SarahPythonista** [comment]
I've been able to replicate the 404 on the staging server. I think I know what the issue is. Will keep you in the loop.

**Comment by malemburg** [comment]
The problem is that the jobs app requires an authenticated user in order to show job details and the create form redirects to the job details after entering them.

I think the best way to handle this is to either redirect to a "thank you" page or, probably better, always require logins for job postings.

The error does not happen for authenticated users.

**Comment by ssbarnea** [comment]
Not quite true based on my experience: I did the submission after I logged in (username: sorin).

/sorin

**Comment by malemburg** [comment]
Hmm, perhaps I'm not seeing the 404 because I'm in the Job Admin Group.

**Comment by malemburg** [comment]
Note: The job entries do succeed, ie. they are entered into the database, so this is mostly a (pretty bad) user experience bug :-)

**Comment by berkerpeksag** [comment]
> Hmm, perhaps I'm not seeing the 404 because I'm in the Job Admin Group.

Your account probably have "staff" status :) See https://github.com/python/pythondotorg/blob/master/jobs/views.py#L175

**Comment by malemburg** [comment]
Ah, right, yes, I have that flag set as well. I guess the permission checks need some extra care :-)

Perhaps just redirecting to a thank you page is the better approach, after all.
