### ISSUE TITLE
The job filter bar doesn't work

### ISSUE THREAD

**Issue by malemburg** [python/pythondotorg#605]
If you go here: https://www.python.org/newjobs/ you can see a purple filter bar at the top of the page.

Clicking on any of the first three filters entries in the bar leaves you with an empty jobs result. The drop-downs all show an "All..." entry, but this also results in an empty result (even though there are entries in the database).

I would assume the filters to show the types, categories and locations from the database in the drop-down, but instead they just have the "All..." entry.

If it's not possible to show all possible filter entries and make the filters work, it's better to completely remove the bar to avoid confusing the users.

**Comment by SarahPythonista** [comment]
No jobs were showing up at all, even without filtering (at least for me). Were you seeing jobs without filtering? 

It appears that jobs don't show up (even when approved) unless they have an expiry date and time. I'll open a ticket and look into setting up a default expiry date, which is assigned when the job is created.

There should now be one job showing (I added an expiry date and time). It's under executive.

**Comment by malemburg** [comment]
I can see 3 jobs without any filtering.

Note that this is on the production site, not the staging server.

**Comment by malemburg** [comment]
On the staging site, I can now see one entry as well and it does apparently list the job types and categories for which there are entries in the database in the drop-downs.

**Comment by frankwiles** [comment]
This was fixed awhile ago.  Closing.
