### ISSUE TITLE
Need Default Expiry Date and Time

### ISSUE THREAD

**Issue by SarahPythonista** [python/pythondotorg#606]
Jobs don't show up unless they have an expiry date and time. So, we need to make it a required field, and perhaps add a default value.

**Comment by malemburg** [comment]
On 07.03.2015 23:01, SarahRK wrote:

> Jobs don't show up unless they have an expiry date and time. So, we need to make it a required field, and perhaps add a default value. 

There is a default expiry date set by the system (I don't remember
the default duration, but I think it was something like 2 months).

If the system doesn't set this if no explicit expires date is given,
this would be a bug.

## 

Marc-Andre Lemburg
Director
Python Software Foundation
http://www.python.org/psf/

**Comment by SarahPythonista** [comment]
Just checked; it does. Older jobs (such as the job I adjusted) didn't for some reason. But it appears to work fine, now.

**Comment by frankwiles** [comment]
Yeah I noticed we weren't doing expiration as was planned in a couple of places and fixed it during our first sprint.
