### ISSUE TITLE
Editing of job records should be possible for everyone in the "Job Board Admin" group

### ISSUE THREAD

**Issue by malemburg** [python/pythondotorg#617]
At the moment, only the creator of a job entry can edit the job via the web interface, e.g.

https://staging.python.org/newjobs/165/edit/

Since job reviewers will need an easy way to fix small issues, it would be better to use that same interface rather than go into the Django admin interface and edit the database record.

PS: There already is a JobBoardAdminRequiredMixin to check for group membership.

**Comment by berkerpeksag** [comment]
Actually, JobBoardAdminRequiredMixin is not working properly. For example, you need to be a "staff" member to see the job review list or job review detail page anyway.
