### ISSUE TITLE
Do not ask for confirmation on logout

### ISSUE THREAD

**Issue by berkerpeksag** [python/pythondotorg#618]
When I click the "sign out" link, it redirects to "/accounts/logout/" and then asks "Are you sure you want to sign out?". It's an unnecessary step in my opinion.

**Comment by benjaminp** [comment]
The problem with this is that now you can be logged out if other sites simply GET `/accounts/logout/`. Can't we just make the logout button POST to the logout page?

**Comment by berkerpeksag** [comment]
Good idea. but it will look ugly without using hacks like `href="#"`, `href="javascript:void(0)"` or without making CSS dance to style the `<button>` element properly. We can just revert https://github.com/python/pythondotorg/commit/3cf2b4ecaada4ab511342a16718db829db28e04c.

**Comment by benjaminp** [comment]
6605ad8cae57344b77b75ececfe35066ea22e31d
