### ISSUE TITLE
Downloads page shouldn't promote pre-releases

### ISSUE THREAD

**Issue by nanonyme** [python/pythondotorg#621]
Currently list of releases has pre-releases and releases all mixed up. We had in #python today two users who had installed alpha versions of Python because www.python.org was unclear as to what they should download. Development versions should be somehow hidden in some separate development version listing. This thing mostly happens to new users who don't know what they should be downloading and it's very bad PR for Python when new users get buggy versions of Python when they try it for the first time.

**Comment by frankwiles** [comment]
That was actually my intention when we added the pre-release link, but apparently I didn't actually strip the pre-releases out of the main list.  Thanks for reporting that!
