### ISSUE TITLE
An alternative, much simpler job board

### ISSUE THREAD

**Issue by salimfadhley** [python/pythondotorg#624]
Hey @malemburg , I know you've been working on building a new Django based job-site. 

You might have heard that Steve Stagg, Daniel Pope and myself have had a go at an alternative. We wanted to design something that works for very busy people so we asked ourself how we can make a job-board that is as low maintenance as possible.

One idea we had was to just make the process for submitting a job ad be a github pull request. We also made the whole thing a static site that's recompiled (in Travis) any time a PR is merged. We also figured that the whole thing can be hosted on GitHub for absolutely nothing. 

There's some self interest in getting something to working real sooon: our business depends on being able to hire lots of good Python developers. Having a functioning Python.org job board really matters to us, so one way or another we want to help you get the job site working.

So here's my request: 
- If you like what we've done, can we use this approach for the official Python.org job board?
- Alternativly - would you mind linking to our site from the currently defunct jobs page - at least until yours is operational. Then at least we have a temporary job board in place of the page that's been static for a year.

Our working site:
[The Free Python Job Board](http://pythonjobs.github.io/)

Our jobs database:
https://github.com/pythonjobs/jobs

Our static site compiler:
https://github.com/pythonjobs/template

**Comment by malemburg** [comment]
Hi Salim, we will be launching the python.org job board next week, so I don't really see a need to replace what we've worked on for the past year with something completely new, which (again) wasn't designed to meet our needs.

**Comment by salimfadhley** [comment]
Actually that's a major relief - things have been much harder since the python.org jobs board went offline. I eagerly look forwards to the relaunched site!
