### ISSUE TITLE
Checking a preview of a job comment comes back with a non-styled form

### ISSUE THREAD

**Issue by malemburg** [python/pythondotorg#625]
See e.g. https://staging.python.org/newjobs/160/review/, enter a comment, click on "preview".

The base template does not seem to be used for this preview.

**Comment by berkerpeksag** [comment]
This is related to #591. Personally, I'd just remove the preview link since it doesn't have markdown or reST support.

**Comment by malemburg** [comment]
Fine with me. At the moment it just looks strange.

**Comment by malemburg** [comment]
I assume that because of #591 was can also not change the thank you page for the comment, right ?

It currently says that a moderator will get to you before the comment appears no the site, which is probably correct for a blog post comment, but not for the comments in the jobs app.

Instead of the thank you page it would be better to return straight to the job page, since it's likely that the posting will subsequently be rejected (with the comment explaining the reason).
