### ISSUE TITLE
Enable the jobs app under /jobs/

### ISSUE THREAD

**Issue by malemburg** [python/pythondotorg#628]
The jobs app currently runs under /newjobs/. For the launch next week, we will have to change this to /jobs/ again.

AFAIK, these changes are necessary:
- rename /newjobs/ to /jobs/ in pydotorg/urls.py
- disable the redirect from /jobs/ to /community/jobs/ in the web server chef setup for the site
- fix the navbar link at the top of the site to point to /jobs/ instead of /community/jobs/

**Comment by berkerpeksag** [comment]
> For the launch next week,

Off-topic but, is this date a hard deadline? It would be better if we can improve things like UX and fix inconsistency between JobBoardAdminRequiredMixin vs. request.user.is_staff in jobs/views.py.

**Comment by malemburg** [comment]
@berkerpeksag Yes, I want to definitely launch next week. We have reached a point where the app is basically usable and that's what we wanted for phase 1. We can then proceed to fix remaining issues and new ones as we go along, including the permissions and the UX issues.

**Comment by malemburg** [comment]
Regarding the is_staff issue: I've made sure that all job reviewers do have this status. They will also need this status to be able to go to the Django admin UI and fix database records directly until we have more functionality available through the main UI.

**Comment by frankwiles** [comment]
Do we have a set date/time for this launch? staging and prod no longer use Chef and instead salt so we need to put in an infrastructure ticket [with psf-salt](https://github.com/python/psf-salt/) to get it removed as we go live.

**Comment by malemburg** [comment]
I'm still waiting to get access to the prod database to fix some issues with the jobs tables: we will be starting with a new set of jobs categories and types (technologies), but the existing job entries prevent us from deleting the old ones, since the cascaded deletes would remove all existing job entries.

I would like to remove all existing associations of existing job entries with any of the job types and set the categories to "Other" (ID 20) on all of the entries.

If you know some other way of doing this, please let me know. Perhaps we could run some migration to the same effect.

Once that's done, we can remove the old categories and types and we can then go live.

**Comment by frankwiles** [comment]
Well we could probably get away with just blowing out the job data at this point as I see maybe 2 real job listings from 2014 that somehow made it into the system but obviously never really advertised. 

But that isn't a real solution, just pushed up https://github.com/python/pythondotorg/issues/631 which allows for Types and Categories to be deactivated and preserve the linkage.

**Comment by malemburg** [comment]
Excellent. Thanks.

We'd rather not remove the old data (just clean it up a bit, e.g. remove test entries), since the entry was a _lot_ of work and we might want to use it in the future for searches, statistics and the like.

**Comment by malemburg** [comment]
I've opened a PR to get the salt stack updated: https://github.com/python/psf-salt/pull/40

Now fixing the urls.py and trying to find the navbar redirect.

**Comment by malemburg** [comment]
That's probably generated from the site tree: https://www.python.org/admin/sitetree/tree/1/
so will have to be fixed afterwards.

**Comment by malemburg** [comment]
urls.py is fixed. The site tree still needs to be updated, but for now we're focusing on #637.

**Comment by malemburg** [comment]
Fixed the site tree as well.
