### ISSUE TITLE
Allow JobType and JobCategories to be deactivated

### ISSUE THREAD

**Issue by frankwiles** [python/pythondotorg#631]
Need to be able to remove from current listings and future Job submissions, without breaking links to older expired Job objects.

**Comment by malemburg** [comment]
Very nice! So if I understand correctly, we can now simply de-activate categories and types which are no longer used ?

**Comment by frankwiles** [comment]
Yes.  It will keep them out of the forms for submission and nav (even if there is an active job with it FYI) but not mess up any of the detail display or current listings at all.  Just deactivate what you don't want visible at any point and it should be "gone" in the ways one would expect.
