### ISSUE TITLE
Edit page in review panel causes 502 error

### ISSUE THREAD

**Issue by malemburg** [python/pythondotorg#637]
See e.g. https://www.python.org/jobs/159/edit/
Click on "submit".

For some reason, the selected job technology "Evangelism" is _deleted_ from the database as a result of clicking submit.

**Comment by berkerpeksag** [comment]
How can I reproduce the issue locally? https://www.python.org/jobs/159/edit/ is 404 for me (probably don't have permissions).

**Comment by malemburg** [comment]
I just gave you permissions.

To reproduce, try the following:
1. go to https://www.python.org/jobs/159/edit/; the posting should have "Evangelism" selected
2. click the submit button
3. you get the 502
4. go to the job entry in the database: https://www.python.org/admin/jobs/job/159/; you'll find that "Evangelism" is missing as job technology
5. go to the job tech page and add it back: https://www.python.org/admin/jobs/jobtype/
6. now you can go back the jobs page, select the new "Evangelism" entry, click "submit" (which succeeds)
and then the game starts again.

**Comment by malemburg** [comment]
The net effect is that we will quickly remove all job technologies from the database and probably also corrupt the jobs entries.

**Comment by malemburg** [comment]
@frankwiles : Could you please have a look at this as well ? We don't have access to the logs of the system, so it's difficult to say what exactly is going wrong. It's rather strange that editing job record would cause a job technology record to be removed.

**Comment by malemburg** [comment]
I have a feeling the problem is caused by this code: https://github.com/python/pythondotorg/commit/a9d6929eadff3ef70c30b32394ce81870ce4d145

This line looks strange: self.object.job_types.all().delete()

**Comment by malemburg** [comment]
Tested: the problem is fixed now.
