### ISSUE TITLE
Need a better name for "Job technologies"

### ISSUE THREAD

**Issue by malemburg** [python/pythondotorg#639]
We are using the field to add characterizations/tags of the job to the entry. This includes things like "Database", "Web", but also "Management" or "Evangelism".

Technology is only part of that characterization.

**Comment by hugovk** [comment]
Triage: I couldn't find anything named "job technologies" at or under https://www.python.org/jobs/

Has this since been fixed?

**Comment by malemburg** [comment]
I believe I was referring to https://github.com/python/pythondotorg/blob/main/jobs/models.py#L58

The description still reads "Job Technologies". On the public website, this is listed as Job Types, which is a better name.

The backend still uses "Job Technologies", though, e.g. https://www.python.org/jobs/7698/edit/?next=/jobs/moderate/

**Comment by hugovk** [comment]
Triage: can this closed now https://github.com/python/pythondotorg/pull/2557 is merged?
