### ISSUE TITLE
CSS of jobs review panel doesn't work on the release branch

### ISSUE THREAD

**Issue by malemburg** [python/pythondotorg#645]
If you compare

https://www.python.org/newjobs/review/

with

https://staging.python.org/newjobs/review/

You will see that the nice CSS shown on the staging site does not appear on the production site, even though the release branch is up to date.

Is this a Fastly cache issue ?

**Comment by berkerpeksag** [comment]
https://www.python.org/newjobs/review/ works for me. It was probably a cache issue.

**Comment by malemburg** [comment]
On 17.03.2015 18:22, Berker Peksag wrote:

> https://www.python.org/newjobs/review/ works for me. It was probably a cache issue.

Hmm, I tried a different browser and get the same result: the nice
grey background are not displayed and there's no spacing between the
columns and rows.

It may still be a cache issue, though: could be local to the particular
Fastly node I'm using.

## 

Marc-Andre Lemburg

**Comment by berkerpeksag** [comment]
@malemburg can this be closed now?

**Comment by malemburg** [comment]
Yes :-)
