### ISSUE TITLE
Reduce the number of notification emails per job posting

### ISSUE THREAD

**Issue by malemburg** [python/pythondotorg#656]
The jobs@python.org list is currently getting three notification emails with the same content for each job posting.

The emails have date/times about a second apart, e.g.
- Date: Tue, 17 Mar 2015 19:11:04 -0000
- Date: Tue, 17 Mar 2015 19:11:05 -0000
- Date: Tue, 17 Mar 2015 19:11:06 -0000

but otherwise look pretty identical.

This may be a simple misconfiguration of the mail system, but could also be the result of a bug in the jobs app.

**Comment by malemburg** [comment]
I'm starting to believe that we're hitting the problem described here: https://github.com/r4fek/django-cassandra-engine/issues/4 (for a different DB backend, but the issues looks very similar).

It's possible that post_save signals have an issue in Django 1.7.3.

**Comment by malemburg** [comment]
The signal is sent three times in each submission request, even for edits of existing records.

**Comment by berkerpeksag** [comment]
I've refactored to use AppConfig.ready() to register signals and I've confirmed that the on_job_was_submitted listener is registered once. But it didn't fixed the issue.

I also have created a custom signal instead of post_save and it didn't fixed the issue as well.

**Comment by berkerpeksag** [comment]
I don't think this is a Django bug. I've tested with Django 1.6, Django 1.7.2 and 1.7.6 and the issue is same.

**Comment by malemburg** [comment]
On 18.03.2015 23:28, Berker Peksag wrote:

> I don't think this is a Django bug. I've tested with Django 1.6, Django 1.7.2 and 1.7.6 and the issue is same.

Hmm, then I don't understand why the "created" is apparently never
set.

## 

Marc-Andre Lemburg

**Comment by berkerpeksag** [comment]
Note: AppConfig verison is here: https://github.com/python/pythondotorg/compare/master...berkerpeksag:issue-656

**Comment by malemburg** [comment]
On 18.03.2015 23:48, Berker Peksag wrote:

> Note: AppConfig verison is here: https://github.com/python/pythondotorg/compare/master...berkerpeksag:issue-656

Going forward that's certainly an improvement, even if it
doesn't fix the issue at hand.

Could you post those changes as PR ?

## 

Marc-Andre Lemburg

**Comment by berkerpeksag** [comment]
Well, I finally fixed the problem :) The problem is that we are saving `self.object` two times in views. Instead, we should have work on `form.instance`. I've opened https://github.com/python/pythondotorg/pull/671

**Comment by malemburg** [comment]
We're still getting two emails per change.

Also see #679.

**Comment by berkerpeksag** [comment]
https://github.com/python/pythondotorg/pull/680 should fix this.

**Comment by malemburg** [comment]
I can confirm that it's finally working. Thanks, @berkerpeksag

**Comment by berkerpeksag** [comment]
Great :)
