### ISSUE TITLE
Fix example text

### ISSUE THREAD

**Issue by 1st1** [python/pythondotorg#66]
I think that

"""Lists (known as arrays in other languages) are one of the compound data type that Python understands. """

should be replaced with simple

"""List (known as "array" in other languages) is one of the compound data type that Python supports."""

**Comment by fcurella** [comment]
I think the first version sounds better, although it does contain a typo. It should say 'data types', plural, as in:

"Lists (known as arrays in other languages) are one of the compound data types that Python understands. "
