### ISSUE TITLE
Lots of duplicate job submission messages?

### ISSUE THREAD

**Issue by smontanaro** [python/pythondotorg#668]
I'm seeing typically four or more copies of each submission. Is that to be expected? The message headers are all messed up as well. Here's an example (highlighted) of part of the headers from one message. Markdown isn't working for me, but notice all the empty message headers with no newlines in the second row: "Mime-Version: Content-Type:", etc. I can't figure out how to attach the raw message, or I would do that...

```
DomainKey-Signature: a=rsa-sha1; c=nofws; d=mg.python.org; s=k1; q=dns;
 h= Mime-Version: Content-Type: Content-Transfer-Encoding: Subject: From:
 To: Date: Message-Id: Sender;
 b=SUFeVux+OpcrALyuvHoh9jtfW1TBv49gB+x8gMkvhoZVfmD6NIsh3QukuBS0O0ajaJrV8f
 ULxNJ+2NS2RPL4NPxc0rzJ8ozm2S07qSPEIic2a/I4IXGKb76gdZ61e9AK3EKl2eNySRehme
 7twzeBuECkiY8f/3+4ptneGCseA5g=
Received: from pydotorg-prod.iad1.psf.io (Unknown [162.242.237.77]) by
 mxa.mailgun.org with ESMTP id 55089774.5cba030-in07; Tue, 17 Mar 2015
 21:07:00 -0000 (UTC)
Mime-Version: 1.0
From: noreply@python.org
To: jobs@python.org
Date: Tue, 17 Mar 2015 21:07:00 -0000
Message-Id: <20150317210700.1145.36868@pydotorg-prod.iad1.psf.io>
X-Mailgun-Sid: WyI4MzcwOCIsICJqb2JzQHB5dGhvbi5vcmciLCAiNTFlNTkiXQ==
Subject: [Jobs] Job Submitted for Approval: Senior Full Stack Python
 Engineer, iMatchative
X-BeenThere: jobs@python.org
X-Mailman-Version: 2.1.19
Precedence: list
```

Skip

**Comment by malemburg** [comment]
The headers look strange indeed. We already have a ticket open for the duplicate emails: #656

**Comment by malemburg** [comment]
I think those are not real headers, but instead part of the DKIM header value.

**Comment by malemburg** [comment]
Closing this ticket, since we're tracking it on #656.
