### ISSUE TITLE
502 when submitting/saving a job

### ISSUE THREAD

**Issue by Hannahmc8** [python/pythondotorg#669]

**Comment by malemburg** [comment]
This is likely caused by the issue #652.

**Comment by malemburg** [comment]
If you run into this problem, please check your descriptions in an online ReST editor such as http://rst.ninjs.org/

**Comment by Hannahmc8** [comment]
Thanks Marc, I'm not one of the techies at our firm so will be at sea I guess!

Hannah McIntyre

Founder | CrunchBoards 
Brighton, UK
Fast, effortless, beautiful. Transform your accounts package into Financial Intelligence. Show me how!
Sent from my iPhone

On 18 Mar 2015, at 17:27, Marc-Andre Lemburg notifications@github.com wrote:

If you run into this problem, please check your descriptions in an online ReST editor such as http://rst.ninjs.org/

**Comment by malemburg** [comment]
On 18.03.2015 19:55, Hannahmc8 wrote:

> Thanks Marc, I'm not one of the techies at our firm so will be at sea I guess!

Could you perhaps post the descriptions here ? Then we can check them.

## Thanks,

Marc-Andre Lemburg

**Comment by berkerpeksag** [comment]
https://github.com/python/pythondotorg/blob/master/docutils.conf is likely fixed this issue, too. Can we close this now?

**Comment by malemburg** [comment]
Yes. Thanks, Berker.
