### ISSUE TITLE
Most success stories categories look empty

### ISSUE THREAD

**Issue by gvanrossum** [python/pythondotorg#69]
Is this also still example text from the beta? It makes it look like Python isn't very successful. :-(

**Comment by Mariatta** [comment]
I haven't look into how this works yet, but perhaps https://www.python.org/success-stories/ should be deactivated or redirect it to https://www.python.org/about/success/

**Comment by berkerpeksag** [comment]
I've moved old success stories into the new app in #1102. It can be seen on staging.p.o and it will be deployed on production next week.
