### ISSUE TITLE
Typo on psf membership page

### ISSUE THREAD

**Issue by IanLee1521** [python/pythondotorg#699]
I couldn't find the text in the code here (in the database?) but there is a typo on: https://www.python.org/psf/membership/#what-membership-classes-are-there

In 5. Contributing members:

`For details on signing up as a managing member, refer to this post on the PSF blog.`

should be

`For details on signing up as a contributing member, refer to this post on the PSF blog.`

Or possibly something else.

**Comment by ned-deily** [comment]
Thanks for the report.  The text has been changed as you suggested.
