### ISSUE TITLE
Please use ISO date format

### ISSUE THREAD

**Issue by mkesper** [python/pythondotorg#70]
9/29/2012 is soooo ugly to everyone not US, please use the ISO standard 2012-09-29.
This also makes much more sense when comparing dates as least significant is right and most significant is left as with normal numbers.

**Comment by hynek** [comment]
This: https://xkcd.com/1179/ :)

**Comment by radiosilence** [comment]
Seconded - even if you do decide to use a localised date format (a questionable decision), it is incorrect to presume that the locale is en_US. 

In fact, it's most likely a better idea to send a UTC full datetime string to the client, and then have it formatted locally with JavaScript.

Or at least, make use of Django's localisation features.

**Comment by peterlandry** [comment]
Some of the dates on the homepage have been updated, or will be soon. The actual display is similar (though it should be localized in terms of M/D/Y vs D/M/Y properly), and there's a `<time>` tag with a full ISO 8601 datetime. The blog entry list is waiting on https://github.com/python/pythondotorg/pull/144 to be merged.

Does that change address your concern?

**Comment by mkesper** [comment]
Hi,

Am 21.02.2014 00:55, schrieb Peter Landry:

> Some of the dates on the homepage have been updated, or will be soon.
> The actual display is similar (though it should be localized in terms of
> M/D/Y vs D/M/Y properly), and there's a with a full ISO 8601 datetime.

How can you achieve that?
I'd say it's impossible, even the proper language is already difficult.
Please save yourself from headaches and use the only true (short) date
format YYYY-MM-DD.

Best wishes
Michael

**Comment by hynek** [comment]
Please don’t localize, that’s confusing since you can never be 100% sure what format the date is in depending on your browser, OS, and configuration.  Just follow the wisdom of xkcd and use YYYY-MM-DD which is unequivocal in any part of the world.

**Comment by peterlandry** [comment]
Thanks all, I've submitted a PR with this feedback: https://github.com/python/pythondotorg/pull/153

Please let me know if you see any issues with the approach I took.

**Comment by fcurella** [comment]
fixed in 81e67ff71ec9f6c74747759f7d68d0a23093c239

**Comment by peterlandry** [comment]
Just a heads up that I (somehow) messed up the order of the parts, but fixed it in https://github.com/python/pythondotorg/commit/f7d792d684e6c74f4a3e508bc29bbe2bacc458f0

If you see the wrong format, please wait just a bit, it may be that the auto deployment caught the first, incorrect version, but it will soon be fixed.

**Comment by peterlandry** [comment]
All set.
