### ISSUE TITLE
Typo in psf bylaws

### ISSUE THREAD

**Issue by IanLee1521** [python/pythondotorg#700]
Can't find the text in the source code (in database?) so opening issue rather than Pull Request.

https://www.python.org/psf/bylaws/

Under "History" at the very end:

`Amended by the PSF board on Ay 16th, 2014.`

should (probably) be:

`Amended by the PSF board on May 16th, 2014.`

**Comment by ned-deily** [comment]
Thanks, the typo is now fixed.

**Comment by IanLee1521** [comment]
Would that have been something I could have fixed and just didn't know where to make the change?

**Comment by ned-deily** [comment]
Much of the content of the web site is contained in the website's Django database, not in the codebase, and currently modified through the admin interface (or other, specialized apps) by site admins.
