### ISSUE TITLE
Invalid "Sent by" in job posting emails

### ISSUE THREAD

**Issue by pneff** [python/pythondotorg#705]
When writing a review comment on a job posting, the "Sent by" value is set as "None", even though both the name and email have been filled out.

Also in the approval emails it appears that between "Good luck in filling your position," and "Python Job Board" there should be a name which is also blank for me. I've looked at https://www.python.org/users/edit/ as well to see if I could add a name there, but I can't find any name field there to fill out.

**Comment by malemburg** [comment]
The review name is now filled in, provided the user name details are set.

**Comment by malemburg** [comment]
Fixed now via #715.
