### ISSUE TITLE
Site doesn't allow users to edit their name entries

### ISSUE THREAD

**Issue by malemburg** [python/pythondotorg#706]
If you go to https://www.python.org/users/edit/ after login, you can only edit some preferences, but it's impossible to edit the first and last name entries of the record.

Looking through some records, it seems that only very few of the 16k+ user entries we have on the site has the first and last name set on the user record, so there may well also be a bug in the signup procedure.

**Comment by berkerpeksag** [comment]
I think the reason is that there are already Membership.legal_name and Membership.preferred_name attributes for the same purpose: https://github.com/python/pythondotorg/blob/master/users/models.py#L54

**Comment by malemburg** [comment]
On 23.03.2015 18:36, Berker Peksag wrote:

> I think the reason is that there are already Membership.legal_name and Membership.preferred_name attributes for the same purpose: https://github.com/python/pythondotorg/blob/master/users/models.py#L54

Right, but those are only used for PSF membership and only set in
case someone signs up as PSF (basic) member.

The main user record attributes are not set for some reason and
also not editable after user creation, which is a bit of a bummer for
any kind of app which needs access to these, like e.g. the jobs
app.

## 

Marc-Andre Lemburg

**Comment by rochacbruno** [comment]
I need to change my username, because I misspelled when registering.

rochcbruno --> rochacbruno

How can I change?

**Comment by rochacbruno** [comment]
Name and Lastname I can change in https://www.python.org/users/membership/edit/ only username (reasonable) I cannot change.

**Comment by malemburg** [comment]
On 23.03.2015 19:55, Bruno Rocha wrote:

> I need to change my username, because I misspelled when registering.
> 
> rochcbruno --> rochacbruno
> 
> How can I change?

Please create a new user account with the correct name. I can then
remove the old one.

## 

Marc-Andre Lemburg
