### ISSUE TITLE
Job-Posting Overview: No Edit-Button

### ISSUE THREAD

**Issue by okin** [python/pythondotorg#713]
The job overview at https://www.python.org/jobs/mine/ has no link that enables a poster to edit a rejected post.

The link should lead to https://www.python.org/jobs/123456/edit/ (where I placed _123456_ as an example job ID).

**Comment by malemburg** [comment]
On 25.03.2015 12:24, Niko Wenselowski wrote:

> The job overview at https://www.python.org/jobs/mine/ has no link that enables a poster to edit a rejected post.
> 
> The link should lead to https://www.python.org/jobs/123456/edit/ (where I placed _123456_ as an example job ID).

The process we're using does not support editing rejected postings.

Corrected postings should be resubmitted as new job postings.

## 

Marc-Andre Lemburg

**Comment by okin** [comment]
This was not clear to me based on the feedback mail.
I'll close this.
