### ISSUE TITLE
Setup management commands to generate and load development fixtures

### ISSUE THREAD

**Issue by frankwiles** [python/pythondotorg#719]
To ease local development, create two management commands.  One to be used as a cron job to generate a sanitized development fixture.  And another to download and load that fixtures for developers working locally.

**Comment by frankwiles** [comment]
Note this will not actually work until this psf-salt PR is merged https://github.com/python/psf-salt/pull/45

**Comment by berkerpeksag** [comment]
This is great, thanks! :)
