### ISSUE TITLE
Community Tab in navbar

### ISSUE THREAD

**Issue by adelq** [python/pythondotorg#72]
- Button links to '#unresolved'
- Local events in dropdown link to '#'

**Comment by akuchling** [comment]
The 'URL is Pattern' box was checked on the 'Community' item for some reason; after unchecking it, the link now goes to the top community page.

**Comment by akuchling** [comment]
The local events in the dropdown is a neat idea, but I don't know how soon it can actually be implemented.  I've replaced the links with some more generic text.  

Thanks for your report!
