### ISSUE TITLE
Search results for Python releases are broken

### ISSUE THREAD

**Issue by gvanrossum** [python/pythondotorg#720]
When I search the python.org search box for a keyword that returns returns from the downloads section of the site, the links in the search results have the form "//downloads/releases/..." which makes most browsers interpret the link as going to the host "downloads" -- which of course doesn't exist. I've verified this with recent releases of Firefox and Chrome on OSX.

This is probably due to the recent refactor of the downloads pages? (For which I am actually grateful, before it was a bit of a mess!)

**Comment by frankwiles** [comment]
Oops sorry about that. All fixed!
