### ISSUE TITLE
job board rejection lameness

### ISSUE THREAD

**Issue by CarlFK** [python/pythondotorg#727]
This could be better.  I may try to improve it, but not anytime soon.   It may need a page or two refactored and written up.

Being rejected sucks, and what we do makes it worse: people want to know why, and we send them into a page that doesn't answer that.

The reject email says:

> Unfortunately, your listing does not comply to our Job Board listing guidelines (see https://www.python.org/community/jobs/howto/). 

that page says

> if the posting was rejected, you will get an additional email telling you whether there is a way to improve the posting to make it fit our guidelines. 
> 
> Note: Jobs must be primarily focused on Python. Please make sure your posting explains how Python is used for that specific job or your post will get rejected.

And there is lots of text about ReST (relevant to why it was rejected) and volunteers and other things not really relevant. 

Things that would help:
1. specify why it was rejected in the email
2. point to a page that is just listing guidelines and nothing else.

**Comment by malemburg** [comment]
I think you're missing an important detail in the rejection process:

We always send a comment explaining why the posting was rejected prior to actually running the rejection.

**Comment by berkerpeksag** [comment]
I agree with @malemburg.

I tweaked UI a bit and made clearer that an admin can reject the job posting with a comment explaining the reason behind the rejection.

![](https://user-images.githubusercontent.com/26338/30244285-0388697c-95c4-11e7-8193-03f4cf9ac6b1.png)

They will still get two emails: One for rejection and the other for the comment about the reasoning.

We could possibly send just one email and include all review comments in the email, but I'm not sure that would be improvement. Thoughts?

**Comment by hugovk** [comment]
There's been no further suggestions, so I think we can close this: a comment is always sent with the rejection, and the UI has been made clearer.
