### ISSUE TITLE
Code font in examples hard to read

### ISSUE THREAD

**Issue by hynek** [python/pythondotorg#73]
It looks like this on my Mac (OS X 10.9, Chrome 33): 
![image](https://f.cloud.github.com/assets/41240/2216110/ad91b41c-9a02-11e3-8da2-d4383c61125c.png)
 and I really have to squint to read that.

Courier New is also a really terrible font at that size on the web. May I suggest to kick it out so the `monospace` fallback gets used sooner? FWIW, I use

```
'Source Code Pro', 'Anonymous Pro', Consolas, 'Envy Code R', 'Ubuntu Mono', Inconsolata-g, Inconsolata, monospace;
```

on my homepage so everyone is likely to get their favorite coding font.  If that idea doesn’t appeal to you (but just imagine everyone seeing Python in their favorite font :)), I’d really like to have just `monospace` which will look fine everywhere.

**Comment by jhogue** [comment]
There was much discussion about this previously when we had Preview out in the open. People seemed to think that the font stack we came to would be best, as some of the fonts you have suggested are fonts that people have to go out and get (I guess most of the people who were part of the conversation thought that default system fonts would be better). This is the stack now: 

`Consolas,'Lucida Console','Liberation Mono','DejaVu Sans Mono','Bitstream Vera Sans Mono','Courier New',monospace,sans-serif`

I would not mind shortening the list or adding in some alternatives to the stack. But I know that this little detail has people on all sides with all sorts of opinions, so pleasing everyone may not be possible.

**Comment by hynek** [comment]
I'm not asking to replace your stack (mine had the same spirit though
:)). 

I just want Courier New gone b/c it's hard to read.  If you replace it
with my beloved Source Code Pro I'll be even happier but Courier New is
the reason I opened this ticket. :)

P.S. The Source fonts are Idan-approved. ;)

**Comment by annaraven** [comment]
The <code>+</code> and other operators on the Intuitive Interpretation box are really hard to read against the blue, because of the minimal color contrast (green on blue). Is there a way we could BOLD it when it's against the blue background or something to make it more accessible?

FWIW - I ran it on a color analyzer and it does not meet accessibility requirements for contrast.

**Comment by hynek** [comment]
Yeah Anna is right. Disregard my font comments, the problem is just that the fonts are wayyy too dark.  I don’t think it’s necessary to make them bold, just make them _brighter_.

Thanks!

**Comment by hynek** [comment]
This appears to be fixed, closing! :)

![2017-10-14 at 19 04](https://user-images.githubusercontent.com/41240/31577617-88f0796a-b112-11e7-9fbc-1795cf7f166b.png)
