### ISSUE TITLE
Can someone help me find the old contents of /doc/essays/ppt/ ?

### ISSUE THREAD

**Issue by gvanrossum** [python/pythondotorg#732]
In my public html on Dinsdale there's a link to https://www.python.org/doc/essays/ppt/ which has stopped working. Does anyone have the contents that used to be there? I seem to have misplaced it (because it wasn't in my own home dir to begin with -- I don't know what I was thinking, but it was a long time ago :-).

https://twitter.com/argenpython/status/587842911485747200

**Comment by malemburg** [comment]
On 14.04.2015 11:33, Guido van Rossum wrote:

> In my public html on Dinsdale there's a link to https://www.python.org/doc/essays/ppt/ which has stopped working. Does anyone have the contents that used to be there? I seem to have misplaced it (because it wasn't in my own home dir to begin with -- I don't know what I was thinking, but it was a long time ago :-).

Dinsdale still has the directory and content:

http://legacy.python.org/doc/essays/ppt/

## 

Marc-Andre Lemburg

**Comment by gvanrossum** [comment]
Thanks! I will make sure to download these.
