### ISSUE TITLE
Tweet sidebar looks garish

### ISSUE THREAD

**Issue by lfaraone** [python/pythondotorg#738]
![image](https://cloud.githubusercontent.com/assets/73410/7288640/ca51eda8-e919-11e4-9a20-de04f3197f1d.png)

The twitter sidebar interferes with the readability of PEPs and other pages, and doesn't add much value. 

If we're going to keep it on pages besides the homepage, can we at least not show it on static docs?

**Comment by berkerpeksag** [comment]
+1, but I think design is going to change soon. Here is a wireframe from a public python.org meeting on IRC: http://dev.projectevolution.com/python/2015/working-wires/getstarted.php?here=about

**Comment by malemburg** [comment]
On 23.04.2015 05:17, Berker Peksag wrote:

> +1, but I think design is going to change soon. Here is a wireframe from a public python.org meeting on IRC: http://dev.projectevolution.com/python/2015/working-wires/getstarted.php?here=about

Ah, so we're switching to PHP finally ;-)

Seriously, isn't it possible to style the Twitter sidebar in some
way that it doesn't completely fall out of the overall design
approach ?

I also don't see much value having it on pretty much every content
page. Having a box on the home page would be enough PSF promotion,
IMO :-)

## 

Marc-Andre Lemburg

**Comment by berkerpeksag** [comment]
> Ah, so we're switching to PHP finally ;-)

Well, PHP is web scale. So it should be a good thing :)

> I also don't see much value having it on pretty much every content
> page. Having a box on the home page would be enough PSF promotion,
> IMO :-)

+1. It's easy to remove the Twitter box. I can open a new PR to remove it.

**Comment by jhogue** [comment]
I'm working on the redesign now (in Python, Django, and SASS – no PHP :) ) and agree that the Twitter widget does not need to be on every page, esp. the text heavy ones. Design wise, according to Twitter's Terms of Use, there is not much we are allowed to do aside from customize what they allow in their widgets. I can make the new templates smarter, and not show the widget in most cases.

**Comment by hugovk** [comment]
Is this still an issue?

On the one hand, PEPs now have their own website at https://peps.python.org/ (repo: https://github.com/python/peps) and don't show the Twitter widget.

Second, the widget now looks better compared to the 2015 version, for example https://www.python.org/about/gettingstarted/:

![image](https://user-images.githubusercontent.com/1324225/205020769-099c301b-81a9-4b79-a570-0705e9c9bbaf.png)

**Comment by malemburg** [comment]
I think it's time to remove the Twitter widget altogether. After a while of showing tweets from 2017 (in 2023), it now has become completely useless:

![image](https://github.com/python/pythondotorg/assets/6735498/3f157af7-56ad-467a-9b0d-40b909100772)

**Comment by di** [comment]
Looks like the Twitter widget lives here: https://github.com/python/pythondotorg/blob/67207962a817b4dc345843f7524fd2da8f4f2252/templates/python/inner.html#L629-L658

**Comment by hugovk** [comment]
Please see PR https://github.com/python/pythondotorg/pull/2329 to remove it.

**Comment by malemburg** [comment]
All merged now. Thanks, @hugovk
