### ISSUE TITLE
Old PEP links no longer work

### ISSUE THREAD

**Issue by malemburg** [python/pythondotorg#741]
There are many links out in the wild (the wiki.python.org is full of such links) which use the old PEP link structure, e.g.

http://www.python.org/peps/pep-0255.html

These should get redirected to the new URL:

https://www.python.org/dev/peps/pep-0255/

Probably best to do this using an nginx rewrite rule.

**Comment by frankwiles** [comment]
Fixed and live

**Comment by malemburg** [comment]
@frankwiles Thanks.
