### ISSUE TITLE
Clarify how to set location on profile page

### ISSUE THREAD

**Issue by mahmoud** [python/pythondotorg#744]
Currently if I go to my user page (https://www.python.org/users/mahmoud/) by clicking "Your account" next to the search bar/socialize button, the site says "Location: Not Specified"

However, if I click on "Edit my profile" I don't see a field to add my location anywhere. I believe there was a field on signup, but I must have accidentally skipped it.

**Comment by berkerpeksag** [comment]
Thanks for the report. You can update the location field(it's actually three fields :) city, state, country) at the "Edit PSF Membership" page: https://www.python.org/users/membership/edit/
