### ISSUE TITLE
Debug=True and Csrf errors on login

### ISSUE THREAD

**Issue by arcticlinux** [python/pythondotorg#746]
When trying to create an account or log in getting a django debug screen with csrf errors, which shouldn't happen in production sites. Might be because I'm on mobile but seems like a more general issue.

**Comment by frankwiles** [comment]
I'm not able to reproduce this.  On desktop or iOS.  What mobile OS and browser are you using? Honestly it shouldn't matter to get that the site would have to, as you said, be DEBUG=True which it isn't.  You weren't by chance hitting the staging site (staging.python.org) were you?

**Comment by arcticlinux** [comment]
Sorry, I was wrong about the DEBUG=True, I was reading the screen too quickly and it was just small on my phone.

I am/was using the LastPass built in browser on iPhone, copy and pasting the account signup email confirmation link, which renders the form (which should have the CSRF token) and then clicking the confirm button.

I just tried it again, clicking directly on the email into Mobile Safari and it worked, and then tried pasting again into Mobile LastPass (I think it uses embedded Safari),  sorry for the erroneous report.
![img_1518](https://cloud.githubusercontent.com/assets/96047/7455348/9f555e82-f238-11e4-8604-640c9ea12856.PNG)

**Comment by berkerpeksag** [comment]
> I just tried it again, clicking directly on the email into Mobile Safari and it worked, and then tried pasting again into Mobile LastPass (I think it uses embedded Safari), sorry for the erroneous report.

Thanks for the report! Did you logout before using Mobile LastPass? If not, this is the expected behavior since you're already logged in.
