### ISSUE TITLE
PSF Contributor Agreement on-line form appears to be broken

### ISSUE THREAD

**Issue by ned-deily** [python/pythondotorg#747]
As reported here (https://bugs.python.org/issue24142#msg242719), the box on  https://www.python.org/psf/contrib/contrib-form to allow on-line submission of the PSF Contributor Agreement seems to be broken: there is not text displayed.  The source for the box comes from a JS snippet loaded from https://secure.echosign.com/.  I'm not sure who set this up and who is maintaining it. @malemburg, any ideas?

**Comment by berkerpeksag** [comment]
It could be a temporary problem. Works for me now.

**Comment by ned-deily** [comment]
Ah, I should have checked other browsers.  It does render correctly with Firefox 38.0 on OS X.  More specifically, I see it fails if OS X Safari's (8.0.6) Settings -> Privacy - Cookies and website data are set to "Allow from current website only" (which is my default) but works if set to "Always allow".

**Comment by berkerpeksag** [comment]
Oh, thanks for the detail. In this case I don't think there's anything to do. echosign.com already sent the P3P header. There are some workarounds, but since we don't have access to the page in the iframe, we probably can't do anything other than telling users update the setting to "Always allow" or use a different browser.

**Comment by ned-deily** [comment]
Yeah, although I don't know if that covers the OP's case.  In any case, it's ugly.

**Comment by malemburg** [comment]
Last time I tried it, it worked fine. Note that I'm using Firefox.

At the moment, python.org is down, so I can't check whether there were any changes that may have caused the forms to break.

**Comment by fhoech** [comment]
Adding secure.echosign.com to exceptions (allow) for third party cookies helped, thanks.
[ Maybe turning the iframe into a simple link would be a workable solution? That way changing browser config shouldn't be necessary ]

**Comment by berkerpeksag** [comment]
I just added a direct link to the CLA form with a note at https://www.python.org/psf/contrib/contrib-form/
