### ISSUE TITLE
2.4.X links on www.python.org/downloads/windows/ point to the wrong files

### ISSUE THREAD

**Issue by PJBaker** [python/pythondotorg#751]
On the [www.python.org/downloads/windows/](https://www.python.org/downloads/windows/) page, the "Windows x86 MSI installer" links for versions 2.4.4, 2.4.3, 2.4.2 and 2.4.0 point to the IA64 versions of the installers rather than the x86 versions.

For example, the 2.4.4 link points to "python-2.4.4.ia64.msi" rather than "python-2.4.4.msi".

**Comment by berkerpeksag** [comment]
Good catch! I've just fixed all of them. Thank you for the report!
