### ISSUE TITLE
User profile missing: 404 error

### ISSUE THREAD

**Issue by ghost** [python/pythondotorg#752]
I get a 404 error on this page: https://www.python.org/users/brogme/.
Can you  completely delete this account or fix this issue?
I can't edit profile information, name, surname, e-mail address, etc.

Kind regards

**Comment by berkerpeksag** [comment]
I couldn't find any user named "brogme". Could you please give us more information?

**Comment by loewis** [comment]
I don't think there ever was a brogme user on www.python.org. I suggest to close this issue as invalid.
