### ISSUE TITLE
Missing possibility for users to delete their account or change PSF membership status

### ISSUE THREAD

**Issue by ghost** [python/pythondotorg#757]
Dear all,

it is a good idea to add a "delete" button in main menu to permit to all users to delete one's profile from python.org web site and/or PSF subscription without passing everytime times from psf@python.org email.

What do you think about?
Cheers

**Comment by malemburg** [comment]
Good idea. We just had a similar request to pydotorg-www@python.org and I too found that it's not possible to remove the account or PSF membership.

Since I find this a rather big issue, I've marked it as bug rather than enhancement.
