### ISSUE TITLE
Add profile picture

### ISSUE THREAD

**Issue by ghost** [python/pythondotorg#758]
Why not implement a profile picture uploader?
My idea is:
- user can choose an image from a library provided by Python.org community
- user can set personal gravatar account as profile picture (this solution is the best because we can apply a control-filter to on uploaded image)
- user can upload a personal image

Cheers!

**Comment by berkerpeksag** [comment]
python.org account is only needed for becoming a PSF member. Other than that, user profiles aren't used at the site so I think it would be better to keep the implementation simpler. Thank you for the suggestion.
