### ISSUE TITLE
Add links to forums in Community tab...

### ISSUE THREAD

**Issue by jedie** [python/pythondotorg#759]
Under menu point https://www.python.org/community/ are no links to the biggest python forums:

---

![screenshot](http://snag.gy/5Qvm5.jpg)

---

IMHO there should be a "forum" section added and contains these forums:
- http://www.python-forum.org/ (Biggest English speaking forum)
- http://www.python-forum.de/ (biggest German speaking forum)

**Comment by niscp** [comment]
Can I start working on this ?

**Comment by berkerpeksag** [comment]
Hi @niscp, go for it, but we don't have a tool to edit/add content for contributors yet. If you can send your work as plain text(in the same format as https://www.python.org/community/lists/), I can create a Forum page.

Thanks! :)

**Comment by thinkhuman** [comment]
@niscp are you working on this?  If not, I was interested.

**Comment by kaustav1996** [comment]
Hi I am gonna work on this. thanks :)

**Comment by kaustav1996** [comment]
[forums.txt](https://github.com/python/pythondotorg/files/1133677/forums.txt)
Forums page in txt format . shall I also add the files? I made it using https://www.python.org/community/lists/ as a reference

**Comment by berkerpeksag** [comment]
Thanks, @kaustav1996. I'm going to import the text next week.

**Comment by kaustav1996** [comment]
Okay

**Comment by berkerpeksag** [comment]
Ok, I've now converted your HTML document to reST, simplified its content a bit and added some other popular forums. I've created a new page at https://www.python.org/community/forums/

Thank you all!
