### ISSUE TITLE
Redesign "Use Python for…"

### ISSUE THREAD

**Issue by ddaaddaaps** [python/pythondotorg#763]
Hello,
I'm think some projects names need rename to more correct or change structure to this board. Something like in GUI development is "PyGtk", but correct name is PyGTK and I'm think as well PyGTK dead and now GTK for Python project name is PyGObject(aka PyGI).

Sorry for my bad English language, Thanks!

**Comment by thinkhuman** [comment]
Can you provide a URL to what you're referring to? I can't find it.

**Comment by alesandroortiz** [comment]
@thinkhuman: It's on the home page of https://www.python.org, bottom right in the screenshot below.

![image](https://cloud.githubusercontent.com/assets/1619599/12851843/154d5252-cbfa-11e5-9ab9-5cd1d95aea4d.png)

**Comment by thinkhuman** [comment]
Thanks @thephpjedi. I've got a stupid question: how do I contribute text/link corrections? This isn't a simple HTML edit. Would be grateful for any guidance to make a first-time contribution.

**Comment by berkerpeksag** [comment]
Hi @thinkhuman, we don't have an easy way to make content contributions right now. If you can paste your changes here, I can apply them. Thanks! :)

**Comment by nmve** [comment]
Hello,

@berkerpeksag, "Web Programming" I think must become "Web Development" same as GUI Development (https://en.wikipedia.org/wiki/Web_development), it's more corrent name.
In GUI Development remove "PyGtk" because project dead, GTK+ bindings for Python now is PyGObject.
"GUI Development: tkInter, PyGObject, Qt (PyQt, PySide), wxPython" <- How about it?
...or - "GUI Development: tkInter, PyGObject, PyQt, PySide, wxPython, Kivy*".
PySide - www.pyside.org
* add Kivy (www.kivy.org) to the list? 

Anyone? Agrees or not? Maybe other's have ideas? :-)

**Comment by berkerpeksag** [comment]
Thanks, @nmve! I've now addressed all of your suggestions.

Perhaps we can rename IPython to Jupyter too? @Carreau what's the correct name to use for scientific computing part of the project. If I understand http://ipython.org/#jupyter-and-the-future-of-ipython correctly, we should go with Jupyter.

**Comment by Carreau** [comment]
> what's the correct name to use for scientific computing part of the project.

That depends exactly what you want to mean. IPython is alive and well, and downloaded by ~ 4 times as many users than Jupyter, so 3 out of 4 user do not have Jupyter install and still use IPython and many "Old timers" still refer to "IPython notebook".  Still Jupyter seem to have a better publicity.

Do we have to choose ? Or can we put both ? 

If so I can come up with a sentence paragraph for both and poke the rest of the team for their thoughts.

**Comment by berkerpeksag** [comment]
> Do we have to choose ?

You don't have to :) I was just wondering which name would be better in the "Scientific and Numeric" line.
See the "Use Python for..." box in the screenshot in https://github.com/python/pythondotorg/issues/763#issuecomment-180426134. If you think that the current name is fine then we can close this issue.

> Or can we put both ?

That's an option too.

> If so I can come up with a sentence paragraph for both and poke the rest of the team for their thoughts.

We don't have enough space to put a sentence unfortunately. Just project name and a link to the project home page.
