### ISSUE TITLE
The online interpreter should not be an IPython shell by default

### ISSUE THREAD

**Issue by lordmauve** [python/pythondotorg#764]
The examples on the python.org homepage are shown in the style of the standard Python repl. When I click on the >_ icon, I would expect to see a Python prompt very similar to that in the examples.

I would also expect the behaviour when I download and run python on my local computer to be very similar to the online shell I've already experienced.

The IPython shell may be powerful for advanced users but we should avoid increasing the cognitive load for new users by introducing the IPython shell as their first contact with the Python repl.

**Comment by berkerpeksag** [comment]
+1. It should be the default Python REPL.

**Comment by gpjt** [comment]
PythonAnywhere dev here (we provide the online interpreter).   We can definitely change to using a regular Python REPL if that's what people want.

**Comment by rochacbruno** [comment]
:+1:

**Comment by ghost** [comment]
+1. Good idea!

**Comment by berkerpeksag** [comment]
@gpjt that would be great, thanks! :)

**Comment by berkerpeksag** [comment]
@gpjt is there anything I can do to move this forward?

**Comment by gpjt** [comment]
Sorry, I kind of dropped the ball on this!  I've posted to the appropriate mailing list to see if there are any objections.  It's a really easy change on our side, but we don't want to change it without making sure no-one has serious objections.

We can probably upgrade it to Python 3.5 at the same time -- might do that anyway.

**Comment by gpjt** [comment]
OK, that's done.  We have non-IPython 3.5.1 on the front page as of today.

**Comment by gpjt** [comment]
I don't have the privileges to close this issue, unfortunately.  But I think it should be marked fixed.

**Comment by berkerpeksag** [comment]
Many thanks @gpjt! :)
