### ISSUE TITLE
Open ftps and sensitive Directory 

### ISSUE THREAD

**Issue by secomunity** [python/pythondotorg#767]
Hi , i just found a sensitive directory in your website look like a open ftp folders and DB and old version maybe for your old software - this is the full path https://www.python.org/ftp/ ---- https://www.python.org/ftp/python/  --- and of course ther is a lot of paths you can chek it in the link ,

thanks guys

**Comment by benjaminp** [comment]
Yep, those are public Python downloads.

**Comment by secomunity** [comment]
all right , thanks
