### ISSUE TITLE
Page scrolling issues on iOS

### ISSUE THREAD

**Issue by youtux** [python/pythondotorg#771]
I'm not sure if anyone noticed this, but the page scrolling on iOS (specifically 8.1 on the iPhone 5s) is problematic.
To reproduce the bug:
Open python.org using Safari on iOS, scroll down and then scroll up. The window will always jump to the beginning of page, which is very annoying.

**Comment by berkerpeksag** [comment]
Thanks for the report. This is a duplicate of #531.

**Comment by youtux** [comment]
Oops sorry for that, I didn't see it.
