### ISSUE TITLE
Access to protected content

### ISSUE THREAD

**Issue by Spriithy** [python/pythondotorg#773]
Hey !
I just figured out that your website gives access to some protected content.
I guess you bought the `Flux-Regular` font. Well, it costs about 30$ but your website gives access to the `.woff` or `.eof` file. That means, anyone can download the file, and easily convert it as a `.tff` file.
# How to get the `fluxregular.woff` (`.eof`) file

Basically go on any page of the python.org website. Then show the page source code with your browser. In the `<head>` of the html file, just look for the `style.css` file. click it. 
![capture d ecran 2015-06-02 a 23 49 44](https://cloud.githubusercontent.com/assets/2387743/7948139/220830ce-0982-11e5-8936-b54d68058e86.png)

After that, just look for `fulxregular` then you should see it appears 3 times. 

![image](https://cloud.githubusercontent.com/assets/2387743/7948172/44941018-0982-11e5-9a43-61c60d14e882.png)

Select the version you like, then identify the file directory. As it is written : `../fonts/FluxRegular.eot` you should get your url like so :

![image](https://cloud.githubusercontent.com/assets/2387743/7948220/95183596-0982-11e5-86a2-4792d3915650.png)

The it easily downloads the file.

When you got this file, you can simply convert it into installable font file (`.tff`) using any software you need.

Thanks to fix it, or ignore it if you believe that this is actually not normal to have some protected content available for free.

**Comment by lvh** [comment]
It is supposed to be available. If it was not available, your browser would not be able to access it and use it to display text.
