### ISSUE TITLE
Varying minor release numbers on https://www.python.org/ftp/python/

### ISSUE THREAD

**Issue by jayvdb** [python/pythondotorg#779]
On https://www.python.org/ftp/python/, minor releases up to 3.3.0 are numbered X.Y , whereas 3.3.0 is X.Y.0 .

This causes difficulties for automated installation of any version, such as https://github.com/ogrisel/python-appveyor-demo/issues/9 which a common pattern and included in https://packaging.python.org/en/latest/appveyor.html

**Comment by ned-deily** [comment]
I'm not sure what action you are proposing here.  As far as I know, there has never been any guarantee of what the URIs for downloads look like.  There have been other differences in files between major releases, such as what formats are offered.  Scraping the URIs from the release announcement or the release pages on python.org is one sure way to find the URIs for a release.  Since many downstream users of Python have surely cached the URIs for past releases for their own build processes, they can't be changed now.  I suppose we could create symlinks for some releases, like 2.7 -> 2.7.0 and then symlinks for all the versioned files in 2.7, but that seems like that's adding work and potential confusion for something that, AFAIK up until now, no one has complained about.

**Comment by jayvdb** [comment]
> ... but that seems like that's adding work and potential confusion for something that,
> AFAIK up until now, no one has complained about.

It is only fairly recently (3.3; November 2013) that the numbering scheme has changed, affecting only the two releases so far, and most of the user base is not yet migrated to v3.

I'm glad nobody else has complained about this yet; it means my limit duplicate issue search was good enough. ;-)

> Scraping the URIs from the release announcement or the release pages on python.org
> is one sure way to find the URIs for a release.

It is definitely solvable on the client side with a bit of added complexity, but I raised this in case it is something that you might consider solving for all clients.

There does appear to be more consistency in the 'downloads' release URLs for the release pages.
https://www.python.org/downloads/release/python-26/ - 404
https://www.python.org/downloads/release/python-260/ - 200
https://www.python.org/downloads/release/python-261/ - 200
https://www.python.org/downloads/release/python-270/ - 200

However the 'download' release pages have the same problem.
https://www.python.org/download/releases/2.6/ - 200
https://www.python.org/download/releases/2.6.0/ - 200
https://www.python.org/download/releases/3.1/ - 200
https://www.python.org/download/releases/3.1.0/ - 404
https://www.python.org/download/releases/3.1.1/ - 200
https://www.python.org/download/releases/3.3/ - 404

I think I've occasionally hit broken links around these pages for old releases.  I've not worried too much about them at the time, as they are old and there are better problems to solve and easily worked around.  But I cant seem to find any now, so maybe that is fixed.

> I suppose we could create symlinks for some releases ..

Symlinks on https://www.python.org/ftp/python/ would be great ;-)  I can see that it would introduce a bit of confusion for some, but https://www.python.org/ftp/python/ is not the landing page for the easily confused.

> ... and then symlinks for all the versioned files ...

I'd be happy if the symlinks were done at the directory level only, rather than also for the files in those directories  It is less change on your side, but it does reduce the client side problem considerably.  That way the directory listing is at least easily reachable with only one numbering scheme, which at least confirms the version number matches a real release.  Then determining the correct or best file name, if one exists, involves a bit of parsing or guess work, which was required anyway so this is only a marginal increase in complexity.

Rather than creating symlinks for all old releases to match the new numbering scheme, affecting 11 releases I believe, I personally would be happy if there were symlinks from the old numbering scheme (X.Y) to the new one (X.Y.0), which would only affect the three releases 3.3(.0) and 3.4(.0) and 3.5(.0) yet to come.  But this may not be something you'd want to maintain for all future '.0' releases, which would defeat the purpose of this approach.

**Comment by berkerpeksag** [comment]
A little off-topic: We should merge all information at https://www.python.org/downloads/release/python-260/ and https://www.python.org/download/releases/2.6/ in one page.

**Comment by hugovk** [comment]
> On [python.org/ftp/python](https://www.python.org/ftp/python/), minor releases up to 3.3.0 are numbered X.Y , whereas 3.3.0 is X.Y.0 .
> 
> This causes difficulties for automated installation of any version, such as [ogrisel/python-appveyor-demo#9](https://github.com/ogrisel/python-appveyor-demo/issues/9) which a common pattern and included in [packaging.python.org/en/latest/appveyor.html](https://packaging.python.org/en/latest/appveyor.html)

As noted, since 3.3, a consistent x.y.z version has been used. 

Python 3.3 was released in 2013, and by now everything older than 3.8 is end-of-life, so I don't think it matters too much about the ancient releases. Thanks anyway!
