### ISSUE TITLE
Link to pyGTK on the front page.

### ISSUE THREAD

**Issue by PTNobel** [python/pythondotorg#781]
python.org has a link to pyGTK, which is deprecated in favor of pyGobject, under the "Use Python for…" box.

**Comment by berkerpeksag** [comment]
http://www.pygtk.org/ says:

> Windows users may still want to keep using PyGTK until more convenient installers are published.

Perhaps we can also add pyGobject and keep pyGTK for a while?

**Comment by berkerpeksag** [comment]
Added. Thanks for the report!
