### ISSUE TITLE
OS-specific download pages list pre-releases

### ISSUE THREAD

**Issue by nanonyme** [python/pythondotorg#782]
https://www.python.org/downloads/ -> Windows, Linux, OSX pages still list alpha/beta builds even though the main listing now works as expected ( #621 ) .We just had a user go to their OS-specific page instead of clicking the obvious download link and unintentionally download a beta build for Python3.5. While the suffixed naming convention is obvious to us who have used Python more, it is not for newcomers.

**Comment by SujaySKumar** [comment]
Hi,
I would like to fix this. In the current downloads page for a specific os, which of them are alpha/beta builds?

**Comment by nanonyme** [comment]
@SujaySKumar Eg https://www.python.org/downloads/windows/ -> Python 3.5.0 - 2015-09-13 is final; Python 3.5.0rc4 - 2015-09-09, ..., Python 3.5.0b4 - 2015-07-26, ..., Python 3.5.0a4 - 2015-04-20.. are prereleases. That is, release candidates, betas and alphas could (should?) be filtered out not to confuse users who aren't specifically wanting to test prerelease versions

**Comment by SujaySKumar** [comment]
@nanonyme So what do you think will be the ideal solution? Providing a separate page for alpha and beta builds?

**Comment by nanonyme** [comment]
@SujaySKumar Sorry for lack of answer. Yes, I think separate page might work or splitting the page to multiple parts and having intra-page anchrors for finding the prereleases. It's just, these pages are currently very obvious to browse to from the main page for a beginner and they might not understand what a/b/rc means. At best it means they end up testing a release candidate, at worst it means they use a completely broken alpha build when they're taking their first steps to the language
