### ISSUE TITLE
404s from links on https://www.python.org/psf/records/board/

### ISSUE THREAD

**Issue by dreid** [python/pythondotorg#783]
Specifically the links to
- Meeting Minutes
- Resolutions passed by the board.
- Treasurer Reports
- Conference Committee Reports

all 404 because they seem to include an extra `/board/` in the linked URLs.

**Comment by berkerpeksag** [comment]
Thanks for the report. Looks like this is already fixed.

**Comment by berkerpeksag** [comment]
I closed this too early. The last two links are still broken.

**Comment by berkerpeksag** [comment]
Fixed.
