### ISSUE TITLE
Sample examples with wrong syntax

### ISSUE THREAD

**Issue by carlosjrxd** [python/pythondotorg#785]
Hi, sorry if i write something wrong in english. I am from Brazil, and speak portuguese.

So, the Sample Program has the old Syntax, maybe cause some problems for newbies
like me trying to learn python.

For example. In this first sample. 

print "Hello, World" 

correct

print ("Hellow, World")

You knows, Can change? Has more wrong samples. Thank You. 

https://wiki.python.org/moin/SimplePrograms

**Comment by berkerpeksag** [comment]
Thanks for the report, Carlos. The page you mentioned is part of the Python wiki, which means you can edit it yourself. Please see https://wiki.python.org/moin/FrontPage#Editing_pages for learning how to edit a page on the wiki.
