### ISSUE TITLE
Missing public GPG key from list of keys

### ISSUE THREAD

**Issue by zooba** [python/pythondotorg#786]
Steve Dower's (me) public GPG key (used for Python 2.7.10 and 3.5 releases) is not listed on https://www.python.org/downloads/ with the other keys.

The key id is 487034E5 and you can find it at http://pgp.mit.edu/pks/lookup?op=get&search=0xFC624643487034E5

**Comment by ned-deily** [comment]
I've updated the box on the downloads page to include your key and made pull request #787 to update the static downloadable file to include all of the past and present release manager keys.
