### ISSUE TITLE
Python 2.7 landing page references old versions

### ISSUE THREAD

**Issue by scw** [python/pythondotorg#789]
When searching for "Python 2.7" with DDG, the first result is this page:
  https://www.python.org/download/releases/2.7/

It references five year old releases rather than the current releases, and it'd be helpful for it to have up-to-date information.

**Comment by ned-deily** [comment]
Thanks for the comment. The 2.7 page has been changed to link to the current maintenance release, 2.7.10.

**Comment by scw** [comment]
Thanks!
