### ISSUE TITLE
PSF page doesn't list our sponsors

### ISSUE THREAD

**Issue by malemburg** [python/pythondotorg#79]
The PSF landing page doesn't prominently list our sponsors.

If we want to keep our sponsors happy and attract more of them, we should definitely give them a more prominent listing on the landing page.

The page does have a prominent box for the "league of awesome". Those are companies which have donated services to the PSF, but are not sponsor members. These could be listed on the donation page instead, perhaps under a separate section to highlight their ongoing donation.

**Comment by malemburg** [comment]
I removed the dummy league of awesome content and replaced it with a sponsors box.

**Comment by ncoghlan** [comment]
Not sure if I should put this here or in a new issue, but the sponsor list at https://www.python.org/psf/ is a bit outdated - it still lists Sun, and they no longer exist. Sun are correctly missing from https://www.python.org/psf/members#sponsor-members, but newer sponsors like Red Hat aren't there.

The PSF landing page also renders as part of the "Python" section in the main nav, which feels a bit weird.

**Comment by frankwiles** [comment]
Sponsors seem up to date now.
