### ISSUE TITLE
About page has 404 link

### ISSUE THREAD

**Issue by wslack** [python/pythondotorg#790]
https://www.python.org/about/, see the bottom right "open source" widget with text: "Python is developed under an OSI-approved open source license, making it freely usable and distributable, even for commercial use. Python's license is administered by the Python Software Foundation."

The last link (https://www.python.org/psf-inner) 404's and for the life of me, I have no idea what's being called by this code:

```
                    {% box 'aboutpython-opensource' %}
```

**Comment by ned-deily** [comment]
Thanks for the report.  The link has been changed to go to the current PSF landing page: https://www.python.org/psf-landing/.  (Objects like the box you cite are maintained in the website database and managed through the website's admin interface.)

**Comment by wslack** [comment]
Thanks, feel much less crazy.
