### ISSUE TITLE
Bug Python 2.7.7 and Python 2.7.9

### ISSUE THREAD

**Issue by francesco1119** [python/pythondotorg#791]
On my Debian Wheezy I've tried do install the latest Python but I find myself in a conflict now:

Building dependency tree  
Reading state information... Done
You might want to run 'apt-get -f install' to correct these.
The following packages have unmet dependencies:
 libpython2.7 : Depends: python2.7 (= 2.7.3-6+deb7u2) but 2.7.9-2 is installed
 python2.7 : Depends: python2.7-minimal (= 2.7.9-2) but 2.7.3-6+deb7u2 is installed
             Depends: libpython2.7-stdlib (= 2.7.9-2) but it is not installable
 python2.7-dev : Depends: python2.7 (= 2.7.3-6+deb7u2) but 2.7.9-2 is installed
E: Unmet dependencies. Try using -f.

'apt-get -f install' asks me to REMOVE more than 2GB of software and I don't want that

**Comment by ned-deily** [comment]
Sorry, this issue tracker is for problems with the python.org website.  The problem you are describing is a Debian package management issue, nothing to do with python.org or even Python itself.  You should try looking for help via one of the many Debian-related channels; see, for instance, https://www.debian.org/support.
