### ISSUE TITLE
Annoying horizontal scroll

### ISSUE THREAD

**Issue by yuvadm** [python/pythondotorg#795]
The homepage (as well as many others tested) has a few dozen pixels on the right side that overflow and create an annoying horizontal scroll. Tested on latest Firefox on OS X.

![screen shot 2015-07-16 at 15 32 41](https://cloud.githubusercontent.com/assets/315080/8722726/19e8881a-2bd0-11e5-8e2c-7651829c17c8.png)

**Comment by berkerpeksag** [comment]
Thanks for the report, Yuval. This is a duplicate of #731.

**Comment by yuvadm** [comment]
Sorry for the dupe :)
