### ISSUE TITLE
Docs page's sidebar jitter on mouse wheel scroll on Chrome.

### ISSUE THREAD

**Issue by biwin** [python/pythondotorg#797]
The sidebar on the documentation pages ex. https://docs.python.org/2/library/collections.html vibrates/flashes on mouse wheel scroll. 
The sidebar with class `sphinxsidebar` , works okay when scrolling with the scrollbar, also Firefox but not with mouse wheel on Chrome.

may be some positioning issues, (top position is calculated on scroll).

please consider fixing it.

**Comment by berkerpeksag** [comment]
Thanks for the report! I can reproduce it, but the correct place to report this is https://bugs.python.org
