### ISSUE TITLE
PEP pages scroll to top mid-read on iPhone Mobile Safari

### ISSUE THREAD

**Issue by jeremy-w** [python/pythondotorg#798]
I have been unable to pin down what triggers this.

I did note that selecting a section from the TOC seemed to reliably reproduce the issue: The page would jump to the section, then immediately (and frustratingly) scroll up to the top of the page. Hitting the refresh button would then repeat this behavior: the page would load, go to the anchor identified by the fragment in the URL, and then scroll straight to the top of the page.

**Comment by berkerpeksag** [comment]
Thanks for the report. I think this is somewhat related to https://github.com/python/pythondotorg/issues/531. We've partly fixed this recently. You can test the fix at https://staging.python.org/.

**Comment by berkerpeksag** [comment]
This should fixed now.
