### ISSUE TITLE
python .pth file

### ISSUE THREAD

**Issue by Luna-CY** [python/pythondotorg#799]
不知道你们能看懂中文吗？没办法，我不会英文

今天在看py学习手册讲到.pth文件，我试了一下似乎只能在sitepackages所列出的目录中使用，工作目录下的.pth文件并不能使用，我觉得这样并不好，.pth文件存在的目的就是在项目中方便的批量设置模块导入路径，所以在项目目录中使用.pth文件才更加合理不是吗？

**Comment by berkerpeksag** [comment]
Hey @MCtion, thank you for your report, but this is not the right place for questions like this. You may want to ask on https://groups.google.com/forum/#!forum/python-cn (or please see the list of local Python user groups in China: https://wiki.python.org/moin/LocalUserGroups#China)
