### ISSUE TITLE
Download information is no longer easily accessible

### ISSUE THREAD

**Issue by malemburg** [python/pythondotorg#80]
The downloads page on python.org used to list a number of alternative Python distributions and implementations, and gave instructions on how to verify the downloads, including key lists for the GPG verification:

http://legacy.python.org/download/

This page is no longer easily accessible on the new site via the menu, even though the old download page is still available as:

http://python.org/download/

**Comment by birkenfeld** [comment]
Yes, this info has to be restored.
The alternate implementations list is already on its own page, linked from the top menu.
The GPG info should be linked from a box below the releases list, I think. (Maybe if we remove the "History" box.)
