### ISSUE TITLE
Home-page Jitter

### ISSUE THREAD

**Issue by Engid** [python/pythondotorg#801]
Hello,

I noticed that the code examples on the top of the home page have different heights. When they change from one example to the next (on an automatic cycle), the placement of the text below jumps either up or down depending on the dimensions of the new code example. Could the cycle be paused when the user has scrolled past the examples? Or perhaps their dimensions could have a consistent height throughout? 

Thank you
Nick

**Comment by berkerpeksag** [comment]
Thank you for your report and sorry for our late response. I can't reproduce this with Chrome 49.0.2623.112 under Linux and Chrome 62.0.3202.94 under OS X Yosemite. Can you please give us more information (e.g. browser and device information)

**Comment by karlafalcao** [comment]
Hello guys, I would like to contribute to pythondotorg frontend issues. I would like to know if this PR is still valid?

**Comment by berkerpeksag** [comment]
I think we can close it since it's an old issue and we never heard back from the OP. It's not easy to reproduce frontend issues if we don't have enough information.
