### ISSUE TITLE
'Open Mike' Link Broken (Diversity In Python section)

### ISSUE THREAD

**Issue by smartscott82** [python/pythondotorg#803]
My name is Scott and I work as a QA engineer.  

URL:  https://wiki.python.org/moin/DiversityInPython

Issue:  In the "What you can do - Simple, personal actions:" section.  Fourth Bullet Point down.  The "Open Mike" Link is broken.  The link is http://python-open-mike.posterous.com
posterous is a site that is no longer existing.

**Comment by berkerpeksag** [comment]
Hi Scott, thanks for the report. https://wiki.python.org/moin/DiversityInPython is part of the Python Wiki which means you can also edit it yourself(please see https://wiki.python.org/moin/#Editing_pages more information). Unfortunately, according to http://geekfeminism.wikia.com/wiki/Python_Open_Mike, "Open Mike" is no longer active. Perhaps discussing alternatives on https://mail.python.org/mailman/listinfo/diversity-sig would be the next step.

**Comment by smartscott82** [comment]
Thanks.  I will discuss alternatives on the provided link.  Enjoy the day. 

```
 On Tuesday, July 28, 2015 11:38 AM, Berker Peksag <notifications@github.com> wrote:
```

 Hi Scott, thanks for the report. https://wiki.python.org/moin/DiversityInPython is part of the Python Wiki which means you can also edit it yourself(please see https://wiki.python.org/moin/#Editing_pages more information). Unfortunately, according to http://geekfeminism.wikia.com/wiki/Python_Open_Mike, "Open Mike" is no longer active. Perhaps discussing alternatives on https://mail.python.org/mailman/listinfo/diversity-sig would be the next step.—
