### ISSUE TITLE
Somebody wrote webmaster.  Cannot get confirmation email for job board

### ISSUE THREAD

**Issue by lac22** [python/pythondotorg#804]
Text of what they told webmaster here:
Date:    Tue, 28 Jul 2015 09:35:54 -0000
To:      "'webmaster@python.org'" webmaster@python.org
From:    Helene Althuon hf@solute.de
Subject: Failured registration regarding a new account for your webforums

Dear webmaster,

We pretty much adore your webspaces and as a German E-Commerce-company,
working lots with python, we would be happy to publish some interesting
vacancies to your job board.

Unfortunally we – solute gmbh, who is a German company settled in Karlsruhe,
Baden-Württemberg - were not able to register successfully at your python job
board by ourself– for we didn´t receive an confirmation email after filling
in the single gaps through signing up… I know hope, you can help us joining
your board.

While signing up I used my mailadress [1] hf@solute.de and tried to register
under our company name first, which is “solute gmbh”, afterwards I tried the
registration again with “billiger.de” which is one of our main services and
at least in Germany popular by Television spots.

We would be very happy, if taking part in your forums would be possible for
us, for we always have a big need of python lovers in our company…

Thank you very much in anticipation for your kind help,

yours sincerely from Karlsruhe,

Helene Althuon

Assistant HR

billiger.de

solute gmbh

Zeppelinstraße 15

D-76185 Karlsruhe

Tel:            +49 721-86956-388

Fax:            +49 (0)721 - 86956-66

E-Mail:         hf@solute.de

Web:            [2]http://www.billiger.de

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Geschäftsführer: Lorenz Petersen

Sitz: Karlsruhe

Registergericht: Amtsgericht Mannheim

Registernummer: HRB 110579

Umsatzsteueridentifikationsnummer: DE234663798

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

http://cdn.billiger.com/static/mail/demexco.png

Treffen Sie unsere Experten zum persönlichen Gespräch [3]Jetzt Termin
vereinbaren.

Wir freuen uns auf Ihren Besuch!

Ihr dmexco-Ticket erhalten Sie bis einschließlich 17.8.15 kostenlos [4]hier!

References:

[1] mailto:hf@solute.de
[2] http://www.billiger.de/
[3] mailto:shops@billiger.de
[4] http://www.dmexco.de/tickets

**Comment by berkerpeksag** [comment]
It looks like we never sent a confirmation email to them. According to https://github.com/pennersr/django-allauth/issues/218#issuecomment-15017604, if they try to login to python.org with that email/username again, django-allauth will send another confirmation email automatically.

**Comment by berkerpeksag** [comment]
I assume this is no longer a problem. #846 has been opened to document what they need to do to get another confirmation email. Thank you for the report.
