### ISSUE TITLE
Legacy Website should have out-of-date banner on all pages

### ISSUE THREAD

**Issue by jayvdb** [python/pythondotorg#806]
The front page of http://ftp.python.org/ (http://legacy.python.org) reports

"This is the legacy website for Python. It is no longer being updated. It will remain available until all content has been ported over to the new website which is available here."

This should appear prominently on all pages, especially

http://ftp.python.org/download/

```
The current production versions are Python 3.4.0 and Python 2.7.6.
```

http://ftp.python.org/download/releases/

```
The current production versions are 3.4.0 and 2.7.6.
```

**Comment by loewis** [comment]
I think this should be resolved differently: ftp.python.org should become a CNAME for www.python.org. AFAICT, this should work for most URLs. It would be good to monitor ftp.python.org for a while to see whether any important URLs are forgotten. Preferably, the virtual host for ftp.python.org would then actually redirect to www.python.org, to point out that ftp.python.org is also deprecated.

I'm not sure whether the original issue still exists when ftp is redirected. I don't think it is necessary to point out that it's a legacy site if somebody deliberately navigates to legacy.python.org.

**Comment by brainwane** [comment]
https://legacy.python.org/download/ is currently available to the public and says

> The current production versions are Python 3.4.0 and Python 2.7.6.

https://legacy.python.org/download/releases/ also says

> The current production versions are 3.4.0 and 2.7.6.

I suggest that we redirect at least _these_ pages, immediately, to their equivalents on www.python.org. @ewdurbin is that possible?

**Comment by brainwane** [comment]
@JulienPalard @ewdurbin Pinging on this as I work to close out tasks that have to do with communicating the sunsetting of Python 2.

**Comment by JulienPalard** [comment]
I don't think I can help on this one (TBH I was not aware of legacy.python.org).

**Comment by ewdurbin** [comment]
These two new redirects were added to legacy.python.org's configuration and are active:

```
    RedirectMatch permanent ^/download/?$ https://www.python.org/downloads/
    RedirectMatch permanent ^/download/releases/?$ https://www.python.org/downloads/
```

**Comment by ewdurbin** [comment]
FWIW it seems that the ftp.python.org hostname has been gone for a fairly long time.

I think that this issue may be able to be closed out completely. Someone please reopen if necessary.
