### ISSUE TITLE
update https://www.python.org/news/ to say that 3.5.0b4 is available

### ISSUE THREAD

**Issue by lac22** [python/pythondotorg#807]
Announcement here: https://mail.python.org/pipermail/python-announce-list/2015-July/010840.html

**Comment by berkerpeksag** [comment]
That page is way out-dated. Perhaps we should add a note and a link to https://www.python.org/blogs/.

**Comment by lac22** [comment]
We already have a News menu item with 4 dropdowns on every page.
Python News: https://www.python.org/blogs/
Community News: http://planetpython.org/
PSF News: http://pyfound.blogspot.se/  
PyCON News: http://pycon.blogspot.se/  (I suppose the last two are blogspot getting me a local mirror)

I'd change the menu item from 'Community News' to 'Community Blogs' since that is really
what it is. (I think that https://www.python.org/blogs/ isn't the best name for Python Insider blog posts, and python-insider (or development-news) would be better.)

Then I would make https://www.python.org/news/ redirect to  PSF News.  Python News is a tad
boring for the media, some of whom have the attention span of mayflies. 

Do we own planetpython.org as well?  It would be good if that page got a header that mentioned
that this was a list of Python blogs, as well as a link for 'how to request that your python blog
get added to PlanetPython'.  But I don't know where to suggest that.

**Comment by berkerpeksag** [comment]
I've now added a redirect from `/news/` to `/blogs/`.
