### ISSUE TITLE
Mobile page scroll hijacking is unacceptable

### ISSUE THREAD

**Issue by vanzomerenc** [python/pythondotorg#812]
To the poor soul who thought he was doing good with this feature, I'm sorry. It breaks regular use. Scrolling up is a common action when reading web pages. Having page scrolling interrupted by automatic scrolls to the top of the page is not only annoying, but it makes the page much less useable due to the constant interruption of reading.

**Comment by lac22** [comment]
I think you have found this bug.
https://github.com/python/pythondotorg/issues/531

Are you on Chrome or Safari?

And, since the issue is closed, we thought we had it fixed. Can you provide more details about
what mobile device you have and what browser?

**Comment by berkerpeksag** [comment]
Also, please clear your browser's cache before testing the website.

**Comment by vanzomerenc** [comment]
Using Chrome on Android

**Comment by vanzomerenc** [comment]
Chrome 44.0.2403.133 on Android 5.1

**Comment by vanzomerenc** [comment]
Clearing cache did not fix the issue, which is still exactly as described in #532. Should we close this issue and reopen that one since it is the same issue?

**Comment by vanzomerenc** [comment]
Sorry, I meant issue #531. Should have caught that while proofreading.

**Comment by berkerpeksag** [comment]
No, this could be a different issue since we removed the code that causes #531. Do you see this behavior in every page? Can you also try to reproduce this at https://staging.python.org/ ? (please clear browser's cache first) If you see this behavior when you near to the bottom of the page, then https://github.com/python/pythondotorg/blob/master/static/js/script.js#L238 might the culprit.

**Comment by berkerpeksag** [comment]
@vanzomerenc do you still reproduce this issue? If so, could you please give us the steps to reproduce the problem?

**Comment by vanzomerenc** [comment]
I can no longer reproduce this issue.

I'd also like to apologize for my tone when I opened it, and for letting it sit for 2 years without responding.

Consider it closed.

**Comment by berkerpeksag** [comment]
No problem, I can definitely understand your frustration :) Thank you for following up on this!
