### ISSUE TITLE
vagrant up fails

### ISSUE THREAD

**Issue by loewis** [python/pythondotorg#815]
I just tried to install the site with "vagrant up", and it fails. The end of the vagrant log reads

==> default: Running chef-solo...
==> default: stdin: is not a tty
==> default: [2015-08-25T16:08:57+00:00] INFO: Forking chef instance to converge...
==> default: Starting Chef Client, version 12.4.1
==> default: [2015-08-25T16:08:57+00:00] INFO: **\* Chef 12.4.1 ***
==> default: [2015-08-25T16:08:57+00:00] INFO: Chef-client pid: 1579
==> default: [2015-08-25T16:08:58+00:00] INFO: Setting the run_list to ["role[python-dev-box]"] from CLI options
==> default: [2015-08-25T16:08:58+00:00] INFO: Run List is [role[python-dev-box]]
==> default: [2015-08-25T16:08:58+00:00] INFO: Run List expands to [apt, pythondotorg::locale, build-essential, python, ruby::1.9.1, postgresql::client, postgresql::server, git, mercurial, pythondotorg::db, pythondotorg::prereq, pythondotorg::project]
==> default: [2015-08-25T16:08:58+00:00] INFO: Starting Chef Run for precise64
==> default: [2015-08-25T16:08:58+00:00] INFO: Running start handlers
==> default: [2015-08-25T16:08:58+00:00] INFO: Start handlers complete.
==> default: 
==> default: Running handlers:
==> default: [2015-08-25T16:08:58+00:00] ERROR: Running exception handlers
==> default: Running handlers complete
==> default: [2015-08-25T16:08:58+00:00] ERROR: Exception handlers complete
==> default: Chef Client failed. 0 resources updated in 1.326027316 seconds
==> default: [2015-08-25T16:08:58+00:00] ERROR: undefined method `cheffish' for nil:NilClass
==> default: [2015-08-25T16:08:58+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

**Comment by loewis** [comment]
Apparently, that's a bug in Chef 12.4.x: https://github.com/chef/chef/issues/3659

**Comment by loewis** [comment]
Downgrading to 12.3 gives a different error:

==> default: [2015-08-25T18:48:18+00:00] ERROR: Cookbook loaded at path(s) [/tmp/vagrant-chef/af1f5f4d5264e310ee6feed79a05099b/cookbooks/build-essential] has invalid metadata: The `name' attribute is required in cookbook metadata

That apparently is an incompatibility introduced in Chef 12: http://blog.endpoint.com/2015/04/the-name-attribute-is-required-in.html

**Comment by berkerpeksag** [comment]
Thanks for investigating this. I have a WIP branch to switch to Ansible: https://github.com/berkerpeksag/pythondotorg/tree/switch-to-ansible I will try to finish it this week, so hopefully we won't have to use our outdated Chef recipes soon.

**Comment by loewis** [comment]
Ok. Even with the Chef downgrade, it still fails, since the aws is a dependent cookbook, but not included. I'll refrain from reporting that until either

a) this issue is closed by accepting my merge request, or
b) the switch to ansible happened, making the merge request obsolete.

Please understand that other people cannot easily work on pydotorg until this gets resolved.

**Comment by berkerpeksag** [comment]
Sorry, I just saw the PR and merged it. Thanks!
