### ISSUE TITLE
"Audio/Video Instructional..."  broken link 

### ISSUE THREAD

**Issue by CarlFK** [python/pythondotorg#821]
https://www.python.org/doc/av/#conference-talk-and-video-lecture-repositories

```
Python videos at video.google.com (videos)
    Pretty much the ultimate video storage site in general, Google Videos ...
```

Google Videos link is 404.  

I wold remove all of those vid links - the point of PyVideo.org is to be the place to go for Python videos.

**Comment by berkerpeksag** [comment]
Done. Also kept PyCon 2008 videos since they are not on pyvideo.org.

Thanks for the report.
