### ISSUE TITLE
Datetime-SIG is not listed on the "sigs" page

### ISSUE THREAD

**Issue by abalkin** [python/pythondotorg#829]
See https://www.python.org/community/sigs/

**Comment by berkerpeksag** [comment]
Who is the coordinator of datetime-sig? Brett, Chris or you?

Thanks!

**Comment by abalkin** [comment]
I don't think a "coordinator" has been formally appointed. @brettcannon ?

**Comment by brettcannon** [comment]
If someone has to be appointed I guess I can do it as a neutral party but I'm actually not involved with what happens on the mailing list beyond getting it set up.

**Comment by abalkin** [comment]
You can "appoint" me if you want.

**Comment by abalkin** [comment]
BTW, @abalkin = Alexander Belopolsky.

**Comment by berkerpeksag** [comment]
Done: https://www.python.org/community/sigs/

Thanks for the report.
