### ISSUE TITLE
PSF donation list is not being updated

### ISSUE THREAD

**Issue by malemburg** [python/pythondotorg#83]
The donation page (http://python.org/psf/donations/) reads:

"""
Donors

The PSF would like to thank the following donors for their contributions. Donors are listed in descending order using an algorithm that takes into account both the amount of donation and the age of the donation.

Please check back in a few hours, after the automated system has a chance to update the list of donors.

"""

For the time being, it may be better to redirect the page to the legacy site, which does receive these updates.

**Comment by malemburg** [comment]
The same problem exists on the legacy site.

I've replaced the template text with a notice now.

**Comment by berkerpeksag** [comment]
I'm going to keep #709 open and close this one as a duplicate because the former has much more information.
