### ISSUE TITLE
Saving a draft job board posting submits it

### ISSUE THREAD

**Issue by mahmoud** [python/pythondotorg#833]
... I think. I created a job listing (now at https://www.python.org/jobs/734/), hit "Save Draft" and it took me to a page thanking me for my submission. The posting is pretty much done, I just wanted to preview it. Anyways, I found the "Edit this posting" link eventually and resubmitted it as a non-Draft, but the flow is a bit confusing.

**Comment by pneff** [comment]
This will be fixed when #859 is merged.

**Comment by mahmoud** [comment]
Great! Maybe I'll have another job posting by then :)

**Comment by berkerpeksag** [comment]
#859 has been merged.
