### ISSUE TITLE
Success stories "Author name" display confusion

### ISSUE THREAD

**Issue by mahmoud** [python/pythondotorg#834]
I submitted a PayPal Python developer's Success Story via [this interface](https://www.python.org/success-stories/create/), putting their name under the "Author" field. But now, that author field [isn't really being displayed anywhere](https://www.python.org/success-stories/mahmoud-hashemi/), making it look like it's my words. 

While I can certainly attest to the benefits, I was curious if the design could be made clearer.

**Comment by berkerpeksag** [comment]
Agreed, it looks a bit weird. I'll take a look at it, thanks! Do you want me to update the current entry in the meantime?

**Comment by mahmoud** [comment]
Yes please and thank you!

**Comment by berkerpeksag** [comment]
Updated the title to "PayPal, Inc." for now: https://www.python.org/success-stories/paypal-inc/

Let me know if you want change it to a more informative title.

**Comment by berkerpeksag** [comment]
This should be fixed by #1099. It's not deployed on python.org yet.
