### ISSUE TITLE
current document reciting deprecated code

### ISSUE THREAD

**Issue by MarkPuchalaII** [python/pythondotorg#835]
I was reading through the docstring document, today, at https://www.python.org/dev/peps/pep-0257/#handling-docstring-indentation.
It cites a "trim()" function, which uses "sys.maxint".
I read in https://docs.python.org/3.1/whatsnew/3.0.html#integers, that "sys.maxint" was deprecated in PEP 0238.
If we replace "sys.maxint" with "sys.maxsize" it should be completely current again.

P.S. I am new to programming in general, let alone here. Please let me know of any courtesies/standards I might have missed in this post.

**Comment by berkerpeksag** [comment]
Thanks for the report and welcome to Python programming :) Yes, we can definitely update the code in PEP 257, but the better place to report issues like this would be https://bugs.python.org (or you can send an email to peps@python.org).
