### ISSUE TITLE
Location missing in user profile edit

### ISSUE THREAD

**Issue by alvations** [python/pythondotorg#839]
`Location` on the python profile page remains `Not Specified` for profile page but there is nowhere to input location on https://www.python.org/users/edit/ . After looking at https://www.python.org/users/, there are quite a lot of unspecified location =(

Seems like the location field can only be specified on the PSF membership page: https://www.python.org/users/membership/

Maybe the location field should also be available on the python user/edit page too.

**Comment by berkerpeksag** [comment]
That's because the location field is needed for PSF membership. I don't see any need for displaying location information of users in the current form of python.org.

Thanks for the report.
