### ISSUE TITLE
Old information on alternative Python implementations page

### ISSUE THREAD

**Issue by djet-me** [python/pythondotorg#842]
I just opened page with alternative Python implementations (https://www.python.org/download/alternatives/) and have wondered that links not working anymore.

List of bad links and ways to fix them I added below:

Stackless Python (maybe it just temporary problem with server).
Python XY moved to GitHub - http://python-xy.github.io/
WinPython moved to GitHub - http://winpython.github.io/
Portable Python is not being developed anymore. And their site now just work as alternativeTo.

**Comment by lac22** [comment]
Christian Tismer is aware of the problem on the stackless site, but he cannot fix it right now.  So that one is temporary.

**Comment by lac22** [comment]
Also portable python (further down the list) is no more.

But https://www.pythonanywhere.com/ should probably be added.

**Comment by malemburg** [comment]
Thanks for reporting the broken links.

I fixed the Python XY and WinPython ones and removed Portable Python, since the page doesn't even offer older downloads, so is basically defunct.

**Comment by malemburg** [comment]
> But https://www.pythonanywhere.com/ should probably be added.

Added this to a new section.

I wonder whether we should also include pointers to e.g.
Brython, Pyston, etc.

**Comment by malemburg** [comment]
I'll ask around on pydotorg-www.
