### ISSUE TITLE
Jobs navigation menu is broken

### ISSUE THREAD

**Issue by krysros** [python/pythondotorg#843]
![jobs](https://cloud.githubusercontent.com/assets/5299999/10862768/d73f84f6-7fb6-11e5-91d5-3d6b8419a99c.png)

To reproduce:
1. Click on item from subnav menu
2. Try again

**Comment by arku** [comment]
If you look closely, it shows the text _No Active Categories_ because we are currently viewing a category which is a leaf node in the category tree.

**Comment by berkerpeksag** [comment]
This is now fixed in https://github.com/python/pythondotorg/commit/c652d0584876efe05afd06a2d0a72678e658a9b3 but apparently GitHub is no longer links commit sha to the issue. Thank you for the report. I'm going to deploy it to production next week.
