### ISSUE TITLE
how to fixed this problems ?

### ISSUE THREAD

**Issue by bvvuz** [python/pythondotorg#845]
how to fixed this problems (OS, - Win2003 SP2 Ru 32bit, operation, started-opened new version Python) ?,...or this version (Python v3.5) not support this OS (messages Python; - not a valid Win32 application) ?
![1](https://cloud.githubusercontent.com/assets/15726839/11030841/67de3e7a-86f2-11e5-9259-145c83c5e4ab.jpg)

**Comment by berkerpeksag** [comment]
Thanks for the report! Two things:
- Python 3.5 doesn't actually support Win XP and we've updated the Windows installer to abort installation process early (with a user friendly message) on Win XP in 3.5.1. It will be released in next month or so.
- This tracker is for reporting bugs in www.python.org itself. You can report issues like this on bugs.python.org

**Comment by bvvuz** [comment]
Hi,

Thanks for this messages (this very good news, - support Python 3.5.1 OS Win XP)
:).

Best regards, sl.

---

  10.11.2015, 0:21:38 пользователь Berker Peksag (notifications@github.com)
  написал:

  Thanks for the report! Two things:

```
* Python 3.5 doesn't actually support Win XP and we've updated the Windows
  installer to abort installation process early (with a user friendly
  message) on Win XP in 3.5.1. It will be released in next month or so.

* This tracker is for reporting bugs in www.python.org itself. You can
  report issues like this on bugs.python.org
```

**Comment by berkerpeksag** [comment]
Just to clarify: Python 3.5.1 won't support Win XP. It will just stop the installation process with a better and user friendly error message(e.g. Python 3.5 doesn't support Win XP. Please install Win 7 SP1 or use Python 3.4 -- I don't use Windows, so I don't remember the exact wording) instead of throwing a cryptic error message like above.

**Comment by bvvuz** [comment]
Hi,

Thanks for the answer. Unfortunately I do not have a license to Windovs7 :(...

Best regards, sl.

---

  11.11.2015, 5:24:14 пользователь Berker Peksag (notifications@github.com)
  написал:

  Just to clarify: Python 3.5.1 won't support Win XP. It will just stop the
  installation process with a better and user friendly error message(e.g.
  Python 3.5 doesn't support Win XP. Please install Win 7 SP1 or use Python 3.4
  -- I don't use Windows, so I don't remember the exact wording) instead of
  throwing a cryptic error message like above.
