### ISSUE TITLE
https://www.python.org/accounts/signup/ should list what to do if you don't get a confirmation message

### ISSUE THREAD

**Issue by lac22** [python/pythondotorg#846]
First, look at your spam folder (if you have one).

Then ....

(something other than 'mail webmaster' who will only tell you to submit a bug report here.
This might not be how you want to handle people from yahoo and other places who canot
receive the mail in the first place).

**Comment by berkerpeksag** [comment]
I've documented this in `templates/account/verification_sent.html`:

![](https://user-images.githubusercontent.com/26338/30854695-1c98f284-a2bb-11e7-8443-829d54b8392a.png)
