### ISSUE TITLE
https://www.python.org/downloads/ and https://www.python.org/downloads/windows/

### ISSUE THREAD

**Issue by lac22** [python/pythondotorg#848]
should mention IN LARGE LETTERS that 3.5 does not run on Windows XP.  Stick with 3.4,
upgrade your Windows OS, or move to a different OS if you want to run 3.5

3.5.1 will detect XP and warn people in advance, but that won't be out for a month or more.
In the  meantime python-list is downing in XP users who don't know why it is not working.

**Comment by tjguk** [comment]
I'm just waiting for #876 to be merged, to be sure the approach is sound. Then I can look at adding other warnings.
