### ISSUE TITLE
Add a prominent button/link to easily go back to the legacy site

### ISSUE THREAD

**Issue by malemburg** [python/pythondotorg#85]
During the transition phase, I think it's important to allow people to easily go back to the legacy site. Otherwise, they may end up being frustrated trying to find information in locations where they used to be and no longer are.

**Comment by birkenfeld** [comment]
Do we still need this?

**Comment by malemburg** [comment]
I think we do - at least until we have sorted out the navigation issues and ported more content over to the new site (or made it accessible via the menus).
