### ISSUE TITLE
Python Job Board converts "@" to "%40" in email addresses

### ISSUE THREAD

**Issue by anonymousAwesome** [python/pythondotorg#851]
If somebody gives their email as "test@abc.com" in their job posting, the mailto link generated is "mailto:test%40abc.com".  I don't know if %40 would work just as well as @, but I wouldn't want to chance it when there's a potential job offer riding on it.

**Comment by malemburg** [comment]
%40 does indeed correspond to @ - it's the URL encoded form, so that's perfectly correct.

**Comment by anonymousAwesome** [comment]
I just checked; neither Yahoo mail nor Gmail accept an email address in the form "test%40test.com"

**Comment by malemburg** [comment]
On 27.11.2015 15:22, Brendan Jones wrote:

> I just checked; neither Yahoo mail nor Gmail accept an email address in the form "test%40test.com"

No, but the link on the web page will work correctly.

Perhaps I'm not understanding what use case you think will
not work.

## 

Marc-Andre Lemburg
http://www.malemburg.com/
