### ISSUE TITLE
Update Brazilian local conference link and name

### ISSUE THREAD

**Issue by diegorocha** [python/pythondotorg#860]
In https://www.python.org/community/workshops/ there is a link to Brazilian Python Conference. But, the conferece name has changed, it's no longer PyConBrasil, in the last years it's was called "Python Brasil" (because of a local misunderstanding), and the correct site is http://pythonbrasil.org.br/ (it's redirect to the last or next edition).

Please, can someone fix it?

**Comment by berkerpeksag** [comment]
Done. Thanks for the report.
