### ISSUE TITLE
Python 3 download button at https://www.python.org/downloads/ doesn't work on Windows

### ISSUE THREAD

**Issue by brettcannon** [python/pythondotorg#863]
It just says "Download" and if you click the button it sends you to https://www.python.org/downloads/ instead of a download for Python 3.5.

**Comment by berkerpeksag** [comment]
It should be fixed now. Could you please try again? I've update the release info and tweaked the page to show Windows download button via Chrome devtools for test purposes since I'm on Linux.

**Comment by brettcannon** [comment]
It works, although it's linked to the exe installer instead of the msi (although i don't if it really matters, just the 2.7 installer is the msi).

**Comment by berkerpeksag** [comment]
There isn't also any MSI file for 3.5.0: https://www.python.org/downloads/release/python-350/ I'm a total Windows newbie, but it might be related to the new installer?

**Comment by malemburg** [comment]
FWIW: The 3.4.4rc1 release record did not have the "pre-release" checkbox set. Not sure whether this caused the problem, but I've set it now.

Python 3.5 no longer ships with MSI files. The installers are .exes.

**Comment by brettcannon** [comment]
I see my mistake: was mixing up the web installer with the msi. Either way I consider the problem fixed. Thanks!

**Comment by larryhastings** [comment]
I've also fixed the automation.  This problem shouldn't happen again... or at least until the next time we revamp the installers.
