### ISSUE TITLE
Too much horizontal space on mobile Safari

### ISSUE THREAD

**Issue by davisagli** [python/pythondotorg#866]
On mobile Safari the breadcrumbs force the viewport to be too wide. See one of the PEPs for an example.
![image](https://cloud.githubusercontent.com/assets/49014/11705688/993a861a-9ea6-11e5-9fd5-ca224a8752f4.png)

**Comment by berkerpeksag** [comment]
Thanks for the report. I think this is a duplicate of https://github.com/python/pythondotorg/issues/731. Could you confirm?

**Comment by davisagli** [comment]
It's not clear to me that it's a duplicate of 731. The problem doesn't occur for me on the homepage; only on pages with long breadcrumbs.

**Comment by davisagli** [comment]
Thanks!
