### ISSUE TITLE
Make very clear that windows XP is not supported  for 3.5 before people start downloading it

### ISSUE THREAD

**Issue by lac22** [python/pythondotorg#867]
https://www.python.org/downloads/  -- change to the Popup that says
Not the OS you are looking for? Python can be used on 21 different operating systems and environments. <View the full list>

This reads as if View the full list will give you a list of the 21 different operating systems, not
the full list of all python source dowloads you can get, which is what the link actually produces.

I suspect the '21' included windows XP and windows server 2003 and other things we no
longer support so the number is plain wrong.  But in any case, this would be a very good
place to say  that windows XP is not supported.

---

And here: https://www.python.org/downloads/windows/
we need an introductory paragraph saying that windows XP is not supported in 3.5 and
later.  3.4.3 is the latest version of  C python that windows XP users can run.

**Comment by crwilcox** [comment]
Could also add to https://docs.python.org/3/using/windows.html (cpython source under /docs)
EDIT: submitted a patch for this part to the cpython hg repo. http://bugs.python.org/issue25874

**Comment by brettcannon** [comment]
The "Notes on this release" section of the Python 3.5.1 release page can also start off by mentioning that Windows XP support was dropped.

**Comment by tjguk** [comment]
A warning now shows on the "supernav" popup box for downloads
