### ISSUE TITLE
Python version selector in Docs

### ISSUE THREAD

**Issue by vincentdavis** [python/pythondotorg#868]
From the documentation pages for python 2.7 and 3.4, 3.5, 3.6 it is possible to select another python version in the breadcrumb at the top left of the page (see screen shot). This is not available for python 2.6, 3.2 and  3.3 (see screenshot)

![screenshot_63](https://cloud.githubusercontent.com/assets/232564/12072098/a4e0727e-b08d-11e5-839c-9c84e2bdbc0f.png)

![screenshot_62](https://cloud.githubusercontent.com/assets/232564/12072099/ac8aff12-b08d-11e5-87a4-2a4bae7c4cc0.png)

**Comment by berkerpeksag** [comment]
Thanks for the report!

The version switcher is activated via a `versionswitcher` option in `Doc/Makefile` in CPython codebase. Docs are generated daily by using that Makefile, but 2.6, 3.2 and 3.3 are in security-fix-only mode (which means they won't even get documentation fixes) so the daily build script skips generating docs for those versions.

(Also, the correct place for reporting docs.python.org issues is https://bugs.python.org)
