### ISSUE TITLE
Last Updated Date on Documentation Page

### ISSUE THREAD

**Issue by bmweiner** [python/pythondotorg#869]
I'm not sure if this is a bug or intended behavior:

When visiting the Python 2.7.11 [documentation page](https://docs.python.org/2.7/) using Chrome 47.0.2526.106 m, the date after "last updated" will sometimes change between several dates when refreshing the page. For example, after refreshing the page three times, I might see the date change as follows:

```
Welcome! This is the documentation for Python 2.7.11, last updated Jan 03, 2016.
Welcome! This is the documentation for Python 2.7.11, last updated Dec 24, 2015.
Welcome! This is the documentation for Python 2.7.11, last updated Jan 01, 2016.
```

After refresh, the date will be the same, earlier, or later than the previous. I also tried clearing the browser history in case it was a caching issue. Is this a result of load balancing with inconsistent versions?

**Comment by berkerpeksag** [comment]
Thanks for the report. It's likely a cache/load balancing issue on our CDN provider and I don't know we can do much about it (see also https://github.com/python/psf-salt/issues/63) Also, docs.python.org is out of scope for this tracker :)
