### ISSUE TITLE
pypi has intermittent SSL problems

### ISSUE THREAD

**Issue by solomonty** [python/pythondotorg#870]
Attempts to download from pypi fail on an intermittent basis

 % wget  -S https://pypi.python.org/packages/source/a/awscli/awscli-1.9.7.tar.gz
--2016-01-08 21:21:35--  https://pypi.python.org/packages/source/a/awscli/awscli-1.9.7.tar.gz
Resolving pypi.python.org... 23.235.46.223
Connecting to pypi.python.org|23.235.46.223|:443... connected.
Unable to establish SSL connection.

**Comment by solomonty** [comment]
Error <urlopen error [Errno 104] Connection reset by peer> while getting https://pypi.python.org/packages/source/r/requests/requests-2.4.3.tar.gz#md5=02214b3a179e445545de4b7a98d3dd17 (from https://pypi.python.org/simple/requests/)

**Comment by berkerpeksag** [comment]
Thanks for the report, but this tracker is for issues with www.python.org only. PyPI is a separated project and its tracker is located at https://bitbucket.org/pypa/pypi/issues
