### ISSUE TITLE
devguide needs to mention github

### ISSUE THREAD

**Issue by evelynmitchell** [python/pythondotorg#872]
https://docs.python.org/devguide/
mentions hg,python.org

I poked around this repo, but couldn't find what generated 'devguide'.

**Comment by ned-deily** [comment]
How to help with the Developer's Guide documentation is documented in the devguide here: https://docs.python.org/devguide/docquality.html#helping-with-the-developer-s-guide

Does that answer your questIon?

**Comment by evelynmitchell** [comment]
Thanks ned-deily. Is the dev guide going to be moving  to github as well?

**Comment by ned-deily** [comment]
It will be available through GitHub.
