### ISSUE TITLE
Various broken links

### ISSUE THREAD

**Issue by ghost** [python/pythondotorg#880]
https://www.python.org/community/irc/
1. The link "python-pound.org" yields a server not found error, I couldn't find any info, it seems the site just went down
2. The link labelled "_IRCnet_" gives a server not found error, I don't know if its the same page, but it seems they may have moved to ircnet.org as opposed to ircnet.com
3. The link "Freenode.net is a project of the Peer-Directed Projects Center..." goes to http://freenode.net/pdpc.shtml which results in a 404, this is because "we were forced to dissolve PDPC, freenode’s parent organisation." detailed here: https://blog.freenode.net/2013/03/bye-bye-pdpc/

https://www.python.org/download/other/
1. Both links under the BeOS section 404 I suggest that these links be replaced by build instructions, such as a simplified version of https://github.com/python-git/python/blob/master/Misc/BeOS-NOTES

https://www.python.org/doc/av/
1. DjangoDose (audio) link results in an internal server error

In addition there are two other broken links described in #875 and #847

**Comment by tjguk** [comment]
Thanks; I've removed / fixed the issues on the irc page (which is CMS-based so easy).

**Comment by ghost** [comment]
Looks good, I'll take care of the other two when I have some time if no one else gets to them.

**Comment by theaverageguy** [comment]
On it.

**Comment by berkerpeksag** [comment]
BeOS port of Python doesn't have a maintainer since Python 2.5 days. I guess we can remove the BeOS section completely.

I've moved DjangoDose to "Inactive Podcast Repositories" in another issue.
