### ISSUE TITLE
Impossible to download, eg, 2.6

### ISSUE THREAD

**Issue by tjguk** [python/pythondotorg#882]
Someone contacted webmaster@ asking about downloading 2.6. I pointed him to https://www.python.org/ftp/python/ but:
- That URL doesn't appear to be referenced anywhere, as an ultimate fallback
- https://www.python.org/downloads/ shows several (!) flavours of 2.7 and 3.4+ but nothing earlier
- https://www.python.org/download/releases/ only shows 1.6 and earlier

AFAICT the releases on /downloads are managed via the "Releases" model. ISTM that we could fruitfully show the latest only of any given version (so 2.7.11, 3.4.4, 3.5.1). We might go back a version or two more (2.6, 3.3). From there we might as well link through to the "/ftp" URL above ("If you need a version not mentioned here...").

In fact, there are version-specific pages, eg, https://www.python.org/download/releases/2.6/ but I can't see an easy way to get to them without guessing the URL.

**Comment by ned-deily** [comment]
> https://www.python.org/downloads/ shows several (!) flavours of 2.7 and 3.4+ but nothing earlier

It does show earlier releases back to 2.0; you just have to scroll the list of releases within the box.

**Comment by tjguk** [comment]
Well that was embarrassing. Thanks, @ned-deily; I was obviously moving far too fast to spot that!

I think there is still a case for removing all but the most recent versions and linking to the FTP site for everything else. But I don't feel strongly about it. Assuming that no-one chimes in in the next day or so, I'm happy to close this as nothing-to-do.

**Comment by berkerpeksag** [comment]
I agree that the current listing is a bit hard to use. We could group releases or only show the latest release of 3.x.y in https://www.python.org/downloads/

**Comment by tjguk** [comment]
@berkerpeksag presumably "the latest release of 3.x" -- 3.x.y is what we currently have.

**Comment by berkerpeksag** [comment]
@tjguk yes, good catch, thanks :)

**Comment by hugovk** [comment]
Seems no-one felt strongly enough to do anything about this in eight years, so let's close this (we can always re-open if someone is motivated to update it :)
