### ISSUE TITLE
Display issues with event search results

### ISSUE THREAD

**Issue by donaladams** [python/pythondotorg#883]
Currently when I search for events on python.org (from https://www.python.org/events/), the rendered page has a number of display issues (https://www.python.org/search/?q=london&submit=).

Below ~800px, the yellow element (CSS class .single-event-date) which should show some date information, is just displaying the nonsensical string "From at through at ,". Here's a screenshot from mobile safari:

![mobile_safari_pyorg](https://cloud.githubusercontent.com/assets/1864489/12797021/e88d3a52-cab9-11e5-86fc-563c89683b6e.jpg)

Above ~800px, the elements of the text mentioned above are stacked on top of each other (.single-event-date > .date-start and .single-event-date > .date-end). Here's a screenshot from Chrome on Mac OS X:

![pyorg](https://cloud.githubusercontent.com/assets/1864489/12796759/5bfa94b4-cab8-11e5-971a-fe61cfac4b89.jpg)

**Comment by donaladams** [comment]
Just to add - the links to the events pages are also incorrect. For example, clicking on "The London Python Meetup" in the above screenshots links to the incorrect url `https://events/python-user-group/238/`as opposed to the correct url `https://www.python.org/events/python-user-group/238/`

**Comment by berkerpeksag** [comment]
Thank you for your analysis. This was also reported in https://github.com/python/pythondotorg/issues/924.

**Comment by CianciuStyles** [comment]
Hello! I'd like to take care of this bug but, after managing to make the codebase work (not without problems, but this could be added as an issue on its own), every time I try to search an event, the resulting page ends up empty (even if there are some valid events in the Events page). Any tips on how to solve this problem, which would allow me to test when the bug is fixed?

**Comment by berkerpeksag** [comment]
Thanks for working on this @CianciuStyles.

We are using Haystack and Elasticsearch so you need to 1) setup an Elasticsearch instance on your machine 2) update the HAYSTACK_CONNECTIONS setting in pydotorg/settings/local.py to use it

Please let me know if you have more questions, thanks!

**Comment by Mariatta** [comment]
@berkerpeksag Can information about setting up haystack or elasticsearch be added to the docs? https://pythondotorg.readthedocs.io/contributing.html

**Comment by berkerpeksag** [comment]
I think there is (or there was) a note somewhere in install.rst, but if there isn't, it would be nice to have a short note about installing Elasticsearch and updating the HAYSTACK_CONNECTIONS setting (we should probably say that it's an optional step so contributors can ignore it if they want to work different parts of the site)
