### ISSUE TITLE
Make http://docs.python.org/tut/ point to the Python 3 version?

### ISSUE THREAD

**Issue by The-Compiler** [python/pythondotorg#884]
From what I'm seeing, it seems to be the general consensus to recommend new Python programmers to start with Python 3, rather than 2.

However, http://docs.python.org/tut/ (which is e.g. linked from the topic in the `#python` IRC channel) still points to the Python 2 version of the tutorial. Wouldn't it make more sense for it to point to the Python 3 version?

**Comment by berkerpeksag** [comment]
Thanks for the report. I've opened https://github.com/python/psf-salt/pull/79 to redirect it to the Python 3 tutorial.

**Comment by The-Compiler** [comment]
Awesome, thank you!
