### ISSUE TITLE
python.org/dev/committers redirection missing

### ISSUE THREAD

**Issue by kamyar** [python/pythondotorg#888]
I was linked to [python.org/dev/committers](https://www.python.org/dev/committers) while visiting [http://pythonmentors.com/](http://pythonmentors.com/) and it is missing(Error 404).
It seems the [legacy path](http://legacy.python.org/dev/committers) was redirecting to https://hg.python.org/committers.txt

**Comment by berkerpeksag** [comment]
Thanks for the report. I've added a redirect for /dev/committers/ to the hg.p.o link.
