### ISSUE TITLE
freetype v1/2 install problem 

### ISSUE THREAD

**Issue by CarlFK** [python/pythondotorg#891]
https://pythondotorg.readthedocs.org/install.html#freetype-not-found-on-osx

This occurs on Ubuntu Wily too.  

sudo apt-get build-dep python-pil
cd /usr/include
sudo ln -s freetype2 freetype
cd -
pip install Pillow==2.0.0

pip install -r requirements.txt

**Comment by berkerpeksag** [comment]
@CarlFK would you lite to update the docs? I'm still using 12.04 so I couldn't reproduce it :)

**Comment by berkerpeksag** [comment]
I'm unable to reproduce this in Ubuntu 16.04.1.
