### ISSUE TITLE
Calendar entries don't receive updates from Google calendars

### ISSUE THREAD

**Issue by malemburg** [python/pythondotorg#892]
Example:

I recently (Feb 21, 2016) fixed the description of this entry:

https://calendar.google.com/calendar/event?eid=bmszNzM4bHY0bHZlMDhsYjI5amc1dGthMW8gajdnb3YxY21ucXI5dHZnMTRrNjIxajd0NWNAZw&ctz=Etc/GMT

to point to a new URL (https://tw.pycon.org/2016/en-us/), but the corresponding entry on python.org still points to the previous one (http://pycontw.blogspot.tw/2015/10/pycontw2016-coming.html):

https://www.python.org/events/python-events/371/

This causes complaints from people who submit their events and then want the entries updated.

**Comment by berkerpeksag** [comment]
https://github.com/python/pythondotorg/pull/919 should fix this.

**Comment by berkerpeksag** [comment]
By the way, because of https://github.com/python/pythondotorg/blob/master/events/importer.py#L57, ICSImporter will create a new location entry if the LOCATION field has changed in the ICS document.

**Comment by malemburg** [comment]
Thanks, Berker, but the above entry has not updated itself. Is there anything I need to do to make this happen ?

**Comment by malemburg** [comment]
Ok, the PR wasn't merged yet.

**Comment by malemburg** [comment]
For some reason the release PR is taking ages to pass the Github merge check: https://github.com/python/pythondotorg/pull/921

**Comment by berkerpeksag** [comment]
For the record, staging https://staging.python.org/events/python-events/371/ now uses the new URL (https://tw.pycon.org/2016/en-us/).

**Comment by malemburg** [comment]
The merge worked today, so let's see whether this also fixes the production entry. If so, I'd be a happy bunny, and several calendar users as well :-) Thanks, again, Berker, for working on this.

**Comment by malemburg** [comment]
Nice: the production site has picked up the modification of the URL as well.

**Comment by berkerpeksag** [comment]
Great! I'll take a look at https://github.com/python/pythondotorg/issues/560 (and others) hopefully this week.
