### ISSUE TITLE
typo in tutorial

### ISSUE THREAD

**Issue by tmotr** [python/pythondotorg#896]
https://docs.python.org/3/tutorial/controlflow.html#keyword-arguments

the token 'type' cannot be used as a function argument, 'type' is a reserved word.
consider "species='Norwegian Blue'"

**Comment by joncle** [comment]
@tmotr It's not a reserved word - it's a builtin function which one can shadow - so while the example is perfectly valid, it's probably best for the official documentation to not suggest that naming. In that sense `species` might well make more sense.

**Comment by tmotr** [comment]
oh! thank you. i had no idea. thank you so much.

Sage Antonia Collins
