### ISSUE TITLE
trouble with https://www.python.org/download/releases/2.7/

### ISSUE THREAD

**Issue by dmerejkowsky** [python/pythondotorg#897]
Two things
- The text still mentions Python 2.7.10 as the latest bug fix release
- The download links all point to 2.7.0 (and since the file names contains 2.7, it's easy to be mistaken and think you are downloading the latest release ...)

**Comment by ned-deily** [comment]
Thanks for the report.  The convention of referring to the initial release of a new Python version as the **.0** release was introduced in releases more recent than 2.7 primarily to avoid ambiguities like this.  I have updated the 2.7 release page to refer to the release as 2.7.0 and to link to 2.7.11 for the latest bug fix release.

**Comment by dmerejkowsky** [comment]
That was fast. Thanks :)
