### ISSUE TITLE
Podcast list out of date

### ISSUE THREAD

**Issue by melinath** [python/pythondotorg#899]
On https://www.python.org/doc/av/, under "Podcast Repositories"

The links for the following podcasts go to inactive / missing websites:
- A Little Bit of Python
- Python411
- Djangodose
  *Jython Monthly
- PyCon Podcast

Additionally, the following podcasts are missing:
- [Talk Python To Me](talkpython.fm)
- [podcast.__init__](podcastinit.com)

**Comment by berkerpeksag** [comment]
Thanks for the report, @melinath!

I've moved the inactive podcasts to "Inactive Podcast Repositories" section and added your suggestions to the list.
