### ISSUE TITLE
Identify key problems with community involvement

### ISSUE THREAD

**Issue by techtonik** [python/pythondotorg#902]
I don't know statistics about site visits (#901), but a https://github.com/python/pythondotorg/graphs/contributors shows almost a staggering lack of new people contributing to the project.

![image](https://cloud.githubusercontent.com/assets/515889/13905957/96a1aab8-eede-11e5-8883-4fe9bf5eb11d.png)

**Comment by berkerpeksag** [comment]
Duplicate of https://github.com/python/pythondotorg/issues/534.

**Comment by techtonik** [comment]
Oops. I am surprised to see this is a duplicate.

**Comment by techtonik** [comment]
@berkerpeksag #534 was just closed, so should we forget about problem?
