### ISSUE TITLE
Make postresql stuff optional

### ISSUE THREAD

**Issue by techtonik** [python/pythondotorg#903]
There is a decline in amount of contributors to this project. I can't say what are the main reasons exactly (#902), but for me (I am on Windows machine with 3Gb of system memory) Vagrant box is a very slow option and setting up PostgreSQL is a major overkill - for example pip doesn't install bindings.

So, is it possible to run the site on different backend for development? I think that Django should be independent of database.

**Comment by berkerpeksag** [comment]
Two things:
- The jobs app doesn't work with the sqlite backend (it's uses some PostgreSQL specific features)
- We want to use the same database configuration in development to avoid possible regressions
