### ISSUE TITLE
uWSGI is not referenced in project anywhere

### ISSUE THREAD

**Issue by techtonik** [python/pythondotorg#904]
`uWSGI==2.0.10` from requirements.txt - where it is used?

**Comment by benjaminp** [comment]
That's how it's deployed in production.

**Comment by techtonik** [comment]
@benjaminp and where are deployment scripts?

**Comment by benjaminp** [comment]
python/psf-salt

**Comment by techtonik** [comment]
So it should move there then.

**Comment by berkerpeksag** [comment]
python/psf-salt uses https://github.com/python/pythondotorg/blob/master/requirements.txt to deploy the site in production. There's no need to make uwsgi a special case (it's also useful for testing production configurations on a VM).

**Comment by techtonik** [comment]
@berkerpeksag and where is the instruction how to run production version of python.org on local machine?
