### ISSUE TITLE
Not compatible with Python 3.5

### ISSUE THREAD

**Issue by techtonik** [python/pythondotorg#906]
Attempting to run with Python 3.5 gives:

```
AttributeError: module 'html.parser' has no attribute 'HTMLParseError'
```

https://stackoverflow.com/questions/34827566/attributeerror-module-html-parser-has-no-attribute-htmlparseerror

The solution is upgrade Django to 1.8+ once [staging2](https://github.com/python/pythondotorg/branches) branch is fixed and merged back or rebased.

**Comment by malemburg** [comment]
Anatoly, please stop opening tickets for feature requests. You are using up time of our volunteer contributors, with no real benefit for anyone.
