### ISSUE TITLE
Documented specific application requirements

### ISSUE THREAD

**Issue by techtonik** [python/pythondotorg#907]
From https://github.com/python/pythondotorg/issues/903#issuecomment-199224793 it is clear that the web site is not a standard Django application - it requires some PostgreSQL specific features, there is a requirement to have Ruby installed, deployment is done through some complicated mechanism.

In ideal world this is documented with a diagram. Maybe there are GSoC students with steAm background that can take the task?..

**Comment by berkerpeksag** [comment]
python.org is a standard Django application. Any non-trivial Django application will require some database specific features at some point. https://pythondotorg.readthedocs.org/install.html#manual-setup already states that you'll need Ruby, gem and some Ruby packages for frontend development. Deployment is an automated and pretty straightforward process. All production settings are in the psf-salt repo (which is also stated at https://pythondotorg.readthedocs.org/index.html).

**Comment by techtonik** [comment]
@berkerpeksag and how to use that psf-salt?

**Comment by berkerpeksag** [comment]
Why do you want to use it? You don't need know how to use Salt to contribute to python.org. Documentation for psf-salt can be found in that repository.

**Comment by techtonik** [comment]
I want to ensure that my development environment doesn't miss anything from production version.
