### ISSUE TITLE
staging2 navigation on the left

### ISSUE THREAD

**Issue by techtonik** [python/pythondotorg#908]
@frankwiles I just saw https://staging2.python.org/ and it looks cool. Is it possible to move navigation to the right? I suspect most people are right-handed, so when they have to touch navigation, their right arm need to move across the screen and shroud it.

**Comment by malemburg** [comment]
Anatoly, please stop opening tickets for feature requests. You are using up time of our volunteer contributors, with no real benefit for anyone.
