### ISSUE TITLE
Python 2.7.11 - Py_Initialize() => ImportError: No module named site

### ISSUE THREAD

**Issue by dadomani** [python/pythondotorg#909]
Calling Py_Initialize() from a *.cpp code under Visual Studio 2010 the execution will
reports a runtime error:

ImportError: No module named site

Using 2.7.10 everything works fine

```
#ifdef _DEBUG
  #undef _DEBUG
  #include <Python.h>
  #define _DEBUG
#else
  #include <Python.h>
#endif

int main(int argc, char* argv[])
{
    printf("a\n");
    Py_SetProgramName(argv[0]);

    printf("b\n");
    Py_Initialize();

    printf("c\n");
    Py_Finalize();

    printf("d\n");
    return 0;
}

```

OUTPUT IS:
a
b
ImportError: No module named site
Press any key to continue . . .

**Comment by berkerpeksag** [comment]
This tracker is for issues with www.python.org only. Please ask your question on StackOverflow or a similar forum.

**Comment by techtonik** [comment]
@berkerpeksag how about a "wrong tracker" label to estimate how big the problem is?
