### ISSUE TITLE
Guido's essays (http://www.python.org/doc/essays/) do not render correctly

### ISSUE THREAD

**Issue by Yhg1s** [python/pythondotorg#91]
Guido's essays, listed in http://www.python.org/doc/essays/ and linked from the main doc page, do not render correctly: individual essays are HTML but are rendered as text: http://www.python.org/doc/essays/graphs/ for example.

**Comment by fcurella** [comment]
I've fixed these form the admin. They aren't in any fixture, so the fix should stick.
