### ISSUE TITLE
What apps require specific PostgreSQL features and why

### ISSUE THREAD

**Issue by techtonik** [python/pythondotorg#911]
Reticketed from #907. I think that it is important to explain people things that they can not figure out themselves (see #910). The thing that I can not figure out (and find appropriate code pieces) is where PostreSQL features are required and why.

**Comment by berkerpeksag** [comment]
Like I said before, it's the jobs app that uses PostgreSQL specific features. You can see it by changing the database setting to use SQLite and opening `/jobs/` URL in your browser.
