### ISSUE TITLE
Python Community - Merchandise - Broken Thumbnails

### ISSUE THREAD

**Issue by ghost** [python/pythondotorg#915]
On the Python Community - [Merchandise](https://www.python.org/community/merchandise/) page, there are broken thumbnails for the following images:

freewear-logo.png
freewear-1.png
pythongear-logo.png

**Comment by berkerpeksag** [comment]
Looks like all three images are available at legacy.python.org (for example http://legacy.python.org/community/merchandise/freewear-1.png). @jfleach would you like to send a PR to move them into `static/images/`?

**Comment by ghost** [comment]
A [pull request](https://github.com/python/pythondotorg/pull/917) was submitted for this issue.

**Comment by berkerpeksag** [comment]
https://www.python.org/community/merchandise/ works fine now. Thanks again!
