### ISSUE TITLE
Consider removing user listing page

### ISSUE THREAD

**Issue by berkerpeksag** [python/pythondotorg#916]
Is there a use case to keep https://www.python.org/users/ ? It basically dumps all user information without filtering ability. Perhaps we can add a view to return total member and PSF member counts in JSON format and then use it at https://www.python.org/users/membership/ (e.g. we have 72.000 PSF members).

**Comment by malemburg** [comment]
I'm not sure whether removing the listing is really wanted by the users. In it's current state, the listing pretty useless (except for Google et al.), so adding a few filters would be nice, but people do have the option to edit these profile pages and also make them invisible, so those pages are a feature of the website.

+1 on adding a statistics page with total number of registered users and total number of PSF members registered.

**Comment by berkerpeksag** [comment]
Since the consensus was to keep the page, I've just fixed #943 and decided to close this as 'wontfix'.
