### ISSUE TITLE
Upgrade feedparser to 5.2

### ISSUE THREAD

**Issue by berkerpeksag** [python/pythondotorg#918]
From requirements.txt:

```
git+https://code.google.com/p/feedparser/@dc3bd29bfc1b#egg=feedparser
```

Changelog is here: https://github.com/kurtmckee/feedparser/blob/develop/NEWS

**Comment by aliev** [comment]
@berkerpeksag 
Ups sorry, I've missed this issue. Should I upgrade feedparser also in requirements?

**Comment by berkerpeksag** [comment]
Hi @aliev, thank you for your interest! This needs a little bit more work than just updating requirements.txt. We need to make sure that feedparser 5.2 doesn't cause any regressions (and we need to add more tests if needed).

Please let me know if you have any question.

**Comment by aliev** [comment]
@berkerpeksag thanks! I do not think that there is a lot of work. I will test locally

**Comment by aliev** [comment]
@berkerpeksag looks like all tests has been passed https://github.com/python/pythondotorg/pull/942

**Comment by berkerpeksag** [comment]
Current tests are probably not that important as we don't have good test coverage in that area. We need to check feedparser 5.2 changelog and manually test it.

**Comment by aliev** [comment]
@berkerpeksag I see! In this case, give me a little more time for writing tests. I try to install the fixtures and it seems it will take more time than I expected :)

**Comment by aliev** [comment]
Hi, @berkerpeksag ! Could you help me with testing new feedparser? maybe you have some idea of testing process?

**Comment by berkerpeksag** [comment]
Of course, but it might take a while as I will be traveling in the next few days.

**Comment by aliev** [comment]
@berkerpeksag thanks! please let me know :)

**Comment by berkerpeksag** [comment]
Thanks @aliev!

**Comment by aliev** [comment]
@berkerpeksag thanks u too! :)
