### ISSUE TITLE
Switch to django-restframework

### ISSUE THREAD

**Issue by berkerpeksag** [python/pythondotorg#922]
We need to upgrade tastypie before upgrade Django to 1.8 first. Instead of upgrading, I'd prefer switch to django-restframework since its API is simpler, more stable and currently maintained by its original author.

**Blockers**

- [x] PR #1123 - Increase test coverage of the API: https://github.com/python/pythondotorg/blob/master/downloads/tests/test_views.py#L52

**Comment by auvipy** [comment]
i think it's a very good decision.

**Comment by auvipy** [comment]
any way I can help?

**Comment by berkerpeksag** [comment]
Hey @auvipy, this is a pretty low priority at the moment, but if you'd like work on it I'd suggest to write tests for the existing API first. We already have a few tests at https://github.com/python/pythondotorg/blob/master/downloads/tests/test_views.py#L52 so increasing test coverage would be great (we can also move those tests to `test_api.py`).

In case you want to play with it, the primary user of the API is https://hg.python.org/release/file/tip/add-to-pydotorg.py.

**Comment by auvipy** [comment]
OK :)
