### ISSUE TITLE
Please drop leading zeros from PEP numbers

### ISSUE THREAD

**Issue by gvanrossum** [python/pythondotorg#923]
The title of e.g. PEP 8 is shown as PEP 0008: https://www.python.org/dev/peps/pep-0008/ While it's correct to have the leading zeros in the URLs, they should not appear in the title. The PEP is commonly known as "PEP 8", not "PEP 0008". (I see the latter pop up occasionally, probably because the website shows it that way, but it's really ugly and unnecessary.)

**Comment by berkerpeksag** [comment]
The fix was easy. I just tested it in my dev environment. I will try to write a test case and deploy it.

**Comment by berkerpeksag** [comment]
The staging site works fine: https://staging.python.org/dev/peps/pep-0008/

**Comment by gvanrossum** [comment]
Thanks Berker!!

--Guido (mobile)
