### ISSUE TITLE
search results style problem(eg:india in search bar)

### ISSUE THREAD

**Issue by sabareeshkk** [python/pythondotorg#924]
when i do a search in the site the result it shows has broken styles
![screenshot from 2016-04-07 11 26 21](https://cloud.githubusercontent.com/assets/6927891/14341987/f4b011f2-fcb3-11e5-9ec6-74f3142184d6.png). am attached the screen shot with this issue.

**Comment by berkerpeksag** [comment]
Thanks for the report. This is a duplicate of https://github.com/python/pythondotorg/issues/883.
