### ISSUE TITLE
Save profile shows Error 404: File not Foud

### ISSUE THREAD

**Issue by ghost** [python/pythondotorg#925]
Navigate to User account -> Edit your user profile; then fill out all fields and choose "Don't allow search engines to index my profile page", "Only logged-in users can see my e-mail address" and do not check "Make my profile public". The information will be saved, but you will be redirect to an Error 404 page.

**Comment by berkerpeksag** [comment]
Thanks for the report. Good catch! Will fix this today.

**Comment by berkerpeksag** [comment]
I just pushed a fix. It would be great if you could test it on https://staging.python.org (it should be online in an hour or so).

Thanks again! :)

**Comment by ghost** [comment]
Tested on https://staging.python.org and everything is working fine. Good job!
