### ISSUE TITLE
Getting wiki editing rights is counterintuitive and confusing

### ISSUE THREAD

**Issue by native-api** [python/pythondotorg#926]
Here's the situation as I've just seen it as a regular contributor:
- Tried to fix a factual error on https://wiki.python.org/moin/WindowsCompilers
- There's no editing link and the page is marked "ImmutablePage". Okay, maybe a registration is required to edit anything. Many wikis do that (in fact, virtually all of them except Wikipedia).
- Registered, logged in - the page is still marked as ImmutablePage. Shucks, looks like I just can't - it must be protected to be editable only by mods or something. Given the critical value of instructions on it, this is quite possible.
- Created [an issue in the bug tracker](http://bugs.python.org/issue26768) - what else? Only [to learn from a more experienced user](http://bugs.python.org/issue26768) that normal users _are_ supposed to be able to edit the page but there's an [unusual requirement](https://wiki.python.org/moin/FrontPage#Editing_pages). Of course, it's documented somewhere. But I need to know beforehand that it's even _possible_ for there to be something to go looking for it.

So, here are the problems:
- Requiring anything except registration to edit _regular pages_ is extremely counterintuitive and unexpected. It's the _entire point_ of wikis that after registering at most, I'm considered a full-fledged regular user and can edit (regular) pages right away. There _can't_ be anything else besides additional privileges required to edit _some,_ more "important" pages - or it's not a wiki and thus can't bear that brand name.
- If registration doesn't grant any rights, there's no point in it, why is it even there? It's confusing because it _looks_ like it's granting me everything I need while it actually isn't.
  - If you wish to approve every user manually, restrict registration itself instead (and include relevant fields into registration form if you require additional information for the approval).
- If I can't edit a page, I can't see why (and, consequently, if it's possible to fix that).

**Comment by native-api** [comment]
I suggested to restrict registration rather than inform users why they can't edit because it looks simpler to implement. The ImmutablePage stuff without any hints is a part of the wiki engine and thus can't be changed easily.

**Comment by malemburg** [comment]
All wiki pages have a link at the bottom explaining how to get edit permissions:

"Unable to edit the page? See the FrontPage for instructions."

Perhaps we ought to some note to the signup page as well.

**Comment by native-api** [comment]
Never looked there. As I said, I never expected there to be anything not already built into the engine and standard procedures (and do assert there should never be - as a user, I visit hundreds of sites and can't be bothered to learn all the little quirks of each one before I'm willing to invest significant time into it. Standard procedures are called "standard" for a reason).

**Comment by smontanaro** [comment]
If you've no history with the Python wiki, perhaps a bit of explanation is in order. When first created, it worked like just about every other wiki I've ever seen. Anyone could edit any page. That is, I believe, "standard practice" in the wiki world. (It certainly was back in a simpler time.) Eventually, spammers started scribbling on many key pages (those which, like FrontPage, appeared highest and most frequently in Google searches). By "scribble," I actually mean "completely replace useful page contents with their crap." A bunch of us BITD subscribed to all change notifications precisely so we could jump in and revert spammy changes. When dealing with this manually became too big of a problem, we started requiring people to login to edit, at least for those key pages. That restriction may have been extended to the rest of the wiki. I've been away for quite awhile, and only glance at things now. Note that this change was not taken lightly.

I don't recall enough about the wiki to remember if there's an easy way to add the edit message anywhere other than in the page footer. Like I said, it's been awhile. If you know of a way to easily move that message up near the menu where it would be easier to find (bonus points if it only appears when the page is market immutable), please submit a patch.

**Comment by native-api** [comment]
I have read https://wiki.python.org/moin/FrontPage#Editing_pages after being pointed to it so I do understand this kludge was introduced to confound the bad guys, and you probably didn't have time or will to invent anything elaborate. The only problem is, this succeeded _too much,_ confounding the good guys, too.

Hearing that you admit this to not be an ideal solution and are open to change, I consider my job here as a reporter done.

**Comment by native-api** [comment]
Now, is the registration code and wiki engine used by the site here in the Github project or somewhere else? E.g. I can't find UI messages in the code base.

**Comment by malemburg** [comment]
On 15.04.2016 17:36, native-api wrote:

> I have read https://wiki.python.org/moin/FrontPage#Editing_pages after being pointed to it so I do understand this kludge was introduced to confound the bad guys, and you probably didn't have time or will to invent anything elaborate. The only problem is, this succeeded _too much,_ confounding the good guys, too.

Maybe some of the good guys, but certainly not all, since we're
getting regular requests for editing permissions to the pydotorg-www
mailing lists.

Overall, we're quite happy with the current situation, but improvements
are welcome, of course.

## 

Marc-Andre Lemburg
http://www.malemburg.com/

**Comment by malemburg** [comment]
On 15.04.2016 17:48, native-api wrote:

> Now, is the registration and wiki engine used by the site here in the Github project or somewhere else? E.g. I can't find UI messages in the code base.

The wiki engine is a standard moin instance. The config is not checked
in to this repo (which is for the python.org site), nor anywhere
else, so if you would like to help, it would be great if you could
find the right places in a standard config to improve things.

This is the repo for moin: http://hg.moinmo.in/moin/1.9/

## Thanks,

Marc-Andre Lemburg
http://www.malemburg.com/

**Comment by malemburg** [comment]
Since there was no further movement on this ticket, I'm closing it.
