### ISSUE TITLE
Broken links in essays/list2str/

### ISSUE THREAD

**Issue by scop** [python/pythondotorg#927]
https://www.python.org/doc/essays/list2str/

The two sample code links at the bottom of the page are broken:

``` html
<LI><A HREF="f.py">timing f1() through f7()</A>
<LI><A HREF="g.py">timing g1() and g2()</A>
```

**Comment by berkerpeksag** [comment]
Thanks! For reference, the files are available in legacy site:
- http://legacy.python.org/doc/essays/list2str/f.py
- http://legacy.python.org/doc/essays/list2str/g.py

**Comment by berkerpeksag** [comment]
Fixed.

**Comment by scop** [comment]
Cool. I'd suggest sending them as `text/plain` instead of `application/octet-stream` though.

**Comment by berkerpeksag** [comment]
Could you please open a new issue for that (I couldn't find a quick way to serve them as text/plain)?
