### ISSUE TITLE
Cannot Donwload Older Versions

### ISSUE THREAD

**Issue by jweaver0312** [python/pythondotorg#929]
I have attempted to download older versions of python and when I hit download, it goes to its release page without any download info. The only versions it lets me download are 3.5.1 and 2.7.11.

**Comment by ned-deily** [comment]
If you click on the Downloads tab and then All Releases, you should see a list of many Python releases and Download links for them. The shortcut: https://www.python.org/downloads/

**Comment by jweaver0312** [comment]
That's what I've been trying. It's not letting me download versions other than 2.7.11 and 3.5.1.

On Apr 16, 2016, at 9:51 PM, Ned Deily <notifications@github.com<mailto:notifications@github.com>> wrote:

Closed #929https://github.com/python/pythondotorg/issues/929.

##

**Comment by ned-deily** [comment]
Use the Download links in the list of releases, not the two buttons at the top of the page.

**Comment by jweaver0312** [comment]
That's what I did and it brought me to the release page.

On Apr 16, 2016, at 9:54 PM, Ned Deily <notifications@github.com<mailto:notifications@github.com>> wrote:

Use the Download links in the list of releases, not the two buttons at the top of the page.

##

**Comment by ned-deily** [comment]
Scroll down the release page and there should be a list of links for all of the artifacts associated with that release.  (What release are you trying to download?)

**Comment by jweaver0312** [comment]
I was trying to download 3.3.6 and tested with other versions that are not 3.5.1 nor 2.7.11.

On Apr 16, 2016, at 9:56 PM, Ned Deily <notifications@github.com<mailto:notifications@github.com>> wrote:

Scroll down the release page and there should be a list of links for all of the artifacts associated with that release. (What release are you trying to download?)

##

**Comment by ned-deily** [comment]
Python 3.3 is now in security-fix-mode only which means that it only receives security fixes and that only source tarballs are provided for it, i.e. no Windows or OS X binary installers.  So, if you are looking for a binary installer, there are none here.  You might be able to find one from a third-party distributor.

**Comment by jweaver0312** [comment]
What about Python 3.2?

On Apr 16, 2016, at 10:01 PM, Ned Deily <notifications@github.com<mailto:notifications@github.com>> wrote:

Python 3.3 is now in security-fix-mode only which means that it only receives security fixes and that only source tarballs are provided for it, i.e. no Windows or OS X binary installers. So, if you are looking for a binary installer, there are none here. You might be able to find one from a third-party distributor.

##

**Comment by ned-deily** [comment]
3.2 is also in security-fix only mode and is weeks away from moving to end-of-life (retired) status.  The last release for which binary installers was available is 3.2.5 (https://www.python.org/download/releases/3.2.5/); there is a newer 3.2.6 source-only release (https://www.python.org/downloads/release/python-326/).   The last release of 3.3.x for which there were binary installers was 3.3.5 (https://www.python.org/download/releases/3.3.5/).

It might help if you could say what you are trying to do on what platform.

**Comment by jweaver0312** [comment]
Which versions are and which ones aren't in security fix only mode?

On Apr 16, 2016, at 10:07 PM, Ned Deily <notifications@github.com<mailto:notifications@github.com>> wrote:

3.2 is also in security-fix only mode and is weeks away from moving to end-of-life (retired) status. The last release for which binary installers was available is 3.2.5 (https://www.python.org/download/releases/3.2.5/); there is a newer 3.2.6 source-only release (https://www.python.org/downloads/release/python-326/). The last release of 3.3.x for which there were binary installers was 3.3.5 (https://www.python.org/download/releases/3.3.5/).

It might help if you could say what you are trying to do on what platform.

##

**Comment by ned-deily** [comment]
3.5.x and 2.7.x.  See https://docs.python.org/devguide/#status-of-python-branches

**Comment by jweaver0312** [comment]
Which ones have binary installers?

On Apr 16, 2016, at 10:09 PM, Ned Deily <notifications@github.com<mailto:notifications@github.com>> wrote:

3.5.x and 2.7.x. See https://docs.python.org/devguide/#status-of-python-branches

##

**Comment by ned-deily** [comment]
If you check the release pages, you'll see that only those in "bugfix" status do; "security" only branches do not have binary installers.

**Comment by jweaver0312** [comment]
Another question, how would I update 3.3.5 to 3.3.6?

On Apr 16, 2016, at 10:12 PM, Ned Deily <notifications@github.com<mailto:notifications@github.com>> wrote:

If you check the release pages, you'll see that only those in "bugfix" status do; "security" only branches do not have binary installers.

##

**Comment by ned-deily** [comment]
Sorry, this is not a help forum.  You can either download the source tarball for 3.3.6 and use it or download the development Mercurial repo and update to the "v3.3.6" tag.  The developer's guide has more information: https://docs.python.org/devguide/#quick-start.  And you can ask on one of the help forums: https://docs.python.org/devguide/#quick-start.  Good luck!
