### ISSUE TITLE
Blog Time/Date is not styled correctly

### ISSUE THREAD

**Issue by andy-partington** [python/pythondotorg#93]
http://www.python.org/blogs/

Date on the left hand side under Python Insider is underneath the text 

<p class="date-posted"><time datetime="2013-03-04 15:00|06">Monday, March 4, 2013</time></p>

**Comment by hjwp** [comment]
![python_dot_org_blog_date_styling_screenshot](https://f.cloud.github.com/assets/769730/2218346/0a7dcd94-9a2d-11e3-910f-dbf66622b321.PNG)

**Comment by frankwiles** [comment]
Duplicate, closing
