### ISSUE TITLE
DIRECTORY LISTING

### ISSUE THREAD

**Issue by rootabhi1** [python/pythondotorg#930]
Directory Listing in https://mail.python.org.  Sensitive Website Files are downloaded from this url

Here is P.O.C.
1-https://mail.python.org/pipermail

2-https://mail.python.org/pipermail/cryptography-dev/
![capture1](https://cloud.githubusercontent.com/assets/18510535/14585686/d3661f48-049a-11e6-8876-b8e0a6692f28.JPG)
![capture2](https://cloud.githubusercontent.com/assets/18510535/14585689/dd821cde-049a-11e6-9d4f-193aa6eaba42.JPG)

**Comment by smontanaro** [comment]
Can you describe which files you believe to be sensitive? The example you
highlight, the cryptography-dev mailing list, is a public list, with public
archives. Popping up a level to the /pipermail directory, just lists the
archives of the other public mailing lists.

If you think there any private mailing list archives are exposed, please be
specific.

**Comment by rootabhi1** [comment]
Sir i have attached a .txt file with this 
is this for client end, this text file contains some confidential messgaes which are supposed not to be for end user
[2016-April.txt.gz](https://github.com/python/pythondotorg/files/223220/2016-April.txt.gz)
[Uploading 2016-April.txt…]()

**Comment by rootabhi1** [comment]
if thiis directory listing is not fir end user so,why you disclosed this link
https://mail.python.org/pipermail/
![capture](https://cloud.githubusercontent.com/assets/18510535/14596362/97716cee-0563-11e6-83c2-3cb63be82f0f.JPG)
![capture2](https://cloud.githubusercontent.com/assets/18510535/14596372/a95c456e-0563-11e6-891e-2f8faa7f0352.JPG)

**Comment by malemburg** [comment]
What you are seeing are the public archives of the mailing lists we host on python.org. There's nothing secret here. The 404 you are seeing for the slash-less version of https://mail.python.org/pipermail is just a harmless config error.

Thanks for your report, but this is not a vulnerability on our site.
