### ISSUE TITLE
Instructions at "https://www.python.org/psf/contrib/" are incomplete

### ISSUE THREAD

**Issue by gvanrossum** [python/pythondotorg#931]
The section "Submission instructions" says "We currently accept contributor forms through postal mail, fax, or by email." even though in fact the preferred approach is to use the online form (https://www.python.org/psf/contrib/contrib-form/) linked from the text at the top of the page. Repeating the link here would be helpful for the casual visitor of this page.

**Comment by ned-deily** [comment]
Thanks for the suggestion.  I've modified the "Submission Instructions" section to include a link to the online form in the first paragraph and moved the other methods to a second paragraph.

**Comment by gvanrossum** [comment]
Thanks!
