### ISSUE TITLE
filter docs unclear wording

### ISSUE THREAD

**Issue by unfamiliarplace** [python/pythondotorg#934]
The current docs for both filter and itertools.filterfalse use the following wording (emphasis added):

> all elements that **are** false are removed
> returns the items that **are** false

This could be confusing for a new Python programmer, because the actual behaviour is that elements are equality-compared, not identity-compared.

Suggested wording: "are equal to False"

https://docs.python.org/3.5/library/functions.html#filter
https://docs.python.org/3.5/library/itertools.html#itertools.filterfalse

**Comment by berkerpeksag** [comment]
Thanks for the report. The correct place to report Python documentation issues is https://bugs.python.org.
