### ISSUE TITLE
Menu bar

### ISSUE THREAD

**Issue by dgitty** [python/pythondotorg#935]
Your website looks nice. The menu bar has a tiny glitch. Resizing the screen from large to small to large and clicking the menu bar opened up the side menu options and directed me to the bottom of the page to the bottom menu options. I think what is supposed to happen is after making the screen large again would only trigger the side menu options from showing up when clicking the menu button.

**Comment by Ivoz** [comment]
Are you able to attach an image which shows the undesirable behaviour happening?

**Comment by berkerpeksag** [comment]
This might be a duplicate of https://github.com/python/pythondotorg/issues/812.

**Comment by pvcraven** [comment]
How do you get the menubar to reappear? After disappearing into the menu button, I can't get the menu bar back. Even after clearing cache. 

http://imgur.com/RbUQdJc

This made me very confused about navigation.

**Comment by dgitty** [comment]
Hi, the page looks as if it has been updated since I posted that comment 14 days ago. There seems to no longer be any sidebar so I guess the problem has been resolved.

**Comment by Ivoz** [comment]
@pvcraven if your screenshotted problem is still happening in general I would suggest you file a separate bug

**Comment by berkerpeksag** [comment]
@drvuong thank you for the follow-up. Closing this as 'outdated'.

@pvcraven that menu button only displayed when `Modernizr.touch` returns `true` so it won't be shown on desktop. I can take look at it if you can give me the steps to reproduce it (you can just left a comment in this issue)
