### ISSUE TITLE
 I think this is a small bug in urlparse.py

### ISSUE THREAD

**Issue by salmonx** [python/pythondotorg#938]
run :  `urlparse.urlparse('http://google.com]')`
then: raise ValueError("Invalid IPv6 URL")

```
if url[:2] == '//':

    netloc, url = _splitnetloc(url, 2)

    **if (('[' in netloc and ']' not in netloc) or

            (']' in netloc and '[' not in netloc)):

        raise ValueError("Invalid IPv6 URL")**
```

---

TO SOLVE IT , I THINK IT IS BETTER TO JUST REMOVE THE LINES BOLDED ABOVE.

**Comment by berkerpeksag** [comment]
Please use https://bugs.python.org to report issues with the Python standard library.
