### ISSUE TITLE
Python shell does not accept keyboard interrupt and runs infinitely.

### ISSUE THREAD

**Issue by lokeshmeher** [python/pythondotorg#939]
I ran an infinite loop just for testing the shell and hit CTRL-C so many times after just about 2 seconds to stop the loop but the shell would never accept "keyboard interrupt" as a normal python shell does. I wonder if the shell keeps running even after I closed the browser window. I don't know what the issue is.
Please fix it as it can cause many potential security issues.
Here's the code I wrote:

```
import random
while True:
    print(random.randint(1, 1000000000000))
```

**Comment by berkerpeksag** [comment]
Two things:
1. This is not the correct place to report questions about Python.
2. I can't reproduce your problem on my system so I'd suggest to ask your question on python-list or StackOverflow.

**Comment by lokeshmeher** [comment]
@berkerpeksag This was on the python.org site. Here's the link: https://www.python.org/shell/

**Comment by lac22** [comment]
In a message of Sat, 28 May 2016 10:54:16 -0700, Berker Peksag writes:

> Two things:
> 1. This is not the correct place to report questions about Python.
> 2. I can't reproduce your problem on my system so I'd suggest to ask your question on python-list or StackOverflow.

I don't think this a Python question.  I think this person is reporting a
problem with the python-console-in-a-browser that is on the python.org
which we get from python anywhere.

I am not sure where this should get reported, though.

Laura

**Comment by berkerpeksag** [comment]
Thanks for details. The shell on python is maintained by pythonanywhere.com. @gpjt could you please take a look at this?

**Comment by pythonanywhere** [comment]
Control-C does work -- I just confirmed, no regression.  Making sure that this works is pretty much one of the first functional tests we implemented.  

I suspect the original reporter is using a browser on a slow machine, or has a slow Internet connection.  When you run code like that, then the server starts sending out lots of output.  This is sent to your browser as fast as possible, but if JavaScript on the client processes it slowly then although your control-C has been sent back to the server, and the server has interrupted the code and stopped sending data, your browser may wind up processing the data already sent for some time.

As a point of comparison -- on my machine (UK based, fibre-optic broadband, recent processor) the control-C takes effect within seconds.

**Comment by lokeshmeher** [comment]
Yes, I have a slow internet connection. But I have a fast processor(4670K at 4.6GHz). So, I think the problem is the slow internet connection. I tested it again a few times and on an average it took about 32 seconds to log the keyboard interrupt on the browser screen. @pythonanywhere is right. The data the server had sent is probably buffered and the screen just keeps displaying it till the buffer is empty. So, the user would have to wait for all the buffered data to finish displaying if the user has a slow internet connection. @berkerpeksag please close the issue.
