### ISSUE TITLE
Pagination should be cutted

### ISSUE THREAD

**Issue by aliev** [python/pythondotorg#943]
A long list of pagination numbers looks terrifying (users list page: https://www.python.org/users/). For example Django Pure Pagination package has a page range option: `'PAGE_RANGE_DISPLAYED': 10,`.

more detailed in pictures :)

What we have now

![](https://habrastorage.org/files/e23/e0e/c07/e23e0ec073cb4a409bbe880a605c6a0d.png)

What expected

![](https://habrastorage.org/files/024/8dd/57f/0248dd57fbd14205b18bd5317f498093.png)

*\* UPD **

or maybe infinity scroll?

**Comment by berkerpeksag** [comment]
I prefer not to use any third party library to achieve this. Note that we may remove the user listing page in the future. See #916.

**Comment by berkerpeksag** [comment]
We can implement this by subclassing `Paginator.page_range`. Then the paginator class should be passed to the `ListViews`:

```py
class UserList(ListView):
   ...

   paginator_class = CustomPaginator

   def get_paginator(self, queryset, per_page, orphans=0, allow_empty_first_page=True):
       return CustomPaginator(range_size=10)
```

According to https://docs.djangoproject.com/en/1.11/ref/class-based-views/mixins-multiple-object/#django.views.generic.list.MultipleObjectMixin.paginator_class we need to define both `paginator_class` and `get_paginator` if our `Paginator` subclass' constructor have a different signature.

Note that #916 is a blocker of this issue.
