### ISSUE TITLE
please include the PC/icons/* files from the python repository

### ISSUE THREAD

**Issue by doko42** [python/pythondotorg#945]
please include the PC/icons/\* files from the python repository.  The python mercurial repository ships PC/icons/\* files, although these are not used anymore for any Python build on any architecture. Please could you include these (maybe as part of community/python logs) in this project?  The corresponding issue in the python tracker is http://bugs.python.org/issue17500

**Comment by berkerpeksag** [comment]
I think we already have the same logos (except the source.xar file) in the community logos page. If source.xar is an important file I can upload to the community logos page.

**Comment by malemburg** [comment]
We do and the .xar file includes an old variant which is not the official version of the logo. Overall, the data in PC/icons/\* dir is not official logo data, so I don't think we should include on the website.

It may actually be better to do the reverse: i.e. add the official logo files from the website to the PC/logo/ dir and replace the in-official files with the official ones.

**Comment by malemburg** [comment]
Some additional files are available here: https://wiki.python.org/psf/Python%20Logos

**Comment by ned-deily** [comment]
@doko42 brought this issue up with me at the PyCon sprints. His concern is that Debian considers .xar files to be non-free and thus they have to explicitly delete the file from each Python release when they repackage. It's not clear to us whether the .xar file is needed at all anymore but, as a precaution, he thought that saving in pythondotorg repo and removing it from cpython would make sure it didn't get lost and solve the non-free issue for redistributors.  Otherwise, no other changes are being proposed.

**Comment by malemburg** [comment]
On 06.06.2016 17:59, Ned Deily wrote:

> @doko42 brought this issue up with me at the PyCon sprints. His concern is that Debian considers .xar files to be non-free and thus they have to have explicitly delete the file from each Python release when they repackage. It's not clear to us whether the .xar file is needed at all anymore but, as a precaution, he thought that saving in pythondotorg repo and removing it from cpython would make sure it didn't get lost and solve the non-free issue for redistributors.  Otherwise, no other changes are being proposed.

Hi Ned,

as mentioned, neither the .xar nor the .svg file in the directory
contain the official logo files, so IMO they can both be deleted and
don't have to be hosted anywhere else.

If people are seeking the official logos, they should go to the
website.

## Cheers,

Marc-Andre Lemburg
http://www.malemburg.com/

**Comment by ned-deily** [comment]
OK, good, then I guess we can close this issue.  OK, @doko42?

**Comment by doko42** [comment]
ok. maybe a different request would be the addition of the logo with just the two snakes, which can be used as a desktop icon for starting the the interpreter.

**Comment by berkerpeksag** [comment]
Looks like this can be closed now. Please reopen if not.
