### ISSUE TITLE
3.4 buildbot link should be removed

### ISSUE THREAD

**Issue by terryjreedy** [python/pythondotorg#946]
https://www.python.org/dev/buildbot/ has "Stable builders for the Python 3.4 branch" which links to http://buildbot.python.org/3.4.stable/ which (properly) no longer exists. "404 Not Found".  Delete the line.

**Comment by berkerpeksag** [comment]
This should probably be reported to https://mail.python.org/mailman/listinfo/python-buildbots python.org people don't have access to buildbot.python.org.

**Comment by terryjreedy** [comment]
On 6/8/2016 9:31 PM, Berker Peksag wrote:

> This should probably be reported to
> https://mail.python.org/mailman/listinfo/python-buildbots python.org
> people don't have access to buildbot.python.org.

It is the www.python.org page, not buildbot.python.org, that has the bad 
link to be removed.  The bottom of the www.python.org page says to 
report bugs to pydotorg.  If that is wrong, it should also be changed.

**Comment by ned-deily** [comment]
The 3.4 links are now removed.  Thanks for the report.

**Comment by berkerpeksag** [comment]
You're right. I misread the issue (probably forgot to wake up :))
