### ISSUE TITLE
Wrong link to PyPi bug tracker

### ISSUE THREAD

**Issue by Yvan-Masson** [python/pythondotorg#947]
Hi,

If I am not wrong, the link provided on https://www.python.org/about/website/ to the PyPi bug tracker should be https://bitbucket.org/pypa/pypi/issues instead of http://sourceforge.net/tracker/?group_id=66150&atid=513503

Best regards,
Yvan

**Comment by berkerpeksag** [comment]
Fixed, thanks for the report.
