### ISSUE TITLE
404 Error offilne documentaion....

### ISSUE THREAD

**Issue by hilalahmadbhat** [python/pythondotorg#949]
Hi,
I m new to python
I needed to get offline docs for learning python
But getting this error
![python err](https://cloud.githubusercontent.com/assets/11781084/16031839/9ef3de20-321d-11e6-9681-4df366fe3f72.PNG)

**Comment by ned-deily** [comment]
Sorry, the off-line documentation set is not produced for Python pre-releases, like release candidates, only for the final release.  3.5.2 final should be available in about two weeks.   Is that a link you found on a python.org webpage?

**Comment by ned-deily** [comment]
Oh, sorry, I see that the bad links are here; https://docs.python.org/3/download.html.  That's too bad!  Until 3.5.2 is officially released, you could download the 3.5.1 version here:  https://docs.python.org/3/archives/python-3.5.1-docs-pdf-letter.zip

**Comment by jnm3** [comment]
It looks like they have some bad links or missing files but I was able to find the file I was looking for by dropping off folders until I found what I was looking for.
https://docs.python.org/3.5/archives/
https://docs.python.org/2.7/archives/
This will show you a list of files that are available for download.
Hope this helps

**Comment by berkerpeksag** [comment]
Thanks for the report. This should be fixed now: https://docs.python.org/3/download.html
