### ISSUE TITLE
There seems to be something wrong with the Python on nethunter.

### ISSUE THREAD

**Issue by nickyang28** [python/pythondotorg#951]
![screenshot_20160619-004346](https://cloud.githubusercontent.com/assets/19889990/16176468/00260676-35d6-11e6-877b-9469db5e4520.png)

How can I fix it?

**Comment by tavatchaina** [comment]
ฉันจะแก้มันได้ยังไงครับ

**Comment by nickyang28** [comment]
So what can I do

**Comment by berkerpeksag** [comment]
This is a installation problem in sqlmap, not a Python problem. Please contact developers of sqlmap.

**Comment by nickyang28** [comment]
It doesn't make sense. Those who run sqlmap said it is about python. But you said it is about sqlmap. However, all python related tools don't work. So I believe it is a python problem.

**Comment by ned-deily** [comment]
@Doveyang, regardless of where the problem lies, this issue tracker is for problems with the python.org website, not with Python itself.  Take a look at the Help page of the website for suggestions of where to go for help with Python issues:  https://www.python.org/about/help/.  Good luck!
