### ISSUE TITLE
Correct informations contained on the about webpage

### ISSUE THREAD

**Issue by lionel-martin** [python/pythondotorg#952]
Please fix the following things on the [About-Website webpage](https://www.python.org/about/website/) :

> Note that this address is only for problems with the main python.org website. For problems with PyPI please use the [PyPI bug tracker](https://bitbucket.org/pypa/pypi/issues).
- The new issue tracker is [on Github](https://github.com/pypa/pypi-legacy/issues)

> To report a bug or to suggest an enhancement, send an e-mail to webmaster@python.org.
- I received an email asking me to post here. Thus please replace or complement the email address with [this issue tracker](https://github.com/python/pythondotorg/issues)

**Comment by ned-deily** [comment]
Thanks for the report.  The link is now updated.
