### ISSUE TITLE
Can not obtain login to site; never received E-mail with link (for bugs.python.org)

### ISSUE THREAD

**Issue by luhler** [python/pythondotorg#953]
I have tried about 10 times to obtain a login to: bugs.python.org.

I never receive E-mail from  the site to confirm my login status.

(lloyd_uhler@sbcglobal.net)

**Comment by berkerpeksag** [comment]
Can you please check your spam folder? If you still don't get any email from bugs.python.org, please write to http://psf.upfronthosting.co.za/roundup/meta/ or #python-dev IRC channel on Freenode. This tracker is for issues with www.python.org only and we don't have control on bugs.python.org. Thanks!

**Comment by luhler** [comment]
Dear Sir,

I cannot obtain a login to both bugs.python.org or to the PSF Meta Tracker. I never receive E-mail (The SPAM folder is empty).

I view my E-mail first under yahoo.com. This is supported by att. After viewing and manually filtering, I download into Microsoft Outlook.

I have tried now for 4 days to post my bug on bugs.python.org.

I am running Python 3 and get errors when running  socket.py.

I am at a standstill.

Lloyd

**Comment by luhler** [comment]
Can not obtain login from either PSF Meta Tracker or bugs.python.org. I never receive E-mail reply.
It turns out that a few other people have the same proble.

  

```
On Tuesday, June 28, 2016 11:03 PM, Berker Peksag <notifications@github.com> wrote:
```

 Can you please check your spam folder? If you still don't get any email from bugs.python.org, please write to http://psf.upfronthosting.co.za/roundup/meta/ or #python-dev IRC channel on Freenode. This tracker is for issues with www.python.org only and we don't have control on bugs.python.org. Thanks!—
