### ISSUE TITLE
Download directory listing out of date

### ISSUE THREAD

**Issue by chrullrich** [python/pythondotorg#954]
https://www.python.org/ftp/python/3.5.2/ returns a directory listing, but it is not up to date. It contains only rc1 files and directories, even though 3.5.2 has been released, its files can be downloaded, and e.g. https://www.python.org/ftp/python/3.5.2/amd64/ returns a (presumably) valid list of files.

**Comment by malemburg** [comment]
Adding @larryhastings ... I presume this is a permission error on the server. It's happening in releases every now and then. Perhaps something to fix in the release script(s) ?!

**Comment by ned-deily** [comment]
It looks up-to-date now.  It may also have been a caching issue with the CDN.  The steps in PEP 101 should ensure that the permissions are always correct.  I'm going to close this for now.  We can reopen it if the problem reappears.
