### ISSUE TITLE
Redirect /download/releases/X.Y.Z to /downloads/release/python-XYZ

### ISSUE THREAD

**Issue by berkerpeksag** [python/pythondotorg#956]
Currently, `/download/releases/X.Y.Z` links are stored in the `pages.Page` model but we already have same feature in the `downloads` application. It would be nice to
1. merge their content
2. redirect `/download/releases/X.Y.Z` to `/downloads/releases/python-XYZ`

for all 2.7 and 3.x releases. We should keep the old URL active for older releases like 1.6, 2.3, etc.

**Pros**
- No need to duplicate release notes anymore
- One less step for release managers

**Comment by ned-deily** [comment]
+1. Actually, we're no longer consistently creating the duplicated page in `/download/releases`, for example, for 2.7.11.  I, for one, had forgotten about the old pattern of links. I'm not sure how important it is to maintain them forever but if the redirects could be generated automatically that would be great.  ( @benjaminp @larryhastings )
