### ISSUE TITLE
Add PythonHosted to monitoring?

### ISSUE THREAD

**Issue by pvcraven** [python/pythondotorg#958]
It looks like pythonhosted.org (used for python package docs) is part of the python.org set of websites. But it is not being monitored on https://status.python.org/ right now. I noticed because pythonhosted.org has been down for a while now, at the time of this writing.

If PythonHosted.org is part of the python web site system, it should be added to the monitoring. If it isn't, then never mind.

**Comment by berkerpeksag** [comment]
pythonhosted.org is maintained by PyPI and Infrastructure teams. This tracker is only for issues with www.python.org. I would suggest to send an email to infrastructure@python.org.
