### ISSUE TITLE
Donor List

### ISSUE THREAD

**Issue by MarkMangoba** [python/pythondotorg#961]
Donor list at the bottom does not retrieve names of donors. Done through dinsdale server? Contact Kurt on where to begin fixing this issue.

https://www.python.org/psf/donations/

**Comment by berkerpeksag** [comment]
There are already duplicated reports about this: See https://github.com/python/pythondotorg/issues/709 and https://github.com/python/pythondotorg/issues/83.

**Comment by MarkMangoba** [comment]
Thanks Berker, i'll check the report out.

**Comment by berkerpeksag** [comment]
Closing this as a duplicate of #709 since Marc-Andre and Kurt gave their feedback there. I've also added the location of the data and the script that updates the old donations page there..
