### ISSUE TITLE
PSF>>>  Legal>>>  Bylaws

### ISSUE THREAD

**Issue by MarkMangoba** [python/pythondotorg#964]
Takes you out of the "PSF" website hiearchy and places you in the "Python" hiearchy

**Comment by MarkMangoba** [comment]
@berkerpeksag i'm not seeing the issue in the CMS, seems to be in the correct hierarchy.  Can you take a look at this? @ejodlowska reported the issue.

**Comment by berkerpeksag** [comment]
Fixed: https://www.python.org/psf/bylaws/

`psf/default.html` was missing in the _Template name_ field of the _Advanced options_ section.

**Comment by MarkMangoba** [comment]
@ejodlowska update to the issue.  Thanks @berkerpeksag!
