### ISSUE TITLE
python.org doesn't accept my new password.  I can't login.  Please help, thank you!

### ISSUE THREAD

**Issue by splitdarkmatter** [python/pythondotorg#971]

**Comment by MarkMangoba** [comment]
Hello, did you try a password reset again?  https://www.python.org/accounts/password/reset/ - feel free to email your email address you signed up with at mmangoba@python.org.

**Comment by MarkMangoba** [comment]
@splitdarkmatter i sent you an email regarding your python.org account, if you are still having trouble - please let me know.  I will close this for now.
