### ISSUE TITLE
"Python 2.7.11 is the latest bugfix release"

### ISSUE THREAD

**Issue by jwilk** [python/pythondotorg#975]
https://www.python.org/downloads/release/python-2711/ reads:

> Python 2.7.11 is the latest bugfix release of the Python 2.7 series.

Actually the lastest release is 2.7.12.

**Comment by berkerpeksag** [comment]
Good catch, fixed! It now reads:

> Python 2.7.11 is a bugfix release of the Python 2.7 series.

Thanks!
