### ISSUE TITLE
Download Page Poorly Detailed

### ISSUE THREAD

**Issue by Spocking** [python/pythondotorg#976]
The download page https://www.python.org/downloads/ doesn't say whether the "Python" download is the compiler executable, or an interpreter, or a development environment, or libraries, or a code editor, or tutorial, or a video about snakes. Could that be clarified?

**Comment by ned-deily** [comment]
There are already a number of issues related to the limited choices provided by the Download buttons on the Download dropdown.  I think this issue is probably already covered by one of those already grouped under the "downloads" label.  It's not really a "content" issue, assuming @Spocking is referring to the download buttons.  The complete information about the files available with each release is already available on the page for each release, shown in the scroll box in the lower part of the Downloads page.

**Comment by berkerpeksag** [comment]
I agree with Ned. We also explicitly say "source code" or "source release" when there is no binary available for a platform.

**Comment by Spocking** [comment]
Ok, 3 days later, and I still can't find out whether "Download Python" downloads a compiler, an interpreter, a development environment, libraries, a code editor, a tutorial, or a video. And it still isn't labeled in any functional way. This is neither logical nor professional.

**Comment by ned-deily** [comment]
Sorry, I think there is general agreement that the Download buttons, specifically, and the page, in general, could use some improvement and that will happen in the future but that will take some time to decide what design changes to make.  Like nearly all aspects of the Python project, the website is maintained primarily by volunteers so it's usually not possible to immediately respond to every issue.

What are being offered here are the official distributions for Python releases.  As noted on the page, there are binary installers offered for Windows and Mac OS X and source releases for all other platforms.  The contents of those distributions differ somewhat among the platforms but generally provide the binaries or source for installing a Python interpreter, libraries, a development environment and code editor (IDLE), and documentation.  There is more platform-specific information about releases further down the page.  And the full set of distribution formats for each release are available on the releases page.

The designers of the current website tried to make the Download buttons smart by having them download the most current stable release of either Python 3 or 2 in the most-popular formats for your platform based on your browser type and that can be perhaps too non-obviously smart.  But, pressing download and examining the resulting downloaded file should be fairly self-explanatory and there is further information included in the downloads (READMEs, installer welcome files, etc).   It seems like this hasn't been a big problem so far for the many thousands of people who have downloaded releases from this page.  But if you have suggestions on how to improve it, that would be great.
