### ISSUE TITLE
Donation Button

### ISSUE THREAD

**Issue by MarkMangoba** [python/pythondotorg#977]
Where is the donation button in the donation page?
https://www.python.org/psf/donations/

Reported by:  Shingo

**Comment by MarkMangoba** [comment]
@berkerpeksag just checked, in HTML, the donation button works, but since the page is in RST - it doesn't show up properly (although the raw HTML tag is there).   Can you take a look?

**Comment by berkerpeksag** [comment]
I think the `raw` directive has been disabled by `django-markitup` for security purposes: https://github.com/jamesturk/django-markupfield/blob/master/markupfield/markup.py#L78 I suggest changing the form markup with a [plain link](http://www.blogbyben.com/2009/04/paypal-link-generator-build-your-own-1.html).

**Comment by MarkMangoba** [comment]
@berkerpeksag did this just happen?  I believe it was working for several weeks last time I looked at it.  Thanks, i'll change it if need to be.

**Comment by berkerpeksag** [comment]
The fix was released in django-markitup 1.3.2 in 2015 so my guess is that it was working because of caching (Fastly caches pretty aggressively :)).

**Comment by ejodlowska** [comment]
More on the security issue: http://docutils.sourceforge.net/docs/ref/rst/directives.html#raw-data-pass-through

**Comment by MarkMangoba** [comment]
Changed content markup to HTML.  Confirmed donation button is now working.
