### ISSUE TITLE
Update PSF Sponsor Page copy

### ISSUE THREAD

**Issue by bwaliszewski** [python/pythondotorg#979]
Sponsorship policy
Original copy:

Any organization is welcome to apply for sponsor membership - however, approval of the membership is conditional on a member vote at a member meeting, and the Board may issue a recommendation to the members regarding the application.

In the time between this board recommendation and acceptance by members (which may take up to a year), the sponsor may be listed as a Pending Sponsor on the website, after the application and prorated annual fee have been received. If a sponsor's application is not approved by the PSF membership, any fees already paid will be retained as a donation.

New suggested copy: 

Any organization is welcome to apply for sponsor membership. Approval of the membership is conditional on a vote by the PSF Sponsor Working Group. In the time between discussion and approval by the working group, the sponsor may be listed as a Pending Sponsor on the website, after the application and prorated annual fee have been received. If a sponsor's application is not approved by the PSF Working Group, any fees already paid will be retained as a donation.

**Comment by MarkMangoba** [comment]
@bwaliszewski this has been completed.  https://www.python.org/psf/sponsorship/.
