### ISSUE TITLE
Change https://www.python.org/about/website/ to link to this issue tracker

### ISSUE THREAD

**Issue by fingolfin** [python/pythondotorg#982]
Earlier today, I found an issue with the python.org website. I googled how to report issues with python.org, which lead me to https://www.python.org/about/website/

The instructions there were clear:

```
To report a bug or to suggest an enhancement, send an e-mail to <webmaster@python.org>.
```

After doing that, I received an automatic reply which pointed me to this tracker.

May I suggest updating the instructions on https://www.python.org/about/website to also link to this issue tracker?

**Comment by berkerpeksag** [comment]
Thanks for the report! I've now changed it to

```
To report a bug or to suggest an enhancement, please use the pythondotorg issue tracker.
```
