### ISSUE TITLE
Fix PEP links

### ISSUE THREAD

**Issue by fingolfin** [python/pythondotorg#983]
I just followed a Hacker News link to https://www.python.org/dev/peps/pep-0526. At the bottom of that page, it says:

```
Source: https://hg.python.org/peps/file/tip/pep-0526.txt
```

Following that link leads to an error page. Looking a bit deeper, it seems that the PEPs were moved to GitHub. See here: https://hg.python.org/peps/rev/65c5d45eab5f.

Some digging on this Github repo lead me to https://github.com/python/pythondotorg/blob/master/peps/converters.py -- it seems that file hardcodes the links to hg.python.org, and should be updated to link to GitHub instead. For PEP 526, an appropriate link might be https://github.com/python/peps/blob/master/pep-0526.txt.

But to my surprise, not all PEPs seem to have such a "Source: URL" entry.  At least https://www.python.org/dev/peps/pep-0525 does not. I found no other examples of this.

**Comment by berkerpeksag** [comment]
Thanks for the report. I've fixed PEP links.

> But to my surprise, not all PEPs seem to have such a "Source: URL" entry. At least https://www.python.org/dev/peps/pep-0525 does not. I found no other examples of this.

That's weird. I'm unable to reproduce this in my machine. I've added a test in 35a5c27 and also let's see if we can reproduce the problem on staging.python.org.

**Comment by fingolfin** [comment]
Just to clarify: When you say you cannot reproduce, do you mean that if you visit https://www.python.org/dev/peps/pep-0525 then you _do_ see the "Source: URL" text? Or do you mean that if you run the website one your machine, then localhost:/dev/peps/pep-0525 shows the "Source: URL" text?

I don't see it on https://www.python.org/dev/peps/pep-0525 and also not on https://staging.python.org/dev/peps/pep-0525/

**Comment by fingolfin** [comment]
I also note that the `Source:` text comes right after `</html>`.... seems you guys are embedding a raw external HTML file??? Of course this will cause the W3C validator to complain. If you care about that, I can submit a separate issue on this.

**Comment by berkerpeksag** [comment]
> Just to clarify: When you say you cannot reproduce, do you mean that if you visit https://www.python.org/dev/peps/pep-0525 then you do see the "Source: URL" text? Or do you mean that if you run the website one your machine, then localhost:/dev/peps/pep-0525 shows the "Source: URL" text?

The latter. Sorry, I should have more clear. I don't have access to logs so I don't know what's going on production. I will get in touch with the infrastructure team.

**Comment by berkerpeksag** [comment]
> Of course this will cause the W3C validator to complain. If you care about that, I can submit a separate issue on this.

That would be great, thanks! I'm working on some improvements to our PEP importer.
