### ISSUE TITLE
Session takeover vulnerability/bug Found on python.org

### ISSUE THREAD

**Issue by Yadnyawalkya** [python/pythondotorg#984]
Hi there, I noticed session takeover vulnerability on python.org. 
Details are as follows :

**Browser I Used**
1.  Mozilla Firefox v48
2.  Google Chromium v51

**Operating System Used**
Windows 8.1 also checked Edubuntu 14.04

**Login Required**
Yes

**Vulnerable Link**
[https://www.python.org](url)

**Description**
Sessions of users accounts not terminated after been password changed

**Steps to reproduce issue** 
        _(You have to use two browsers here. You can use Incognito mode)_
1.  Register an account  on  [https://www.python.org](url) with a valid information. 
2.  Logged into your account with first browser
3.  On second browser, Login on same account  and  Change/Reset  password.
4.  Now goto first browser and  refresh the link i.e. [https://www.python.org](url). You will notice that  sessions are still alive and not terminated.

**Possible Impact Scenario** 
Suppose Victim Logged into his account at internet cafe and forgot to Logout. 
Suppose You are attacker and you found victims account is open on same PC. Now attacker can download 'EditThisCookie 1.4.1' Chrome extension and export/copy cookie of victims acc  in text file. 
Now victim get to know that someone is using his acc and he just change password.
But attacker have victims account's cookies so he can just import that cookie with 'EditThisCookie 1.4.1'  and use victims account anytime because all sessions are not get terminating after password change. This may leads to miss-use of victims details and account . 

**Expected**
All live sessions must  terminate after password changed.

**Comment by berkerpeksag** [comment]
I think Django already does this, but we don't use built-in authentication tools. `django-allauth` may not destroy session data at logout or profile update. I will do further investigation.

Thanks for the report!

**Comment by berkerpeksag** [comment]
I think 76a461f should resolve this. @YadnyawalkyaTale could you please try again https://staging.python.org/ in an hour (it should be deployed automatically to the staging site.)

I'd like add your name to https://github.com/python/pythondotorg/blob/master/templates/humans.txt Feel free send a pull request or I can add it myself.

**Comment by YadnyawalkyaTale** [comment]
Just checked issue, It is no-more reproducible ! Great fix btw ;)
You can add my blog link [http://yadnyawalkya.blogspot.in](http://yadnyawalkya.blogspot.in) with name _Yadnyawalkya Tale_ to _human.txt._

Sorry for replying after day, I had forgotten about this issue.
Thank again ! Have a great weekend :)

**Comment by YadnyawalkyaTale** [comment]
Just checked issue, It is no-more reproducible ! Great fix btw 
You can add my blog link [http://yadnyawalkya.blogspot.in](http://yadnyawalkya.blogspot.in) with name _Yadnyawalkya Tale_ to _human.txt._

Sorry for replying after day, I had forgotten about this issue.
Thank again ! Have a great weekend :)

**Comment by YadnyawalkyaTale** [comment]
Just checked issue, It is no-more reproducible ! Great fix btw :)
You can add my blog link [http://yadnyawalkya.blogspot.in](http://yadnyawalkya.blogspot.in) with name _Yadnyawalkya Tale_ to _human.txt._

Sorry for replying after day, I had forgotten about this issue.
Thank again ! Have a great weekend :)

**Comment by Yadnyawalkya** [comment]
Just checked issue, It is no-more reproducible ! Great fix btw ;)  

You can add blog link [http://yadnyawalkya.blogspot.in](http://yadnyawalkya.blogspot.in) with my name _Yadnyawalkya Tale_ to _human.txt._ Please add pull request from your end.

Sorry for replying after day, I had forgotten about this issue.
Thanks again ! Have a great weekend :)

**Comment by berkerpeksag** [comment]
Done in https://github.com/python/pythondotorg/commit/1bb02131bb7f988003841a2239ab80d19be949b6, thanks!
