### ISSUE TITLE
Broken links in "D-Link Australia..." success story

### ISSUE THREAD

**Issue by cmdelatorre** [python/pythondotorg#988]
The [D-Link Australia Uses Python to Control Firmware Updates](https://www.python.org/about/success/dlink/) success story has two broken links:
- A non-existent image https://www.python.org/about/success/dlink/recovery-screen-small.jpg and
- Its zoom link https://www.python.org/about/success/dlink/recovery-screen.jpg
  (both exist in the legacy website)

**Comment by berkerpeksag** [comment]
Thanks for the report. I've removed broken links.
