### ISSUE TITLE
Pagination in examples obscured by slide copy

### ISSUE THREAD

**Issue by linssen** [python/pythondotorg#99]
![screen shot 2014-02-20 at 12 29 21](https://f.cloud.github.com/assets/67624/2218227/c83cd4ea-9a2a-11e3-8842-affab8d0cd5d.png)

**Comment by berkerpeksag** [comment]
Thanks for the report. This looks already fixed. I couldn't reproduce the behavior on Chrome, Firefox and several mobile devices.
