### ISSUE TITLE
which tracker to use for license questions?

### ISSUE THREAD

**Issue by mwichmann** [python/pythondotorg#996]
The license FAQ at https://wiki.python.org/moin/PythonSoftwareFoundationLicenseFaq ends with this line:
_If in doubt, please raise the question on the tracker. A core developer will then guide you._ 
There is not a hyperlink to the tracker, and it's perhaps not entirely clear which tracker is appropriate, as elsewhere in documentation (help page) we say:
...
- If you suspect a bug in the Python core, search the Python Bug Tracker.
- If you think you've found a security vulnerability in Python, please read the instructions for reporting security issues.
- If you've found a problem with this web site, check the pythondotorg issue tracker.

A license question isn't really a bug in the Python Core, nor is it a website problem.  A respondent has had some questions and apparently neither option rang quite right, so they chose another not-correct option, email to webmaster.   It would be good if we could clarify a bit where to go for license questions, or at least hyperlink to the place we want them to file an issue if that's the best approach.

**Comment by berkerpeksag** [comment]
Thanks for the report! I think both psf@python.org and https://mail.python.org/mailman/listinfo/python-legal-sig would be the best places to ask.

**Comment by mwichmann** [comment]
Adding from email thread:

Hi Steve/Nick/webmasters,

We have created the legal@python.org mailing list to help field such
emails. If you get further inquiries similar to this, please forward it
there. On the mailing list, we have myself and Van as well as a few others
for accountability.

I have asked Mark, our IT Manager, to also add the address to the site
under /legal so people may email it directly.

Best regards,

Ewa
Director of Operations
Python Software Foundation

**Comment by berkerpeksag** [comment]
Thanks. It looks like Mark opened https://github.com/python/pythondotorg/issues/997 to address this.

**Comment by berkerpeksag** [comment]
Looks like legal@p.o. mailing list has been created at https://mail.python.org/mailman/listinfo/legal and the address has been added to https://www.python.org/about/legal/ so I think this issue can be closed now.
