### ISSUE TITLE
PSF Sponsor Prospectus 2016

### ISSUE THREAD

**Issue by MarkMangoba** [python/pythondotorg#999]
@bwaliszewski let me know what wording should go with the PSF Sponsor Prospectus 2016 and under which section:  https://www.python.org/psf/sponsorship/

**Comment by bwaliszewski** [comment]
Under "How to become a Sponsor", add the following copy to the beginning of the paragraph: 
Download [link to pdf] a copy of the PSF Sponsor Prospectus for more details about sponsorship.

**Comment by MarkMangoba** [comment]
Linked the PDF https://www.python.org/psf/sponsorship/.
